begin;
create function pg_temp.verify(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();o uuid:=gen_random_uuid();s uuid:=game_private.current_season();bid uuid;pid uuid;f uuid;
 q jsonb;res jsonb;first jsonb;jobid uuid;paused timestamptz;d jsonb;denied boolean;next_s uuid;ledger0 bigint; item text; blueprint text; rules jsonb;
begin
 insert into auth.users(id) values(a),(b),(o);
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',o::text,true);perform public.game_state();
 update public.game_user_roles set role_id='owner' where player_id=o;
 perform set_config('game.reason','CI crafting fixtures',true);
 update public.game_settings set value=300 where key='actions_per_minute';
 update public.game_settings set value=100000 where key='inventory_weight_limit_grams';
 update public.game_players set cash=10000 where id=a;
 perform set_config('request.jwt.claim.sub',a::text,true);
 select p.id,b.id into pid,bid from public.game_district_plots p join public.game_district_buildings b on b.plot_id=p.id where p.season_id=s and p.code='W25';
 update public.game_property_leases set released_at=clock_timestamp() where building_id=bid and released_at is null;
 res:=public.property_action('rent',jsonb_build_object('season_id',s,'plot_id',pid,'rent',300,'version',1,'request_id',gen_random_uuid()));
 perform pg_temp.verify(not res?'error','Lease fixture failed '||res::text);

 res:=public.property_action('install_station',jsonb_build_object('season_id',s,'plot_id',pid,'cost',500,'space',20,'request_id',gen_random_uuid()));
 perform pg_temp.verify(not res?'error','Station failed '||res::text);
 insert into public.game_inventory(season_id,player_id,good_id,quantity) values(s,a,'silk',18),(s,a,'steel',12),(s,a,'copper-ingot',4);
 foreach item in array array['reinforced-jacket','kevlar-vest'] loop
  q:=jsonb_build_object('season_id',s,'building_id',bid,'recipe_id',item,'version',1,'source','carried','batches',1,'request_id',gen_random_uuid());
  set local role authenticated;
  res:=public.crafting_action('start',q);
  perform pg_temp.verify(res?'error','Armour crafted without learning blueprint');
  reset role;
  blueprint:=case when item='reinforced-jacket' then 'reinforced_jacket_blueprint' else 'kevlar_vest_blueprint' end;
  insert into public.game_inventory(season_id,player_id,good_id,quantity) values(s,a,blueprint,2);
  set local role authenticated;
  res:=public.crafting_action('learn',q||jsonb_build_object('request_id',gen_random_uuid()));
  perform pg_temp.verify(not res?'error','Armour learning failed '||res::text);
  first:=public.crafting_action('start',q);
  perform pg_temp.verify(not first?'error','Armour crafting failed '||first::text);
  perform pg_temp.verify(public.crafting_action('start',q)=first,'Craft retry duplicated job');
  jobid:=(first->>'job_id')::uuid;
  res:=public.crafting_action('collect',jsonb_build_object('season_id',s,'job_id',jobid,'destination','carried','request_id',gen_random_uuid()));
  perform pg_temp.verify(res?'error','Collected armour early');
  reset role;
  update public.game_season_jobs set ready_at=clock_timestamp()-interval '1 second' where id=jobid;
  q:=jsonb_build_object('season_id',s,'job_id',jobid,'destination','carried','request_id',gen_random_uuid());
  set local role authenticated;
  first:=public.crafting_action('collect',q);
  perform pg_temp.verify(not first?'error','Collect failed '||first::text);
  perform pg_temp.verify(public.crafting_action('collect',q)=first,'Collect retry duplicated armour');
  res:=public.inventory_action('equip',jsonb_build_object('season_id',s,'item_key','good:'||item,'equipment_slot','armor','quantity',1,'request_id',gen_random_uuid()));
  perform pg_temp.verify(not res?'error','Armour equip failed '||res::text);
  reset role;
  perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id=blueprint)=1,'Learning consumed wrong blueprint quantity');
  rules:=game_private.robbery_factors(s,a);
  perform pg_temp.verify((rules->>'defense')::numeric=case when item='reinforced-jacket' then 15 else 35 end,'Armour defence not applied or stacked');
  perform pg_temp.verify((select count(*) from public.game_inventory_gear where season_id=s and player_id=a and equipment_slot='armor' and location='equipped')=1,'Multiple armour slots equipped');
 end loop;
 perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='silk')=9,'Wrong fabric consumption');
 perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='steel')=6,'Wrong steel consumption');
 res:=public.crafting_action('start',jsonb_build_object('season_id',s,'building_id',bid,'recipe_id','homemade-pistol','version',1,'source','carried','batches',1,'request_id',gen_random_uuid()));
 perform pg_temp.verify(res?'error','Existing blueprint gate bypassed');
 res:=public.crafting_action('learn',jsonb_build_object('season_id',s,'recipe_id','kevlar-vest','version',1,'source','carried','request_id',gen_random_uuid()));
 perform pg_temp.verify(res?'error','Repeated learning consumed another blueprint');
end$$;
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();s uuid:=game_private.current_season();d uuid;bid uuid;pid uuid;q jsonb;r jsonb;first jsonb;site jsonb;attempt uuid;job uuid;gear uuid;denied boolean;
begin
 insert into auth.users(id) values(a),(b);
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('game.reason','CI bandages fixture',true);
 update public.game_settings set value=300 where key='actions_per_minute';
 update public.game_settings set value=20 where key='bandage_heal_amount';
 update public.game_settings set value=0 where key='scavenging_patrol_enabled';
 update public.game_bin_rules set cash_chance=0,pickaxe_chance=0,lockpick_chance=0,pistol_blueprint_chance=0,bullet_blueprint_chance=0,bandages_blueprint_chance=0,reinforced_jacket_blueprint_chance=100,kevlar_vest_blueprint_chance=0;
 select id into d from public.game_districts where slug='the-waterfront';
 q:=jsonb_build_object('season_id',s,'district_id',d,'request_id',gen_random_uuid());
 r:=public.scavenging_action('enter',q);perform pg_temp.verify(not r?'error','Enter failed '||r::text);
 select x into site from jsonb_array_elements(public.bin_diving_state()->'scavenging'->'targets')x where x->>'kind'='bin' limit 1;
 update game_private.scav_sessions set node=(site->>'node')::int,route_points=jsonb_build_array(jsonb_build_array((site->>'node')::int%5,(site->>'node')::int/5)) where player_id=a;
 attempt:=gen_random_uuid();
 r:=public.scavenging_action('search',q||jsonb_build_object('request_id',attempt,'target_id',site->>'id'));perform pg_temp.verify(not r?'error','Search failed '||r::text);
 update game_private.scav_sessions set pending=pending||jsonb_build_object('ready_at',clock_timestamp()-interval '1 second') where player_id=a;
 q:=jsonb_build_object('season_id',s,'attempt_id',attempt,'request_id',gen_random_uuid());
 set local role authenticated;
 first:=public.scavenging_action('finish',q);perform pg_temp.verify(not first?'error','Discovery failed '||first::text);
 perform pg_temp.verify(public.scavenging_action('finish',q)=first,'Discovery retry changed');
 r:=public.bin_diving_state();perform pg_temp.verify((r->'inventory'->>'reinforced_jacket_blueprint')::int=1,'Discovery absent from stash');
 reset role;
 perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='reinforced_jacket_blueprint')=1,'Discovery duplicated blueprint');
end$$;

do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();s uuid:=game_private.current_season();d uuid;bid uuid;pid uuid;q jsonb;r jsonb;first jsonb;site jsonb;attempt uuid;job uuid;gear uuid;denied boolean;
begin
 insert into auth.users(id) values(a),(b);
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('game.reason','CI bandages fixture',true);
 update public.game_settings set value=300 where key='actions_per_minute';
 update public.game_settings set value=20 where key='bandage_heal_amount';
 update public.game_settings set value=0 where key='scavenging_patrol_enabled';
 update public.game_bin_rules set cash_chance=0,pickaxe_chance=0,lockpick_chance=0,pistol_blueprint_chance=0,bullet_blueprint_chance=0,bandages_blueprint_chance=0,reinforced_jacket_blueprint_chance=0,kevlar_vest_blueprint_chance=100;
 select id into d from public.game_districts where slug='the-waterfront';
 q:=jsonb_build_object('season_id',s,'district_id',d,'request_id',gen_random_uuid());
 r:=public.scavenging_action('enter',q);perform pg_temp.verify(not r?'error','Enter failed '||r::text);
 select x into site from jsonb_array_elements(public.bin_diving_state()->'scavenging'->'targets')x where x->>'kind'='bin' limit 1;
 update game_private.scav_sessions set node=(site->>'node')::int,route_points=jsonb_build_array(jsonb_build_array((site->>'node')::int%5,(site->>'node')::int/5)) where player_id=a;
 attempt:=gen_random_uuid();
 r:=public.scavenging_action('search',q||jsonb_build_object('request_id',attempt,'target_id',site->>'id'));perform pg_temp.verify(not r?'error','Search failed '||r::text);
 update game_private.scav_sessions set pending=pending||jsonb_build_object('ready_at',clock_timestamp()-interval '1 second') where player_id=a;
 q:=jsonb_build_object('season_id',s,'attempt_id',attempt,'request_id',gen_random_uuid());
 set local role authenticated;
 first:=public.scavenging_action('finish',q);perform pg_temp.verify(not first?'error','Discovery failed '||first::text);
 perform pg_temp.verify(public.scavenging_action('finish',q)=first,'Discovery retry changed');
 r:=public.bin_diving_state();perform pg_temp.verify((r->'inventory'->>'kevlar_vest_blueprint')::int=1,'Discovery absent from stash');
 reset role;
 perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='kevlar_vest_blueprint')=1,'Discovery duplicated blueprint');
end$$;

rollback;
