begin;
create function pg_temp.verify(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();s uuid:=game_private.current_season();d uuid;bid uuid;pid uuid;q jsonb;r jsonb;first jsonb;site jsonb;attempt uuid;job uuid;gear uuid;denied boolean;
begin
 insert into auth.users(id) values(a),(b);
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('game.reason','CI bandages fixture',true);
 update public.game_settings set value=300 where key='actions_per_minute';
 update public.game_settings set value=20 where key='bandage_heal_amount';
 update public.game_settings set value=0 where key='scavenging_patrol_enabled';
 update public.game_bin_rules set cash_chance=0,pickaxe_chance=0,lockpick_chance=0,pistol_blueprint_chance=0,bullet_blueprint_chance=0,bandages_blueprint_chance=100;
 select id into d from public.game_districts where slug='the-waterfront';
 q:=jsonb_build_object('season_id',s,'district_id',d,'request_id',gen_random_uuid());
 r:=public.scavenging_action('enter',q);perform pg_temp.verify(not r?'error','Enter failed '||r::text);
 select x into site from jsonb_array_elements(public.bin_diving_state()->'scavenging'->'targets')x where x->>'kind'='bin' limit 1;
 update game_private.scav_sessions set node=(site->>'node')::int,route_points=jsonb_build_array(jsonb_build_array((site->>'node')::int%5,(site->>'node')::int/5)) where player_id=a;
 attempt:=gen_random_uuid();
 r:=public.scavenging_action('search',q||jsonb_build_object('request_id',attempt,'target_id',site->>'id'));perform pg_temp.verify(not r?'error','Search failed '||r::text);
 update game_private.scav_sessions set pending=pending||jsonb_build_object('ready_at',clock_timestamp()-interval '1 second') where player_id=a;
 q:=jsonb_build_object('season_id',s,'attempt_id',attempt,'request_id',gen_random_uuid());
 set local role authenticated;
 first:=public.scavenging_action('finish',q);perform pg_temp.verify(not first?'error','Discovery failed '||first::text);
 perform pg_temp.verify(public.scavenging_action('finish',q)=first,'Discovery retry changed');
 r:=public.bin_diving_state();perform pg_temp.verify((r->'inventory'->>'bandages_blueprint')::int=1,'Discovery absent from stash');
 reset role;
 perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='bandages_blueprint')=1,'Discovery duplicated blueprint');
 q:=jsonb_build_object('season_id',s,'recipe_id','bandages','version',1,'source','carried','request_id',gen_random_uuid());
 first:=public.crafting_action('learn',q);perform pg_temp.verify(not first?'error','Learning failed '||first::text);
 perform pg_temp.verify(public.crafting_action('learn',q)=first,'Learning retry changed');
 perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='bandages_blueprint')=0,'Learning did not consume exactly one');
 perform pg_temp.verify(exists(select 1 from public.game_learned_blueprints where season_id=s and player_id=a and recipe_id='bandages'),'Knowledge missing');
 select p.id,b.id into pid,bid from public.game_district_plots p join public.game_district_buildings b on b.plot_id=p.id where p.season_id=s and p.code='W25';
 update public.game_property_leases set released_at=clock_timestamp() where building_id=bid and released_at is null;
 update public.game_players set cash=10000 where id=a;
 r:=public.property_action('rent',jsonb_build_object('season_id',s,'plot_id',pid,'rent',300,'version',1,'request_id',gen_random_uuid()));perform pg_temp.verify(not r?'error','Lease failed '||r::text);
 r:=public.property_action('install_station',jsonb_build_object('season_id',s,'plot_id',pid,'cost',500,'space',20,'request_id',gen_random_uuid()));perform pg_temp.verify(not r?'error','Station failed '||r::text);
 insert into public.game_inventory(season_id,player_id,good_id,quantity) values(s,a,'silk',1) on conflict(season_id,player_id,good_id) do update set quantity=game_inventory.quantity+1;
 q:=q||jsonb_build_object('request_id',gen_random_uuid(),'building_id',bid,'batches',1);
 r:=public.crafting_action('start',q);perform pg_temp.verify(not r?'error','Craft failed '||r::text);job:=(r->>'job_id')::uuid;
 update public.game_season_jobs set ready_at=clock_timestamp()-interval '1 second' where id=job;
 r:=public.crafting_action('collect',jsonb_build_object('season_id',s,'job_id',job,'destination','carried','request_id',gen_random_uuid()));perform pg_temp.verify(not r?'error','Collect failed '||r::text);
 perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='bandages')=5,'Wrong craft output');
 update public.game_season_players set health=37 where season_id=s and player_id=a;
 q:=jsonb_build_object('season_id',s,'item_key','good:bandages','request_id',gen_random_uuid(),'heal',99999,'player_id',b);
 set local role authenticated;
 first:=public.inventory_action('use_bandage',q);perform pg_temp.verify(not first?'error' and (first->>'health')::numeric=57,'Server heal amount ignored '||first::text);
 perform pg_temp.verify(public.inventory_action('use_bandage',q)=first,'Healing retry changed');
 r:=public.inventory_action('use_bandage',q||'{"heal":1}');perform pg_temp.verify(r?'error','Mismatched nonce accepted');
 reset role;
 perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='bandages')=4,'Retry double-consumed');
 perform pg_temp.verify((select health from public.game_season_players where season_id=s and player_id=b) is null,'Foreign vitals changed');
 perform pg_temp.verify(exists(select 1 from public.game_inventory_ledger where player_id=a and good_id='bandages' and delta=-1),'Consumption ledger missing');
 perform pg_temp.verify(exists(select 1 from public.game_audit where actor_id=a and reason like 'Use bandage:%'),'Health audit missing');
 update public.game_settings set value=35 where key='bandage_heal_amount';
 update public.game_season_players set health=95 where season_id=s and player_id=a;
 q:=q||jsonb_build_object('request_id',gen_random_uuid());r:=public.inventory_action('use_bandage',q);
 perform pg_temp.verify((r->>'healed')::numeric=5 and (r->>'health')::numeric=100,'Normal max cap failed');
 q:=q||jsonb_build_object('request_id',gen_random_uuid());r:=public.inventory_action('use_bandage',q);perform pg_temp.verify(r?'error','Full health consumed item');
 update public.game_season_players set health=120 where season_id=s and player_id=a;
 r:=public.inventory_action('use_bandage',q);perform pg_temp.verify(r?'error','Boosted health consumed item');
 perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='bandages')=3,'Failed heal consumed item');
 update public.game_season_players set health=20 where season_id=s and player_id=a;
 r:=public.inventory_action('equip',jsonb_build_object('season_id',s,'item_key','good:bandages','equipment_slot','medical','request_id',gen_random_uuid()));perform pg_temp.verify(not r?'error','Medical equip failed '||r::text);
 select id into gear from public.game_inventory_gear where season_id=s and player_id=a and equipment_slot='medical';
 perform set_config('request.jwt.claim.sub',b::text,true);
 update public.game_season_players set health=20 where season_id=s and player_id=b;
 r:=public.inventory_action('use_bandage',jsonb_build_object('season_id',s,'item_key','gear:'||gear,'request_id',gen_random_uuid()));perform pg_temp.verify(r?'error','Consumed another player equipment');
 perform set_config('request.jwt.claim.sub',a::text,true);
 r:=public.inventory_action('use_bandage',jsonb_build_object('season_id',s,'item_key','gear:'||gear,'request_id',gen_random_uuid()));perform pg_temp.verify((r->>'health')::numeric=55,'Equipped healing or configured amount failed '||r::text);
 perform pg_temp.verify((select quantity=0 and location='retired' and equipment_slot is null from public.game_inventory_gear where id=gear),'Medical slot not cleared');
 r:=public.inventory_action('equip',jsonb_build_object('season_id',s,'item_key','good:bandages','equipment_slot','medical','request_id',gen_random_uuid()));
 select id into gear from public.game_inventory_gear where season_id=s and player_id=a and equipment_slot='medical';
 r:=public.inventory_action('gear_store',jsonb_build_object('season_id',s,'item_key','gear:'||gear,'building_id',bid,'request_id',gen_random_uuid()));perform pg_temp.verify(not r?'error','Gear storage fixture failed '||r::text);
 r:=public.inventory_action('use_bandage',jsonb_build_object('season_id',s,'item_key','gear:'||gear,'request_id',gen_random_uuid()));perform pg_temp.verify(r?'error','Consumed stored bandage remotely');
 update public.game_seasons set status='locked' where id=s;
 r:=public.inventory_action('use_bandage',q||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.verify(r?'error','Used item during locked season');
 update public.game_seasons set status='open' where id=s;
 r:=public.inventory_action('use_bandage',q||jsonb_build_object('season_id',gen_random_uuid(),'request_id',gen_random_uuid()));perform pg_temp.verify(r?'error','Stale season accepted');
 perform pg_temp.verify(not has_function_privilege('authenticated','game_private.inventory_action_before_bandages(text,jsonb)','execute'),'Retired helper exposed');
 perform pg_temp.verify(not has_function_privilege('anon','public.inventory_action(text,jsonb)','execute'),'Anonymous action exposed');
end$$;
select 'PASS: blueprint discovery, learning, crafting, healing, caps, configured amount, medical slot, privacy, audit and retries';
rollback;
