begin;
create function pg_temp.assert_bank(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
create function pg_temp.reject_bank_write() returns trigger language plpgsql as $$begin
 if current_setting('game.test_bank_failure',true)='on' then raise exception 'Simulated bank write failure';end if;return new;
end$$;
create trigger test_bank_failure before update on public.game_bank_accounts for each row execute function pg_temp.reject_bank_write();
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();owner_id uuid:=gen_random_uuid();s uuid:=game_private.current_season();next_s uuid;
 q jsonb;res jsonb;first jsonb;initial_cash bigint;initial_score numeric;after_score numeric;denied boolean;value jsonb;n int;before_entries int;before_cash bigint;
begin
 insert into auth.users(id) values(a),(b),(owner_id);
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',owner_id::text,true);perform public.game_state();
 update public.game_user_roles set role_id='owner' where player_id=owner_id;
 perform set_config('request.jwt.claim.sub',a::text,true);
 select cash into initial_cash from public.game_players where id=a;
 select score into initial_score from game_private.season_scores(s,'net_worth') where player_id=a;
 q:=jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'amount',1000,'player_id',b,'balance',99999999);
 set local role authenticated;
 res:=public.bank_state();
 perform pg_temp.assert_bank((res->>'balance')::bigint=0 and jsonb_array_length(res->'history')=0,'New bank is not empty');
 first:=public.bank_action('deposit',q);perform pg_temp.assert_bank(not first?'error','Deposit failed: '||first::text);
 res:=public.bank_action('deposit',q);perform pg_temp.assert_bank(res=first,'Retry changed receipt');
 res:=public.bank_action('deposit',q||'{"amount":2000}');perform pg_temp.assert_bank(res?'error','Reused nonce accepted changed amount');
 denied:=false;begin update public.game_bank_accounts set balance=99999;exception when insufficient_privilege then denied:=true;end;
 perform pg_temp.assert_bank(denied,'Direct balance writes permitted');
 denied:=false;begin perform 1 from public.game_bank_ledger;exception when insufficient_privilege then denied:=true;end;
 perform pg_temp.assert_bank(denied,'Private bank ledger exposed');
 reset role;
 perform pg_temp.assert_bank((select cash=initial_cash-1000 from public.game_players where id=a),'Wallet debit incorrect');
 perform pg_temp.assert_bank((select balance=1000 from public.game_bank_accounts where player_id=a and season_id=s),'Deposit or forged target incorrect');
 perform pg_temp.assert_bank(not exists(select 1 from public.game_bank_accounts where player_id=b),'Forged player ID received money');
 perform pg_temp.assert_bank((select count(*) from public.game_bank_ledger where player_id=a)=1,'Retry duplicated bank entry');
 perform pg_temp.assert_bank((select count(*) from public.game_ledger where player_id=a and reason='National Bank deposit: '||(q->>'request_id'))=1,'Missing or duplicated wallet ledger');
 select score into after_score from game_private.season_scores(s,'net_worth') where player_id=a;
 perform pg_temp.assert_bank(initial_score=after_score,'Deposit changed net worth');
 perform set_config('request.jwt.claim.sub',b::text,true);
 res:=public.bank_state();perform pg_temp.assert_bank((res->>'total')::int=0 and (res->>'balance')::bigint=0,'Another player sees bank records');
 res:=public.bank_action('withdraw',q||jsonb_build_object('request_id',gen_random_uuid()));
 perform pg_temp.assert_bank(res?'error','Stranger withdrew someone else money');
 perform pg_temp.assert_bank(not exists(select 1 from public.game_bank_accounts where player_id=b),'Failed withdrawal left an empty account');
 perform set_config('request.jwt.claim.sub',a::text,true);
 res:=public.bank_action('withdraw',q||jsonb_build_object('request_id',gen_random_uuid(),'amount',300));
 perform pg_temp.assert_bank(not res?'error','Withdrawal failed: '||res::text);
 perform pg_temp.assert_bank((select cash=initial_cash-700 from public.game_players where id=a),'Withdrawal did not credit cash');
 perform pg_temp.assert_bank((select balance=700 from public.game_bank_accounts where player_id=a),'Withdrawal balance incorrect');
 select score into after_score from game_private.season_scores(s,'net_worth') where player_id=a;
 perform pg_temp.assert_bank(initial_score=after_score,'Withdrawal changed net worth');
 foreach value in array array['0'::jsonb,'-1'::jsonb,'1.5'::jsonb,'"100"'::jsonb,'null'::jsonb,'true'::jsonb,'1000000001'::jsonb] loop
  res:=public.bank_action('deposit',q||jsonb_build_object('request_id',gen_random_uuid(),'amount',value));
  perform pg_temp.assert_bank(res?'error','Invalid amount accepted: '||value::text);
 end loop;
 res:=public.bank_action('deposit',q||jsonb_build_object('request_id',gen_random_uuid(),'amount',initial_cash));
 perform pg_temp.assert_bank(res?'error','Overdraft deposit succeeded');
 res:=public.bank_action('withdraw',q||jsonb_build_object('request_id',gen_random_uuid(),'amount',701));
 perform pg_temp.assert_bank(res?'error','Bank overdraft succeeded');
 res:=public.bank_action('deposit',q-'request_id');perform pg_temp.assert_bank(res?'error','Missing nonce accepted');
 res:=public.bank_action('deposit',q-'season_id');perform pg_temp.assert_bank(res?'error','Missing season accepted');
 -- A failure after the wallet has moved must roll back the wallet, account and both ledgers.
 perform set_config('game.test_bank_failure','on',true);
 res:=public.bank_action('deposit',q||jsonb_build_object('request_id',gen_random_uuid(),'amount',100));
 perform pg_temp.assert_bank(res?'error','Simulated account failure not raised');
 perform set_config('game.test_bank_failure','off',true);
 perform pg_temp.assert_bank((select cash=initial_cash-700 from public.game_players where id=a),'Bank failure lost wallet funds');
 perform pg_temp.assert_bank((select count(*) from public.game_bank_ledger where player_id=a)=2,'Failed transfer created bank ledger');
 perform pg_temp.assert_bank((select count(*) from public.game_ledger where player_id=a and reason like 'National Bank %')=2,'Failed transfer created wallet ledger');
 -- The actual Owner setting path remains permission-checked and audited.
 set local role authenticated;
 res:=public.staff_action('setting','{"key":"bank_deposits_enabled","value":0,"reason":"Pause deposits test"}');
 perform pg_temp.assert_bank(res?'error','Player paused the bank');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 res:=public.staff_action('setting','{"key":"bank_deposits_enabled","value":0,"reason":"Pause deposits test"}');
 perform pg_temp.assert_bank(not res?'error','Owner cannot configure bank: '||res::text);
 perform set_config('request.jwt.claim.sub',a::text,true);
 res:=public.bank_action('deposit',q||jsonb_build_object('request_id',gen_random_uuid(),'amount',100));
 perform pg_temp.assert_bank(res?'error','Paused bank accepted deposits');
 res:=public.bank_action('withdraw',q||jsonb_build_object('request_id',gen_random_uuid(),'amount',100));
 perform pg_temp.assert_bank(not res?'error','Pausing deposits trapped withdrawals');
 reset role;
 update public.game_settings set value=1 where key='bank_deposits_enabled';
 for n in 1..11 loop
  res:=public.bank_action('deposit',q||jsonb_build_object('request_id',gen_random_uuid(),'amount',1));
  perform pg_temp.assert_bank(not res?'error','Statement setup transfer failed');
 end loop;
 res:=public.bank_state(0);perform pg_temp.assert_bank((res->>'total')::int=14 and jsonb_array_length(res->'history')=10,'Statement page one incorrect');
 res:=public.bank_state(10);perform pg_temp.assert_bank(jsonb_array_length(res->'history')=4,'Statement page two incorrect');
 perform pg_temp.assert_bank((res->'totals'->>'deposited')::int=1011 and (res->'totals'->>'withdrawn')::int=400,'Flow totals incorrect');
 set local time zone 'Pacific/Auckland';
 res:=public.bank_state();perform pg_temp.assert_bank(jsonb_array_length(res->'flow')=7,'UTC flow length incorrect');
 perform pg_temp.assert_bank((select sum((x->>'deposits')::numeric) from jsonb_array_elements(res->'flow') x)=1011,'UTC flow lost deposits');
 denied:=false;begin delete from public.game_bank_ledger where player_id=a;exception when raise_exception then denied:=true;end;
 perform pg_temp.assert_bank(denied,'Ledger can be deleted');
 denied:=false;begin update public.game_bank_ledger set delta=0;exception when raise_exception then denied:=true;end;
 perform pg_temp.assert_bank(denied,'Ledger can be modified');
 denied:=false;begin delete from public.game_bank_accounts where player_id=a;exception when raise_exception then denied:=true;end;
 perform pg_temp.assert_bank(denied,'Account history can be deleted');
 denied:=false;begin delete from game_private.bank_requests where player_id=a;exception when raise_exception then denied:=true;end;
 perform pg_temp.assert_bank(denied,'Transfer references can be deleted');
 perform set_config('game.bank_request_id','',true);
 denied:=false;begin update public.game_bank_accounts set balance=balance+1 where player_id=a;exception when raise_exception then denied:=true;end;
 perform pg_temp.assert_bank(denied,'Unreferenced balance change allowed');
 -- Real season snapshot/reset path preserves archived money and immutable records.
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 res:=public.season_action('create','{"name":"Bank next season","reason":"Bank reset test"}');
 perform pg_temp.assert_bank(not res?'error','Cannot create next season: '||res::text);next_s:=(res->>'season_id')::uuid;
 res:=public.season_action('lock',jsonb_build_object('season_id',s,'reason','Bank reset test'));
 perform pg_temp.assert_bank(not res?'error','Cannot lock season: '||res::text);
 perform set_config('request.jwt.claim.sub',a::text,true);
 res:=public.bank_action('deposit',q||jsonb_build_object('request_id',gen_random_uuid(),'amount',1));perform pg_temp.assert_bank(res?'error','Closed season transfer allowed');
 res:=public.bank_action('deposit',q);perform pg_temp.assert_bank(res=first,'Closed season retry lost original receipt');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 res:=public.season_action('snapshot',jsonb_build_object('season_id',s,'reason','Bank snapshot test'));perform pg_temp.assert_bank(not res?'error','Cannot snapshot bank season: '||res::text);
 res:=public.season_action('archive',jsonb_build_object('season_id',s,'reason','Bank archive test'));perform pg_temp.assert_bank(not res?'error','Cannot archive bank season: '||res::text);
 res:=public.season_action('launch_next',jsonb_build_object('season_id',next_s,'expected_current_season',s,'confirmation','RESET '||(select name from public.game_seasons where id=s),'reason','Bank reset test'));
 perform pg_temp.assert_bank(not res?'error','Cannot reset bank season: '||res::text);
 perform set_config('request.jwt.claim.sub',a::text,true);
 res:=public.bank_state();perform pg_temp.assert_bank((res->>'balance')::bigint=0 and (res->>'total')::int=0,'Old balance leaked into new season');
 res:=public.bank_action('deposit',q);perform pg_temp.assert_bank(res?'error','Old request crossed season');
 perform pg_temp.assert_bank((select count(*) from public.game_bank_ledger where player_id=a and season_id=s)=14,'Reset deleted bank ledger');
 perform pg_temp.assert_bank((select balance from public.game_bank_accounts where player_id=a and season_id=s)=611,'Reset changed old bank account');
 perform pg_temp.assert_bank((select count(*) from game_private.bank_requests where player_id=a and season_id=s)=14,'Reset deleted transfer history');
end$$;
select 'PASS: bank ownership, conservation, ledger integrity, retries, rollback, pagination, UTC flow, permissions, limits, settings and real season reset';
rollback;
