begin;
create function pg_temp.verify(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();o uuid:=gen_random_uuid();s uuid:=game_private.current_season();bid uuid;pid uuid;f uuid;
 q jsonb;res jsonb;first jsonb;jobid uuid;paused timestamptz;d jsonb;denied boolean;next_s uuid;ledger0 bigint;
begin
 insert into auth.users(id) values(a),(b),(o);
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',o::text,true);perform public.game_state();
 update public.game_user_roles set role_id='owner' where player_id=o;
 perform set_config('game.reason','CI crafting fixtures',true);
 update public.game_settings set value=300 where key='actions_per_minute';
 update public.game_settings set value=100000 where key='inventory_weight_limit_grams';
 update public.game_players set cash=10000 where id=a;
 perform set_config('request.jwt.claim.sub',a::text,true);
 select p.id,b.id into pid,bid from public.game_district_plots p join public.game_district_buildings b on b.plot_id=p.id where p.season_id=s and p.code='W25';
 update public.game_property_leases set released_at=clock_timestamp() where building_id=bid and released_at is null;
 res:=public.property_action('rent',jsonb_build_object('season_id',s,'plot_id',pid,'rent',300,'version',1,'request_id',gen_random_uuid()));
 perform pg_temp.verify(not res?'error','Lease fixture failed '||res::text);
 insert into public.game_inventory(season_id,player_id,good_id,quantity) values(s,a,'pistol_blueprint',2),(s,a,'bullet_blueprint',1),(s,a,'iron-ingot',12),(s,a,'copper-ingot',8);
 q:=jsonb_build_object('season_id',s,'building_id',bid,'recipe_id','homemade-pistol','version',1,'source','carried','request_id',gen_random_uuid());
 res:=public.crafting_action('start',q||'{"batches":1}');perform pg_temp.verify(res?'error','Unlearned recipe crafted');
 first:=public.crafting_action('learn',q);perform pg_temp.verify(not first?'error','Learning failed: '||first::text);
 res:=public.crafting_action('learn',q);perform pg_temp.verify(res=first,'Learning retry changed result');
 perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='pistol_blueprint')=1,'Learning consumed wrong quantity');
 res:=public.crafting_action('learn',q||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.verify(res?'error','Duplicate learning consumed a spare');
 perform pg_temp.verify((select count(*) from public.game_learned_blueprints where season_id=s and player_id=a)=1,'Knowledge duplicate');
 perform pg_temp.verify(exists(select 1 from public.game_inventory_ledger where player_id=a and good_id='pistol_blueprint' and delta=-1),'Blueprint consume omitted ledger');
 res:=public.crafting_action('start',q||jsonb_build_object('request_id',gen_random_uuid(),'batches',1));perform pg_temp.verify(res?'error','Crafted without a table');
 res:=public.property_action('install_station',jsonb_build_object('season_id',s,'plot_id',pid,'cost',500,'space',20,'request_id',gen_random_uuid()));perform pg_temp.verify(not res?'error','Station fixture failed');
 select id into f from public.game_property_stations where building_id=bid and player_id=a and removed_at is null;
 res:=public.inventory_action('store',jsonb_build_object('season_id',s,'building_id',bid,'good_id','iron-ingot','quantity',2,'request_id',gen_random_uuid()));perform pg_temp.verify(not res?'error','Store fixture failed');
 q:=q||jsonb_build_object('request_id',gen_random_uuid(),'source','both','batches',1,'output_units',9999);
 set local role authenticated;
 first:=public.crafting_action('start',q);perform pg_temp.verify(not first?'error','Combined source failed: '||first::text);
 res:=public.crafting_action('start',q);perform pg_temp.verify(res=first,'Queue retry changed result');
 jobid:=(first->>'job_id')::uuid;
 denied:=false;begin update public.game_learned_blueprints set recipe_id='homemade-bullets';exception when insufficient_privilege then denied:=true;end;perform pg_temp.verify(denied,'Direct knowledge update allowed');
 denied:=false;begin perform 1 from public.game_crafting_batches;exception when insufficient_privilege then denied:=true;end;perform pg_temp.verify(denied,'Private jobs exposed');
 reset role;
 perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='iron-ingot')=8,'Wrong combined carried deduction');
 perform pg_temp.verify((select quantity from public.game_storage_inventory where season_id=s and player_id=a and building_id=bid and good_id='iron-ingot')=0,'Property materials not consumed first');
 perform pg_temp.verify((select output_units from public.game_crafting_batches where job_id=jobid)=1,'Browser overrode output');

 -- Missing a later input rolls back earlier material reservations.
 select sum(quantity) into ledger0 from public.game_inventory where season_id=s and player_id=a and good_id in('iron-ingot','copper-ingot');
 res:=public.crafting_action('start',q||jsonb_build_object('request_id',gen_random_uuid(),'batches',3,'source','carried'));
 perform pg_temp.verify(res?'error','Crafted without all required inputs');
 perform pg_temp.verify((select sum(quantity) from public.game_inventory where season_id=s and player_id=a and good_id in('iron-ingot','copper-ingot'))=ledger0,'Failed craft partially consumed materials');

 res:=public.crafting_action('collect',jsonb_build_object('season_id',s,'job_id',jobid,'destination','carried','request_id',gen_random_uuid()));perform pg_temp.verify(res?'error','Collected before ready');
 res:=public.property_action('remove_station',jsonb_build_object('season_id',s,'plot_id',pid,'request_id',gen_random_uuid()));perform pg_temp.verify(res?'error','Removed an occupied crafting table');
 res:=public.property_action('vacate',jsonb_build_object('season_id',s,'plot_id',pid,'request_id',gen_random_uuid()));perform pg_temp.verify(res?'error','Returned keys with a pending job');
 perform set_config('request.jwt.claim.sub',b::text,true);d:=public.crafting_state();perform pg_temp.verify(jsonb_array_length(d->'learned')=0 and jsonb_array_length(d->'jobs')=0,'Player saw another player knowledge/jobs');
 res:=public.crafting_action('collect',jsonb_build_object('season_id',s,'job_id',jobid,'destination','carried','request_id',gen_random_uuid()));perform pg_temp.verify(res?'error','Stole another player output');
 update public.game_user_roles set role_id='moderator' where player_id=b;
 denied:=false;begin perform public.crafting_manage('{}');exception when raise_exception then denied:=true;end;perform pg_temp.verify(denied,'Moderator edited crafting economy');
 perform set_config('request.jwt.claim.sub',o::text,true);
 res:=public.crafting_manage('{"id":"homemade-pistol","version":1,"name":"Homemade pistol","description":"Rebalanced recipe","seconds":30,"output_units":2,"materials":{"iron-ingot":5,"copper-ingot":3},"enabled":true,"reason":"Balance the test crafting recipe"}');
 perform pg_temp.verify(not res?'error','Owner recipe edit failed '||res::text);
 perform pg_temp.verify((select output_units from public.game_crafting_batches where job_id=jobid)=1,'Owner edited queued output');
 perform pg_temp.verify(exists(select 1 from public.game_audit where actor_id=o and reason like 'Crafting recipe:%'),'Recipe edits not audited');
 perform set_config('request.jwt.claim.sub',a::text,true);
 res:=public.crafting_action('start',q||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.verify(res?'error','Accepted stale recipe');
 update public.game_seasons set status='locked',locked_at=clock_timestamp()-interval '5 minutes' where id=s;
 select ready_at into paused from public.game_season_jobs where id=jobid;
 res:=public.crafting_action('collect',jsonb_build_object('season_id',s,'job_id',jobid,'destination','carried','request_id',gen_random_uuid()));perform pg_temp.verify(res?'error','Crafting ran during locked season');
 update public.game_seasons set status='open',locked_at=null where id=s;
 perform pg_temp.verify((select ready_at>paused+interval '4 minutes' from public.game_season_jobs where id=jobid),'Pause time not restored');
 update public.game_season_jobs set ready_at=clock_timestamp()-interval '1 second' where id=jobid;
 update public.game_settings set value=1000 where key='inventory_weight_limit_grams';
 q:=jsonb_build_object('season_id',s,'job_id',jobid,'destination','carried','request_id',gen_random_uuid());
 res:=public.crafting_action('collect',q);perform pg_temp.verify(res?'error','Overweight collection allowed');perform pg_temp.verify((select status from public.game_season_jobs where id=jobid)='queued','Full bag destroyed completed job');
 update public.game_settings set value=100000 where key='inventory_weight_limit_grams';
 update public.game_storage_rules set capacity=20 where building_type='garage';
 res:=public.crafting_action('collect',q||'{"destination":"storage"}');perform pg_temp.verify(res?'error','Overfull storage collection allowed');
 update public.game_storage_rules set capacity=200 where building_type='garage';
 first:=public.crafting_action('collect',q);perform pg_temp.verify(not first?'error','Collection failed '||first::text);
 res:=public.crafting_action('collect',q);perform pg_temp.verify(res=first,'Collection retry duplicated output');
 perform pg_temp.verify((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='homemade-pistol')=1,'Incorrect crafted quantity');
 perform pg_temp.verify((select value from public.game_season_stats where season_id=s and player_id=a and metric='crafting')=1,'Crafting metric not recorded');
 -- Cancellation preserves materials in overflow-safe deliveries.
 q:=jsonb_build_object('season_id',s,'building_id',bid,'recipe_id','homemade-bullets','version',1,'source','carried','request_id',gen_random_uuid());
 res:=public.crafting_action('learn',q);perform pg_temp.verify(not res?'error','Bullet blueprint failed');
 res:=public.crafting_action('start',q||jsonb_build_object('batches',1,'request_id',gen_random_uuid()));perform pg_temp.verify(not res?'error','Bullet job failed');jobid:=(res->>'job_id')::uuid;
 first:=public.crafting_action('cancel',jsonb_build_object('season_id',s,'job_id',jobid,'request_id',gen_random_uuid()));perform pg_temp.verify(not first?'error','Cancellation failed');
 perform pg_temp.verify((select sum(quantity) from public.game_inventory_deliveries where season_id=s and player_id=a and reason='Returned crafting materials')=2,'Cancellation lost materials');
 -- A new season has no inherited learning; history remains intact.
 update public.game_seasons set status='archived',reset_at=clock_timestamp() where id=s;
 insert into public.game_seasons(name,status,starting_cash,starting_crates) values('Crafting test next','open',10000,5) returning id into next_s;
 update game_private.season_runtime set season_id=next_s where singleton;
 update public.game_players set season_id=next_s where id=a;
 d:=public.crafting_state();perform pg_temp.verify(jsonb_array_length(d->'learned')=0 and jsonb_array_length(d->'jobs')=0,'Crafting carried into next season');
 perform pg_temp.verify((select count(*) from public.game_learned_blueprints where player_id=a and season_id=s)=2,'Season reset deleted learning history');
end$$;
rollback;
