begin;
do $$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); c uuid:=gen_random_uuid(); s uuid:=game_private.current_season(); d uuid; p public.game_district_plots; r jsonb; q jsonb; auction uuid; offer uuid; before_cash bigint; ledger_count bigint; denied boolean; building uuid; gang_a uuid; gang_b uuid;
begin
 insert into auth.users(id) values(a),(b),(c);
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',c::text,true);perform public.game_state();
 perform set_config('game.reason','Rollback-only district test funding',true);
 update public.game_players set cash=100000 where id in(a,b,c);
 select id into d from public.game_districts where slug='the-waterfront';
 if (select count(*) from public.game_district_plots where district_id=d and season_id=s)<>24 then raise exception 'Waterfront needs 24 plots'; end if;
 if (select count(*) from public.game_district_businesses where district_id=d and season_id=s and archived_at is null)<>6 then raise exception 'Waterfront needs six businesses'; end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 select * into p from public.game_district_plots where district_id=d and season_id=s and code='W07';
 q:=jsonb_build_object('plot_id',p.id,'season_id',s,'version',p.version,'total',p.base_price+ceil(p.base_price*.03));
 set local role authenticated;
 denied:=false;begin update public.game_district_plots set owner_id=a where id=p.id;exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Browser can directly edit ownership'; end if;
 r:=public.district_action('buy',q||'{"total":1}'::jsonb);if not(r?'error') then raise exception 'Forged price accepted';end if;
 r:=public.district_action('buy',q||jsonb_build_object('season_id',gen_random_uuid()));if not(r?'error') then raise exception 'Wrong season accepted';end if;
 r:=public.district_action('buy',q);if r?'error' then raise exception 'Purchase failed: %',r;end if;
 reset role;
 if (select owner_id from public.game_district_plots where id=p.id)<>a then raise exception 'Owner not transferred';end if;
 if (select count(*) from public.game_property_sales where plot_id=p.id)<>1 then raise exception 'Missing property sale';end if;
 if (select cash from public.game_players where id=a)<>100000-(q->>'total')::bigint then raise exception 'Purchase debit wrong';end if;
 if not exists(select 1 from public.game_ledger where player_id=a and delta=-(q->>'total')::bigint) then raise exception 'Missing wallet ledger';end if;
 perform set_config('request.jwt.claim.sub',b::text,true);
 r:=public.district_action('buy',q);if not(r?'error') then raise exception 'Double purchase accepted';end if;
 r:=public.district_action('build',q||'{"building_type":"warehouse","cost":3000}'::jsonb);if not(r?'error') then raise exception 'Other player can build';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 r:=public.district_action('build',q||'{"building_type":"warehouse","cost":1}'::jsonb);if not(r?'error') then raise exception 'Forged construction price accepted';end if;
 r:=public.district_action('build',q||'{"building_type":"telegram","cost":6000}'::jsonb);if not(r?'error') then raise exception 'Zoning bypassed';end if;
 r:=public.district_action('build',q||'{"building_type":"warehouse","cost":3000}'::jsonb);if r?'error' then raise exception 'Construction failed: %',r;end if;
 r:=public.district_action('build',q||'{"building_type":"warehouse","cost":3000}'::jsonb);if not(r?'error') then raise exception 'Duplicate building';end if;
 r:=public.district_action('complete',q);if not(r?'error') then raise exception 'Early construction completion';end if;
 update public.game_district_buildings set ready_at=now()-interval '1 second' where plot_id=p.id;
 r:=public.district_action('complete',q);if r?'error' then raise exception 'Complete construction failed: %',r;end if;
 r:=public.district_action('sell',q||'{"price":5000,"offers_allowed":true}'::jsonb);if r?'error' then raise exception 'Sale listing failed %',r;end if;
 perform set_config('request.jwt.claim.sub',b::text,true);
 select cash into before_cash from public.game_players where id=b;
 r:=public.district_action('offer',q||'{"price":4000}'::jsonb);if r?'error' then raise exception 'Funded offer failed %',r;end if;
 if (select cash from public.game_players where id=b)<>before_cash-4120 then raise exception 'Offer not fully funded';end if;
 select id into offer from public.game_plot_offers where plot_id=p.id and buyer_id=b and status='open';
 r:=public.district_action('offer_cancel',q||jsonb_build_object('offer_id',offer));if r?'error' then raise exception 'Offer refund failed %',r;end if;
 if (select cash from public.game_players where id=b)<>before_cash then raise exception 'Offer refund amount wrong';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 r:=public.district_action('auction',q||'{"price":5000}'::jsonb);if r?'error' then raise exception 'Auction failed %',r;end if;
 select id into auction from public.game_plot_auctions where plot_id=p.id and status='open';
 perform set_config('request.jwt.claim.sub',b::text,true);
 r:=public.district_action('bid',q||'{"price":5000}'::jsonb);if r?'error' then raise exception 'First bid failed %',r;end if;
 perform set_config('request.jwt.claim.sub',c::text,true);
 r:=public.district_action('bid',q||'{"price":5100}'::jsonb);if r?'error' then raise exception 'Outbid failed %',r;end if;
 if (select cash from public.game_players where id=b)<>before_cash then raise exception 'Outbid refund wrong';end if;
 r:=public.district_action('auction_finish',q);if not(r?'error') then raise exception 'Early settlement allowed';end if;
 update public.game_plot_auctions set ends_at=now()-interval '1 second' where id=auction;
 r:=public.district_action('auction_finish',q);if r?'error' then raise exception 'Settlement failed %',r;end if;
 if (select owner_id from public.game_district_plots where id=p.id)<>c or (select owner_id from public.game_district_buildings where plot_id=p.id and archived_at is null)<>c or (select owner_id from public.game_district_businesses where plot_id=p.id and archived_at is null)<>c then raise exception 'Attached building and business title not transferred';end if;
 r:=public.district_action('auction_finish',q);if not(r?'error') then raise exception 'Duplicate settlement';end if;
 if (select sum(amount) from public.game_plot_escrow_entries where plot_id=p.id)<>0 then raise exception 'Escrow did not reconcile';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 r:=public.district_action('business',q||'{"name":"Stolen Company","status":"open"}'::jsonb);if not(r?'error') then raise exception 'Former owner can edit business';end if;
 select * into p from public.game_district_plots where district_id=d and season_id=s and code='W08';
 q:=jsonb_build_object('plot_id',p.id,'season_id',s,'version',p.version,'total',p.base_price+ceil(p.base_price*.03));
 update public.game_players set cash=0 where id=a;
 r:=public.district_action('buy',q);if not(r?'error') then raise exception 'Negative balance allowed';end if;
 if exists(select 1 from public.game_property_sales where plot_id=p.id) then raise exception 'Failed purchase left a sale record';end if;
 insert into public.game_user_roles(player_id,role_id) values(a,'moderator') on conflict(player_id) do update set role_id='moderator';
 denied:=false;begin perform public.district_manage('control',jsonb_build_object('district_id',d,'reason','Unauthorized moderation edit'));exception when others then denied:=true;end;
 if not denied then raise exception 'Moderator can edit economy by default';end if;
 insert into public.game_role_permissions(role_id,permission_id) values('moderator','districts.manage');
 r:=public.district_manage('control',jsonb_build_object('district_id',d,'controller_gang_id','','neutral_influence',100,'fortification',20,'status','neutral','reason','Explicitly granted district moderation'));
 if r?'error' then raise exception 'Explicit economic permission failed %',r;end if;
 if not exists(select 1 from public.game_audit where actor_id=a and reason='Explicitly granted district moderation') then raise exception 'Missing Owner audit';end if;
 insert into public.game_season_gangs(season_id,name) values(s,'Rollback Gang A') returning id into gang_a;
 insert into public.game_season_gangs(season_id,name) values(s,'Rollback Gang B') returning id into gang_b;
 insert into public.game_district_gang_control(season_id,district_id,gang_id,influence) values(s,d,gang_a,20),(s,d,gang_b,30);
 r:=public.district_state('the-waterfront');
 if jsonb_array_length(r->'influence')<>2 then raise exception 'Multi-gang territory missing';end if;
 denied:=false;begin update public.game_property_sales set price=1 where plot_id=p.id;exception when others then denied:=true;end;
 -- Ensure immutability is exercised on a row that exists.
 denied:=false;begin update public.game_district_events set description='erased' where district_id=d;exception when others then denied:=true;end;
 if not denied then raise exception 'Event history mutable';end if;
 update public.game_seasons set status='locked',locked_at=now() where id=s;
 r:=public.district_action('buy',q);if not(r?'error') then raise exception 'Locked season permits trading';end if;
 if exists(select 1 from public.game_players where cash<0) then raise exception 'Negative wallet found';end if;
end $$;
select 'PASS: district seed, RLS, forged quotes, duplicate purchases, zoning, construction, escrow offers, competing bids, attached title transfer, ledger, permissions, audit, multi-gang control, immutable events and season lock' as result;
rollback;
