begin;
create function pg_temp.fp_check(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
do $$declare u uuid:=gen_random_uuid();s uuid:=game_private.current_season();d uuid;c uuid:=gen_random_uuid();q jsonb;r jsonb;v game_private.scav_sessions;before_row game_private.scav_sessions;site jsonb;point jsonb;patrol jsonb;t timestamptz;nonce uuid;balance bigint;denied boolean;begin
 insert into auth.users(id) values(u);perform set_config('request.jwt.claim.sub',u::text,true);perform public.game_state();select id into d from public.game_districts where slug='the-waterfront';
 perform set_config('game.reason','CI first-person movement and pursuit assertions',true);
 update public.game_settings set value=0 where key='scavenging_patrol_enabled';
 q:=jsonb_build_object('season_id',s,'district_id',d,'request_id',gen_random_uuid());r:=public.scavenging_action('enter',q);perform pg_temp.fp_check(not r?'error','Entry failed');
 q:=q||jsonb_build_object('controller',c);
 set local role authenticated;r:=public.street_motion('begin',q);reset role;
 perform pg_temp.fp_check(r?'session' and not r?'error','Authenticated movement unavailable: '||r::text);
 perform pg_temp.fp_check(not has_function_privilege('anon','public.street_motion(text,jsonb)','EXECUTE'),'Anonymous movement access');
 r:=public.street_motion('step',q||'{"sequence":1,"dx":1,"dy":1,"sprint":false,"x":4,"y":2,"speed":99999}'::jsonb);
 select * into v from game_private.scav_sessions where player_id=u;
 perform pg_temp.fp_check(not r?'error','Valid input failed: '||r::text);
 perform pg_temp.fp_check(game_private.scav_route_length(v.route_points)<.08,'Forged speed or destination accepted');
 perform pg_temp.fp_check(abs(extract(epoch from v.arrives_at-v.departed_at)-.5)<.001,'Server lease duration changed');
 before_row:=v;r:=public.street_motion('step',q||'{"sequence":1,"dx":-1,"dy":-1}'::jsonb);select * into v from game_private.scav_sessions where player_id=u;
 perform pg_temp.fp_check(v.route_points=before_row.route_points and v.departed_at=before_row.departed_at,'Stale input restarted movement');
 r:=public.street_motion('step',q||'{"sequence":2,"dx":100,"dy":0}'::jsonb);perform pg_temp.fp_check(r?'error','Invalid direction accepted');
 r:=public.street_motion('step',q||jsonb_build_object('controller',gen_random_uuid(),'sequence',2,'dx',1,'dy',0));perform pg_temp.fp_check(r?'error','Old tab changed the active controls');
 r:=public.street_motion('step',q||'{"sequence":3,"dx":0,"dy":0}'::jsonb);select * into v from game_private.scav_sessions where player_id=u;
 perform pg_temp.fp_check(v.arrives_at=v.departed_at,'Key release failed to stop');
 perform pg_temp.fp_check(game_private.scav_position(before_row.route_points,before_row.departed_at,before_row.arrives_at,clock_timestamp()+interval '1 hour')=before_row.route_points->-1,'Disconnected input lease continued forever');
 perform pg_temp.fp_check(not game_private.foot_clear('[0.129,0.135]','[0.135,0.129]',.13),'Tiny corner clipping bypassed walls');
 point:=game_private.foot_step('[0,0]',1,1,.5,10,.13);perform pg_temp.fp_check(abs(sqrt((point->>0)::numeric^2+(point->>1)::numeric^2)-.05)<.00001,'Diagonal input speeds up travel');
 perform pg_temp.fp_check(not game_private.foot_clear('[0,0.5]','[1,0.5]',.13),'Building does not block sight');
 select x into site from jsonb_array_elements(public.bin_diving_state()#>'{scavenging,targets}')x where x->>'kind'='bin' limit 1;
 point:=jsonb_build_array((site->>'node')::int%5,((site->>'node')::int/5)::numeric+case when (site->>'node')::int/5=2 then -.04 else .04 end);
 update game_private.scav_sessions set route_points=jsonb_build_array(point),arrives_at=clock_timestamp(),departed_at=clock_timestamp() where player_id=u;
 nonce:=gen_random_uuid();r:=public.scavenging_action('search',q||jsonb_build_object('request_id',nonce,'target_id',site->>'id'));perform pg_temp.fp_check(not r?'error','Nearby search rejected: '||r::text);
 -- Detection starts a chase, cancels the search and never pays its loot. Walking alone was safe above.
 update public.game_settings set value=1 where key in('scavenging_search_chase_enabled','scavenging_patrol_enabled');
 t:=clock_timestamp();patrol:=jsonb_build_array(jsonb_build_object('id','test-detection','route_points',jsonb_build_array(point,jsonb_build_array(point->0,(point->>1)::numeric+case when (point->>1)::numeric>1 then -.5 else .5 end),point),'epoch',extract(epoch from t),'seconds_per_block',8,'radius',.22));
 update game_private.scav_sessions set pending=pending||jsonb_build_object('patrols',patrol,'patrol_sentence_minutes',5,'started_at',t,'ready_at',t+interval '10 seconds') where player_id=u;
 select cash into balance from public.game_players where id=u;r:=game_private.scav_resolve_patrol();
 perform pg_temp.fp_check((r->>'pursuit')::boolean and not coalesce((r->>'caught')::boolean,false),'Detection skipped warning and chase: '||r::text);
 select * into v from game_private.scav_sessions where player_id=u;
 perform pg_temp.fp_check(v.pending is null and v.pursuit->>'kind'='foot','Search not converted to on-foot pursuit');
 perform pg_temp.fp_check(not (public.prison_state()->>'jailed')::boolean,'Warning phase already imprisoned player');
 perform pg_temp.fp_check((select cash from public.game_players where id=u)=balance and not exists(select 1 from public.game_bin_dives where player_id=u),'Interrupted search paid loot');
 r:=public.scavenging_action('enter',q||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.fp_check(r?'error','District change escaped pursuit');
 -- Disconnecting cannot avoid the closing cordon; retries must retain a single arrest.
 update game_private.scav_sessions set pursuit=pursuit||jsonb_build_object('deadline',clock_timestamp()-interval '1 second') where player_id=u;
 r:=public.prison_state();perform pg_temp.fp_check((r->>'jailed')::boolean,'Offline cordon failed to arrest');
 r:=public.prison_state();perform pg_temp.fp_check((select count(*) from game_private.scav_arrests where player_id=u)=1,'Retry duplicated arrest history');
 set local role authenticated;denied:=false;begin perform game_private.street_settle(s,u,'escaped');exception when insufficient_privilege then denied:=true;end;reset role;perform pg_temp.fp_check(denied,'Browser can forge an escape');
end$$;
select 'PASS: first-person input authority, stale tabs, replay, lease expiry, collision, proximity, pursuit grace, interrupted loot and offline custody';
rollback;
