
begin;
do $$
declare owner_id uuid:=gen_random_uuid(); mod_id uuid:=gen_random_uuid(); player uuid:=gen_random_uuid();
 sid uuid:=gen_random_uuid(); res jsonb; blocked boolean; balance bigint; msg_id uuid; i integer;
begin
 insert into auth.users(id) values(owner_id),(mod_id),(player);
 perform set_config('request.jwt.claim.sub',owner_id::text,true); perform public.game_state();
 perform set_config('request.jwt.claim.sub',mod_id::text,true); perform public.game_state();
 perform set_config('request.jwt.claim.sub',player::text,true); perform public.game_state();
 update public.game_user_roles set role_id='owner' where player_id=owner_id;
 update public.game_user_roles set role_id='moderator' where player_id=mod_id;
 set local role authenticated;
 res:=public.staff_action('grant_money',jsonb_build_object('player_id',player,'amount',50,'reason','test grant'));
 if not res ? 'error' then raise exception 'Player granted money'; end if;
 blocked:=false; begin perform game_private.act('job','{"job":"docks"}'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'Unguarded economic function exposed'; end if;
 perform set_config('request.jwt.claim.sub',mod_id::text,true);
 res:=public.staff_action('grant_money',jsonb_build_object('player_id',mod_id,'amount',50,'reason','self grant'));
 if not res ? 'error' then raise exception 'Moderator granted money'; end if;
 res:=public.staff_action('role',jsonb_build_object('player_id',mod_id,'role_id','owner','reason','escalate'));
 if not res ? 'error' then raise exception 'Moderator escalated'; end if;
 res:=public.staff_action('ban_permanent',jsonb_build_object('player_id',owner_id,'reason','target owner'));
 if not res ? 'error' then raise exception 'Moderator banned Owner'; end if;
 res:=public.staff_action('mute',jsonb_build_object('player_id',player,'minutes',10,'reason','test mute'));
 if res ? 'error' then raise exception 'Mute failed: %',res; end if;
 perform set_config('request.jwt.claim.sub',player::text,true);
 res:=public.community_action('chat','{"body":"muted message"}');
 if not res ? 'error' then raise exception 'Mute bypassed'; end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 reset role;
 select count(*)=1 into blocked from public.game_user_roles where role_id='owner';
 set local role authenticated;
 if blocked then
 res:=public.staff_action('role',jsonb_build_object('player_id',owner_id,'role_id','player','reason','remove owner'));
 if not res ? 'error' then raise exception 'Last Owner removed'; end if;
 end if;
 res:=public.staff_action('setting','{"key":"market_fee_percent","value":101,"reason":"invalid setting"}');
 if not res ? 'error' then raise exception 'Invalid setting accepted'; end if;
 res:=public.staff_action('setting','{"key":"market_fee_percent","value":7,"reason":"valid setting"}');
 if res ? 'error' then raise exception 'Owner setting failed'; end if;
 res:=public.staff_action('permission','{"role_id":"moderator","permission_id":"players.warn","enabled":false,"reason":"revoke permission"}');
 if res ? 'error' then raise exception 'Permission revocation failed'; end if;
 perform set_config('request.jwt.claim.sub',mod_id::text,true);
 res:=public.staff_action('warn',jsonb_build_object('player_id',player,'reason','revoked capability'));
 if not res ? 'error' then raise exception 'Revoked permission still works'; end if;
 res:=public.staff_action('kick',jsonb_build_object('player_id',player,'reason','session test'));
 if res ? 'error' then raise exception 'Kick failed'; end if;
 perform set_config('request.jwt.claim.sub',player::text,true);
 blocked:=false; begin perform public.game_state(); exception when raise_exception then blocked:=true; end;
 if not blocked then raise exception 'Kicked session still active'; end if;
 if exists(select 1 from public.game_players) then raise exception 'Kicked session can read REST'; end if;
 reset role;
 insert into auth.sessions(id,user_id,created_at) values(sid,player,clock_timestamp()+interval '1 second');
 perform set_config('request.jwt.claims',jsonb_build_object('session_id',sid)::text,true);
 set local role authenticated;
 perform public.game_state();
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 res:=public.staff_action('grant_money',jsonb_build_object('player_id',player,'amount',100,'reason','audited grant'));
 if res ? 'error' then raise exception 'Owner grant failed'; end if;
 reset role;
 if (select sum(delta) from public.game_ledger where player_id=player)<>(select cash from public.game_players where id=player) then raise exception 'Ledger mismatch'; end if;
 update public.game_players set cash=cash+1 where id=player;
 if (select sum(delta) from public.game_ledger where player_id=player)<>(select cash from public.game_players where id=player) then raise exception 'Direct adjustment not captured'; end if;
 blocked:=false; begin delete from public.game_ledger where player_id=player; exception when raise_exception then blocked:=true; end;
 if not blocked then raise exception 'Ledger deleted'; end if;
 blocked:=false; begin update public.game_audit set reason='tampered'; exception when raise_exception then blocked:=true; end;
 if not blocked then raise exception 'Audit mutable'; end if;
 blocked:=false; begin delete from auth.users where id=player; exception when foreign_key_violation then blocked:=true; end;
 if not blocked then raise exception 'Auth deletion cascaded history'; end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 set local role authenticated;
 perform public.community_action('chat','{"body":"retained message"}');
 reset role;
 select id into msg_id from public.game_chat where player_id=owner_id;
 set local role authenticated;
 perform public.staff_action('delete_chat',jsonb_build_object('id',msg_id,'reason','moderation test'));
 reset role;
 if not exists(select 1 from public.game_chat where id=msg_id and body='retained message' and deleted_at is not null) then raise exception 'Soft delete lost evidence'; end if;
 perform set_config('request.jwt.claim.sub',player::text,true);
 set local role authenticated;
 for i in 1..65 loop res:=public.game_action('invalid','{}'); end loop;
 if res->>'error' <> 'Too many actions. Try again in a minute.' then raise exception 'Failed requests bypass limiter: %',res; end if;
 reset role;
 -- A permanent ban must block both RPC mutations and direct reads.
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 set local role authenticated;
 res:=public.staff_action('ban_permanent',jsonb_build_object('player_id',player,'reason','ban regression'));
 if res ? 'error' then raise exception 'Ban failed'; end if;
 perform set_config('request.jwt.claim.sub',player::text,true);
 blocked:=false; begin perform public.game_action('job','{"job":"docks"}'); exception when raise_exception then blocked:=true; end;
 if not blocked then raise exception 'Banned player acted'; end if;
 if exists(select 1 from public.game_goods) then raise exception 'Ban bypassed via REST'; end if;
 reset role;
 update public.game_sanctions set expires_at=now()-interval '1 second' where player_id=player and kind='ban';
 set local role authenticated; perform public.game_state(); reset role;
 -- Evidence access and report management are separately enforced.
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 set local role authenticated;
 res:=public.community_action('report','{"subject":"Evidence test","body":"Report for permission testing"}');
 if res ? 'error' then raise exception 'Report failed'; end if;
 reset role;
 select id into msg_id from public.game_cases where player_id=owner_id limit 1;
 set local role authenticated;
 res:=public.staff_action('evidence',jsonb_build_object('case_id',msg_id,'body','Private staff evidence','reason','investigation'));
 if res ? 'error' then raise exception 'Evidence failed: %',res; end if;
 res:=public.staff_action('permission','{"role_id":"moderator","permission_id":"evidence.view","enabled":false,"reason":"restricted evidence"}');
 perform set_config('request.jwt.claim.sub',mod_id::text,true);
 res:=public.staff_state();
 if jsonb_array_length(res->'evidence')<>0 then raise exception 'Private evidence leaked'; end if;
 reset role;
 blocked:=false; begin truncate public.game_ledger; exception when raise_exception then blocked:=true; end;
 if not blocked then raise exception 'Ledger truncation permitted'; end if;
end $$;
select 'PASS: permissions, escalation denial, Owner protection, last Owner, settings validation, permission revocation, mute, session kick, REST denial, re-login, ledger conservation, immutable history, soft deletion, failure rate limit' as result;
rollback;
