begin;
create function pg_temp.check_inventory(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
create function pg_temp.fail_storage() returns trigger language plpgsql as $$begin if current_setting('inventory.test_fail',true)='on' then raise exception 'Simulated storage write failure';end if;return new;end$$;
create trigger test_storage_failure before insert or update on public.game_storage_inventory for each row execute function pg_temp.fail_storage();
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();o uuid:=gen_random_uuid();s uuid:=game_private.current_season();p public.game_district_plots;bld uuid;res jsonb;q jsonb;first jsonb;initial_score numeric;after_score numeric;initial_cash bigint;denied boolean;next_s uuid;n int;val jsonb;carry_before int;ledger_before bigint;frozen numeric;
begin
 insert into auth.users(id) values(a),(b),(o);
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',o::text,true);perform public.game_state();
 update public.game_user_roles set role_id='owner' where player_id=o;
 perform set_config('game.reason','CI inventory fixture funding',true);update public.game_players set cash=1000000 where id=a;
 perform set_config('request.jwt.claim.sub',a::text,true);
 select * into p from public.game_district_plots where season_id=s and status='available' and owner_type='none' and archived_at is null and zoning='industrial' and not exists(select 1 from public.game_district_buildings where plot_id=game_district_plots.id and archived_at is null) order by code limit 1;
 res:=public.district_action('buy',jsonb_build_object('season_id',s,'plot_id',p.id,'version',p.version,'total',p.base_price+ceil(p.base_price*.03)));
 perform pg_temp.check_inventory(not res?'error','Plot purchase failed: '||res::text);
 res:=public.district_action('build',jsonb_build_object('season_id',s,'plot_id',p.id,'building_type','warehouse','cost',3000));
 perform pg_temp.check_inventory(not res?'error','Warehouse construction failed: '||res::text);
 select id into bld from public.game_district_buildings where plot_id=p.id and archived_at is null;
 q:=jsonb_build_object('season_id',s,'building_id',bld,'good_id','whiskey','quantity',3,'request_id',gen_random_uuid(),'owner_id',b,'capacity',999999);
 res:=public.inventory_action('store',q);perform pg_temp.check_inventory(res?'error','Unfinished building accepted stock');
 update public.game_district_buildings set ready_at=now()-interval '1 second' where id=bld;
 res:=public.district_action('complete',jsonb_build_object('season_id',s,'plot_id',p.id));perform pg_temp.check_inventory(not res?'error','Construction did not complete');
 select cash into initial_cash from public.game_players where id=a;select score into initial_score from game_private.season_scores(s,'net_worth') where player_id=a;
 set local role authenticated;
 first:=public.inventory_action('store',q);perform pg_temp.check_inventory(not first?'error','Storage failed: '||first::text);
 res:=public.inventory_action('store',q);perform pg_temp.check_inventory(res=first,'Retry changed result');
 res:=public.inventory_action('store',q||'{"quantity":2}');perform pg_temp.check_inventory(res?'error','Changed request reused nonce');
 res:=public.inventory_state();perform pg_temp.check_inventory((res->'stores'->0->>'used')::int=3,'Storage state incorrect');
 denied:=false;begin update public.game_storage_inventory set quantity=99999;exception when insufficient_privilege then denied:=true;end;perform pg_temp.check_inventory(denied,'Direct storage write allowed');
 denied:=false;begin perform 1 from public.game_inventory_ledger;exception when insufficient_privilege then denied:=true;end;perform pg_temp.check_inventory(denied,'Private inventory ledger exposed');
 reset role;
 perform pg_temp.check_inventory((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='whiskey')=2,'Carried debit incorrect');
 perform pg_temp.check_inventory((select quantity from public.game_storage_inventory where building_id=bld and player_id=a and good_id='whiskey')=3,'Stored credit incorrect');
 perform pg_temp.check_inventory((select cash from public.game_players where id=a)=initial_cash,'Storage silently charged cash');
 perform pg_temp.check_inventory((select count(*) from public.game_inventory_ledger where player_id=a and request_id=(q->>'request_id')::uuid)=2,'Transfer ledger not paired');
 select score into after_score from game_private.season_scores(s,'net_worth') where player_id=a;perform pg_temp.check_inventory(initial_score=after_score,'Storing stock changed net worth');
 perform set_config('request.jwt.claim.sub',b::text,true);
 res:=public.inventory_state();perform pg_temp.check_inventory(jsonb_array_length(res->'stores')=0,'Another player sees private property contents');
 res:=public.inventory_action('retrieve',q||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.check_inventory(res?'error','Stranger retrieved another player stock');
 res:=public.inventory_action('store',q||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.check_inventory(res?'error','Stranger stored in another property');
 perform set_config('request.jwt.claim.sub',a::text,true);
 res:=public.game_action('list','{"good_id":"whiskey","quantity":3,"unit_price":100}');perform pg_temp.check_inventory(res?'error','Market listed protected warehouse stock');
 -- Stocked property cannot be sold, auctioned, offered or removed.
 denied:=false;begin update public.game_districts set archived_at=now() where id=p.district_id;exception when raise_exception then denied:=true;end;perform pg_temp.check_inventory(denied,'District archive stranded stored items');
 res:=public.district_action('sell',jsonb_build_object('season_id',s,'plot_id',p.id,'price',10000,'offers_allowed',true));perform pg_temp.check_inventory(res?'error','Stocked property listed');
 denied:=false;begin insert into public.game_plot_auctions(plot_id,seller_id,minimum_bid,tax_rate,ends_at) values(p.id,a,1000,3,now()+interval '1 day');exception when raise_exception then denied:=true;end;perform pg_temp.check_inventory(denied,'Stocked property auction opened');
 denied:=false;begin update public.game_district_plots set owner_id=b where id=p.id;exception when raise_exception then denied:=true;end;perform pg_temp.check_inventory(denied,'Storage ownership transferred');
 denied:=false;begin update public.game_district_buildings set owner_id=b where id=bld;exception when raise_exception then denied:=true;end;perform pg_temp.check_inventory(denied,'Building owner changed with stock');
 perform set_config('request.jwt.claim.sub',o::text,true);
 res:=public.district_manage('building',jsonb_build_object('season_id',s,'plot_id',p.id,'building_type','garage','reason','CI cannot strand stored goods'));perform pg_temp.check_inventory(res?'error','Owner replaced stocked warehouse');
 res:=public.inventory_manage('rule','{"building_type":"warehouse","version":1,"capacity":2,"enabled":false,"reason":"Reduce capacity without deleting goods"}');perform pg_temp.check_inventory(not res?'error','Owner capacity edit failed: '||res::text);
 perform pg_temp.check_inventory(exists(select 1 from public.game_audit where actor_id=o and reason like 'Inventory rules:%'),'Rule edit was not audited');
 perform set_config('request.jwt.claim.sub',a::text,true);
 denied:=false;begin perform public.inventory_manage('rule','{"building_type":"warehouse","capacity":9999,"enabled":true,"reason":"Unauthorized edit"}');exception when raise_exception then denied:=true;end;perform pg_temp.check_inventory(denied,'Player configured storage');
 res:=public.inventory_action('store',q||jsonb_build_object('request_id',gen_random_uuid(),'quantity',1));perform pg_temp.check_inventory(res?'error','Paused deposits accepted');
 res:=public.inventory_action('retrieve',q||jsonb_build_object('request_id',gen_random_uuid(),'quantity',1));perform pg_temp.check_inventory(not res?'error','Paused deposits trapped retrieval');
 update public.game_storage_rules set enabled=true where building_type='warehouse';
 res:=public.inventory_action('store',q||jsonb_build_object('request_id',gen_random_uuid(),'quantity',1));perform pg_temp.check_inventory(res?'error','Capacity limit ignored');
 update public.game_storage_rules set capacity=2000 where building_type='warehouse';
 foreach val in array array['0'::jsonb,'-1'::jsonb,'1.5'::jsonb,'"1"'::jsonb,'null'::jsonb,'1000001'::jsonb] loop
  res:=public.inventory_action('store',q||jsonb_build_object('request_id',gen_random_uuid(),'quantity',val));perform pg_temp.check_inventory(res?'error','Invalid quantity accepted');
 end loop;
 res:=public.inventory_action('store',q||jsonb_build_object('request_id',gen_random_uuid(),'quantity',4));perform pg_temp.check_inventory(res?'error','Stored more goods than carried');
 res:=public.inventory_action('retrieve',q||jsonb_build_object('request_id',gen_random_uuid(),'quantity',3));perform pg_temp.check_inventory(res?'error','Retrieved more than stored');
 select quantity into carry_before from public.game_inventory where season_id=s and player_id=a and good_id='whiskey';select count(*) into ledger_before from public.game_inventory_ledger where player_id=a;
 perform set_config('inventory.test_fail','on',true);
 res:=public.inventory_action('store',q||jsonb_build_object('request_id',gen_random_uuid(),'quantity',1));perform pg_temp.check_inventory(res?'error','Simulated write did not fail');
 perform set_config('inventory.test_fail','off',true);
 perform pg_temp.check_inventory((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='whiskey')=carry_before,'Failed storage lost carried stock');
 perform pg_temp.check_inventory((select count(*) from public.game_inventory_ledger where player_id=a)=ledger_before,'Failed transfer left ledger entries');
 -- Future registered goods join the same inventory and storage automatically.
 insert into public.game_goods(id,name,business_name,business_cost,batch_size,cycle_seconds,business_available) values('ci-inventory-good','CI future good','Test only',1,1,60,false);
 insert into public.game_inventory(season_id,player_id,good_id,quantity) values(s,a,'ci-inventory-good',4),(s,a,'pickaxe',2);
 res:=public.inventory_state();perform pg_temp.check_inventory(exists(select 1 from jsonb_array_elements(res->'goods') g where g->>'id'='ci-inventory-good'),'Future catalog item missing');
 res:=public.inventory_action('store',q||jsonb_build_object('request_id',gen_random_uuid(),'good_id','ci-inventory-good','quantity',1));perform pg_temp.check_inventory(not res?'error','Future item cannot be stored');
 res:=public.inventory_action('store',q||jsonb_build_object('request_id',gen_random_uuid(),'good_id','pickaxe','quantity',2));perform pg_temp.check_inventory(not res?'error','Pickaxe storage failed');
 res:=public.bin_diving_action('equip',jsonb_build_object('season_id',s,'request_id',gen_random_uuid()));perform pg_temp.check_inventory(res?'error','Equipped a protected pickaxe');
 res:=public.inventory_action('retrieve',q||jsonb_build_object('request_id',gen_random_uuid(),'good_id','pickaxe','quantity',1));perform pg_temp.check_inventory(not res?'error','Pickaxe retrieval failed');
 res:=public.bin_diving_action('equip',jsonb_build_object('season_id',s,'request_id',gen_random_uuid()));perform pg_temp.check_inventory(not res?'error','Retrieved pickaxe cannot be equipped');
 perform pg_temp.check_inventory(exists(select 1 from public.game_inventory_ledger where player_id=a and good_id='pickaxe' and location='carried' and delta=-1),'Equipment consumption missing from history');
 denied:=false;begin delete from public.game_inventory_ledger where player_id=a;exception when raise_exception then denied:=true;end;perform pg_temp.check_inventory(denied,'Inventory ledger can be deleted');
 denied:=false;begin delete from public.game_storage_inventory where player_id=a;exception when raise_exception then denied:=true;end;perform pg_temp.check_inventory(denied,'Stored records can be deleted');
 -- Actual season lifecycle preserves storage and its contribution to final rankings.
 perform set_config('request.jwt.claim.sub',o::text,true);
 res:=public.season_action('create','{"name":"Inventory next season","reason":"CI inventory reset"}');perform pg_temp.check_inventory(not res?'error','Season creation failed');next_s:=(res->>'season_id')::uuid;
 res:=public.season_action('lock',jsonb_build_object('season_id',s,'reason','CI inventory lock'));perform pg_temp.check_inventory(not res?'error','Season lock failed');
 perform set_config('request.jwt.claim.sub',a::text,true);
 res:=public.inventory_action('retrieve',q||jsonb_build_object('request_id',gen_random_uuid(),'quantity',1));perform pg_temp.check_inventory(res?'error','Locked season transfer allowed');
 res:=public.inventory_action('store',q);perform pg_temp.check_inventory(res=first,'Closed season replay lost original result');
 perform set_config('request.jwt.claim.sub',o::text,true);
 res:=public.season_action('snapshot',jsonb_build_object('season_id',s,'reason','CI inventory snapshot'));perform pg_temp.check_inventory(not res?'error','Season snapshot failed: '||res::text);
 res:=public.season_action('archive',jsonb_build_object('season_id',s,'reason','CI inventory archive'));perform pg_temp.check_inventory(not res?'error','Archive failed');
 res:=public.season_action('launch_next',jsonb_build_object('season_id',next_s,'expected_current_season',s,'confirmation','RESET '||(select name from public.game_seasons where id=s),'reason','CI inventory next season'));perform pg_temp.check_inventory(not res?'error','Season reset failed: '||res::text);
 perform set_config('request.jwt.claim.sub',a::text,true);
 res:=public.inventory_state();perform pg_temp.check_inventory(jsonb_array_length(res->'stores')=0,'Old property storage leaked into new season');
 res:=public.inventory_action('retrieve',q);perform pg_temp.check_inventory(res?'error','Old season request accepted');
 perform pg_temp.check_inventory((select sum(quantity) from public.game_storage_inventory where season_id=s and player_id=a)=4,'Reset deleted stored history');
 perform pg_temp.check_inventory(exists(select 1 from public.game_inventory_ledger where season_id=s and player_id=a),'Reset deleted inventory ledger');
end$$;
select 'PASS: inventory ownership, construction, capacity, conservation, retry, rollback, market isolation, equipment, future goods, audit, immutable history and real season reset';
rollback;
