begin;
-- Use the production RPCs and tables; roll back all fixtures at the end.
do $$
declare buyer uuid:=gen_random_uuid();seller uuid:=gen_random_uuid();other_seller uuid:=gen_random_uuid();
 s uuid:=game_private.current_season();d uuid;o uuid;r jsonb;request jsonb;first_result jsonb;before_cash bigint;t uuid;receipt_count bigint;
begin
 insert into auth.users(id) values(buyer),(seller),(other_seller);
 perform set_config('game.reason','CI partial buy orders',true);
 perform set_config('request.jwt.claim.sub',buyer::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',seller::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',other_seller::text,true);perform public.game_state();
 select id into d from public.game_districts where slug='the-waterfront';
 perform set_config('request.jwt.claim.sub',buyer::text,true);
 select cash into before_cash from public.game_players where id=buyer;
 request:=jsonb_build_object('season_id',s,'district_id',d,'good_id','whiskey','quantity',5,'unit_price',100,'request_id',gen_random_uuid());
 first_result:=public.district_market_order('create',request);
 if first_result?'error' then raise exception 'Create failed: %',first_result;end if;
 if public.district_market_order('create',request)<>first_result then raise exception 'Create replay failed';end if;
 select id into strict o from public.game_district_buy_orders where buyer_id=buyer;
 if (select cash from public.game_players where id=buyer)<>before_cash-500 then raise exception 'Incorrect escrow';end if;
 perform set_config('request.jwt.claim.sub',seller::text,true);
 request:=jsonb_build_object('season_id',s,'order_id',o,'quantity',2,'request_id',gen_random_uuid());
 first_result:=public.district_market_order('fill',request);
 if first_result?'error' then raise exception 'Partial fill failed: %',first_result;end if;
 if public.district_market_order('fill',request)<>first_result then raise exception 'Fill replay failed';end if;
 if not exists(select 1 from public.game_district_buy_orders where id=o and remaining_quantity=3 and escrow=300 and status='open') then raise exception 'Partial fill closed or misfunded order';end if;
 if (select count(*) from public.game_district_trades where buy_order_id=o)<>1 then raise exception 'Duplicate trade';end if;
 if (select count(*) from game_private.telegrams where season_id=s and sender_id in(buyer,seller) and recipient_id in(buyer,seller) and body like 'AUTOMATIC MARKET RECEIPT%')<>2 then raise exception 'Missing or duplicate Telegram receipts';end if;
 r:=public.district_market_order('fill',request||jsonb_build_object('request_id',gen_random_uuid(),'quantity',4));
 if not(r?'error') then raise exception 'Overfill accepted';end if;
 perform set_config('request.jwt.claim.sub',other_seller::text,true);
 r:=public.district_market_order('fill',request||jsonb_build_object('request_id',gen_random_uuid(),'quantity',3));
 if r?'error' then raise exception 'Second seller failed: %',r;end if;
 if not exists(select 1 from public.game_district_buy_orders where id=o and remaining_quantity=0 and escrow=0 and status='filled') then raise exception 'Order not fulfilled';end if;
 if (select count(*) from public.game_district_trades where buy_order_id=o)<>2 then raise exception 'Missing partial trades';end if;
 perform set_config('request.jwt.claim.sub',buyer::text,true);
 r:=public.district_market_order('create',jsonb_build_object('season_id',s,'district_id',d,'good_id','whiskey','quantity',3,'unit_price',100,'request_id',gen_random_uuid()));
 if r?'error' then raise exception 'Second order failed: %',r;end if;
 select id into strict o from public.game_district_buy_orders where buyer_id=buyer and status='open';
 perform set_config('request.jwt.claim.sub',seller::text,true);
 r:=public.district_market_order('fill',jsonb_build_object('season_id',s,'order_id',o,'quantity',1,'request_id',gen_random_uuid()));
 if r?'error' then raise exception 'Partial supply failed: %',r;end if;
 perform set_config('request.jwt.claim.sub',buyer::text,true);
 r:=public.district_market_order('cancel',jsonb_build_object('season_id',s,'order_id',o,'request_id',gen_random_uuid()));
 if r?'error' or (select cash from public.game_players where id=buyer)<>before_cash-600 then raise exception 'Remaining refund incorrect: %',r;end if;
 if (select count(*) from game_private.market_price_sales h join public.game_district_trades t on h.source_kind='order' and h.source_id=t.id::text where t.buyer_id=buyer)<>3 then raise exception 'Missing or duplicate price records';end if;
 r:=public.market_price_history('whiskey');
 if (r->>'total')::integer<3 or jsonb_array_length(r->'recent')>10 then raise exception 'Invalid price history response: %',r;end if;
 if public.telegram_preferences()<>'{"purchases":true,"sales":true}'::jsonb then raise exception 'Wrong default preferences';end if;
 perform public.telegram_preferences('{"purchases":false,"sales":true}');
 select count(*) into receipt_count from game_private.telegrams where recipient_id in(buyer,seller);
 perform game_private.market_trade_telegram(s,buyer,seller,'whiskey',1,100,5);
 if (select count(*) from game_private.telegrams where recipient_id in(buyer,seller))<>receipt_count+1 then raise exception 'Muted purchase alert was delivered or sale was muted';end if;
 perform set_config('request.jwt.claim.sub',seller::text,true);
 if public.telegram_preferences()<>'{"purchases":true,"sales":true}'::jsonb then raise exception 'Preferences leaked between accounts';end if;
 select a.thread_id into strict t from game_private.market_receipt_audience a where a.player_id=seller order by a.thread_id limit 1;
 if not game_private.telegram_access(t,seller) or game_private.telegram_access(t,buyer) then raise exception 'Receipt audience is incorrect';end if;
 r:=public.telegram_state(t);
 if r#>>'{thread,can_send}'<>'false' or jsonb_array_length(r->'messages')<>1 then raise exception 'Receipt thread is not readable/read-only: %',r;end if;
 r:=public.telegram_action('send',jsonb_build_object('thread_id',t,'body','Cannot reply'));
 if not(r?'error') then raise exception 'Receipt accepted a reply';end if;
 perform public.telegram_preferences('{"purchases":true,"sales":false}');
 select count(*) into receipt_count from game_private.telegrams where recipient_id in(buyer,seller);
 perform game_private.market_trade_telegram(s,buyer,seller,'whiskey',1,100,5);
 if (select count(*) from game_private.telegrams where recipient_id in(buyer,seller))<>receipt_count then raise exception 'Both-muted sale created receipts';end if;
 if has_function_privilege('authenticated','game_private.market_trade_telegram(uuid,uuid,uuid,text,integer,bigint,bigint,integer)','execute') then raise exception 'Players can forge free market notices';end if;
end $$;
select 'PASS: partial orders, request replay, multiple sellers, overfill rejection, escrow refunds and Telegram receipts';
rollback;
