
begin;
do $$
declare owner uuid:=gen_random_uuid(); a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); s uuid:=game_private.current_season();
 m public.game_mines; other public.game_mines; p public.game_district_plots; q jsonb; r jsonb; first jsonb; shift uuid; cost bigint; reserve bigint; before_cash bigint; aid uuid; denied boolean; nextseason uuid; original_ready timestamptz;
begin
 insert into auth.users(id) values(owner),(a),(b);
 perform set_config('request.jwt.claim.sub',owner::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 perform set_config('game.reason','Rollback-only mining test funding',true);
 update public.game_players set cash=1000000 where id in(owner,a,b);
 insert into public.game_user_roles(player_id,role_id) values(owner,'owner') on conflict(player_id) do update set role_id='owner';
 if (select count(*) from public.game_districts where archived_at is null)<>7 then raise exception 'Dashboard needs all seven districts';end if;
 if (select count(*) from public.game_mines where season_id=s)<>10 then raise exception 'Ten mines were not seeded';end if;
 select x.* into strict m from public.game_mines x join public.game_district_plots p on p.id=x.plot_id where p.code='MQ-01' and x.season_id=s;
 select x.* into strict other from public.game_mines x join public.game_district_plots p on p.id=x.plot_id where p.code='MQ-03' and x.season_id=s;
 q:=jsonb_build_object('season_id',s,'mine_id',m.id,'request_id',gen_random_uuid());
 perform set_config('request.jwt.claim.sub',a::text,true);
 set local role authenticated;
 denied:=false;begin update public.game_mines set remaining=0 where id=m.id;exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Browser can modify reserves';end if;
 r:=public.mining_action('start',q);if not(r?'error') then raise exception 'Mining without pickaxe was allowed';end if;
 r:=public.mining_action('pickaxe',q||'{"price":1}');if not(r?'error') then raise exception 'Forged pickaxe price accepted';end if;
 reset role;
 cost:=game_private.setting('mining_pickaxe_cost');
 r:=public.mining_action('pickaxe',q||jsonb_build_object('price',cost));if r?'error' then raise exception 'Pickaxe acquisition failed %',r;end if;
 if (select cash from public.game_players where id=a)<>1000000-cost then raise exception 'Pickaxe charge wrong';end if;
 if not exists(select 1 from public.game_ledger where player_id=a and delta=-cost and reason='Purchase mining pickaxe') then raise exception 'Missing pickaxe ledger';end if;
 reserve:=m.remaining;q:=q||jsonb_build_object('request_id',gen_random_uuid(),'quantity',999999,'good_id','steel','ready_at','2000-01-01');
 r:=public.mining_action('start',q);if r?'error' then raise exception 'Public mining failed %',r;end if;
 shift:=(r->>'run_id')::uuid;first:=r;
 r:=public.mining_action('start',q);if r<>first then raise exception 'Start retry is not idempotent';end if;
 if (select remaining from public.game_mines where id=m.id)<>reserve-4 then raise exception 'Forged browser yield accepted';end if;
 if (select durability from public.game_mining_tools where player_id=a and season_id=s)<>game_private.setting('mining_pickaxe_durability')-1 then raise exception 'Duplicate pickaxe wear';end if;
 r:=public.mining_action('start',q||jsonb_build_object('request_id',gen_random_uuid()));if not(r?'error') then raise exception 'Overlapping mining shifts accepted';end if;
 q:=jsonb_build_object('season_id',s,'mine_id',m.id,'run_id',shift,'request_id',gen_random_uuid());
 r:=public.mining_action('claim',q);if not(r?'error') then raise exception 'Early resources claimed';end if;
 perform set_config('request.jwt.claim.sub',b::text,true);r:=public.mining_action('claim',q);if not(r?'error') then raise exception 'Other player can claim a shift';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 update public.game_mining_runs set ready_at=now()-interval '1 second' where id=shift;
 r:=public.mining_action('claim',q);if r?'error' then raise exception 'Completed shift claim failed %',r;end if;
 first:=r;r:=public.mining_action('claim',q);if r<>first then raise exception 'Claim retry not idempotent';end if;
 r:=public.mining_action('claim',q||jsonb_build_object('request_id',gen_random_uuid()));if not(r?'error') then raise exception 'Duplicate resource grant';end if;
 if (select quantity from public.game_inventory where player_id=a and season_id=s and good_id='iron-ore')<>4 then raise exception 'Wrong mining inventory';end if;
 if (select count(*) from public.game_mining_yields where run_id=shift)<>1 then raise exception 'Extraction ledger duplicated';end if;
 denied:=false;begin delete from public.game_mining_yields where run_id=shift;exception when others then denied:=true;end;if not denied then raise exception 'Mining history deleted';end if;
 r:=public.game_action('list',jsonb_build_object('season_id',s,'good_id','iron-ore','quantity',1,'unit_price',30));if r?'error' then raise exception 'Mined resources cannot trade %',r;end if;
 before_cash:=(select cash from public.game_players where id=a);
 r:=public.game_action('business',jsonb_build_object('season_id',s,'good_id','iron-ore'));if not(r?'error') then raise exception 'Raw resource factory bypass';end if;
 if (select cash from public.game_players where id=a)<>before_cash then raise exception 'Rejected factory charged cash';end if;
 q:=jsonb_build_object('season_id',s,'mine_id',other.id,'request_id',gen_random_uuid());
 r:=public.mining_action('start',q);if not(r?'error') then raise exception 'Closed mine accepted public work';end if;
 denied:=false;begin perform public.mining_manage(q||'{"status":"open","reason":"Unauthorized opening"}');exception when others then denied:=true;end;
 if not denied then raise exception 'Player can edit mine rules';end if;
 insert into public.game_user_roles(player_id,role_id) values(a,'moderator') on conflict(player_id) do update set role_id='moderator';
 denied:=false;begin perform public.mining_manage(q||'{"status":"open","reason":"Unauthorized opening"}');exception when others then denied:=true;end;
 if not denied then raise exception 'Moderator can edit mining economy';end if;
 perform set_config('request.jwt.claim.sub',owner::text,true);
 r:=public.mining_manage(q||'{"status":"open","access_mode":"private","reason":"Release the copper claim"}');if r?'error' then raise exception 'Owner opening failed %',r;end if;
 if not exists(select 1 from public.game_audit where actor_id=owner and reason='Release the copper claim') then raise exception 'Owner edit missing audit';end if;
 q:=q||jsonb_build_object('request_id',gen_random_uuid(),'price',1000,'minutes',5,'reason','Auction city extraction rights');
 r:=public.mining_action('auction',q);if r?'error' then raise exception 'City auction failed %',r;end if;aid:=(r->>'auction_id')::uuid;
 r:=public.mining_manage(q||jsonb_build_object('request_id',gen_random_uuid(),'remaining',1));if not(r?'error') then raise exception 'Owner changed funded auction terms';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);before_cash:=(select cash from public.game_players where id=a);
 r:=public.mining_action('bid',q||jsonb_build_object('request_id',gen_random_uuid(),'price',1000));if r?'error' then raise exception 'Mine bid failed %',r;end if;
 if (select cash from public.game_players where id=a)<>before_cash-1030 then raise exception 'Mine bid not reserved with tax';end if;
 perform set_config('request.jwt.claim.sub',b::text,true);
 r:=public.mining_action('bid',q||jsonb_build_object('request_id',gen_random_uuid(),'price',1100));if r?'error' then raise exception 'Outbid failed %',r;end if;
 if (select cash from public.game_players where id=a)<>before_cash then raise exception 'Outbid funds not returned';end if;
 r:=public.mining_action('settle',q||jsonb_build_object('request_id',gen_random_uuid()));if not(r?'error') then raise exception 'Mine auction settled early';end if;
 update public.game_plot_auctions set ends_at=now()-interval '1 second' where id=aid;
 perform game_private.mining_close_due();
 if not exists(select 1 from public.game_district_plots where id=other.plot_id and owner_type='player' and owner_id=b) then raise exception 'Winner did not receive title';end if;
 if (select count(*) from public.game_property_sales where plot_id=other.plot_id)<>1 then raise exception 'Missing mine property history';end if;
 if (select sum(amount) from public.game_plot_escrow_entries where reference_id=aid)<>0 then raise exception 'Mine escrow not reconciled';end if;
 if (select cash from public.game_players where id=owner)<>1000000 then raise exception 'City sale paid administrator personally';end if;
 update public.game_mines set operated_at=now()-interval '310 seconds' where id=other.id;
 q:=jsonb_build_object('season_id',s,'mine_id',other.id,'request_id',gen_random_uuid());
 r:=public.mining_action('collect',q);if r?'error' then raise exception 'Owner mine production failed %',r;end if;
 if (select quantity from public.game_inventory where season_id=s and player_id=b and good_id='copper-ore')<>30 then raise exception 'Owner production yield wrong';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);r:=public.mining_action('collect',q);if not(r?'error') then raise exception 'Other player stole production';end if;
 -- Reservations, pickaxes and mine ownership are seasonal; a paused clock cannot earn output.
 q:=jsonb_build_object('season_id',s,'mine_id',m.id,'request_id',gen_random_uuid());
 r:=public.mining_action('start',q);if r?'error' then raise exception 'Second mining shift failed %',r;end if;
 shift:=(r->>'run_id')::uuid;select ready_at into original_ready from public.game_mining_runs where id=shift;
 update public.game_seasons set status='locked',locked_at=now()-interval '60 seconds' where id=s;
 r:=public.mining_action('start',q||jsonb_build_object('request_id',gen_random_uuid()));if not(r?'error') then raise exception 'Locked-season mining allowed';end if;
 update public.game_seasons set status='open',locked_at=null where id=s;
 if (select ready_at from public.game_mining_runs where id=shift)<original_ready+interval '60 seconds' then raise exception 'Paused mining clock was not extended';end if;
 perform game_private.mining_close_due(true);
 if exists(select 1 from public.game_mining_runs where season_id=s and status='working') then raise exception 'Snapshot retained active mining promises';end if;
 insert into public.game_seasons(name,status,starting_cash,starting_crates) values('Mining future season test','draft',10000,5) returning id into nextseason;
 perform game_private.ensure_districts(nextseason);
 if (select count(*) from public.game_mines where season_id=nextseason)<>10 then raise exception 'Mine catalog not ready for next season';end if;
 if exists(select 1 from public.game_district_plots where season_id=nextseason and owner_type='player') then raise exception 'Mine ownership carried into next season';end if;
 if exists(select 1 from public.game_mining_tools where season_id=nextseason) then raise exception 'Pickaxes carried into next season';end if;
end $$;
rollback;
select 'PASS: mine permissions, public shifts, idempotency, resource trading, reserves, auctions, title transfer, audit and seasonal isolation';

