
begin;
do $$
declare a uuid := gen_random_uuid(); b uuid := gen_random_uuid(); offer uuid; cash_a bigint; cash_b bigint; blocked boolean; payload jsonb;
begin
 insert into auth.users(id) values(a),(b);
 perform set_config('request.jwt.claim.sub',a::text,true);
 set local role authenticated;
 payload := public.game_state();
 if (payload->'player'->>'cash')::bigint <> 10000 then raise exception 'Starter cash failed'; end if;
 perform public.game_state();
 if (select quantity from public.game_inventory where player_id=a and good_id='whiskey') <> 5 then raise exception 'Starter duplicated'; end if;
 perform public.game_action('list','{"good_id":"whiskey","quantity":2,"unit_price":300}'::jsonb);
 select id into offer from public.game_listings where seller_id=a and status='active';
 blocked := false;
 begin perform public.game_action('buy',jsonb_build_object('listing_id',offer));
 exception when raise_exception then blocked := sqlerrm = 'You cannot buy your own offer.'; end;
 if not blocked then raise exception 'Self purchase guard failed'; end if;
 perform set_config('request.jwt.claim.sub',b::text,true);
 perform public.game_state();
 if exists(select 1 from public.game_players where id=a) then raise exception 'RLS leaked another wallet'; end if;
 blocked := false;
 begin update public.game_players set cash=999999 where id=b;
 exception when insufficient_privilege then blocked := true; end;
 if not blocked then raise exception 'Direct balance writes allowed'; end if;
 blocked := false;
 begin perform public.game_action('cancel',jsonb_build_object('listing_id',offer));
 exception when raise_exception then blocked := sqlerrm = 'This is not your offer.'; end;
 if not blocked then raise exception 'Other user cancellation allowed'; end if;
 perform public.game_action('buy',jsonb_build_object('listing_id',offer));
 select cash into cash_b from public.game_players where id=b;
 if cash_b <> 9400 then raise exception 'Buyer debit failed'; end if;
 if (select quantity from public.game_inventory where player_id=b and good_id='whiskey') <> 7 then raise exception 'Buyer inventory failed'; end if;
 blocked := false;
 begin perform public.game_action('buy',jsonb_build_object('listing_id',offer));
 exception when raise_exception then blocked := sqlerrm like 'That offer is no longer available%'; end;
 if not blocked then raise exception 'Double purchase allowed'; end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 select cash into cash_a from public.game_players where id=a;
 if cash_a <> 10570 or cash_a+cash_b <> 19970 then raise exception 'Seller credit or 5 percent fee failed'; end if;
 perform public.game_action('list','{"good_id":"whiskey","quantity":1,"unit_price":50}'::jsonb);
 select id into offer from public.game_listings where seller_id=a and status='active';
 perform public.game_action('cancel',jsonb_build_object('listing_id',offer));
 if (select quantity from public.game_inventory where player_id=a and good_id='whiskey') <> 3 then raise exception 'Cancellation escrow failed'; end if;
 blocked := false;
 begin perform public.game_action('list','{"good_id":"whiskey","quantity":-1,"unit_price":50}'::jsonb);
 exception when raise_exception then blocked := sqlerrm like 'Use a quantity%'; end;
 if not blocked then raise exception 'Negative listing allowed'; end if;
 perform public.game_action('job','{"job":"docks"}'::jsonb);
 blocked := false;
 begin perform public.game_action('job','{"job":"docks"}'::jsonb);
 exception when raise_exception then blocked := sqlerrm like 'Your crew is still recovering%'; end;
 if not blocked then raise exception 'Cooldown bypassed'; end if;
 perform public.game_action('business','{"good_id":"whiskey"}'::jsonb);
 blocked := false;
 begin perform public.game_action('collect','{"good_id":"whiskey"}'::jsonb);
 exception when raise_exception then blocked := sqlerrm = 'Production is not ready yet.'; end;
 if not blocked then raise exception 'Early production allowed'; end if;
 reset role;
 update public.game_businesses set collected_at=now()-interval '5 minutes' where player_id=a;
 set local role authenticated;
 perform public.game_action('collect','{"good_id":"whiskey"}'::jsonb);
 if (select quantity from public.game_inventory where player_id=a and good_id='whiskey') <> 6 then raise exception 'Production count failed'; end if;
 reset role;
 set local role anon;
 blocked := false;
 begin perform public.game_state(); exception when insufficient_privilege then blocked := true; end;
 if not blocked then raise exception 'Anonymous game access allowed'; end if;
 reset role;
end $$;
select 'PASS: bootstrap, RLS, direct-write denial, escrow, self-trade denial, ownership, purchase, fee conservation, double-purchase denial, cancellation, input bounds, cooldown, production and anonymous access' as result;
rollback;
