begin;
create function pg_temp.verify(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
do $$
declare owner_id uuid:=gen_random_uuid();a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();s uuid;v jsonb;sentence uuid;denied boolean;next_s uuid;
begin
 insert into auth.users(id) values(owner_id),(a),(b);
 perform set_config('request.jwt.claim.sub',owner_id::text,true);perform public.game_state();
 insert into public.game_user_roles(player_id,role_id) values(owner_id,'owner') on conflict(player_id) do update set role_id='owner';
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 s:=game_private.current_season();
 perform pg_temp.verify((select district_type from public.game_districts where slug='blackwater-island')='prison','Island is not a prison');
 perform pg_temp.verify(not (public.prison_state()->>'jailed')::boolean,'New player jailed');
 perform pg_temp.verify(not has_function_privilege('anon','public.prison_state()','execute'),'Anonymous prison access');
 perform pg_temp.verify(not has_function_privilege('authenticated','game_private.imprison(uuid,integer,text)','execute'),'Client can call internal arrest function');
 set local role authenticated;
 denied:=false;begin perform public.prison_manage('jail',jsonb_build_object('player_id',a,'minutes',10,'reason','Unauthorized'));exception when others then denied:=SQLERRM='Owner permission required.';end;
 perform pg_temp.verify(denied,'Ordinary player could imprison another player');
 reset role;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 v:=public.prison_manage('jail',jsonb_build_object('player_id',a,'minutes',10,'reason','Prison regression sentence'));sentence:=(v->>'sentence_id')::uuid;
 perform set_config('request.jwt.claim.sub',a::text,true);
 set local role authenticated;
 v:=public.prison_state();perform pg_temp.verify((v->>'jailed')::boolean and v->>'district_slug'='blackwater-island','Jailed player not located on island');
 perform pg_temp.verify((public.prison_state()->'sentence'->>'id')::uuid=sentence,'Sentence did not persist on reread');
 denied:=false;begin update public.game_prison_sentences set released_at=clock_timestamp() where player_id=a;exception when insufficient_privilege then denied:=true;end;
 perform pg_temp.verify(denied,'Player could release themselves');
 -- Direct RPC attempts must fail at the same server guard used by normal actions.
 v:=public.game_action('job',jsonb_build_object('season_id',s,'job_id','docks'));
 perform pg_temp.verify(v->>'error' like '%Blackwater Island Prison%','Jailed player could perform a job via RPC');
 reset role;
 perform set_config('request.jwt.claim.sub',b::text,true);set local role authenticated;
 perform pg_temp.verify((select count(*) from public.game_prison_sentences)=0,'Another player could see private sentence');
 perform pg_temp.verify(not (public.prison_state()->>'jailed')::boolean,'Sentence leaked into another identity');
 reset role;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 denied:=false;begin perform public.prison_manage('jail',jsonb_build_object('player_id',a,'minutes',30,'reason','Duplicate arrest'));exception when others then denied:=SQLERRM='This player is already in prison.';end;
 perform pg_temp.verify(denied,'Retry changed an active sentence');
 denied:=false;begin perform public.prison_manage('release',jsonb_build_object('player_id',a,'sentence_id',gen_random_uuid(),'reason','Stale release'));exception when others then denied:=true;end;
 perform pg_temp.verify(denied,'Stale release changed custody');
 perform public.prison_manage('release',jsonb_build_object('player_id',a,'sentence_id',sentence,'reason','Authorized early release'));
 perform set_config('request.jwt.claim.sub',a::text,true);
 perform pg_temp.verify(not (public.prison_state()->>'jailed')::boolean,'Early release failed');
 perform game_private.season_guard();
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 perform public.prison_manage('jail',jsonb_build_object('player_id',a,'minutes',1,'reason','Expiry regression sentence'));
 update public.game_prison_sentences set started_at=clock_timestamp()-interval '2 minutes',release_at=clock_timestamp()-interval '1 second' where player_id=a and season_id=s;
 perform set_config('request.jwt.claim.sub',a::text,true);
 perform pg_temp.verify(not (public.prison_state()->>'jailed')::boolean,'Expired sentence still holds player');
 perform game_private.season_guard();
 perform pg_temp.verify(exists(select 1 from public.game_audit where reason='Authorized early release'),'Release was not audited');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 denied:=false;begin perform public.prison_manage('jail',jsonb_build_object('player_id',a,'minutes',0,'reason','Invalid sentence'));exception when others then denied:=true;end;
 perform pg_temp.verify(denied,'Zero duration accepted');
 perform public.prison_manage('jail',jsonb_build_object('player_id',a,'minutes',10,'reason','Season boundary sentence'));
 insert into public.game_seasons(name,status,starting_cash,starting_crates) values('Prison next season','draft',10000,5) returning id into next_s;
 update game_private.season_runtime set season_id=next_s where singleton;
 perform set_config('request.jwt.claim.sub',a::text,true);
 perform pg_temp.verify(not (public.prison_state()->>'jailed')::boolean,'Old season sentence carried over');
end$$;
select 'PASS: prison designation, sentence persistence, permissions, privacy, gameplay lock, duplicate/stale requests, early release, expiry and season boundary';
rollback;

