begin;
create function pg_temp.verify(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
do $$
declare owner_id uuid:=gen_random_uuid();rescuer uuid:=gen_random_uuid();timer_rescuer uuid:=gen_random_uuid();inmate uuid:=gen_random_uuid();s uuid;v jsonb;attempt_id uuid;
 sentence_id uuid;start_request uuid:=gen_random_uuid();move_request uuid:=gen_random_uuid();before_xp integer;reward integer;target_release timestamptz;denied boolean;
begin
 insert into auth.users(id) values(owner_id),(rescuer),(timer_rescuer),(inmate);
 perform set_config('request.jwt.claim.sub',owner_id::text,true);perform public.game_state();
 insert into public.game_user_roles(player_id,role_id) values(owner_id,'owner') on conflict(player_id) do update set role_id='owner';
 perform set_config('request.jwt.claim.sub',rescuer::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',timer_rescuer::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',inmate::text,true);perform public.game_state();s:=game_private.current_season();
 perform pg_temp.verify(exists(select 1 from public.game_goods where id='lockpick' and inventory_category='tools'),'Lockpick item is missing');
 perform pg_temp.verify((select lockpick_chance between 0 and 100 from public.game_bin_rules),'Lockpick bin-diving chance setting is missing');
 perform pg_temp.verify(exists(select 1 from public.game_leaderboards where season_id=s and metric='breakouts' and enabled),'Breakout leaderboard is missing');
 perform pg_temp.verify(not has_function_privilege('authenticated','game_private.prison_break_action(text,jsonb)','execute'),'Client can execute the internal prison-break function');
 perform pg_temp.verify(has_function_privilege('authenticated','public.prison_break_action(text,jsonb)','execute'),'Client cannot execute the public prison-break action');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 v:=public.prison_manage('configure_breakout',jsonb_build_object('reward_power',77,'reason','Prison break regression reward'));reward:=(v->>'reward_power')::integer;
 perform pg_temp.verify(reward=77 and game_private.setting('prison_break_power')=77,'Owner reward setting did not persist');
 v:=public.prison_manage('jail',jsonb_build_object('player_id',inmate,'minutes',10,'reason','Breakout target sentence'));sentence_id:=(v->>'sentence_id')::uuid;
 insert into public.game_inventory(season_id,player_id,good_id,quantity) values(s,rescuer,'lockpick',2)
  on conflict(season_id,player_id,good_id) do update set quantity=excluded.quantity;
 select xp into before_xp from public.game_players where id=rescuer;
 perform set_config('request.jwt.claim.sub',rescuer::text,true);set local role authenticated;
 v:=public.prison_state();
 perform pg_temp.verify((v->>'lockpicks')::integer=2 and jsonb_array_length(v->'inmates')=1,'Available inmate or lockpick count is wrong');
 perform pg_temp.verify((v->>'reward_power')::integer=77,'Configured reward is missing from prison state');
 v:=public.prison_break_action('start',jsonb_build_object('season_id',s,'request_id',start_request,'sentence_id',sentence_id));
 attempt_id:=(v->'attempt'->>'id')::uuid;
 perform pg_temp.verify(v->>'outcome'='started' and not (v->'attempt'?'target_angle'),'Start did not create a secret lock challenge');
 perform pg_temp.verify((public.prison_state()->>'lockpicks')::integer=1,'Starting did not consume exactly one lockpick');
 denied:=false;begin perform 1 from game_private.prison_break_attempts where id=attempt_id;exception when insufficient_privilege then denied:=true;end;
 perform pg_temp.verify(denied,'Client could read the secret lock angle');
 reset role;
 update game_private.prison_break_attempts set target_angle=12 where id=attempt_id;
 set local role authenticated;
 v:=public.prison_break_action('tension',jsonb_build_object('season_id',s,'request_id',move_request,'attempt_id',attempt_id,'angle',12));
 perform pg_temp.verify(v->>'outcome'='success' and (v->>'reward_power')::integer=77,'Correct lock angle did not succeed');
 v:=public.prison_break_action('tension',jsonb_build_object('season_id',s,'request_id',move_request,'attempt_id',attempt_id,'angle',12));
 perform pg_temp.verify(v->>'outcome'='success','Idempotent success retry changed its result');
 reset role;
 perform pg_temp.verify((select xp from public.game_players where id=rescuer)=before_xp+77,'Successful breakout did not award configured power exactly once');
 perform pg_temp.verify((select value from public.game_season_stats where season_id=s and player_id=rescuer and metric='breakouts')=1,'Breakout metric was not recorded');
 perform pg_temp.verify((select released_at is not null from public.game_prison_sentences where id=sentence_id),'Successful breakout did not release the inmate');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 v:=public.prison_manage('jail',jsonb_build_object('player_id',inmate,'minutes',10,'reason','Second breakout target'));sentence_id:=(v->>'sentence_id')::uuid;
 select release_at into target_release from public.game_prison_sentences where id=sentence_id;
 perform set_config('request.jwt.claim.sub',rescuer::text,true);set local role authenticated;
 v:=public.prison_break_action('start',jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'sentence_id',sentence_id));attempt_id:=(v->'attempt'->>'id')::uuid;
 reset role;update game_private.prison_break_attempts set target_angle=80 where id=attempt_id;set local role authenticated;
 for i in 1..5 loop
  v:=public.prison_break_action('tension',jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'attempt_id',attempt_id,'angle',-80));
 end loop;
 perform pg_temp.verify(v->>'outcome'='caught' and (v->>'attempts_left')::integer=0,'Five misses did not catch the rescuer');
 reset role;
 perform pg_temp.verify((select release_at from public.game_prison_sentences where season_id=s and player_id=rescuer)=target_release,'Caught rescuer did not receive the target inmate release time');
 perform set_config('request.jwt.claim.sub',rescuer::text,true);set local role authenticated;
 v:=public.prison_state();perform pg_temp.verify((v->>'jailed')::boolean,'Caught rescuer is not in custody');
 perform pg_temp.verify((v->'leaderboard'->0->>'breakouts')::integer=1,'Breakout leaderboard did not return the successful rescue');
 reset role;
 insert into public.game_inventory(season_id,player_id,good_id,quantity) values(s,timer_rescuer,'lockpick',1);
 perform set_config('request.jwt.claim.sub',timer_rescuer::text,true);set local role authenticated;
 v:=public.prison_break_action('start',jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'sentence_id',sentence_id));
 attempt_id:=(v->'attempt'->>'id')::uuid;
 reset role;
 update game_private.prison_break_attempts set expires_at=clock_timestamp()-interval '1 second' where id=attempt_id;
 set local role authenticated;
 v:=public.prison_break_action('tension',jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'attempt_id',attempt_id,'angle',0));
 perform pg_temp.verify(v->>'outcome'='caught','Expired lock action did not catch the rescuer');
 v:=public.prison_state();
 perform pg_temp.verify((v->>'jailed')::boolean and (v->'sentence'->>'release_at')::timestamptz=target_release,'Expired lock timer did not impose the target release time');
 reset role;
end$$;
select 'PASS: lockpick loot, secret lock challenge, exact consumption, Owner reward, successful release, power, idempotency, leaderboard, matched failure sentence and timer expiry';
rollback;
