begin;
create function pg_temp.assert_ref(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
do $$
declare owner uuid:=gen_random_uuid();a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();s uuid:=game_private.current_season();
 r public.game_refineries;p public.game_district_plots;recipe public.game_refining_recipes;q jsonb;res jsonb;first jsonb;
 cash_a bigint;cash_b bigint;fuel_before int;ore_before int;score_before numeric;score_after numeric;denied boolean;next_s uuid;
begin
 insert into auth.users(id) values(owner),(a),(b),(c);
 perform set_config('request.jwt.claim.sub',owner::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',c::text,true);perform public.game_state();
 insert into public.game_user_roles values(owner,'owner') on conflict(player_id) do update set role_id='owner';
 perform set_config('game.reason','Isolated refinery fixture funding',true);
 update public.game_players set cash=1000000 where id in(a,b,c);
 insert into public.game_inventory(season_id,player_id,good_id,quantity) values(s,a,'coal',100),(s,a,'iron-ore',100),(s,b,'iron-ore',200),(s,b,'copper-ore',100),(s,c,'iron-ore',100);
 select * into r from public.game_refineries where season_id=s limit 1;perform pg_temp.assert_ref(r.id is not null,'Refinery not seeded');
 select * into p from public.game_district_plots where id=r.plot_id;select * into recipe from public.game_refining_recipes where id='iron';
 perform set_config('request.jwt.claim.sub',a::text,true);
 q:=jsonb_build_object('season_id',s,'refinery_id',r.id,'plot_version',p.version,'total',p.base_price+ceil(p.base_price*.03),'request_id',gen_random_uuid());
 first:=public.refinery_action('buy',q);perform pg_temp.assert_ref(not first?'error','Purchase failed: '||first::text);
 res:=public.refinery_action('buy',q);perform pg_temp.assert_ref(res=first,'Purchase replay failed');
 perform pg_temp.assert_ref((select count(*) from public.game_property_sales where plot_id=p.id)=1,'Repeated purchase duplicated sale');
 perform pg_temp.assert_ref((select owner_id=a from public.game_district_businesses where id=r.business_id),'Business did not follow title');
 select * into p from public.game_district_plots where id=r.plot_id;
 q:=jsonb_build_object('season_id',s,'refinery_id',r.id,'version',r.version,'plot_version',p.version,'request_id',gen_random_uuid());
 perform set_config('request.jwt.claim.sub',b::text,true);
 res:=public.refinery_action('stock',q||jsonb_build_object('good_id','coal','quantity',10));perform pg_temp.assert_ref(res?'error','Stranger can stock owner bunker');
 res:=public.refinery_action('settings',q||jsonb_build_object('fee_mode','cash','cash_fee',0,'output_percent',0,'status','open'));perform pg_temp.assert_ref(res?'error','Stranger can change owner fees');
 set local role authenticated;
 denied:=false;begin update public.game_refinery_fuel set quantity=100000;exception when insufficient_privilege then denied:=true;end;perform pg_temp.assert_ref(denied,'Direct fuel write allowed');
 denied:=false;begin perform 1 from public.game_refinery_receipts limit 1;exception when insufficient_privilege then denied:=true;end;perform pg_temp.assert_ref(denied,'Private receipts exposed');
 reset role;
 select * into recipe from public.game_refining_recipes where id='iron';
 perform set_config('request.jwt.claim.sub',a::text,true);
 select score into score_before from game_private.season_scores(s,'net_worth') where player_id=a;
 res:=public.refinery_action('stock',q||jsonb_build_object('good_id','coal','quantity',50));perform pg_temp.assert_ref(not res?'error','Fuel deposit failed: '||res::text);
 select score into score_after from game_private.season_scores(s,'net_worth') where player_id=a;
 perform pg_temp.assert_ref(score_before=score_after,'Moving fuel changed net worth');
 perform pg_temp.assert_ref((select quantity from public.game_refinery_fuel where refinery_id=r.id and good_id='coal')=50,'Fuel deposit not conserved');
 perform set_config('request.jwt.claim.sub',b::text,true);
 select cash into cash_a from public.game_players where id=a;select cash into cash_b from public.game_players where id=b;
 q:=q||jsonb_build_object('request_id',gen_random_uuid(),'recipe_id','iron','recipe_version',recipe.version,'batches',2,'cash_fee',0,'output_quantity',10000,'owner_id',b);
 first:=public.refinery_action('refine',q);perform pg_temp.assert_ref(not first?'error','Cash order failed: '||first::text);
 perform pg_temp.assert_ref((select cash from public.game_players where id=a)=cash_a+40 and (select cash from public.game_players where id=b)=cash_b-40,'Cash fee not conserved');
 perform pg_temp.assert_ref((select count(*) from public.game_ledger where reason in('Refining fee: '||(first->'receipt'->>'id'),'Refinery revenue: '||(first->'receipt'->>'id')))=2,'Missing fee ledgers');
 perform pg_temp.assert_ref((select quantity from public.game_inventory where player_id=b and season_id=s and good_id='iron-ingot')=20,'Forged yield accepted or output lost');
 perform pg_temp.assert_ref((select quantity from public.game_refinery_fuel where refinery_id=r.id and good_id='coal')=40,'Wrong fuel consumed');
 res:=public.refinery_action('refine',q);perform pg_temp.assert_ref(res=first,'Refining retry rerolled or duplicated');
 res:=public.refinery_action('refine',q||jsonb_build_object('batches',3));perform pg_temp.assert_ref(res?'error','Nonce can be reused with another quantity');
 perform set_config('request.jwt.claim.sub',a::text,true);
 res:=public.refinery_action('settings',jsonb_build_object('season_id',s,'refinery_id',r.id,'version',r.version,'plot_version',p.version,'request_id',gen_random_uuid(),'fee_mode','output','cash_fee',20,'output_percent',15,'status','open'));perform pg_temp.assert_ref(not res?'error','Owner fee edit failed: '||res::text);
 perform set_config('request.jwt.claim.sub',b::text,true);
 res:=public.refinery_action('refine',q||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.assert_ref(res?'error','Stale fee quote accepted');
 select * into r from public.game_refineries where id=r.id;
 q:=q||jsonb_build_object('version',r.version,'request_id',gen_random_uuid(),'batches',1);
 first:=public.refinery_action('refine',q);perform pg_temp.assert_ref(not first?'error','Output fee failed: '||first::text);
 perform pg_temp.assert_ref((first->'receipt'->>'owner_quantity')::int=2 and (first->'receipt'->>'customer_quantity')::int=8,'Percentage must round up and conserve output');
 perform pg_temp.assert_ref((select quantity from public.game_inventory where season_id=s and player_id=a and good_id='iron-ingot')=2,'Owner output share missing');
 select quantity into ore_before from public.game_inventory where player_id=b and season_id=s and good_id='iron-ore';
 res:=public.refinery_action('refine',q||jsonb_build_object('request_id',gen_random_uuid(),'batches',10));perform pg_temp.assert_ref(res?'error','Insufficient ore accepted');
 perform pg_temp.assert_ref((select quantity from public.game_inventory where player_id=b and season_id=s and good_id='iron-ore')=ore_before,'Failed order consumed ore');
 -- No fuel: even a valid ore balance must remain unchanged.
 update public.game_refinery_fuel set quantity=0 where refinery_id=r.id;
 res:=public.refinery_action('refine',q||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.assert_ref(res?'error','Fuel shortage ignored');
 perform pg_temp.assert_ref((select quantity from public.game_inventory where player_id=b and season_id=s and good_id='iron-ore')=ore_before,'Fuel shortage failed to roll back input');
 update public.game_refinery_fuel set quantity=20 where refinery_id=r.id;
 update public.game_districts set status='lockdown' where id=p.district_id;
 res:=public.refinery_action('refine',q||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.assert_ref(res?'error','District lockdown ignored');
 update public.game_districts set status='neutral' where id=p.district_id;
 perform set_config('request.jwt.claim.sub',owner::text,true);
 res:=public.refinery_action('recipe',to_jsonb(recipe)||jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'fuel_units',6,'reason','Adjust coal consumption'));
 perform pg_temp.assert_ref(not res?'error','Game Owner cannot edit recipes: '||res::text);
 perform pg_temp.assert_ref(exists(select 1 from public.game_audit where action='game_refining_recipes.update' and actor_id=owner),'Recipe edit not audited');
 perform set_config('request.jwt.claim.sub',b::text,true);
 res:=public.refinery_action('refine',q||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.assert_ref(res?'error','Stale recipe quote accepted');
 res:=public.refinery_action('recipe',to_jsonb(recipe)||jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'reason','Attempt unauthorized recipe'));perform pg_temp.assert_ref(res?'error','Player can edit recipes');
 -- Owner processing uses fuel but pays no fee to themselves.
 perform set_config('request.jwt.claim.sub',a::text,true);
 q:=q||jsonb_build_object('recipe_version',2,'request_id',gen_random_uuid());
 first:=public.refinery_action('refine',q);perform pg_temp.assert_ref(not first?'error','Owner processing failed: '||first::text);
 perform pg_temp.assert_ref((first->'receipt'->>'cash_fee')::int=0 and (first->'receipt'->>'owner_quantity')::int=0,'Self-refining charged or duplicated fee');
 -- Stock remains attached to the property on resale.
 res:=public.district_action('sell',jsonb_build_object('season_id',s,'plot_id',p.id,'price',50000));
 perform pg_temp.assert_ref(not res?'error','Refinery cannot be listed');
 select * into p from public.game_district_plots where id=p.id;
 perform set_config('request.jwt.claim.sub',c::text,true);
 res:=public.refinery_action('buy',jsonb_build_object('season_id',s,'refinery_id',r.id,'plot_version',p.version,'total',51500,'request_id',gen_random_uuid()));perform pg_temp.assert_ref(not res?'error','Refinery resale failed: '||res::text);
 perform set_config('request.jwt.claim.sub',a::text,true);
 res:=public.refinery_action('withdraw',q||jsonb_build_object('plot_version',p.version+1,'request_id',gen_random_uuid(),'good_id','coal','quantity',1));perform pg_temp.assert_ref(res?'error','Former owner can drain fuel');
 perform pg_temp.assert_ref((select owner_id=c from public.game_district_businesses where id=r.business_id),'Resale business owner stale');
 perform set_config('request.jwt.claim.sub',b::text,true);
 denied:=false;begin delete from public.game_refinery_receipts where refinery_id=r.id;exception when raise_exception then denied:=true;end;perform pg_temp.assert_ref(denied,'Refining history can be deleted');
 update public.game_seasons set status='locked' where id=s;
 res:=public.refinery_action('refine',q||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.assert_ref(res?'error','Locked season allowed refining');
 insert into public.game_seasons(name,status,starting_cash,starting_crates) values('Next refining season','open',100,0) returning id into next_s;
 update game_private.season_runtime set season_id=next_s;perform game_private.ensure_districts(next_s);
 perform pg_temp.assert_ref((select count(*) from public.game_refineries where season_id=next_s)=1,'Next season refinery missing');
 perform pg_temp.assert_ref(not exists(select 1 from public.game_refinery_fuel f join public.game_refineries rr on rr.id=f.refinery_id where rr.season_id=next_s),'Fuel leaked into next season');
 perform pg_temp.assert_ref(jsonb_array_length(public.refinery_state()->'history')=0,'Old receipts leaked into current season');
 perform pg_temp.assert_ref((select count(*) from public.game_refinery_receipts where season_id=s)=3,'Old financial records were lost');
end $$;
select 'PASS: refinery purchase/resale, cash and output fees, quotes, coal stock, valuation, permissions, rollback, retry, audit and seasons';
rollback;
