begin;
create function pg_temp.verify(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
create function pg_temp.rob_player(u uuid,d uuid) returns void language plpgsql as $$declare s uuid:=game_private.current_season();r jsonb;begin
 insert into auth.users(id) values(u);perform set_config('request.jwt.claim.sub',u::text,true);perform public.game_state();
 insert into auth.sessions(id,user_id,created_at) values(u,u,clock_timestamp());
 insert into game_private.player_presence(player_id,session_id,last_seen_at) values(u,u,clock_timestamp());
 insert into public.game_inventory(season_id,player_id,good_id,quantity) values(s,u,'homemade-pistol',1),(s,u,'homemade-bullets',200);
 r:=public.inventory_action('equip',jsonb_build_object('season_id',s,'item_key','good:homemade-pistol','equipment_slot','secondary','request_id',gen_random_uuid()));perform pg_temp.verify(not r?'error','Weapon equip fixture failed '||r::text);
 r:=public.inventory_action('equip',jsonb_build_object('season_id',s,'item_key','good:homemade-bullets','equipment_slot','ammo','quantity',200,'request_id',gen_random_uuid()));perform pg_temp.verify(not r?'error','Ammo fixture failed '||r::text);
 if d is not null then r:=public.scavenging_action('enter',jsonb_build_object('season_id',s,'district_id',d,'request_id',gen_random_uuid()));perform pg_temp.verify(not r?'error','Map fixture failed '||r::text);perform public.bin_diving_state();end if;
end$$;
create function pg_temp.reject_credit() returns trigger language plpgsql as $$begin if new.id::text=current_setting('game.test_robbery_credit_failure',true) and new.cash>old.cash then raise exception 'Simulated credit failure';end if;return new;end$$;
create trigger test_robbery_credit before update on public.game_players for each row execute function pg_temp.reject_credit();
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();s uuid:=game_private.current_season();d uuid;w uuid;ammo uuid;q jsonb;r jsonb;first jsonb;f jsonb;g jsonb;rules game_private.robbery_rules;balance_before bigint;cash_before bigint;n bigint;denied boolean;session_id uuid;accuracy numeric;
begin
 select id into d from public.game_districts where slug='the-waterfront';
 perform set_config('game.reason','CI robbery fixtures',true);update public.game_settings set value=300 where key='actions_per_minute';
 perform pg_temp.rob_player(a,null);perform pg_temp.rob_player(b,d);perform pg_temp.rob_player(c,null);
 perform set_config('request.jwt.claim.sub',b::text,true);r:=public.bank_action('deposit',jsonb_build_object('season_id',s,'amount',5000,'request_id',gen_random_uuid()));perform pg_temp.verify(not r?'error','Bank fixture failed');
 update public.game_players set cash=10000 where id=b;
 perform set_config('request.jwt.claim.sub',a::text,true);r:=public.robbery_state();
 perform pg_temp.verify(jsonb_array_length(r->'targets')>=2,'Online players not visible without a Scavenging session');
 perform pg_temp.verify(not ((r->'targets'->0)?'cash') and not ((r->'targets'->0)?'health'),'Private target data exposed');
 w:=(r->'weapon'->>'id')::uuid;ammo:=(game_private.robbery_weapon(s,a)->>'ammo_id')::uuid;
 q:=jsonb_build_object('season_id',s,'target_id',b,'weapon_id',w,'rules_version',1,'request_id',gen_random_uuid(),'chance',100,'cash',9999999,'bullets',0);
 r:=public.robbery_action('configure',jsonb_build_object('season_id',s,'version',1,'rules','{"bullet_min":3,"bullet_max":3}'::jsonb,'reason','Adjust robbery test rules'));perform pg_temp.verify(r?'error','Player changed rules');
 update public.game_user_roles set role_id='moderator' where player_id=a;
 r:=public.robbery_action('configure',jsonb_build_object('season_id',s,'version',1,'rules','{"bullet_min":0,"bullet_max":0}'::jsonb,'reason','Attempt moderator economy edit'));perform pg_temp.verify(r?'error','Moderator automatically changed robbery rules');
 update public.game_user_roles set role_id='owner' where player_id=a;
 r:=public.robbery_action('configure',jsonb_build_object('season_id',s,'version',1,'rules','{"steal_max":81}'::jsonb,'reason','Attempt out of range cash theft'));perform pg_temp.verify(r?'error','Owner exceeded 80 percent theft cap');
 r:=public.robbery_action('configure',jsonb_build_object('season_id',s,'version',1,'rules','{"bullet_min":3,"bullet_max":3,"min_chance":100,"max_chance":100}'::jsonb,'reason','Guarantee test robbery success'));perform pg_temp.verify(not r?'error','Owner edit failed '||r::text);
 update public.game_user_roles set role_id='player' where player_id=a;
 r:=public.robbery_action('attempt',q);perform pg_temp.verify(r?'error','Stale rule version accepted');q:=q||'{"rules_version":2}';
 r:=public.robbery_action('attempt',q||jsonb_build_object('target_id',a));perform pg_temp.verify(r?'error','Self robbery accepted');
 update game_private.player_presence set last_seen_at=clock_timestamp()-interval '10 minutes' where player_id=b;
 r:=public.robbery_action('attempt',q);perform pg_temp.verify(r?'error','Offline victim accepted');update game_private.player_presence set last_seen_at=clock_timestamp() where player_id=b;
 -- Cross-district and moving targets remain eligible; the attacker never entered Scavenging.
 update game_private.scav_sessions set district_id=(select id from public.game_districts where slug='old-town'),arrives_at=clock_timestamp()+interval '1 minute' where player_id=b;
 perform pg_temp.verify(game_private.robbery_available(s,b,null,clock_timestamp()),'Online cross-district target rejected');
 update public.game_players set sessions_revoked_at=clock_timestamp()+interval '1 second' where id=b;
 r:=public.robbery_action('attempt',q);perform pg_temp.verify(r?'error','Revoked target session accepted');
 perform pg_temp.verify(not exists(select 1 from jsonb_array_elements(public.robbery_state()->'targets') x where x->>'id'=b::text),'Revoked target remained visible');
 update public.game_players set sessions_revoked_at=null where id=b;
 delete from auth.sessions where id=b;
 r:=public.robbery_action('attempt',q);perform pg_temp.verify(r?'error','Signed-out target accepted');
 insert into auth.sessions(id,user_id,created_at) values(b,b,clock_timestamp());
 insert into game_private.player_presence(player_id,session_id,last_seen_at) values(b,b,clock_timestamp()) on conflict(player_id,session_id) do update set last_seen_at=excluded.last_seen_at;
 update game_private.player_presence set last_seen_at=clock_timestamp()-interval '10 minutes' where player_id=a;
 r:=public.robbery_action('attempt',q);perform pg_temp.verify(r?'error','Offline attacker accepted');
 update game_private.player_presence set last_seen_at=clock_timestamp() where player_id=a;
 update public.game_inventory_gear set condition=0 where id=w;
 r:=public.robbery_action('attempt',q);perform pg_temp.verify(r?'error','Broken gun accepted');update public.game_inventory_gear set condition=100 where id=w;
 update public.game_inventory_gear set quantity=2 where id=ammo;
 r:=public.robbery_action('attempt',q);perform pg_temp.verify(r?'error','Insufficient ammunition accepted');update public.game_inventory_gear set quantity=200 where id=ammo;
 perform pg_temp.verify(not exists(select 1 from game_private.robbery_attempts where attacker_id=a),'Invalid request created an outcome');
 select cash into cash_before from public.game_players where id=a;
 set local role authenticated;
 first:=public.robbery_action('attempt',q);perform pg_temp.verify(not first?'error' and (first->>'succeeded')::boolean,'Attempt failed '||first::text);
 perform pg_temp.verify(public.robbery_action('attempt',q)=first,'Duplicate retry changed outcome');
 r:=public.robbery_action('attempt',q||'{"bullets":1}');perform pg_temp.verify(r?'error','Changed retry payload accepted');
 denied:=false;begin perform 1 from game_private.robbery_attempts;exception when insufficient_privilege then denied:=true;end;perform pg_temp.verify(denied,'Private history exposed');
 reset role;
 perform pg_temp.verify((select district_id is null from game_private.robbery_attempts where attacker_id=a),'Global mugging incorrectly recorded a district');
 perform pg_temp.verify(not (public.bin_diving_state()?'robbery'),'Scavenging still contains mugging');
 n:=(first->>'cash')::bigint;perform pg_temp.verify(n between 100 and 8000 and (first->>'bullets')::int=3,'Amount or ammunition trusted browser');
 perform pg_temp.verify((select cash from public.game_players where id=a)=cash_before+n and (select cash from public.game_players where id=b)=10000-n,'Cash not conserved');
 perform pg_temp.verify((select balance from public.game_bank_accounts where season_id=s and player_id=b)=5000,'Bank cash stolen');
 perform pg_temp.verify((select quantity from public.game_inventory_gear where id=ammo)=197 and (select condition from public.game_inventory_gear where id=w)=97,'Ammo/wear duplicated or omitted');
 perform pg_temp.verify((select count(*) from public.game_ledger where player_id in(a,b) and reason like 'Mugging %')=2,'Paired cash ledger missing');
 perform pg_temp.verify((select protected_until>clock_timestamp()+interval '29 minutes' from game_private.robbery_protection where season_id=s and player_id=b),'Victim protection missing');
 perform set_config('request.jwt.claim.sub',c::text,true);
 r:=public.robbery_action('attempt',q||jsonb_build_object('weapon_id',game_private.robbery_weapon(s,c)->>'id','request_id',gen_random_uuid()));perform pg_temp.verify(r?'error','Different attacker bypassed victim protection');
 perform set_config('request.jwt.claim.sub',a::text,true);r:=public.robbery_action('attempt',q||jsonb_build_object('target_id',c,'request_id',gen_random_uuid()));perform pg_temp.verify(r?'error','Attacker cooldown bypassed');
 update game_private.robbery_protection set protected_until=null,ready_at=null where season_id=s;
 update game_private.robbery_rules set min_chance=0,max_chance=0,version=3;
 q:=q||jsonb_build_object('rules_version',3,'request_id',gen_random_uuid());r:=public.robbery_action('attempt',q);
 perform pg_temp.verify(not r?'error' and not (r->>'succeeded')::boolean and (r->>'cash')::bigint=0,'Guaranteed failure transferred cash');
 perform pg_temp.verify((select quantity from public.game_inventory_gear where id=ammo)=194,'Failed attempt did not consume bullets');
 perform pg_temp.verify((select protected_until>clock_timestamp() from game_private.robbery_protection where season_id=s and player_id=b),'Failure did not protect victim');
 update game_private.robbery_protection set protected_until=null,ready_at=null where season_id=s;
 update game_private.robbery_rules set min_chance=100,max_chance=100,version=4;
 select cash into balance_before from public.game_players where id=b;
 perform set_config('game.test_robbery_credit_failure',a::text,true);
 q:=q||jsonb_build_object('rules_version',4,'request_id',gen_random_uuid());r:=public.robbery_action('attempt',q);perform pg_temp.verify(r?'error','Simulated transfer failure ignored');
 perform pg_temp.verify((select cash from public.game_players where id=b)=balance_before and (select quantity from public.game_inventory_gear where id=ammo)=194,'Failed transfer partially consumed cash/ammo');
 perform pg_temp.verify((select protected_until is null from game_private.robbery_protection where season_id=s and player_id=b),'Failed transaction granted protection');perform set_config('game.test_robbery_credit_failure','',true);
 update game_private.robbery_rules set bullet_min=0,bullet_max=0,version=5;
 q:=q||jsonb_build_object('rules_version',5,'request_id',gen_random_uuid());r:=public.robbery_action('attempt',q);perform pg_temp.verify(not r?'error' and (r->>'bullets')::int=0,'Zero-bullet threat failed');
 perform pg_temp.verify((select quantity from public.game_inventory_gear where id=ammo)=194,'Zero-cost threat used bullets');
 -- Random ammunition is bounded by the saved range and the exact roll is consumed.
 update game_private.robbery_protection set protected_until=null,ready_at=null where season_id=s;
 update game_private.robbery_rules set bullet_min=2,bullet_max=4,version=6;
 q:=q||jsonb_build_object('rules_version',6,'request_id',gen_random_uuid());r:=public.robbery_action('attempt',q);
 perform pg_temp.verify(not r?'error' and (r->>'bullets')::integer between 2 and 4,'Random ammunition out of range '||r::text);
 perform pg_temp.verify((select quantity from public.game_inventory_gear where id=ammo)=194-(r->>'bullets')::integer,'Random rolled ammunition consumption differed');
 -- Every factor, including condition-adjusted worn equipment, changes relative odds.
 update game_private.robbery_rules set min_chance=0,max_chance=100,base_chance=50;select * into rules from game_private.robbery_rules;
 f:=game_private.robbery_factors(s,a);g:=game_private.robbery_factors(s,b);
 perform pg_temp.verify(game_private.robbery_chance(f||'{"level":20}',g,rules)>game_private.robbery_chance(f||'{"level":1}',g,rules),'Skill ignored');
 perform pg_temp.verify(game_private.robbery_chance(f||'{"accuracy":100}',g,rules)>game_private.robbery_chance(f||'{"accuracy":0}',g,rules),'Accuracy ignored');
 perform pg_temp.verify(game_private.robbery_chance(f||'{"power":9999}',g,rules)>game_private.robbery_chance(f||'{"power":0}',g,rules),'Power ignored');
 perform pg_temp.verify(game_private.robbery_chance(f,g||'{"defense":1000}',rules)<game_private.robbery_chance(f,g||'{"defense":0}',rules),'Defensive gear ignored');
 update public.game_inventory_gear set condition=10 where id=w;perform pg_temp.verify((game_private.robbery_factors(s,a)->>'attack')::numeric<(f->>'attack')::numeric,'Weapon wear ignored');
 insert into game_private.skill_xp_ledger(season_id,player_id,skill_id,source_id,delta,description) select s,a,'sharpshooting',gen_random_uuid(),xp_to_20,'CI trained player' from public.game_skill_definitions where id='sharpshooting';
 perform pg_temp.verify((game_private.robbery_factors(s,a)->>'level')::int=20,'Stored skill XP not used');
 insert into public.game_range_sessions(season_id,player_id,weapon_id,weapon_good_id,equipment_slot,seed,config,weapon_rule,started_at,ends_at,finished_at,status,shots,difficulty)
 select s,a,w,'homemade-pistol','secondary',1,game_private.range_mode_config('advanced')||'{"move_amplitude":0,"move_vertical":0}',to_jsonb(wr),clock_timestamp()-interval '1 minute',clock_timestamp(),clock_timestamp(),'finished',1,'advanced' from public.game_range_weapons wr where good_id='homemade-pistol' returning id into session_id;
 insert into public.game_range_shots(session_id,season_id,player_id,request_id,weapon_id,ammo_id,elapsed_ms,x,y,round,lane,hit,points,condition_before,condition_after,ammo_before,ammo_after)
 values(session_id,s,a,gen_random_uuid(),w,ammo,0,50,45,0,1,true,100,100,99,200,199);
 accuracy:=(game_private.robbery_factors(s,a)->>'accuracy')::numeric;perform pg_temp.verify(accuracy=100,'Saved advanced accuracy not used: '||accuracy);
 update public.game_seasons set status='locked' where id=s;r:=public.robbery_action('attempt',q||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.verify(r?'error','Season lock bypassed');update public.game_seasons set status='open' where id=s;
 denied:=false;begin delete from game_private.robbery_attempts where attacker_id=a;exception when raise_exception then denied:=true;end;perform pg_temp.verify(denied,'Robbery history deleted');
 perform pg_temp.verify(not has_function_privilege('anon','public.robbery_action(text,jsonb)','execute'),'Anonymous robbery allowed');
 perform pg_temp.verify(not has_function_privilege('authenticated','game_private.robbery_factors(uuid,uuid)','execute'),'Arbitrary private player factors exposed');
end$$;
select 'PASS: robbery eligibility, cash conservation, bank safety, ammo, wear, skill, precision, protection, cooldowns, retries, rollback and permissions';
rollback;
