begin;
create function pg_temp.check_scav(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
do $$
declare u uuid:=gen_random_uuid();other_u uuid:=gen_random_uuid();s uuid:=game_private.current_season();d uuid;q jsonb;r jsonb;first jsonb;site jsonb;car jsonb;attempt uuid;cash_before bigint;denied boolean;
begin
 insert into auth.users(id) values(u),(other_u);perform set_config('request.jwt.claim.sub',u::text,true);perform public.game_state();
 set local role authenticated;
 r:=public.bin_diving_state();
 perform pg_temp.check_scav(r?'scavenging','Signed-in player cannot load the scavenging page');
 perform pg_temp.check_scav(not has_function_privilege('anon','public.bin_diving_state()','EXECUTE'),'Anonymous player can read scavenging');
 reset role;
 select id into d from public.game_districts where slug='the-waterfront';
 perform set_config('game.reason','CI scavenging guaranteed loot',true);
 update public.game_bin_rules set cash_chance=100,pickaxe_chance=0,lockpick_chance=0,pistol_blueprint_chance=0,bullet_blueprint_chance=0,cash_min=77,cash_max=77;
 update public.game_settings set value=100 where key='scavenging_car_success_percent';
 q:=jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'district_id',d);
 r:=public.bin_diving_action('dive',q);perform pg_temp.check_scav(r?'error','Legacy endpoint bypasses the map');
 first:=public.scavenging_action('enter',q);perform pg_temp.check_scav(not first?'error','Enter failed: '||first::text);
 r:=public.scavenging_action('enter',q);perform pg_temp.check_scav(r=first,'Entry retry is not safe');
 set local role authenticated;
 r:=public.bin_diving_state();
 perform pg_temp.check_scav(jsonb_array_length(r->'scavenging'->'targets')=10,'Signed-in player cannot read entered map');
 reset role;
 select x into site from jsonb_array_elements(public.bin_diving_state()->'scavenging'->'targets')x where x->>'kind'='bin' limit 1;
 select x into car from jsonb_array_elements(public.bin_diving_state()->'scavenging'->'targets')x where x->>'kind'='car' limit 1;
 perform pg_temp.check_scav(site is not null and car is not null,'Map needs bins and cars');
 r:=public.scavenging_action('search',q||jsonb_build_object('request_id',gen_random_uuid(),'target_id',site->>'id'));
 perform pg_temp.check_scav(r?'error','Remote search accepted');
 r:=public.scavenging_action('move',q||jsonb_build_object('request_id',gen_random_uuid(),'node',99));perform pg_temp.check_scav(r?'error','Invalid movement accepted');
 r:=public.scavenging_action('move',q||jsonb_build_object('request_id',gen_random_uuid(),'node',(site->>'node')::int));perform pg_temp.check_scav(not r?'error','Movement failed: '||r::text);
 r:=public.scavenging_action('search',q||jsonb_build_object('request_id',gen_random_uuid(),'target_id',site->>'id'));perform pg_temp.check_scav(r?'error','Travel timer bypassed');
 update game_private.scav_sessions set arrives_at=clock_timestamp()-interval '1 second' where player_id=u;
 attempt:=gen_random_uuid();q:=q||jsonb_build_object('request_id',attempt,'target_id',site->>'id');
 first:=public.scavenging_action('search',q);perform pg_temp.check_scav(not first?'error','Search failed: '||first::text);
 perform pg_temp.check_scav(public.scavenging_action('search',q)=first,'Start replay changed');
 q:=jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'attempt_id',attempt,'cash',999999,'xp',999999);
 r:=public.scavenging_action('finish',q);perform pg_temp.check_scav(r?'error','Search timer bypassed');
 update game_private.scav_sessions set pending=pending||jsonb_build_object('ready_at',clock_timestamp()-interval '1 second') where player_id=u;
 select cash into cash_before from public.game_players where id=u;
 first:=public.scavenging_action('finish',q);perform pg_temp.check_scav(not first?'error','Collect failed: '||first::text);
 perform pg_temp.check_scav((select cash from public.game_players where id=u)=cash_before+77,'Cash amount trusts client or missing');
 perform pg_temp.check_scav(public.scavenging_action('finish',q)=first,'Replay returned a different reward');
 perform pg_temp.check_scav((select count(*) from game_private.scav_results where player_id=u)=1,'Replay duplicated a result');
 perform pg_temp.check_scav((select count(*) from game_private.skill_xp_ledger where player_id=u and skill_id='scavenging')=1,'Search replay duplicated Scavenging XP');
 perform pg_temp.check_scav((select sum(delta) from game_private.skill_xp_ledger where player_id=u and skill_id='scavenging')=game_private.setting('scavenging_skill_xp_per_search'),'Completed bin did not earn configured Scavenging XP');
 perform pg_temp.check_scav(not has_function_privilege('authenticated','game_private.scavenging_skill_award()','execute'),'Players can invoke the award trigger directly');
 perform pg_temp.check_scav(exists(select 1 from public.game_ledger where player_id=u and delta=77),'Cash ledger missing');
 r:=public.scavenging_action('search',jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'target_id',site->>'id'));perform pg_temp.check_scav(r?'error','Searched site reused');
 -- Car flow with an isolated player and no inherited cooldown.
 perform set_config('request.jwt.claim.sub',other_u::text,true);perform public.game_state();
 q:=jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'district_id',d);
 r:=public.scavenging_action('enter',q);select x into car from jsonb_array_elements(public.bin_diving_state()->'scavenging'->'targets')x where x->>'kind'='car' limit 1;
 update game_private.scav_sessions set node=(car->>'node')::int,route_points=jsonb_build_array(jsonb_build_array((car->>'node')::int%5,(car->>'node')::int/5)) where player_id=other_u;
 q:=q||jsonb_build_object('request_id',gen_random_uuid(),'target_id',car->>'id');
 r:=public.scavenging_action('search',q);perform pg_temp.check_scav(r?'error','Car opened without a tool');
 insert into public.game_inventory(season_id,player_id,good_id,quantity) values(s,other_u,'lockpick',1);
 first:=public.scavenging_action('search',q);perform pg_temp.check_scav(not first?'error','Car search failed: '||first::text);
 perform pg_temp.check_scav(public.scavenging_action('search',q)=first,'Car retry failed');
 perform pg_temp.check_scav((select quantity from public.game_inventory where player_id=other_u and good_id='lockpick')=0,'Wrong number of lockpicks consumed');
 update game_private.scav_sessions set pending=pending||jsonb_build_object('ready_at',clock_timestamp()-interval '1 second') where player_id=other_u;
 q:=jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'attempt_id',q->>'request_id');
 first:=public.scavenging_action('finish',q);perform pg_temp.check_scav(not first?'error','Car collection failed: '||first::text);
 perform pg_temp.check_scav((select sum(delta) from game_private.skill_xp_ledger where player_id=other_u and skill_id='lockpicking')=25,'Lockpicking XP missing or forged');
 r:=public.scavenging_action('finish',q);perform pg_temp.check_scav(r=first,'Car collect replay failed');
 denied:=false;begin delete from game_private.scav_results where player_id=other_u;exception when raise_exception then denied:=true;end;
 perform pg_temp.check_scav(denied,'Search history can be erased');
 set local role authenticated;
 denied:=false;begin update game_private.scav_sessions set node=14;exception when insufficient_privilege then denied:=true;end;
 perform pg_temp.check_scav(denied,'Browser can move by writing tables');reset role;
 update public.game_districts set status='lockdown' where id=d;
 r:=public.scavenging_action('move',jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'node',1));perform pg_temp.check_scav(r?'error','Lockdown bypassed');
end$$;
do $$
declare u uuid:=gen_random_uuid();s uuid:=game_private.current_season();d uuid;q jsonb;r jsonb;original jsonb;v game_private.scav_sessions;after_move game_private.scav_sessions;site jsonb;route jsonb;a jsonb;b jsonb;i integer;
begin
 insert into auth.users(id) values(u);perform set_config('request.jwt.claim.sub',u::text,true);perform public.game_state();
 select id into d from public.game_districts where slug='the-waterfront';update public.game_districts set status='neutral' where id=d;
 q:=jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'district_id',d);
 r:=public.scavenging_action('enter',q);perform pg_temp.check_scav(not r?'error','Continuous movement entry failed');
 foreach r in array array['{"x":0.5,"y":0.5}'::jsonb,'{"x":-1,"y":0}'::jsonb,'{"x":5,"y":0}'::jsonb,'{"x":"1","y":0}'::jsonb,'{"x":null,"y":0}'::jsonb] loop
  original:=public.scavenging_action('move',q||r||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.check_scav(original?'error','Invalid coordinate accepted: '||r::text);
 end loop;
 q:=q||jsonb_build_object('request_id',gen_random_uuid(),'x',0.5,'y',0,'seconds',0,'speed',999999,'route_points','[[0,0],[4,2]]'::jsonb);
 r:=public.scavenging_action('move',q);perform pg_temp.check_scav(not r?'error','Mid-block move failed: '||r::text);
 select * into v from game_private.scav_sessions where player_id=u;
 perform pg_temp.check_scav(v.route_points->-1='[0.5,0]'::jsonb,'Destination snapped back to a crossing');
 perform pg_temp.check_scav(abs(extract(epoch from v.arrives_at-v.departed_at)-0.5*game_private.setting('scavenging_walk_seconds'))<0.001,'Client controlled travel speed');
 original:=public.scavenging_action('move',q);select * into after_move from game_private.scav_sessions where player_id=u;
 perform pg_temp.check_scav(original=r and after_move.departed_at=v.departed_at,'Retry restarted movement');
 r:=public.scavenging_action('move',q||jsonb_build_object('request_id',gen_random_uuid(),'x',0,'y',1.5));
 perform pg_temp.check_scav(not r?'error','Mid-walk reroute was rejected');
 select * into after_move from game_private.scav_sessions where player_id=u;
 perform pg_temp.check_scav(after_move.route_points->0=game_private.scav_position(v.route_points,v.departed_at,v.arrives_at,after_move.departed_at),'Rerouting teleported the player');
 perform pg_temp.check_scav(after_move.arrives_at>after_move.departed_at,'Reroute skipped travel time');
 update game_private.scav_sessions set arrives_at=clock_timestamp()-interval '1 second' where player_id=u;
 select x into site from jsonb_array_elements(public.bin_diving_state()->'scavenging'->'targets')x where x->>'kind'='bin' limit 1;
 r:=public.scavenging_action('move',q||jsonb_build_object('request_id',gen_random_uuid(),'x',(site->>'node')::int%5,'y',(site->>'node')::int/5));
 perform pg_temp.check_scav(not r?'error','Could not walk to a search site');
 r:=public.scavenging_action('search',q||jsonb_build_object('request_id',gen_random_uuid(),'target_id',site->>'id'));perform pg_temp.check_scav(r?'error','Search accepted during continuous travel');
 -- Adjacent but not at a target: a rounded legacy node must not grant proximity.
 update game_private.scav_sessions set arrives_at=clock_timestamp()-interval '1 second',route_points=jsonb_build_array(jsonb_build_array((site->>'node')::int%5,((site->>'node')::int/5)::numeric+case when (site->>'node')::int/5=2 then -0.1 else 0.1 end)) where player_id=u;
 r:=public.scavenging_action('search',q||jsonb_build_object('request_id',gen_random_uuid(),'target_id',site->>'id'));perform pg_temp.check_scav(r?'error','Rounded node bypassed exact proximity');
 for a in select value from jsonb_array_elements('[[0.25,0],[1,0.4],[4,1.7],[3.6,2]]'::jsonb) loop
  for b in select value from jsonb_array_elements('[[0,1.1],[2.8,1],[4,0.3],[0.75,0]]'::jsonb) loop
   route:=game_private.scav_route(a,b);perform pg_temp.check_scav(route->0=a and route->-1=b,'Route endpoints changed');
   for i in 1..jsonb_array_length(route)-1 loop
    perform pg_temp.check_scav(((route->i->>0)::numeric=(route->(i-1)->>0)::numeric and (route->i->>0)::numeric=trunc((route->i->>0)::numeric)) or ((route->i->>1)::numeric=(route->(i-1)->>1)::numeric and (route->i->>1)::numeric=trunc((route->i->>1)::numeric)),'Route cuts through a building');
   end loop;
  end loop;
 end loop;
end$$;
select 'PASS: continuous street movement, safe rerouting, proximity, travel timing, loot ledger, replay safety, lockpicks, skill XP and permissions';
rollback;
