begin;
create function pg_temp.check_scav(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
do $$
declare u uuid:=gen_random_uuid();other_u uuid:=gen_random_uuid();s uuid:=game_private.current_season();d uuid;q jsonb;r jsonb;first jsonb;site jsonb;car jsonb;attempt uuid;cash_before bigint;denied boolean;
begin
 insert into auth.users(id) values(u),(other_u);perform set_config('request.jwt.claim.sub',u::text,true);perform public.game_state();
 set local role authenticated;
 r:=public.bin_diving_state();
 perform pg_temp.check_scav(r?'scavenging','Signed-in player cannot load the scavenging page');
 perform pg_temp.check_scav(not has_function_privilege('anon','public.bin_diving_state()','EXECUTE'),'Anonymous player can read scavenging');
 reset role;
 select id into d from public.game_districts where slug='the-waterfront';
 perform set_config('game.reason','CI scavenging guaranteed loot',true);
 update public.game_bin_rules set cash_chance=100,pickaxe_chance=0,lockpick_chance=0,pistol_blueprint_chance=0,bullet_blueprint_chance=0,cash_min=77,cash_max=77;
 update public.game_settings set value=100 where key='scavenging_car_success_percent';
 q:=jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'district_id',d);
 r:=public.bin_diving_action('dive',q);perform pg_temp.check_scav(r?'error','Legacy endpoint bypasses the map');
 first:=public.scavenging_action('enter',q);perform pg_temp.check_scav(not first?'error','Enter failed: '||first::text);
 r:=public.scavenging_action('enter',q);perform pg_temp.check_scav(r=first,'Entry retry is not safe');
 set local role authenticated;
 r:=public.bin_diving_state();
 perform pg_temp.check_scav(jsonb_array_length(r->'scavenging'->'targets')=10,'Signed-in player cannot read entered map');
 reset role;
 select x into site from jsonb_array_elements(public.bin_diving_state()->'scavenging'->'targets')x where x->>'kind'='bin' limit 1;
 select x into car from jsonb_array_elements(public.bin_diving_state()->'scavenging'->'targets')x where x->>'kind'='car' limit 1;
 perform pg_temp.check_scav(site is not null and car is not null,'Map needs bins and cars');
 r:=public.scavenging_action('search',q||jsonb_build_object('request_id',gen_random_uuid(),'target_id',site->>'id'));
 perform pg_temp.check_scav(r?'error','Remote search accepted');
 r:=public.scavenging_action('move',q||jsonb_build_object('request_id',gen_random_uuid(),'node',99));perform pg_temp.check_scav(r?'error','Invalid movement accepted');
 r:=public.scavenging_action('move',q||jsonb_build_object('request_id',gen_random_uuid(),'node',(site->>'node')::int));perform pg_temp.check_scav(not r?'error','Movement failed: '||r::text);
 r:=public.scavenging_action('search',q||jsonb_build_object('request_id',gen_random_uuid(),'target_id',site->>'id'));perform pg_temp.check_scav(r?'error','Travel timer bypassed');
 update game_private.scav_sessions set arrives_at=clock_timestamp()-interval '1 second' where player_id=u;
 attempt:=gen_random_uuid();q:=q||jsonb_build_object('request_id',attempt,'target_id',site->>'id');
 first:=public.scavenging_action('search',q);perform pg_temp.check_scav(not first?'error','Search failed: '||first::text);
 perform pg_temp.check_scav(public.scavenging_action('search',q)=first,'Start replay changed');
 q:=jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'attempt_id',attempt,'cash',999999,'xp',999999);
 r:=public.scavenging_action('finish',q);perform pg_temp.check_scav(r?'error','Search timer bypassed');
 update game_private.scav_sessions set pending=pending||jsonb_build_object('ready_at',clock_timestamp()-interval '1 second') where player_id=u;
 select cash into cash_before from public.game_players where id=u;
 first:=public.scavenging_action('finish',q);perform pg_temp.check_scav(not first?'error','Collect failed: '||first::text);
 perform pg_temp.check_scav((select cash from public.game_players where id=u)=cash_before+77,'Cash amount trusts client or missing');
 perform pg_temp.check_scav(public.scavenging_action('finish',q)=first,'Replay returned a different reward');
 perform pg_temp.check_scav((select count(*) from game_private.scav_results where player_id=u)=1,'Replay duplicated a result');
 perform pg_temp.check_scav(exists(select 1 from public.game_ledger where player_id=u and delta=77),'Cash ledger missing');
 r:=public.scavenging_action('search',jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'target_id',site->>'id'));perform pg_temp.check_scav(r?'error','Searched site reused');
 -- Car flow with an isolated player and no inherited cooldown.
 perform set_config('request.jwt.claim.sub',other_u::text,true);perform public.game_state();
 q:=jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'district_id',d);
 r:=public.scavenging_action('enter',q);select x into car from jsonb_array_elements(public.bin_diving_state()->'scavenging'->'targets')x where x->>'kind'='car' limit 1;
 update game_private.scav_sessions set node=(car->>'node')::int where player_id=other_u;
 q:=q||jsonb_build_object('request_id',gen_random_uuid(),'target_id',car->>'id');
 r:=public.scavenging_action('search',q);perform pg_temp.check_scav(r?'error','Car opened without a tool');
 insert into public.game_inventory(season_id,player_id,good_id,quantity) values(s,other_u,'lockpick',1);
 first:=public.scavenging_action('search',q);perform pg_temp.check_scav(not first?'error','Car search failed: '||first::text);
 perform pg_temp.check_scav(public.scavenging_action('search',q)=first,'Car retry failed');
 perform pg_temp.check_scav((select quantity from public.game_inventory where player_id=other_u and good_id='lockpick')=0,'Wrong number of lockpicks consumed');
 update game_private.scav_sessions set pending=pending||jsonb_build_object('ready_at',clock_timestamp()-interval '1 second') where player_id=other_u;
 q:=jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'attempt_id',q->>'request_id');
 first:=public.scavenging_action('finish',q);perform pg_temp.check_scav(not first?'error','Car collection failed: '||first::text);
 perform pg_temp.check_scav((select sum(delta) from game_private.skill_xp_ledger where player_id=other_u and skill_id='lockpicking')=25,'Lockpicking XP missing or forged');
 r:=public.scavenging_action('finish',q);perform pg_temp.check_scav(r=first,'Car collect replay failed');
 denied:=false;begin delete from game_private.scav_results where player_id=other_u;exception when raise_exception then denied:=true;end;
 perform pg_temp.check_scav(denied,'Search history can be erased');
 set local role authenticated;
 denied:=false;begin update game_private.scav_sessions set node=14;exception when insufficient_privilege then denied:=true;end;
 perform pg_temp.check_scav(denied,'Browser can move by writing tables');reset role;
 update public.game_districts set status='lockdown' where id=d;
 r:=public.scavenging_action('move',jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'node',1));perform pg_temp.check_scav(r?'error','Lockdown bypassed');
end$$;
select 'PASS: server travel, search timing, loot ledger, replay safety, lockpicks, skill XP and permissions';
rollback;
