
begin;
do $$
declare owner_id uuid:=gen_random_uuid(); player uuid:=gen_random_uuid(); old_season uuid; next_season uuid; listing uuid; res jsonb; frozen jsonb; v bigint; blocked boolean; gang uuid;
begin
 old_season:=game_private.current_season();
 insert into auth.users(id) values(owner_id),(player);
 perform set_config('request.jwt.claim.sub',owner_id::text,true); perform public.game_state();
 perform set_config('request.jwt.claim.sub',player::text,true); perform public.game_state();
 update public.game_user_roles set role_id='owner' where player_id=owner_id;
 update public.game_players set handle='Season Test Player',subscription='{"plan":"supporter"}' where id=player;
 insert into public.game_season_assets(season_id,player_id,kind,name,quantity,unit_value) values(old_season,player,'land','Test land',2,500);
 insert into public.game_season_loans(season_id,player_id,principal,outstanding) values(old_season,player,1000,300);
 insert into public.game_season_jobs(season_id,player_id,kind,status) values(old_season,player,'crafting','queued');
 insert into public.game_season_gangs(season_id,name) values(old_season,'Test gang') returning id into gang;
 insert into public.game_season_gang_members values(old_season,player,gang,90);
 update public.game_season_players set level=5,skills='{"crafting":4}' where season_id=old_season and player_id=player;
 insert into public.game_sanctions(player_id,kind,reason,actor_id) values(player,'warning','Preserve this moderation record',owner_id);
 set local role authenticated;
 res:=public.season_action('lock',jsonb_build_object('season_id',old_season,'reason','unauthorized lock'));
 if not res ? 'error' then raise exception 'Player controlled season'; end if;
 res:=public.game_action('list','{"good_id":"whiskey","quantity":2,"unit_price":999999}');
 if res ? 'error' then raise exception 'Listing failed: %',res; end if;
 select id into listing from public.game_listings where seller_id=player and status='active';
 res:=public.season_state(old_season,'net_worth',0);
 -- Net worth includes escrow at Owner book value, never the inflated asking price.
 select (r->>'score')::bigint into v from jsonb_array_elements(res->'rankings') r where r->>'player_id'=player::text;
 if v<>11200 then raise exception 'Net worth calculation failed: %',v; end if;
 res:=public.game_action('job','{"job":"docks"}');
 if res ? 'error' then raise exception 'Job failed'; end if;
 res:=public.season_state(old_season,'crime',0);
 select (r->>'score')::bigint into v from jsonb_array_elements(res->'rankings') r where r->>'player_id'=player::text;
 if v<>1 then raise exception 'Authoritative metric not recorded'; end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 res:=public.season_action('create','{"name":"Next Blackwater","reason":"Create test season"}');
 if res ? 'error' then raise exception 'Create failed: %',res; end if;
 next_season:=(res->>'season_id')::uuid;
 res:=public.season_action('configure',jsonb_build_object('season_id',next_season,'name','Next Blackwater','starting_cash',2000,'starting_crates',2,'hall_of_fame_places',3,'reason','Configure next season'));
 if res ? 'error' then raise exception 'Configure failed: %',res; end if;
 res:=public.season_action('snapshot',jsonb_build_object('season_id',old_season,'reason','Snapshot before lock'));
 if not res ? 'error' then raise exception 'Open season snapshot accepted'; end if;
 res:=public.season_action('lock',jsonb_build_object('season_id',old_season,'reason','Close test season'));
 if res ? 'error' then raise exception 'Lock failed: %',res; end if;
 res:=public.game_action('job','{"job":"docks"}');
 if not res ? 'error' then raise exception 'Locked season allowed play'; end if;
 res:=public.staff_action('grant_money',jsonb_build_object('player_id',player,'amount',100,'reason','Locked adjustment'));
 if not res ? 'error' then raise exception 'Owner changed locked economy'; end if;
 res:=public.season_action('snapshot',jsonb_build_object('season_id',old_season,'reason','Capture final rankings'));
 if res ? 'error' then raise exception 'Snapshot failed: %',res; end if;
 frozen:=public.season_state(old_season,'cash',0)->'rankings';
 res:=public.season_action('snapshot',jsonb_build_object('season_id',old_season,'reason','Duplicate snapshot'));
 if not res ? 'error' then raise exception 'Duplicate snapshot accepted'; end if;
 res:=public.season_action('archive',jsonb_build_object('season_id',old_season,'reason','Archive test rankings'));
 if res ? 'error' then raise exception 'Archive failed: %',res; end if;
 res:=public.season_action('launch_next',jsonb_build_object('season_id',next_season,'expected_current_season',old_season,'reason','Missing confirmation'));
 if not res ? 'error' then raise exception 'Reset without confirmation accepted'; end if;
 res:=public.season_state(old_season,'cash',0);
 res:=public.season_action('launch_next',jsonb_build_object('season_id',next_season,'expected_current_season',old_season,'confirmation','RESET '||(res->'season'->>'name'),'reason','Launch clean season'));
 if res ? 'error' then raise exception 'Launch failed: %',res; end if;
 perform set_config('request.jwt.claim.sub',player::text,true);
 res:=public.game_state();
 if (res->'player'->>'cash')::bigint<>2000 or (res->'player'->>'xp')::integer<>0 then raise exception 'Wallet/XP reset failed'; end if;
 if (res->'inventory'->0->>'quantity')::integer<>2 or jsonb_array_length(res->'businesses')<>0 or jsonb_array_length(res->'my_listings')<>0 then raise exception 'Asset reset failed'; end if;
 if res->'player'->>'handle'<>'Season Test Player' or res->'player'->'subscription'->>'plan'<>'supporter' then raise exception 'Permanent identity reset'; end if;
 res:=public.game_action('buy',jsonb_build_object('listing_id',listing,'season_id',old_season));
 if not res ? 'error' then raise exception 'Stale request crossed season boundary'; end if;
 res:=public.game_action('buy',jsonb_build_object('listing_id',listing));
 if not res ? 'error' then raise exception 'Old market order carried forward'; end if;
 res:=public.season_state(old_season,'cash',0);
 if res->'rankings'<>frozen then raise exception 'Archived rankings changed'; end if;
 res:=public.season_profile(player);
 if jsonb_array_length(res->'previous')=0 or jsonb_array_length(res->'current')=0 then raise exception 'Profile missing seasonal rankings'; end if;
 if exists(select 1 from public.game_inventory where season_id=old_season) then raise exception 'Old inventory exposed through REST'; end if;
 reset role;
 if not exists(select 1 from public.game_season_players where player_id=player and season_id=next_season and level=1 and skills='{}') then raise exception 'Skills/level reset failed'; end if;
 if exists(select 1 from public.game_season_assets where season_id=next_season) or exists(select 1 from public.game_season_loans where season_id=next_season)
 or exists(select 1 from public.game_season_jobs where season_id=next_season) or exists(select 1 from public.game_season_gang_members where season_id=next_season) or exists(select 1 from public.game_season_stats where season_id=next_season) then raise exception 'Season state carried forward'; end if;
 if not exists(select 1 from public.game_sanctions where player_id=player) or not exists(select 1 from public.game_hall_of_fame where season_id=old_season) then raise exception 'Preserved history missing'; end if;
 if (select cash from public.game_season_players where season_id=old_season and player_id=player)<>10250 then raise exception 'Old season wallet lost'; end if;
 if (select sum(delta) from public.game_ledger where player_id=player)<>2000 then raise exception 'Ledger broken by reset'; end if;
 blocked:=false; begin delete from public.game_season_results where season_id=old_season; exception when raise_exception then blocked:=true; end;
 if not blocked then raise exception 'Archived rankings deleted'; end if;
 blocked:=false; begin truncate public.game_hall_of_fame; exception when raise_exception then blocked:=true; end;
 if not blocked then raise exception 'Hall of Fame deleted'; end if;
end $$;
select 'PASS: season permissions, valuation, metrics, lifecycle, snapshot freeze, reset confirmation, ledger conservation, season isolation, permanent identity and history, profiles' as result;
rollback;
