begin;
create function pg_temp.skill_check(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
select set_config('game.reason','CI skill curves, permissions and seasonal records',true);
do $$
declare owner_id uuid:=gen_random_uuid();u uuid:=gen_random_uuid();other_id uuid:=gen_random_uuid();s uuid:=game_private.current_season();next_s uuid;payload jsonb;r jsonb;v jsonb;denied boolean;before_cash bigint;before_xp bigint;source uuid:=gen_random_uuid();
begin
 perform pg_temp.skill_check(not exists(select 1 from unnest(array[19,20,100,10000,1000000000]) t cross join generate_series(1,19) l where game_private.skill_threshold(l+1,t)<=game_private.skill_threshold(l,t)),'Level thresholds are not strictly increasing');
 perform pg_temp.skill_check(game_private.skill_threshold(1,10000)=0 and game_private.skill_threshold(20,10000)=10000 and game_private.skill_level(0,10000)=1 and game_private.skill_level(9999,10000)=19 and game_private.skill_level(10000,10000)=20 and game_private.skill_level(10000000,10000)=20,'Level endpoints or cap incorrect');
 perform pg_temp.skill_check(not exists(select 1 from generate_series(2,20) l where game_private.skill_level(game_private.skill_threshold(l,10000)-1,10000)<>l-1 or game_private.skill_level(game_private.skill_threshold(l,10000),10000)<>l),'Boundary XP grants wrong level');
 insert into auth.users(id) values(owner_id),(u),(other_id);
 perform set_config('request.jwt.claim.sub',owner_id::text,true);perform public.game_state();update public.game_user_roles set role_id='owner' where player_id=owner_id;
 perform set_config('request.jwt.claim.sub',u::text,true);perform public.game_state();select cash,xp into before_cash,before_xp from public.game_players where id=u;
 r:=public.skills_state();perform pg_temp.skill_check(jsonb_array_length(r->'skills')=5 and (r->>'max_level')::int=20 and not exists(select 1 from jsonb_array_elements(r->'skills') entry where (entry->>'level')::int<>1 or (entry->>'xp')::bigint<>0),'New player did not start with five level-one skills');
 insert into game_private.skill_xp_ledger(season_id,player_id,skill_id,source_id,delta,description) values(s,u,'crafting',source,2500,'Test completed crafting job'),(s,u,'sharpshooting',gen_random_uuid(),20000,'Test recorded range practice');
 r:=public.skills_state();select x into v from jsonb_array_elements(r->'skills') x where x->>'id'='sharpshooting';perform pg_temp.skill_check((v->>'level')::int=20 and v->'next_level_xp'='null'::jsonb and (v->>'xp')::int=20000,'Excess XP lost or level cap exceeded');
 set local role authenticated;
 denied:=false;begin perform 1 from game_private.skill_xp_ledger;exception when insufficient_privilege then denied:=true;end;perform pg_temp.skill_check(denied,'Private skill XP is exposed');
 denied:=false;begin update public.game_skill_definitions set xp_to_20=19;exception when insufficient_privilege then denied:=true;end;perform pg_temp.skill_check(denied,'Direct skill edits allowed');
 denied:=false;begin perform public.skills_manage('{}');exception when raise_exception then denied:=true;end;perform pg_temp.skill_check(denied,'Player edited skill progression');reset role;
 update public.game_user_roles set role_id='moderator' where player_id=u;
 denied:=false;begin perform public.skills_manage('{}');exception when raise_exception then denied:=true;end;perform pg_temp.skill_check(denied,'Moderator received automatic economic skill control');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 payload:=jsonb_build_object('skill_id','crafting','version',1,'xp_to_20',2500,'crafting_xp_per_minute',20,'expected_crafting_rate',10,'reason','Adjust crafting curve for this test','request_id',gen_random_uuid(),'max_level',999);
 r:=public.skills_manage(payload);perform pg_temp.skill_check(not r?'error','Owner save failed: '||r::text);perform public.skills_manage(payload);
 perform pg_temp.skill_check((select version from public.game_skill_definitions where id='crafting')=2 and (select xp_to_20 from public.game_skill_definitions where id='crafting')=2500,'Retry edited definition twice');
 perform pg_temp.skill_check(exists(select 1 from public.game_audit where actor_id=owner_id and reason like 'Skill configuration:%'),'Owner skill edits omitted audit');
 r:=public.skills_manage(payload||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.skill_check(r?'error','Stale owner editor overwrote a newer configuration');
 r:=public.skills_manage(payload||jsonb_build_object('xp_to_20',5000));perform pg_temp.skill_check(r?'error','Changed payload reused an existing save reference');
 r:=public.skills_manage(payload||jsonb_build_object('request_id',gen_random_uuid(),'version',2,'expected_crafting_rate',20,'xp_to_20',18));perform pg_temp.skill_check(r?'error','Curve accepted too little XP for 20 distinct levels');
 perform set_config('request.jwt.claim.sub',u::text,true);r:=public.skills_state();select x into v from jsonb_array_elements(r->'skills') x where x->>'id'='crafting';perform pg_temp.skill_check((v->>'level')::int=20 and (v->>'xp')::int=2500,'Owner change failed to recalculate level from preserved XP');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 r:=public.skills_manage(payload||jsonb_build_object('request_id',gen_random_uuid(),'version',2,'expected_crafting_rate',20,'xp_to_20',10000));perform pg_temp.skill_check(not r?'error','Raised target save failed');
 perform set_config('request.jwt.claim.sub',u::text,true);r:=public.skills_state();select x into v from jsonb_array_elements(r->'skills') x where x->>'id'='crafting';perform pg_temp.skill_check((v->>'level')::int<20 and (v->>'xp')::int=2500,'Raised target destroyed XP or failed to recalculate level');
 perform pg_temp.skill_check((select cash=before_cash and xp=before_xp from public.game_players where id=u),'Skill progress changed cash or paid power again');
 perform set_config('request.jwt.claim.sub',other_id::text,true);perform public.game_state();r:=public.skills_state();perform pg_temp.skill_check(jsonb_array_length(r->'recent')=0 and not exists(select 1 from jsonb_array_elements(r->'skills') x where (x->>'xp')::bigint<>0),'A player saw another player skill progress');
 denied:=false;begin update game_private.skill_xp_ledger set delta=1 where source_id=source;exception when raise_exception then denied:=true;end;perform pg_temp.skill_check(denied,'Skill history can be edited');
 perform pg_temp.skill_check(not has_function_privilege('anon','public.skills_state()','execute') and not has_function_privilege('authenticated','game_private.skill_activity_award()','execute'),'Skill internals or anonymous access exposed');
 insert into public.game_seasons(name,status,starting_cash,starting_crates) values('Skills next season','draft',10000,5) returning id into next_s;update game_private.season_runtime set season_id=next_s where singleton;
 perform set_config('request.jwt.claim.sub',u::text,true);r:=public.skills_state();perform pg_temp.skill_check(jsonb_array_length(r->'recent')=0 and not exists(select 1 from jsonb_array_elements(r->'skills') x where (x->>'level')::int<>1 or (x->>'xp')::bigint<>0),'Old skill levels carried into a new season');
 perform pg_temp.skill_check((select count(*) from game_private.skill_xp_ledger where season_id=s and player_id=u)=2,'Season change deleted prior skill history');
end$$;
select 'PASS: strict level curve, cap 20, recalculation, preserved XP, private records, owner-only control, audits, retries and seasons';
rollback;
