begin;
create function pg_temp.check_melee(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
select set_config('game.reason','CI melee validation',true);
update public.game_settings set value=0 where key='scavenging_patrol_enabled';
do $$declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();sid uuid:=gen_random_uuid();s uuid:=game_private.current_season();d uuid;p jsonb;r jsonb;hp numeric;begin
 insert into auth.users(id) values(a),(b);
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 insert into auth.sessions(id,user_id,created_at) values(sid,a,clock_timestamp()),(gen_random_uuid(),b,clock_timestamp());
 insert into game_private.player_presence(player_id,session_id) select user_id,id from auth.sessions where user_id in(a,b);
 select id into d from public.game_districts where slug='the-waterfront';
 insert into game_private.scav_sessions(season_id,player_id,district_id,route_points,departed_at,arrives_at,street_seen_at) values(s,a,d,'[[1,0]]',clock_timestamp(),clock_timestamp(),clock_timestamp()),(s,b,d,'[[1.02,0]]',clock_timestamp(),clock_timestamp(),clock_timestamp());
 perform set_config('request.jwt.claim.sub',a::text,true);
 p:=jsonb_build_object('season_id',s,'request_id',gen_random_uuid(),'kind','player','target_id',b,'damage',99999,'position','[1.02,0]');
 r:=public.scavenging_action('punch',p);perform pg_temp.check_melee(not r?'error' and (r->>'hit')::boolean,'Punch failed: '||r);
 select health into hp from public.game_season_players where season_id=s and player_id=b;
 perform pg_temp.check_melee(hp between 91 and 96,'Client forged damage');
 perform pg_temp.check_melee(public.scavenging_action('punch',p)=r,'Replay changed result');
 perform pg_temp.check_melee((select health=hp from public.game_season_players where season_id=s and player_id=b),'Replay applied extra damage');
 perform pg_temp.check_melee(public.scavenging_action('punch',p||jsonb_build_object('request_id',gen_random_uuid()))?'error','Cooldown bypass');
 update game_private.scav_sessions set melee_ready_at=null,melee_protected_until=null;
 update game_private.scav_sessions set route_points='[[4,2]]' where player_id=b;
 perform pg_temp.check_melee(public.scavenging_action('punch',p||jsonb_build_object('request_id',gen_random_uuid()))?'error','Out-of-range punch accepted');
 update game_private.scav_sessions set route_points='[[1.02,0]]',street_seen_at=clock_timestamp()-interval '1 hour' where player_id=b;
 perform pg_temp.check_melee(public.scavenging_action('punch',p||jsonb_build_object('request_id',gen_random_uuid()))?'error','Offline punch accepted');
 perform pg_temp.check_melee(public.scavenging_action('punch',p||jsonb_build_object('request_id',gen_random_uuid(),'target_id',a))?'error','Self punch accepted');
 perform pg_temp.check_melee(not has_function_privilege('anon','public.street_combat_state(uuid,uuid)','execute'),'Anonymous roster access');
 perform pg_temp.check_melee(not has_function_privilege('authenticated','public.scavenging_action_before_melee(text,jsonb)','execute'),'Legacy action exposed');
end$$;
rollback;
