begin;
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();d uuid:=gen_random_uuid();s uuid:=game_private.current_season();t uuid;g uuid;gt uuid;m uuid;r jsonb;q jsonb;nonce uuid;cash_before bigint;fee bigint;denied boolean;body text:='PRIVATE GROUP CONTENT';office public.game_telegram_office;
begin
 insert into auth.users(id,raw_user_meta_data) values
 (a,jsonb_build_object('username','GroupA'||left(replace(a::text,'-',''),8))),
 (b,jsonb_build_object('username','GroupB'||left(replace(b::text,'-',''),8))),
 (c,jsonb_build_object('username','GroupC'||left(replace(c::text,'-',''),8))),
 (d,jsonb_build_object('username','GroupD'||left(replace(d::text,'-',''),8)));
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',c::text,true);perform public.game_state();
 perform set_config('request.jwt.claim.sub',d::text,true);perform public.game_state();
 perform set_config('game.reason','Rollback-only group test',true);
 update public.game_players set cash=100000 where id in(a,b,c,d);
 select * into office from public.game_telegram_office;
 select telegram_fee into fee from public.game_district_businesses where id=office.business_id;
 perform set_config('request.jwt.claim.sub',a::text,true);
 set local role authenticated;
 nonce:=gen_random_uuid();
 q:=jsonb_build_object('request_id',nonce,'name','Waterfront Partners');
 r:=public.telegram_room_action('create',q);if r?'error' then raise exception 'Group create: %',r;end if;t:=(r->>'thread_id')::uuid;
 r:=public.telegram_room_action('create',q);if (r->>'thread_id')::uuid<>t then raise exception 'Duplicate create on retry';end if;
 r:=public.telegram_room_action('create',q||'{"name":"Changed name"}');if not(r?'error') then raise exception 'Idempotency mismatch accepted';end if;
 denied:=false;begin perform game_private.telegram_access(t,b);exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Internal helper exposed';end if;
 r:=public.profile_avatar('javascript:alert(1)');if not(r?'error') then raise exception 'Unsafe avatar saved';end if;
 r:=public.profile_avatar('https://images.example.com/player-a.jpg');if r?'error' then raise exception 'Profile update: %',r;end if;
 reset role;
 if (select avatar_url from game_private.identities where player_id=a)<>'https://images.example.com/player-a.jpg' or (select avatar_url from game_private.identities where player_id=b) is not null then raise exception 'Avatar ownership wrong';end if;
 r:=public.telegram_room_action('invite',jsonb_build_object('request_id',gen_random_uuid(),'thread_id',t,'username',(select username from game_private.identities where player_id=b)));if r?'error' then raise exception 'Invite: %',r;end if;
 perform set_config('request.jwt.claim.sub',b::text,true);
 r:=public.telegram_state();if jsonb_array_length(r->'invitations')<>1 then raise exception 'Invite not visible';end if;
 denied:=false;begin perform public.telegram_state(t);exception when others then denied:=true;end;if not denied then raise exception 'Unaccepted invite reads conversation';end if;
 r:=public.telegram_room_action('accept',jsonb_build_object('request_id',gen_random_uuid(),'thread_id',t));if r?'error' then raise exception 'Accept: %',r;end if;
 r:=public.telegram_room_action('rename',jsonb_build_object('request_id',gen_random_uuid(),'thread_id',t,'name','Stolen group'));if not(r?'error') then raise exception 'Member controls owner settings';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 select cash into cash_before from public.game_players where id=a;
 q:=jsonb_build_object('request_id',gen_random_uuid(),'thread_id',t,'body',body,'fee',fee,'season_id',s);
 r:=public.telegram_action('send',q||jsonb_build_object('fee',fee+1));if not(r?'error') then raise exception 'Forged group fee accepted';end if;
 r:=public.telegram_action('send',q);if r?'error' then raise exception 'Group send: %',r;end if;
 r:=public.telegram_action('send',q);if r?'error' then raise exception 'Group retry: %',r;end if;
 if (select cash from public.game_players where id=a)<>cash_before-fee then raise exception 'Group charged more than once';end if;
 if (select count(*) from game_private.telegram_receipts where message_id in(select id from game_private.telegrams where thread_id=t))<>1 then raise exception 'Wrong receipt count';end if;
 select id into m from game_private.telegrams where thread_id=t;
 if not exists(select 1 from game_private.telegram_deliveries where message_id=m and player_id=b) then raise exception 'Missing group delivery';end if;
 perform set_config('request.jwt.claim.sub',b::text,true);
 set local role authenticated;
 r:=public.telegram_state(t);if r->'messages'->0->>'body'<>body or r->'messages'->0->>'sender_avatar'<>'https://images.example.com/player-a.jpg' then raise exception 'Message or avatar missing: %',r->'messages';end if;
 r:=public.telegram_action('report',jsonb_build_object('message_id',m,'reason','Review this group telegram'));if r?'error' then raise exception 'Group report failed: %',r;end if;
 r:=public.telegram_action('archive',jsonb_build_object('thread_id',t));if r?'error' then raise exception 'Group archive failed';end if;
 reset role;
 perform set_config('request.jwt.claim.sub',c::text,true);
 denied:=false;begin perform public.telegram_state(t);exception when others then denied:=true;end;if not denied then raise exception 'Stranger reads group';end if;
 r:=public.telegram_action('send',q||jsonb_build_object('request_id',gen_random_uuid()));if not(r?'error') then raise exception 'Stranger sends to group';end if;
 r:=public.telegram_action('report',jsonb_build_object('message_id',m,'reason','Spoofed report'));if not(r?'error') then raise exception 'Stranger reports inaccessible message';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 r:=public.telegram_room_action('invite',jsonb_build_object('request_id',gen_random_uuid(),'thread_id',t,'username',(select username from game_private.identities where player_id=c)));
 perform set_config('request.jwt.claim.sub',c::text,true);
 r:=public.telegram_room_action('accept',jsonb_build_object('request_id',gen_random_uuid(),'thread_id',t));
 r:=public.telegram_state(t);if jsonb_array_length(r->'messages')<>0 or (r->>'unread')::integer<>0 then raise exception 'New member sees past telegrams';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 r:=public.telegram_action('send',q||jsonb_build_object('request_id',gen_random_uuid(),'body','NEW GROUP DELIVERY'));if r?'error' then raise exception 'Multi-recipient send: %',r;end if;
 if (select cash from public.game_players where id=a)<>cash_before-2*fee then raise exception 'Group charged per recipient';end if;
 perform set_config('request.jwt.claim.sub',c::text,true);
 r:=public.telegram_state(t);if jsonb_array_length(r->'messages')<>1 or r->'messages'->0->>'body'<>'NEW GROUP DELIVERY' then raise exception 'New member delivery incorrect';end if;
 r:=public.telegram_action('block',jsonb_build_object('player_id',a));
 perform set_config('request.jwt.claim.sub',a::text,true);
 r:=public.telegram_action('send',q||jsonb_build_object('request_id',gen_random_uuid(),'body','BLOCKED GROUP DELIVERY'));if r?'error' then raise exception 'Available members should receive: %',r;end if;
 perform set_config('request.jwt.claim.sub',c::text,true);
 r:=public.telegram_state(t);if r::text like '%BLOCKED GROUP DELIVERY%' then raise exception 'Blocked participant received group message';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 r:=public.telegram_room_action('remove',jsonb_build_object('request_id',gen_random_uuid(),'thread_id',t,'player_id',b));
 perform set_config('request.jwt.claim.sub',b::text,true);
 denied:=false;begin perform public.telegram_state(t);exception when others then denied:=true;end;if not denied then raise exception 'Removed member retains access';end if;
 perform set_config('request.jwt.claim.sub',c::text,true);perform public.telegram_action('unblock',jsonb_build_object('player_id',a));
 perform set_config('request.jwt.claim.sub',a::text,true);
 r:=public.telegram_room_action('transfer',jsonb_build_object('request_id',gen_random_uuid(),'thread_id',t,'player_id',c));if r?'error' then raise exception 'Owner transfer failed %',r;end if;
 r:=public.telegram_room_action('leave',jsonb_build_object('request_id',gen_random_uuid(),'thread_id',t));if r?'error' then raise exception 'Former owner cannot leave';end if;
 if not exists(select 1 from game_private.telegram_room_events where thread_id=t and action='transfer') then raise exception 'Missing private membership history';end if;
 perform set_config('request.jwt.claim.sub',c::text,true);
 r:=public.telegram_room_action('close',jsonb_build_object('request_id',gen_random_uuid(),'thread_id',t));if r?'error' then raise exception 'Close group failed: %',r;end if;
 r:=public.telegram_state(t);if not (r->'thread'->>'closed')::boolean or jsonb_array_length(r->'messages')=0 then raise exception 'Closure removed history';end if;
 r:=public.telegram_action('send',q||jsonb_build_object('request_id',gen_random_uuid()));if not(r?'error') then raise exception 'Closed group accepts messages';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 -- Gang channels use the actual seasonal gang roster, never supplied member lists.
 insert into public.game_season_gangs(season_id,name,data) values(s,'Telegram Test Gang',jsonb_build_object('owner_id',a)) returning id into g;
 insert into public.game_season_gang_members(season_id,player_id,gang_id) values(s,a,g),(s,b,g);
 r:=public.telegram_room_action('gang',jsonb_build_object('request_id',gen_random_uuid(),'gang_id',gen_random_uuid()));if r?'error' then raise exception 'Gang open: %',r;end if;gt:=(r->>'thread_id')::uuid;
 r:=public.telegram_action('send',q||jsonb_build_object('request_id',gen_random_uuid(),'thread_id',gt,'body','GANG ONLY'));if r?'error' then raise exception 'Gang send: %',r;end if;
 perform set_config('request.jwt.claim.sub',b::text,true);
 r:=public.telegram_state(gt);if r->'messages'->0->>'body'<>'GANG ONLY' then raise exception 'Gang delivery missing';end if;
 delete from public.game_season_gang_members where player_id=b and season_id=s;
 denied:=false;begin perform public.telegram_state(gt);exception when others then denied:=true;end;if not denied then raise exception 'Former gang member retains access';end if;
 perform set_config('request.jwt.claim.sub',d::text,true);
 r:=public.telegram_room_action('gang',jsonb_build_object('request_id',gen_random_uuid(),'gang_id',g));if not(r?'error') then raise exception 'Forged gang membership accepted';end if;
 if exists(select 1 from public.game_audit where before_data::text like '%PRIVATE GROUP CONTENT%' or after_data::text like '%PRIVATE GROUP CONTENT%') then raise exception 'Private group message in public audit';end if;
 denied:=false;begin delete from game_private.telegram_deliveries where message_id=m;exception when others then denied:=true;end;if not denied then raise exception 'Private delivery evidence deleted';end if;
end $$;
select 'PASS: group invitations, privacy, avatars, membership, gang authorization, closures, blocks, reports and office fee conservation' as result;
rollback;

