begin;
create function pg_temp.verify(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',msg;end if;end$$;
do $$declare u uuid:=gen_random_uuid();other uuid:=gen_random_uuid();s uuid;home uuid;dest uuid;v uuid;req jsonb;r jsonb;first jsonb;cash0 bigint;begin
 insert into auth.users(id) values(u),(other);perform set_config('request.jwt.claim.sub',u::text,true);perform public.game_state();s:=game_private.current_season();
 perform set_config('game.reason','Travel integration tests',true);update public.game_settings set value=1 where key='travel_enabled';
 select id into home from public.game_districts where slug='the-waterfront';select id into dest from public.game_districts where slug='old-town';
 r:=public.travel_state();perform pg_temp.verify((r#>>'{current,id}')::uuid=home,'Starting location incorrect');
 insert into game_private.scav_district_heat(season_id,player_id,district_id,heat,searches) values(s,u,home,32,4);
 r:=public.travel_state();perform pg_temp.verify((r->>'heat')::numeric between 31 and 32,'Personal dashboard heat missing');
 req:=jsonb_build_object('season_id',s,'district_id',dest,'method','train','request_id',gen_random_uuid(),'cost',0,'seconds',0);
 select cash into cash0 from public.game_players where id=u;
 set local role authenticated;
 first:=public.travel_action('start',req);perform pg_temp.verify(not first?'error','Train failed '||first::text);
 perform pg_temp.verify(public.travel_action('start',req)=first,'Retry charged again');
 r:=public.travel_action('start',req||jsonb_build_object('request_id',gen_random_uuid()));perform pg_temp.verify(r?'error','Overlapping journeys allowed');
 r:=public.scavenging_action('enter',jsonb_build_object('season_id',s,'district_id',dest,'request_id',gen_random_uuid()));perform pg_temp.verify(r?'error','Entered while travelling');
 reset role;
 perform pg_temp.verify((select cash from public.game_players where id=u)=cash0-50,'Fare trusted client');
 perform pg_temp.verify((select arrives_at>clock_timestamp()+interval '40 seconds' from game_private.district_travel where player_id=u),'Travel time trusted client');
 update game_private.district_travel set arrives_at=clock_timestamp()-interval '1 second' where player_id=u;
 r:=public.travel_state();perform pg_temp.verify((r#>>'{current,id}')::uuid=dest and r->'journey'='null'::jsonb,'Arrival did not persist');
 perform pg_temp.verify((r->>'heat')::numeric=0,'Heat leaked between districts');
 insert into game_private.street_vehicles(season_id,player_id,district_id,model_id,name,sale_value,status,source_id) values(s,u,dest,'coupe','Test coupe',1500,'stored',gen_random_uuid()) returning id into v;
 req:=jsonb_build_object('season_id',s,'district_id',home,'method','drive','vehicle_id',v,'request_id',gen_random_uuid());
 r:=public.travel_action('start',req);perform pg_temp.verify(r?'error','Drove without fuel');
 first:=public.travel_action('refuel',jsonb_build_object('season_id',s,'vehicle_id',v,'units',10,'request_id',gen_random_uuid()));perform pg_temp.verify(not first?'error','Refuel failed');
 first:=public.travel_action('start',req);perform pg_temp.verify(not first?'error','Drive failed '||first::text);perform pg_temp.verify(public.travel_action('start',req)=first,'Drive retry changed');
 perform pg_temp.verify((select fuel from game_private.street_vehicles where id=v)=5,'Fuel not consumed exactly once');
 update game_private.district_travel set arrives_at=clock_timestamp()-interval '1 second' where player_id=u;perform public.travel_state();
 perform set_config('request.jwt.claim.sub',other::text,true);perform public.game_state();
 r:=public.travel_action('start',req||jsonb_build_object('request_id',gen_random_uuid(),'district_id',dest));perform pg_temp.verify(r?'error','Used another player car');
 perform set_config('request.jwt.claim.sub',u::text,true);
 select cash into cash0 from public.game_players where id=u;
 r:=public.travel_action('start',jsonb_build_object('season_id',s,'district_id',dest,'method','walk','request_id',gen_random_uuid()));perform pg_temp.verify(not r?'error','Walk failed');
 perform pg_temp.verify((select cash from public.game_players where id=u)=cash0,'Walking charged cash');
 r:=public.street_motion('begin',jsonb_build_object('season_id',s,'district_id',home,'controller',gen_random_uuid()));perform pg_temp.verify(r?'error','Street movement bypassed travel');
 update game_private.district_travel set arrives_at=clock_timestamp()-interval '1 second' where player_id=u;perform public.travel_state();
 update public.game_players set cash=0 where id=u;
 r:=public.travel_action('start',jsonb_build_object('season_id',s,'district_id',home,'method','train','request_id',gen_random_uuid()));perform pg_temp.verify(r?'error','Train allowed without fare');
 perform pg_temp.verify((public.travel_state()->'journey')='null'::jsonb,'Failed fare left a journey');
 update public.game_seasons set status='locked',locked_at=clock_timestamp() where id=s;
 r:=public.travel_action('start',jsonb_build_object('season_id',s,'district_id',home,'method','walk','request_id',gen_random_uuid()));perform pg_temp.verify(r?'error','Travel started in a locked season');

end$$;
rollback;
