import {test,expect,type Page} from "@playwright/test";
import {cookie,token} from "../fixtures/identity.mjs";
const headers={Authorization:"Bearer "+token};
async function capture(page:Page,name:string){const shot=await page.screenshot({path:"test-results/"+name+".jpg",type:"jpeg",quality:70});if(process.env.VISUAL_REVIEW==="1"){const b=shot.toString("base64");for(let n=0;n<b.length;n+=12000)console.log("VISUAL_REVIEW_"+name+"_"+Math.floor(n/12000)+":"+b.slice(n,n+12000));}}
test.beforeEach(async({context,request})=>{test.skip(process.env.GAME_TEST_FIXTURE!=="1","Isolated fixture");await request.post("http://127.0.0.1:54329/__reset_world",{headers});await context.addCookies([{name:"sb-127-auth-token",value:cookie,domain:"localhost",path:"/",sameSite:"Lax"}]);});
test("Bank navigation, deposits, withdrawals and the shared cash display",async({page})=>{
 await page.goto("/dashboard");const nav=page.getByRole("navigation",{name:"Game navigation"});await nav.getByRole("link",{name:"Bank",exact:true}).click();await expect(nav.getByRole("link",{name:"Districts",exact:true})).toHaveCount(0);
 await expect(page.locator(".bank-balance strong")).toHaveText("$0");await expect(page.getByRole("button",{name:"Withdraw funds",exact:true})).toBeDisabled();
 await page.getByRole("button",{name:"Deposit funds",exact:true}).click();await page.getByLabel("Amount ($)",{exact:true}).fill("2500");await page.getByRole("button",{name:"Confirm deposit"}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.locator(".bank-balance strong")).toHaveText("$2,500");await expect(page.locator(".header-cash")).toContainText("$7,500");
 await page.getByRole("button",{name:"Withdraw funds",exact:true}).click();await page.getByLabel("Amount ($)",{exact:true}).fill("500");await page.getByRole("button",{name:"Confirm withdrawal"}).click();await expect(page.locator(".bank-balance strong")).toHaveText("$2,000");await expect(page.locator(".header-cash")).toContainText("$8,000");await expect(page.locator(".bank-statement tbody tr")).toHaveCount(2);
 await expect(page.locator(".bank-flow")).toContainText("$2,500");await expect(page.locator(".bank-flow")).toContainText("$500");
});
test("uncertain replies retry the exact transfer without duplicating money",async({page})=>{
 await page.goto("/bank");let original="",calls=0;await page.route("**/rest/v1/rpc/bank_action",async route=>{calls++;if(calls===1){original=route.request().postData()??"";await route.fetch();await route.abort();}else{expect(route.request().postData()).toBe(original);await route.continue();}});
 await page.getByRole("button",{name:"Deposit funds",exact:true}).click();await page.getByLabel("Amount ($)",{exact:true}).fill("1000");await page.getByRole("button",{name:"Confirm deposit"}).click();await page.getByRole("button",{name:"Retry transfer safely"}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.locator(".bank-balance strong")).toHaveText("$1,000");await expect(page.locator(".header-cash")).toContainText("$9,000");await expect(page.locator(".bank-statement tbody tr")).toHaveCount(1);
});
test("changed funds and closed seasons are enforced; pausing deposits allows withdrawals",async({page,request})=>{
 await page.goto("/bank");await page.getByRole("button",{name:"Deposit funds",exact:true}).click();await page.getByLabel("Amount ($)",{exact:true}).fill("5000");await request.post("http://127.0.0.1:54329/__bank_setup",{headers,data:{cash:1000}});await page.getByRole("button",{name:"Confirm deposit"}).click();await expect(page.getByRole("dialog")).toContainText("Not enough cash");await page.getByRole("button",{name:"Close transfer"}).click();
 await request.post("http://127.0.0.1:54329/__bank_setup",{headers,data:{history:true,pause:true}});await page.reload();await expect(page.getByRole("button",{name:"Deposit funds",exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:"Withdraw funds",exact:true})).toBeEnabled();
 // A pending form belongs to the season in which it was opened.
 await page.getByRole("button",{name:"Withdraw funds",exact:true}).click();await page.getByLabel("Amount ($)",{exact:true}).fill("100");await request.post("http://127.0.0.1:54329/__bank_setup",{headers,data:{nextSeason:true}});await page.getByRole("button",{name:"Confirm withdrawal"}).click();await expect(page.getByRole("dialog")).toContainText("season changed");
 await page.getByRole("button",{name:"Close transfer"}).click();await request.post("http://127.0.0.1:54329/__bank_setup",{headers,data:{close:true}});await page.reload();await expect(page.getByRole("button",{name:"Withdraw funds",exact:true})).toBeDisabled();await expect(page.locator(".bank-status")).toHaveText("SEASON CLOSED");
});
test("real statements paginate and bank artwork stays readable on desktop and mobile",async({page,request})=>{
 await request.post("http://127.0.0.1:54329/__bank_setup",{headers,data:{history:true}});await page.setViewportSize({width:1672,height:1100});await page.goto("/bank");await expect(page.locator(".bank-hero-art")).toBeVisible();await expect.poll(()=>page.locator(".bank-hero-art").evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);
 await expect(page.locator(".bank-statement tbody tr")).toHaveCount(10);await capture(page,"bank-desktop");await page.getByRole("button",{name:"Next →",exact:true}).click();await expect(page.locator(".bank-statement tbody tr")).toHaveCount(4);await expect(page.locator(".bank-pagination")).toContainText("Page 2 of 2");await page.getByRole("button",{name:"← Previous",exact:true}).click();await expect(page.locator(".bank-statement tbody tr")).toHaveCount(10);
 for(const width of [1920,1448,1200,1024,850,768,580,390,360]){await page.setViewportSize({width,height:1100});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"Bank overflow at "+width).toBe(true);}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await capture(page,"bank-mobile");await page.locator(".bank-account").scrollIntoViewIfNeeded();await capture(page,"bank-mobile-account");await page.getByRole("button",{name:"Deposit funds",exact:true}).click();await page.getByLabel("Amount ($)",{exact:true}).fill("5000");await capture(page,"bank-mobile-transfer");expect(await page.getByRole("dialog").evaluate(el=>el.getBoundingClientRect().width)).toBeLessThan(390);
});
