import {test,expect,type Page} from '@playwright/test';
import {cookie,token} from '../fixtures/identity.mjs';
test.beforeEach(async({context,request})=>{test.skip(process.env.GAME_TEST_FIXTURE!=='1','Isolated fixture');await request.post('http://127.0.0.1:54329/__reset_world',{headers:{Authorization:'Bearer '+token}});await context.addCookies([{name:'sb-127-auth-token',value:cookie,domain:'localhost',path:'/'}]);});
async function start(page:Page){page.on('dialog',d=>d.accept());await page.goto('/chop-shop');await expect(page.getByRole('navigation',{name:'Game navigation'})).toBeVisible();await page.getByRole('button',{name:'Commit car · $350'}).click();await expect(page.locator('.chop-workspace-title')).toContainText('Stolen coupe');}
async function loosen(page:Page){for(let n=1;n<=4;n++){const b=page.getByRole('button',{name:'Undo fastener '+n});await expect(b).toBeEnabled();await b.click();}const disconnect=page.getByRole('button',{name:/^Disconnect /});await expect(disconnect).toBeEnabled();await disconnect.click();await expect(page.locator('.chop-loose-part')).toBeEnabled();}
test('active removal requires fasteners, persists through pause and reload, and supports drag salvage',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await start(page);await expect(page.getByRole('button',{name:'Engine Remove battery first'})).toBeDisabled();await page.getByRole('button',{name:'Battery Salvage ×1'}).click();await expect(page.getByRole('button',{name:'Undo fastener 2'})).toBeDisabled();await expect(page.getByRole('button',{name:'Undo fastener 1'})).toBeEnabled();await page.getByRole('button',{name:'Undo fastener 1'}).click();
 await page.getByRole('button',{name:'Pause and release bay'}).click();await page.reload();await expect(page.getByRole('heading',{name:'Saved in paused storage'})).toBeVisible();await page.getByRole('button',{name:'Rejoin bay queue'}).click();await expect(page.getByRole('button',{name:'Undo fastener 1'})).toBeDisabled();for(let n=2;n<=4;n++){const b=page.getByRole('button',{name:'Undo fastener '+n});await expect(b).toBeEnabled();await b.click();}await expect(page.getByRole('button',{name:'Disconnect terminals'})).toBeEnabled();await page.getByRole('button',{name:'Disconnect terminals'}).click();await expect(page.locator('.chop-loose-part')).toBeEnabled();
 await page.locator('.chop-loose-part').scrollIntoViewIfNeeded();const a=(await page.locator('.chop-loose-part').boundingBox())!,b=(await page.locator('.chop-salvage-tray').boundingBox())!;await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:8});await page.mouse.up();await expect(page.getByRole('button',{name:'Battery Removed ✓'})).toBeVisible();await expect(page.getByRole('button',{name:'Engine Salvage ×1'})).toBeEnabled();await page.screenshot({path:'test-results/chop-shop-desktop.jpg',type:'jpeg',fullPage:true});
});
test('mobile removal and keyboard lift fit the screen, then scrap releases the car',async({page})=>{
 await page.setViewportSize({width:390,height:844});await start(page);await page.getByRole('button',{name:'Wheels Salvage ×4'}).click();await loosen(page);const lift=page.getByRole('button',{name:'Lift wheels into tray'});await lift.focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Wheels Removed ✓'})).toBeVisible();await page.getByRole('button',{name:'Doors Salvage ×2'}).click();await page.screenshot({path:'test-results/chop-shop-mobile.jpg',type:'jpeg',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('button',{name:'Scrap remaining shell'}).click();await expect(page.getByRole('status')).toContainText('Shell scrapped');await expect(page.getByRole('button',{name:'Commit car · $350'})).toBeDisabled();
});

test('interrupted entry response retries safely and restores the same car',async({page})=>{
 await page.route('**/rest/v1/rpc/chop_shop_action',async route=>{await route.fetch();await route.abort();await page.unroute('**/rest/v1/rpc/chop_shop_action');});
 page.on('dialog',d=>d.accept());await page.goto('/chop-shop');await page.getByRole('button',{name:'Commit car · $350'}).click();await expect(page.getByRole('button',{name:'Retry action safely'})).toBeVisible();await page.getByRole('button',{name:'Retry action safely'}).click();await expect(page.locator('.chop-workspace-title')).toContainText('Stolen coupe');await expect(page.locator('.chop-footer')).toContainText('Fee paid $350');
});
