import {test,expect,type Page} from "@playwright/test";
import {cookie,token} from "../fixtures/identity.mjs";
const headers={Authorization:"Bearer "+token};
async function capture(page:Page,name:string){const s=await page.screenshot({path:"test-results/"+name+".jpg",type:"jpeg",quality:70});if(process.env.VISUAL_REVIEW==="1"){const b=s.toString("base64");for(let i=0;i<b.length;i+=12000)console.log("VISUAL_REVIEW_"+name+"_"+Math.floor(i/12000)+":"+b.slice(i,i+12000));}}
test.beforeEach(async({context,request})=>{test.skip(process.env.GAME_TEST_FIXTURE!=="1","Isolated fixture");await request.post("http://127.0.0.1:54329/__reset_world",{headers});await context.addCookies([{name:"sb-127-auth-token",value:cookie,domain:"localhost",path:"/",sameSite:"Lax"}]);});
test("Inventory replaces Properties and does not grant starter storage or screenshot items",async({page})=>{
 await page.goto("/dashboard");await page.getByRole("navigation",{name:"Game navigation"}).getByRole("link",{name:"Inventory",exact:true}).click();await expect(page.getByRole("heading",{name:"Inventory",level:1})).toBeVisible();await expect(page.locator(".inv-no-storage")).toContainText("don’t own a storage building");
 await expect(page.locator(".inv-items")).not.toContainText("Tommy Gun");await page.goto("/properties");await expect(page).toHaveURL(/\/inventory$/);await expect(page.locator(".inv-page")).toBeVisible();await capture(page,"inventory-new-player");
});
test("move existing stock into an owned warehouse and retrieve it for trading",async({page,request})=>{
 await request.post("http://127.0.0.1:54329/__inventory_setup",{headers,data:{storage:true}});await page.goto("/inventory");await page.getByLabel("Search inventory").fill("Whiskey");await page.getByRole("button",{name:"Store",exact:true}).click();await page.getByLabel("Quantity",{exact:true}).fill("4");await page.getByRole("button",{name:"Confirm storage"}).click();await expect(page.getByRole("dialog")).toHaveCount(0);
 await expect(page.locator(".inv-selected dl").getByText("4",{exact:true})).toBeVisible();const response=await request.post("http://127.0.0.1:54329/rest/v1/rpc/game_state",{headers,data:{}});expect((await response.json()).inventory.find((x:any)=>x.good_id==="whiskey").quantity).toBe(1);
 await page.getByRole("button",{name:"Retrieve",exact:true}).click();await page.getByLabel("Quantity",{exact:true}).fill("2");await page.getByRole("button",{name:"Confirm retrieval"}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.locator(".inv-selected dl").getByText("3",{exact:true})).toBeVisible();await expect(page.locator(".inv-recent li")).toHaveCount(4);
 await page.getByRole("link",{name:"Trade on the market"}).click();await expect(page).toHaveURL(/market.*whiskey/);
});
test("server rejects changed stock and warehouse capacity, and lost replies retry safely",async({page,request})=>{
 await request.post("http://127.0.0.1:54329/__inventory_setup",{headers,data:{storage:true}});await page.goto("/inventory");await page.getByLabel("Search inventory").fill("Whiskey");await page.getByRole("button",{name:"Store",exact:true}).click();await page.getByLabel("Quantity",{exact:true}).fill("4");await request.post("http://127.0.0.1:54329/__inventory_setup",{headers,data:{capacity:2}});await page.getByRole("button",{name:"Confirm storage"}).click();await expect(page.getByRole("dialog")).toContainText("not have enough free storage");await page.getByRole("button",{name:"Close item transfer"}).click();
 await request.post("http://127.0.0.1:54329/__inventory_setup",{headers,data:{capacity:2000}});await page.reload();await page.getByLabel("Search inventory").fill("Whiskey");await page.getByRole("button",{name:"Store",exact:true}).click();await page.getByLabel("Quantity",{exact:true}).fill("4");await request.post("http://127.0.0.1:54329/__inventory_setup",{headers,data:{quantity:2}});await page.getByRole("button",{name:"Confirm storage"}).click();await expect(page.getByRole("dialog")).toContainText("Not enough carried stock");await page.getByRole("button",{name:"Close item transfer"}).click();await page.reload();
 let first="",calls=0;await page.route("**/rest/v1/rpc/inventory_action",async route=>{calls++;if(calls===1){first=route.request().postData()??"";await route.fetch();await route.abort();}else{expect(route.request().postData()).toBe(first);await route.continue();}});await page.getByLabel("Search inventory").fill("Whiskey");await page.getByRole("button",{name:"Store",exact:true}).click();await page.getByLabel("Quantity",{exact:true}).fill("2");await page.getByRole("button",{name:"Confirm storage"}).click();await page.getByRole("button",{name:"Retry safely"}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.locator(".inv-recent li")).toHaveCount(2);
});
test("filters, existing item artwork, equipment and responsive views",async({page,request})=>{
 await request.post("http://127.0.0.1:54329/__inventory_setup",{headers,data:{storage:true,full:true}});await page.setViewportSize({width:1672,height:1100});await page.goto("/inventory");await expect.poll(()=>page.locator(".inv-item img").evaluateAll((imgs:HTMLImageElement[])=>imgs.every(i=>i.complete&&i.naturalWidth>0))).toBe(true);await capture(page,"inventory-desktop");
 await page.getByRole("navigation",{name:"Inventory categories"}).getByRole("button",{name:/Blueprints/}).click();await expect(page.locator(".inv-items .inv-item")).toHaveCount(2);await page.getByRole("button",{name:"List view",exact:true}).click();await expect(page.locator(".inv-items")).toHaveClass(/as-list/);await page.getByRole("button",{name:"Grid view",exact:true}).click();
 await page.getByRole("navigation",{name:"Inventory categories"}).getByRole("button",{name:/All items/}).click();await page.getByLabel("Search inventory").fill("Pickaxe");await expect(page.locator(".inv-items .inv-item")).toHaveCount(1);await page.getByRole("button",{name:"Equip pickaxe",exact:true}).click();await page.getByRole("button",{name:"Confirm equipment"}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.locator(".inv-equipped")).toContainText("Equipped pickaxe");await page.getByLabel("Search inventory").fill("");
 for(const width of [1920,1448,1366,1200,1100,1024,850,768,580,390,360]){await page.setViewportSize({width,height:1100});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"Inventory overflow at "+width).toBe(true);}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await capture(page,"inventory-mobile");await page.getByLabel("Search inventory").fill("Iron ore");await page.locator(".inv-item").click();await capture(page,"inventory-mobile-detail");await page.getByRole("button",{name:"Store",exact:true}).click();await capture(page,"inventory-mobile-storage");expect(await page.getByRole("dialog").evaluate(el=>el.getBoundingClientRect().width)).toBeLessThan(390);
});
test("Owner can configure storage and existing item categories",async({page,request})=>{
 await page.goto("/owner?section=inventory");await expect(page.locator(".inv-owner")).toBeVisible();const rules=page.locator(".inv-owner form").filter({has:page.getByLabel("Capacity per building")});await rules.getByLabel("Capacity per building").fill("750");await rules.getByLabel("Audit reason").fill("Adjust warehouse capacity");await rules.getByRole("button",{name:"Save storage rules"}).click();await expect(page.getByRole("status")).toContainText("Inventory rules saved");await page.reload();await expect(page.getByLabel("Capacity per building")).toHaveValue("750");
 await request.post("http://127.0.0.1:54329/__inventory_setup",{headers,data:{player:true}});await page.goto("/owner?section=inventory");await expect(page.getByRole("heading",{name:"Owner access required"})).toBeVisible();
});
