import {test,expect} from "@playwright/test";
import {cookie,token} from "../fixtures/identity.mjs";
const headers={Authorization:"Bearer "+token};
test.beforeEach(async({context,request})=>{test.skip(process.env.GAME_TEST_FIXTURE!=="1","Isolated game fixture");await request.post("http://127.0.0.1:54329/__reset_world",{headers});await context.addCookies([{name:"sb-127-auth-token",value:cookie,domain:"localhost",path:"/",sameSite:"Lax"}]);});
test("price history paginates completed trades and resets when item changes",async({page})=>{
 await page.goto("/market?view=history&good=whiskey");await expect(page.locator(".history-table tbody tr")).toHaveCount(10);await expect(page.locator(".history-stats")).toContainText("$100.00");await expect(page.locator(".history-stats")).toContainText("24");
 await page.getByRole("navigation",{name:"Price history pages"}).getByRole("button",{name:"Next"}).click();await expect(page.locator(".history-table tbody tr")).toHaveCount(2);
 await page.getByLabel("History item").selectOption("silk");await expect(page.getByText("No completed trades recorded.")).toBeVisible();await page.getByLabel("History item").selectOption("whiskey");await expect(page.locator(".history-table tbody tr")).toHaveCount(10);
 await page.screenshot({path:"test-results/market-history-desktop.png",fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:"test-results/market-history-mobile.png",fullPage:true});
});
test("players save independent market alert preferences across reloads",async({page})=>{
 await page.goto("/telegrams");await page.getByText("Alert preferences",{exact:true}).click();await expect(page.getByLabel("Items bought",{exact:true})).toBeChecked();await page.getByLabel("Items bought",{exact:true}).uncheck();await page.getByRole("button",{name:"Save alert preferences"}).click();await expect(page.getByText("Alert preferences saved.",{exact:true})).toBeVisible();await page.reload();await page.getByText("Alert preferences",{exact:true}).click();await expect(page.getByLabel("Items bought",{exact:true})).not.toBeChecked();await expect(page.getByLabel("Items sold",{exact:true})).toBeChecked();
 await page.getByLabel("Items sold",{exact:true}).uncheck();await page.getByRole("button",{name:"Save alert preferences"}).click();await expect(page.getByText("Alert preferences saved.",{exact:true})).toBeVisible();await page.screenshot({path:"test-results/telegram-preferences.png",fullPage:true});
});
test("warehouse overview shows capacity, stock, matching requests and property links",async({page,request})=>{
 await request.post("http://127.0.0.1:54329/__inventory_setup",{headers,data:{storage:true}});await request.post("http://127.0.0.1:54329/__buy_orders_setup",{headers,data:{count:12}});await page.goto("/warehouses");await expect(page.getByRole("heading",{name:"Warehouse overview"})).toBeVisible();await expect(page.locator(".warehouse-card")).toHaveCount(2);await expect(page.locator(".warehouse-totals")).toContainText("2,200");await expect(page.locator(".warehouse-order-list article")).toHaveCount(10);await page.getByRole("navigation",{name:"Matching buy orders pages"}).getByRole("button",{name:"Next"}).click();await expect(page.locator(".warehouse-order-list article")).toHaveCount(2);await page.getByText("View contents (0 item types)").first().click();await expect(page.getByText("No items stored here.").first()).toBeVisible();
 await page.screenshot({path:"test-results/warehouse-overview-desktop.png",fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:"test-results/warehouse-overview-mobile.png",fullPage:true});await page.getByRole("link",{name:"Manage contents"}).first().click();await expect(page).toHaveURL(/inventory\?building=/);await expect(page.locator(".inv-scope-line")).toContainText("Property contents");
});
test("history and preferences handle failed reads without showing false defaults",async({page})=>{
 await page.route("**/rest/v1/rpc/market_price_history",route=>route.abort());await page.goto("/market?view=history");await expect(page.getByRole("alert").filter({hasText:"Price history could not load"})).toBeVisible();await page.unroute("**/rest/v1/rpc/market_price_history");await page.locator(".price-history").getByRole("button",{name:"Try again"}).click();await expect(page.locator(".history-table tbody tr")).toHaveCount(10);
 await page.route("**/rest/v1/rpc/telegram_preferences",route=>route.abort());await page.goto("/telegrams");await page.getByText("Alert preferences",{exact:true}).click();await expect(page.locator(".tg-preferences").getByRole("alert")).toBeVisible();await expect(page.getByRole("button",{name:"Save alert preferences"})).toHaveCount(0);await page.unroute("**/rest/v1/rpc/telegram_preferences");await page.locator(".tg-preferences").getByRole("button",{name:"Try again"}).click();await expect(page.getByLabel("Items bought",{exact:true})).toBeChecked();
});
