import {test,expect,type APIRequestContext,type Page} from "@playwright/test";
import {PerspectiveCamera,Vector3,MathUtils} from "three";
import {cookie,token} from "../fixtures/identity.mjs";
import {rangeTarget} from "../../lib/range";
import {rangeWorldPoint,rangePlane} from "../../lib/range-3d";
const headers={Authorization:"Bearer "+token},base="http://127.0.0.1:54329";
const rpc=async(r:APIRequestContext,fn:string,data={})=>(await r.post(base+"/rest/v1/rpc/"+fn,{headers,data})).json();
async function equip(r:APIRequestContext,rifle=true){const good=rifle?"m4-carbine":"homemade-pistol",ammo=rifle?"556x45mm-ammo":"homemade-bullets";await r.post(base+"/__crafting_setup",{headers,data:{grant:{[good]:1,[ammo]:40}}});const d=await rpc(r,"range_state");for(const [id,slot,n] of [[good,rifle?"primary":"secondary",1],[ammo,"ammo",40]])await rpc(r,"inventory_action",{p_action:"equip",p_payload:{season_id:d.season.id,request_id:crypto.randomUUID(),item_key:"good:"+id,equipment_slot:slot,quantity:n}});}
async function start(page:Page){await page.goto("/shooting-range");await page.getByRole("button",{name:"3D indoor range",exact:true}).click();await page.locator(".range-scene").scrollIntoViewIfNeeded();await expect(page.locator(".range-3d-canvas canvas")).toHaveAttribute("data-weapon",/m4-carbine|homemade-pistol/);await page.getByRole("button",{name:/Start session/}).click();await expect(page.locator(".range-action-state")).toHaveText("Ready to fire");}
async function hit(page:Page,r:APIRequestContext,lane=1){await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));const b=(await page.locator(".range-3d-lane").boundingBox())!,d=await rpc(r,"range_state"),s=d.session,e=Date.now()-Date.parse(s.started_at),round=Math.floor(e/(s.config.round_seconds*1000)),t=rangeTarget(s.seed,round,lane,e,s.config),w=rangeWorldPoint(t.x,t.y);const camera=new PerspectiveCamera(MathUtils.radToDeg(2*Math.atan(Math.max(4.2,4.8/(b.width/b.height))/12)),b.width/b.height,.05,60);camera.position.y=rangePlane.centreY;camera.updateMatrixWorld();const p=new Vector3(w.x,w.y,w.z).project(camera);await page.mouse.click(b.x+(p.x+1)/2*b.width,b.y+(1-p.y)/2*b.height);}
test.beforeEach(async({context,request})=>{test.skip(process.env.GAME_TEST_FIXTURE!=="1","Isolated range fixture");await request.post(base+"/__reset_world",{headers});await rpc(request,"range_manage",{p_action:"settings",p_payload:{settings:{range_move_amplitude:0,range_move_vertical:0},reason:"Deterministic 3D projection and accuracy checks"}});await context.addCookies([{name:"sb-127-auth-token",value:cookie,domain:"localhost",path:"/"}]);});
test("indoor 3D M4 records ray-aimed accuracy, ammo, automatic fire and timed reload",async({page,request})=>{
 await equip(request);await page.setViewportSize({width:1536,height:1100});await start(page);await hit(page,request);await expect(page.locator(".range-magazine-counter b")).toHaveText("29 / 30");const hitState=await rpc(request,"range_state");expect(hitState.session.last_shot.hit).toBe(true);expect(hitState.session.last_shot.accuracy_percent).toBeGreaterThan(80);await expect(page.locator(".range-3d-canvas canvas")).toHaveAttribute("data-shot",hitState.session.last_shot.id);
 await page.screenshot({path:"test-results/range-3d-m4.jpg",type:"jpeg",quality:85});await expect(page.locator(".range-action-state")).toHaveText("Ready to fire");const b=(await page.locator(".range-3d-lane").boundingBox())!;await page.mouse.move(b.x+15,b.y+b.height-15);await page.mouse.down();await expect.poll(async()=>(await rpc(request,"range_state")).session.shots).toBeGreaterThanOrEqual(3);await page.mouse.up();await expect(page.locator(".range-action-state")).toHaveText("Ready to fire");const stopped=(await rpc(request,"range_state")).session.shots;await page.waitForTimeout(650);expect((await rpc(request,"range_state")).session.shots).toBe(stopped);
 await page.getByRole("button",{name:"Reload weapon",exact:true}).click();await expect(page.locator(".range-3d-canvas canvas")).toHaveAttribute("data-reloading","true");await page.waitForTimeout(850);await page.screenshot({path:"test-results/range-3d-reload.jpg",type:"jpeg",quality:85});await expect(page.locator(".range-magazine-counter b")).toHaveText("30 / 30");await expect(page.locator(".range-3d-canvas canvas")).toHaveAttribute("data-reloading","false");const d=await rpc(request,"range_state");expect(d.ammo.quantity).toBe(40-stopped);expect(d.weapons[0].condition).toBe(250-stopped);
 await page.getByRole("button",{name:"Classic targets",exact:true}).click();await expect(page.locator(".range-targets")).toBeVisible();expect((await rpc(request,"range_state")).session.id).toBe(d.session.id);await page.getByRole("button",{name:"3D indoor range",exact:true}).click();await expect(page.locator(".range-3d-canvas canvas")).toHaveAttribute("data-weapon","m4-carbine");
});
test("pistol, phone aim and keyboard reload retain accuracy without overflow",async({page,request})=>{
 await equip(request,false);await page.setViewportSize({width:390,height:844});await start(page);await hit(page,request);await expect(page.locator(".range-magazine-counter b")).toHaveText("9 / 10");expect((await rpc(request,"range_state")).session.last_shot.accuracy_percent).toBeGreaterThan(80);await page.locator(".range-lane").focus();await page.keyboard.press("r");await expect(page.locator(".range-3d-canvas canvas")).toHaveAttribute("data-reloading","true");await expect(page.locator(".range-magazine-counter b")).toHaveText("10 / 10");await page.screenshot({path:"test-results/range-3d-phone.jpg",type:"jpeg",quality:85});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test("lost WebGL falls back safely and an uncertain 3D shot is retried once",async({page,request})=>{
 await equip(request);await start(page);let first="";await page.route("**/rest/v1/rpc/range_action",async route=>{if(!first){first=route.request().postData()!;await route.fetch();await route.abort();}else{expect(route.request().postData()).toBe(first);await route.continue();}});await hit(page,request);await expect(page.getByRole("button",{name:"Retry safely"})).toBeVisible();await expect(page.locator(".range-lane")).toHaveAttribute("aria-disabled","true");await page.getByRole("button",{name:"Retry safely"}).click();await expect(page.locator(".range-magazine-counter b")).toHaveText("29 / 30");expect((await rpc(request,"range_state")).session.shots).toBe(1);await page.locator(".range-3d-canvas canvas").evaluate(canvas=>canvas.dispatchEvent(new Event("webglcontextlost",{cancelable:true})));await expect(page.getByText("3D rendering is unavailable on this device.",{exact:false})).toBeVisible();await expect(page.locator(".range-targets")).toBeVisible();expect((await rpc(request,"range_state")).session.shots).toBe(1);
});
