import {test,expect,type Page} from "@playwright/test";
import {cookie,token} from "../fixtures/identity.mjs";
const headers={Authorization:"Bearer "+token};
async function capture(page:Page,name:string){const shot=await page.screenshot({path:"test-results/"+name+".jpg",type:"jpeg",quality:70});if(process.env.VISUAL_REVIEW==="1"){const b=shot.toString("base64");for(let n=0;n<b.length;n+=12000)console.log("VISUAL_REVIEW_"+name+"_"+Math.floor(n/12000)+":"+b.slice(n,n+12000));}}
test.beforeEach(async({context,request})=>{test.skip(process.env.GAME_TEST_FIXTURE!=="1","Isolated fixture");await request.post("http://127.0.0.1:54329/__reset_world",{headers});await context.addCookies([{name:"sb-127-auth-token",value:cookie,domain:"localhost",path:"/",sameSite:"Lax"}]);});
test("buy a refinery, stock coal, change fees and refine your own ore",async({page})=>{
 await page.setViewportSize({width:1500,height:1100});await page.goto("/dashboard");await page.getByRole("link",{name:"Refineries",exact:true}).click();await expect(page.locator(".command-city")).toBeVisible();
 await page.getByRole("button",{name:"Buy refinery"}).click();await page.getByRole("button",{name:"Confirm purchase"}).click();await expect(page.locator(".ref-heading")).toContainText("You");
 await page.getByRole("button",{name:"Manage refinery",exact:true}).click();await page.getByLabel("Fuel quantity").fill("50");await page.getByRole("button",{name:"Load fuel"}).click();await expect(page.getByRole("status")).toContainText("Fuel moved");
 await page.getByLabel("Charge customers").selectOption("output");await page.getByLabel("Refined output share (%)").fill("15");await page.getByRole("button",{name:"Save refining terms"}).click();await expect(page.getByRole("status")).toContainText("saved");
 await capture(page,"refinery-owner");await page.getByRole("button",{name:"Refining service"}).click();await page.getByRole("button",{name:"Review refining order"}).click();await expect(page.getByRole("dialog")).toContainText("$0");await page.getByRole("button",{name:"Confirm refining"}).click();await expect(page.getByRole("status")).toContainText("Ore refined");
});
test("customer cash and output fees, empty fuel and mobile layout",async({page,request})=>{
 await request.post("http://127.0.0.1:54329/__refinery_setup",{headers,data:{customer:true}});await page.setViewportSize({width:1500,height:1100});await page.goto("/refineries");await expect(page.locator(".ref-intel")).toBeVisible();await expect(page.getByRole("heading",{name:"Refineries",exact:true})).toBeVisible();
 for(const width of [1920,1448,1024,768,390,1500]){await page.setViewportSize({width,height:1100});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"Refinery overflow at "+width).toBe(true);}
 await capture(page,"refinery-desktop");await page.getByLabel("Batches",{exact:true}).fill("2");await page.getByRole("button",{name:"Review refining order"}).click();await expect(page.getByRole("dialog")).toContainText("$40");await page.getByRole("button",{name:"Confirm refining"}).click();await expect(page.getByRole("status")).toContainText("Ore refined");
 await request.post("http://127.0.0.1:54329/__refinery_setup",{headers,data:{mode:"output"}});await page.reload();await page.getByRole("button",{name:"Review refining order"}).click();await expect(page.getByRole("dialog")).toContainText("9 Iron ingots");await page.getByRole("button",{name:"Confirm refining"}).click();
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await capture(page,"refinery-mobile");await page.locator(".ref-service").scrollIntoViewIfNeeded();await capture(page,"refinery-mobile-workbench");expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole("button",{name:"Your receipts"}).click();await expect(page.locator(".ref-history article")).toHaveCount(2);
 await request.post("http://127.0.0.1:54329/__refinery_setup",{headers,data:{empty:true}});await page.reload();await expect(page.getByRole("button",{name:"Review refining order"})).toBeDisabled();await expect(page.getByRole("button",{name:"Manage refinery",exact:true})).toHaveCount(0);
});
test("a changed quote is rejected and a lost reply retries without duplicate output",async({page,request})=>{
 await request.post("http://127.0.0.1:54329/__refinery_setup",{headers,data:{customer:true}});await page.goto("/refineries");await page.getByRole("button",{name:"Review refining order"}).click();await request.post("http://127.0.0.1:54329/__refinery_setup",{headers,data:{reprice:true}});await page.getByRole("button",{name:"Confirm refining"}).click();await expect(page.getByRole("dialog")).toContainText("fees changed");await page.getByRole("button",{name:"Close order"}).click();await page.reload();
 let original="",calls=0;await page.route("**/rest/v1/rpc/refinery_action",async route=>{calls++;if(calls===1){original=route.request().postData()??"";await route.fetch();await route.abort();}else{expect(route.request().postData()).toBe(original);await route.continue();}});
 await page.getByRole("button",{name:"Review refining order"}).click();await page.getByRole("button",{name:"Confirm refining"}).click();await page.getByRole("button",{name:"Retry safely"}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await page.getByRole("button",{name:"Your receipts"}).click();await expect(page.locator(".ref-history article")).toHaveCount(1);
});
test("Owner edits recipe fuel and yield with audited reason; players have no access",async({page,request})=>{
 await page.goto("/owner?section=refineries");const form=page.locator(".ref-recipe-form").filter({has:page.getByRole("heading",{name:"Iron refining",exact:true})});
 await form.getByLabel("Fuel per batch",{exact:true}).fill("6");await form.getByLabel("Reason for this change").fill("Adjust coal consumption");await form.getByRole("button",{name:"Save recipe"}).click();await expect(page.getByRole("status")).toContainText("recipe saved");await page.reload();await expect(form.getByLabel("Fuel per batch",{exact:true})).toHaveValue("6");
 await page.getByRole("link",{name:"Fee limits & economy settings"}).click();await expect(page.locator(".ref-owner")).toHaveCount(0);
 await request.post("http://127.0.0.1:54329/__refinery_setup",{headers,data:{player:true}});await page.goto("/owner?section=refineries");await expect(page.locator(".ref-owner")).toContainText("Owner permission required");
});
