import {test,expect,type Page} from '@playwright/test';
import {cookie,token} from '../fixtures/identity.mjs';
const base='http://127.0.0.1:54329',headers={Authorization:'Bearer '+token};
async function capture(page:Page,name:string){const b=(await page.screenshot({type:'jpeg',quality:72,path:'test-results/'+name+'.jpg'})).toString('base64');if(process.env.VISUAL_REVIEW==='1')for(let i=0;i<b.length;i+=12000)console.log('VISUAL_REVIEW_'+name+'_'+Math.floor(i/12000)+':'+b.slice(i,i+12000));}
test.beforeEach(async({context,request})=>{test.skip(process.env.GAME_TEST_FIXTURE!=='1','Isolated fixtures');await request.post(base+'/__reset_world',{headers});await context.addCookies([{name:'sb-127-auth-token',value:cookie,domain:'localhost',path:'/'}]);});
test.afterEach(async({request})=>{if(process.env.GAME_TEST_FIXTURE==='1')await request.post(base+'/__reset_world',{headers});});
test('Skills opens from the top navigation and shows saved progress, maximum level and milestones',async({page,request})=>{
 await request.post(base+'/__skills_setup',{headers,data:{awards:{crafting:2500,sharpshooting:10000,lockpicking:25}}});await page.setViewportSize({width:1536,height:1120});
 await page.goto('/dashboard');await expect(page.locator('.command-quick').getByRole('link',{name:'Skills',exact:true})).toHaveCount(0);await page.getByRole('navigation',{name:'Game navigation'}).getByRole('link',{name:'Skills',exact:true}).click();await expect(page).toHaveURL(/\/skills/);await expect(page.getByRole('heading',{name:'Skills',exact:true})).toBeVisible();
 await expect(page.getByRole('tab')).toHaveCount(4);await expect(page.locator('.skill-card.crafting .skill-card-title b')).toHaveText('10');await expect(page.locator('.skill-card.sharpshooting .skill-card-title b')).toHaveText('20');await expect(page.locator('.skill-card.sharpshooting')).toContainText('MAX LEVEL');
 await expect(page.getByRole('progressbar',{name:'Sharpshooting level progress'})).toHaveAttribute('aria-valuenow','100');await expect(page.locator('.skill-milestones button')).toHaveCount(20);
 await expect.poll(()=>page.locator('.skill-card img').evaluateAll((images:HTMLImageElement[])=>images.every(i=>i.complete&&i.naturalWidth>0))).toBe(true);await capture(page,'skills-desktop');
 await page.getByRole('tab',{name:/Lockpicking/}).click();await expect(page.getByRole('heading',{name:'Lockpicking progression'})).toBeVisible();await page.getByRole('button',{name:'Level 20: 10,000 total XP'}).click();await expect(page.locator('.skill-target-summary')).toContainText('9,975 XP remaining');await expect(page.getByRole('link',{name:'Visit Blackwater Island'})).toHaveAttribute('href','/districts/blackwater-island');await page.reload();await expect(page.getByRole('heading',{name:'Lockpicking progression'})).toBeVisible();await expect(page.locator('.skills-history li')).toHaveCount(3);
});
test('Owner adjusts the level-20 target and every level adapts without changing earned XP',async({page,request})=>{
 await request.post(base+'/__skills_setup',{headers,data:{awards:{crafting:2500}}});await page.goto('/owner?section=skills');await page.getByLabel('Crafting XP to level 20',{exact:true}).fill('2500');await page.getByLabel('Crafting XP per minute',{exact:true}).fill('15');await page.getByLabel('Crafting audit reason').fill('Make the seasonal crafting curve shorter');await expect(page.locator('.skill-curve-preview').first()).toContainText('2,500 XP');await page.getByRole('button',{name:'Save Crafting',exact:true}).click();await expect(page.locator('.skills-owner [role=status]')).toContainText('progression saved');
 await page.goto('/skills');await expect(page.locator('.skill-card.crafting .skill-card-title b')).toHaveText('20');await expect(page.locator('.skill-card.crafting')).toContainText('2,500 XP earned');
 await page.goto('/owner?section=skills');await page.getByLabel('Crafting XP to level 20',{exact:true}).fill('10000');await page.getByLabel('Crafting audit reason').fill('Restore the longer progression target');await page.getByRole('button',{name:'Save Crafting',exact:true}).click();await expect(page.locator('.skills-owner [role=status]')).toContainText('progression saved');
 await page.goto('/skills');await expect(page.locator('.skill-card.crafting .skill-card-title b')).toHaveText('10');await expect(page.locator('.skill-card.crafting')).toContainText('2,500 XP earned');
});
test('An interrupted Owner save retries the same update, and stale saves are rejected',async({page,request})=>{
 await page.goto('/owner?section=skills');await page.getByLabel('Lockpicking XP to level 20',{exact:true}).fill('12000');await page.getByLabel('Lockpicking audit reason').fill('Adjust the lockpicking progression curve');let first='';
 await page.route('**/rest/v1/rpc/skills_manage',async route=>{if(!first){first=route.request().postData()!;await route.fetch();await route.abort();}else{expect(route.request().postData()).toBe(first);await route.continue();}});
 await page.getByRole('button',{name:'Save Lockpicking',exact:true}).click();await expect(page.getByRole('button',{name:'Retry skill save safely'})).toBeVisible();await page.getByRole('button',{name:'Retry skill save safely'}).click();await expect(page.locator('.skills-owner [role=status]')).toContainText('progression saved');
 const d=await(await request.post(base+'/rest/v1/rpc/skills_state',{headers,data:{}})).json();expect(d.skills.find((s:any)=>s.id==='lockpicking').version).toBe(2);expect(d.skills.find((s:any)=>s.id==='lockpicking').xp_to_20).toBe(12000);
 await page.unroute('**/rest/v1/rpc/skills_manage');const current=JSON.parse(first).p_payload;await request.post(base+'/rest/v1/rpc/skills_manage',{headers,data:{p_payload:{...current,version:2,request_id:crypto.randomUUID(),xp_to_20:15000}}});await page.getByLabel('Lockpicking audit reason').fill('Try saving an outdated editor');await page.getByRole('button',{name:'Save Lockpicking',exact:true}).click();await expect(page.locator('.skills-owner [role=status]')).toContainText('settings changed');
});
test('Skills fits mobile, remains readable, refreshes changes and starts fresh next season',async({page,request})=>{
 await request.post(base+'/__skills_setup',{headers,data:{player:true,awards:{crafting:100}}});await page.goto('/skills');await expect(page.getByRole('link',{name:/Owner controls/})).toHaveCount(0);
 for(const width of [360,390,768,1024,1320]){await page.setViewportSize({width,height:940});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.setViewportSize({width:390,height:844});await capture(page,'skills-mobile');await page.getByRole('tab',{name:/Sharpshooting/}).click();await page.getByRole('button',{name:'Level 10: 2,248 total XP'}).click();await expect(page.locator('.skill-target-summary')).toContainText('Level 10');
 await request.post(base+'/__skills_setup',{headers,data:{awards:{sharpshooting:150}}});await page.getByRole('button',{name:'Refresh skills'}).click();await expect(page.locator('.skill-card.sharpshooting')).toContainText('150 XP earned');
 await request.post(base+'/__skills_setup',{headers,data:{season:'77777777-5555-4555-8555-555555555555'}});await page.getByRole('button',{name:'Refresh skills'}).click();await expect(page.locator('.skills-season')).toContainText('Next Season');await expect(page.locator('.skill-card-title b')).toHaveText(['1','1','1','1']);await expect(page.locator('.skills-history li')).toHaveCount(0);
});
