import {test,expect} from "@playwright/test";
import {cookie} from "../fixtures/identity.mjs";
test("Owner office and private Support tickets work on mobile",async({page,context})=>{
 test.skip(process.env.GAME_TEST_FIXTURE!=="1","Requires isolated fixture");
 await context.addCookies([{name:"sb-127-auth-token",value:cookie,domain:"localhost",path:"/"}]);
 await page.setViewportSize({width:390,height:844});await page.goto("/staff");
 await expect(page).toHaveURL(/\/owner$/);await expect(page.getByRole("heading",{name:"Owner panel",exact:true})).toBeVisible();
 const ownerNav=page.getByRole("navigation",{name:"Owner navigation"});
 await ownerNav.getByRole("button",{name:"Economy & production"}).click();
 const settings=page.locator("form").filter({has:page.getByRole("heading",{name:"market fee percent",exact:true})});
 await settings.getByLabel("Value",{exact:true}).fill("7");await settings.getByLabel("Reason",{exact:true}).fill("Browser settings test");await settings.getByRole("button").click();
 await expect(page.getByRole("status")).toContainText("Saved.");
 await ownerNav.getByRole("button",{name:"Control room"}).click();await ownerNav.getByRole("button",{name:"Economy & production"}).click();
 await expect(settings.getByLabel("Value",{exact:true})).toHaveValue("7");
 await page.goto("/community");await expect(page).toHaveURL(/\/support$/);
 await expect(page.locator(".support-page").getByLabel("Message the city")).toHaveCount(0);
 await page.getByLabel("Subject",{exact:true}).fill("Test support request");await page.getByLabel("Details",{exact:true}).fill("Please review this support request.");await page.getByRole("button",{name:"Create ticket"}).click();
 await expect(page.getByRole("heading",{name:"Test support request",exact:true})).toBeVisible();
 await page.goto("/owner?section=tickets");
 const ticket=page.locator("article").filter({has:page.getByRole("heading",{name:"Test support request",exact:true})});
 await ticket.getByLabel("Response to player").fill("The team has reviewed your request.");await ticket.getByLabel("Status",{exact:true}).selectOption("resolved");
 const response=ticket.locator("form").filter({has:page.getByRole("heading",{name:"Case response",exact:true})});
 await response.getByLabel("Reason",{exact:true}).fill("Resolved browser test");await response.getByRole("button").click();
 await page.goto("/support");await expect(page.getByText("The team has reviewed your request.",{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
