import Link from "next/link";
import {Artwork} from "@/components/artwork";
import {EconomyPreview} from "@/components/economy-preview";
import {GameIcon} from "@/components/game-icon";
export default function Home(){return <div className="bw-landing">
 <section className="bw-hero"><Artwork name="harbor" priority/><div className="hero-vignette"/><div className="bw-hero-content"><p className="eyebrow"><span className="gold-line"/> A PLAYER-DRIVEN CRIME ECONOMY</p><p className="bw-location">WELCOME TO BLACKWATER</p><h1>Every fortune<br/>has a <em>dark side.</em></h1><p className="bw-hero-lede">A city built on ambition. An economy built by players.<br className="desktop-break"/> Produce the goods. Set your price. Make your name.</p><div className="bw-hero-actions"><Link className="button" href="/signup">Enter Blackwater <GameIcon name="arrow" size={18}/></Link><Link className="button ghost" href="/login">Log in</Link></div><p className="bw-entry-note">PLAY IN YOUR BROWSER <span>◆</span> NO DOWNLOAD REQUIRED</p></div><div className="bw-hero-bottom"><a href="#economy"><span className="scroll-line"/> Discover the economy</a><span>THE WATERFRONT <i>01 / BLACKWATER</i></span></div></section>
 <div className="bw-trade-strip" aria-label="The Blackwater economy"><span>THE CITY RUNS ON DEALS.</span><span>WHISKEY <i>◆</i> SILK <i>◆</i> STEEL</span><span>MAKE YOURS COUNT.</span></div>
 <section id="economy" className="bw-economy bw-section"><div className="bw-economy-copy"><p className="eyebrow">01 / THE PLAYER-DRIVEN ECONOMY</p><h2>Every deal has<br/><em>someone behind it.</em></h2><p className="section-lede">Your stock becomes their opportunity. Their demand becomes your next move.</p><p>Businesses produce the goods. Players decide what to sell, what to buy, and what a deal is worth. Build your own supply, trade with other players, and put your earnings back to work.</p><div className="economy-principles"><div><span>01</span><p><strong>Own the supply.</strong><small>Build businesses that produce tradable goods.</small></p></div><div><span>02</span><p><strong>Name your price.</strong><small>Create offers on a market run by real players.</small></p></div><div><span>03</span><p><strong>Grow your influence.</strong><small>Reinvest in production. Climb the season rankings.</small></p></div></div></div><div className="bw-exchange-stage"><Artwork name="exchange"/><EconomyPreview/></div></section>
 <section id="city" className="bw-industries bw-section"><div className="bw-section-heading"><div><p className="eyebrow">02 / THE CITY IS YOUR BUSINESS</p><h2>Power starts<br/>with <em>production.</em></h2></div><p>From a quiet back room to the heat of the foundry.<br/>Choose what you produce. Decide how you trade.</p></div><div className="bw-industry-grid">{[
 {art:"distillery" as const,n:"01",district:"THE DOCKS",title:"Liquid ambition.",name:"Backroom distillery",body:"Turn copper, oak, and patience into whiskey crates. Find the buyer who sees their value."},
 {art:"textile" as const,n:"02",district:"OLD TOWN",title:"A finer kind of power.",name:"Textile workshop",body:"Keep the looms turning. Bring silk to a market where every player names their own price."},
 {art:"foundry" as const,n:"03",district:"INDUSTRIAL QUARTER",title:"An iron resolve.",name:"Dockside foundry",body:"Build your steel supply. Turn the city's industrial heartbeat into your next opportunity."}
 ].map(g=><article className="bw-industry" key={g.art}><Artwork name={g.art} alt={g.name+" in Blackwater"}/><div className="industry-shade"/><span className="industry-number">{g.n}</span><div className="industry-copy"><p className="eyebrow">{g.district}</p><h3>{g.title}</h3><p>{g.body}</p><Link href="/signup">Build your {g.name.toLowerCase()} <GameIcon name="arrow" size={17}/></Link></div></article>)}</div></section>
 <section className="bw-season-story bw-section"><div className="season-insignia" aria-hidden="true"><span>BLACKWATER</span><strong>BW</strong><span>HALL OF FAME</span></div><div><p className="eyebrow">03 / YOUR NAME. IN THE RECORD BOOKS.</p><h2>Fortunes rise.<br/><em>Legacies remain.</em></h2><p>Compete across seasons. Build your fortune, climb the leaderboards, and earn your place among the city's names to remember. Archived rankings preserve the story after a season ends.</p><Link className="text-link" href="/signup">Start writing your story <GameIcon name="arrow" size={17}/></Link></div></section>
 <section id="how-to-play" className="bw-invitation"><Artwork name="exchange"/><div className="invitation-shade"/><div><p className="eyebrow">THERE'S A SEAT WAITING FOR YOU.</p><h2>The city doesn't<br/>hand out empires.</h2><p>Make your first move.</p><Link className="button" href="/signup">Create your account <GameIcon name="arrow" size={18}/></Link><span className="invitation-login">Already have a name here? <Link href="/login">Log in</Link></span></div></section>
 </div>;}
