"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {useCrafting} from "./use-crafting";
import {CommodityArtwork} from "./commodity-artwork";
import {GameIcon} from "./game-icon";
import {craftTime,type CraftState} from "@/lib/crafting";
import {kg,type Stock,type InventoryState} from "@/lib/inventory";
type Confirmation={action:string;payload:Record<string,unknown>;title:string;body:string};
function StockPanel({title,items,d,store}:{title:string;items:Stock[];d:InventoryState;store?:InventoryState["stores"][number]}){
 const [filter,setFilter]=useState("all"),[search,setSearch]=useState("");
 const rows=items.filter(x=>x.quantity>0).map(x=>({...x,good:d.goods.find(g=>g.id===x.good_id)})).filter(x=>x.good&&(filter==="all"||x.good.category===filter)&&x.good.name.toLowerCase().includes(search.toLowerCase()));
 return <aside className="cf-panel cf-stock"><header><GameIcon name={store?"property":"inventory"} size={24}/><h2>{title}</h2></header><p className="cf-stock-meter">{store?store.used.toLocaleString()+" / "+store.capacity.toLocaleString()+" storage units":kg(d.capacity.used_grams)+" / "+kg(d.capacity.weight_grams)+" · "+d.capacity.used_slots+" / "+d.capacity.slots+" slots"}</p>
 <div className="cf-stock-tools"><input aria-label={"Search "+title.toLowerCase()} placeholder="Find an item…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label={title+" category"} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All items</option><option value="materials">Materials</option><option value="blueprints">Blueprints</option><option value="weapons">Weapons</option><option value="ammunition">Ammo</option></select></div>
 <div className="cf-stock-grid">{rows.map(x=><div key={x.good_id}><CommodityArtwork goodId={x.good_id} size={92}/><strong>{x.quantity.toLocaleString()}</strong><span>{x.good!.name}</span></div>)}</div>{!rows.length&&<p className="cf-muted">No matching items here.</p>}<Link className="cf-text-link" href={"/inventory"+(store?"?building="+store.id:"")}>{store?"Manage property storage":"Open full inventory"} →</Link></aside>;
}
export function CraftingWorkspace({initial,initialRecipe}:{initial:CraftState;initialRecipe?:string}){
 const h=useCrafting(initial),d=h.data,bag=d.inventory;
 const [building,setBuilding]=useState(initial.building_id??initial.stations[0]?.building_id??""),[recipeId,setRecipe]=useState(initialRecipe??initial.recipes[0]?.id??""),[source,setSource]=useState(initial.building_id||initial.stations.length?"both":"carried"),[batches,setBatches]=useState("1"),[destination,setDestination]=useState("carried"),[confirmation,setConfirmation]=useState<Confirmation|null>(null),[tick,setTick]=useState(0);
 const dialog=useRef<HTMLDialogElement>(null),received=useRef(Date.now());
 useEffect(()=>{received.current=Date.now();},[d.server_time]);
 useEffect(()=>{const timer=setInterval(()=>setTick(x=>x+1),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(confirmation)dialog.current?.showModal();},[confirmation]);
 const now=Date.parse(bag.season.status==="locked"&&bag.season.locked_at?bag.season.locked_at:d.server_time)+(bag.season.status==="open"?Date.now()-received.current:0)+tick*0;
 const station=d.stations.find(s=>s.building_id===building),store=bag.stores.find(s=>s.id===building),recipe=d.recipes.find(r=>r.id===recipeId),known=!!recipe&&d.learned.includes(recipe.id),n=Number(batches);
 const amount=(g:string,mode=source)=>(mode!=="storage"?bag.carried.find(x=>x.good_id===g)?.quantity??0:0)+(mode!=="carried"?store?.contents.find(x=>x.good_id===g)?.quantity??0:0);
 const rows=recipe?Object.entries(recipe.materials).map(([good,units])=>({good,name:bag.goods.find(g=>g.id===good)?.name??good,need:units*n,have:amount(good)})):[];
 const available=Number.isSafeInteger(n)&&n>0&&n<=d.settings.max_batches&&rows.every(x=>x.have>=x.need);
 const stationJobs=d.jobs.filter(j=>j.station_id===station?.id),running=stationJobs.find(j=>Date.parse(j.starts_at)<=now&&Date.parse(j.ready_at)>now);
 const canStart=recipe?.enabled&&known&&station?.ready&&available&&bag.playable&&stationJobs.length<d.settings.queue_limit;
 const ask=(action:string,payload:Record<string,unknown>,title:string,body:string)=>{h.clear();setConfirmation({action,payload:{...payload,season_id:bag.season.id},title,body});};
 const changeBuilding=(value:string)=>{setBuilding(value);if(!value)setSource("carried");const url=new URL(location.href);if(value)url.searchParams.set("building",value);else url.searchParams.delete("building");history.replaceState(null,"",url);};
 return <div className="cf-page" data-feature="crafting-stations"><div className="cf-topline"><Link href={station?"/districts/"+station.slug+"?view=mine":"/districts"}>← {station?station.district:"City districts"}</Link><span>/ {station?station.code+" / ":""}CRAFTING STATION</span>{d.can_manage&&<Link href="/owner?section=crafting">Owner recipe controls ↗</Link>}</div>
 <header className="cf-masthead"><div><p className="cf-eyebrow">BLACKWATER / WORKSHOP</p><h1>Crafting station</h1><p>Learn the trade. Supply the city.</p></div><label>Your workstation<select aria-label="Your workstation" value={station?.building_id??""} disabled={h.busy} onChange={e=>changeBuilding(e.target.value)}><option value="">Blueprint library</option>{d.stations.map(s=><option value={s.building_id} key={s.id}>{s.code} · {s.name} · {s.district}</option>)}</select></label></header>
 {!bag.playable&&<p className="cf-notice">Crafting is paused while this season is closed.</p>}
 {h.notice&&!confirmation&&<p className={"cf-notice "+(h.failed?"error":"")} role={h.failed?"alert":"status"}>{h.notice}</p>}
 <div className="cf-layout"><StockPanel title="Player inventory" items={bag.carried} d={bag}/>
 <section className="cf-bench cf-panel"><header><GameIcon name="tools" size={28}/><div><h2>{station?"Crafting table · "+station.code:"Blueprint library"}</h2><p className="cf-eyebrow">{station?station.name+" / "+station.district:"KNOWLEDGE BUILDS OPPORTUNITY"}</p></div><button className="cf-refresh" aria-label="Refresh crafting" disabled={h.busy} onClick={h.refresh}><GameIcon name="refresh" size={21}/></button></header>
 <nav className="cf-recipes" aria-label="Crafting recipes">{d.recipes.map(r=><button key={r.id} aria-pressed={recipe?.id===r.id} onClick={()=>{setRecipe(r.id);setBatches("1");}}><CommodityArtwork goodId={r.output_good_id} size={54}/><span>{r.name}<small>{d.learned.includes(r.id)?"Learned":"Blueprint required"}{!r.enabled?" · Paused":""}</small></span></button>)}</nav>
 {recipe?<><div className="cf-recipe-hero"><CommodityArtwork goodId={recipe.output_good_id} size={180}/><div><h3>{recipe.name}</h3><p>{recipe.description}</p><span className={"cf-tag "+(known?"learned":"")}>{known?"Recipe learned":"Not learned"}</span></div></div>
 <label className="cf-source">Use materials from<select aria-label="Material source" value={source} disabled={h.busy} onChange={e=>setSource(e.target.value)}><option value="carried">Carried inventory</option>{store&&<><option value="storage">This property only</option><option value="both">Property + carried inventory</option></>}</select></label>
 {!known?<section className="cf-learning"><CommodityArtwork goodId={recipe.blueprint_good_id} size={75}/><div><h3>Learn this blueprint</h3><p>Consumes one blueprint. The recipe stays learned for this season and works at any of your installed tables.</p><p>{amount(recipe.blueprint_good_id)} available in your selected source.</p><button className="cf-gold" disabled={h.busy||!bag.playable||!recipe.enabled||amount(recipe.blueprint_good_id)<1} onClick={()=>ask("learn",{recipe_id:recipe.id,version:recipe.version,building_id:building||null,source},"Learn "+recipe.name,"Consume one blueprint to learn this recipe for the current season?")}>Learn recipe <GameIcon name="blueprint" size={20}/></button></div></section>:<p className="cf-learned-note"><GameIcon name="blueprint" size={20}/>You know this recipe. Spare blueprints can still be traded.</p>}
 <div className="cf-section-heading"><h3>Required materials</h3><span>{rows.filter(x=>x.have>=x.need).length} / {rows.length}</span></div><div className="cf-materials">{rows.map(x=><div key={x.good} className={x.have>=x.need?"enough":"missing"}><CommodityArtwork goodId={x.good} size={90}/><span>{x.name}</span><strong>{x.have.toLocaleString()} / {Number.isFinite(x.need)?x.need.toLocaleString():"—"}</strong></div>)}</div>
 <div className="cf-output"><label>Batches<input aria-label="Crafting batches" type="number" min={1} max={d.settings.max_batches} value={batches} disabled={h.busy} onChange={e=>setBatches(e.target.value)}/></label><div><span><GameIcon name="clock" size={18}/>Craft time</span><strong>{craftTime(recipe.seconds*(n||1))}</strong></div><div><span>Output</span><strong>{Number.isFinite(n)?recipe.output_units*n:"—"} <small>{recipe.name}</small></strong></div></div>
 {!station?<p className="cf-muted">Install a crafting table in a garage or warehouse you own or lease, then open it from your property.</p>:!station.ready?<p className="cf-notice">This station is unavailable. Check the property’s condition, listing and district status.</p>:null}
 <button className="cf-gold cf-full" disabled={h.busy||!canStart} onClick={()=>ask("start",{recipe_id:recipe.id,version:recipe.version,batches:n,building_id:building,source},"Start crafting","Reserve the displayed materials for "+n+" batch"+(n===1?"":"es")+"? Finished items stay in the queue until you collect them.")}><GameIcon name="tools" size={21}/>Add to crafting queue</button>
 {running&&<section className="cf-progress"><div><span>{running.recipe_name}</span><strong>{craftTime((Date.parse(running.ready_at)-now)/1000)} left</strong></div><progress aria-label="Current crafting progress" max={100} value={Math.max(0,Math.min(100,(now-Date.parse(running.starts_at))/(Date.parse(running.ready_at)-Date.parse(running.starts_at))*100))}/></section>}
 </>:<p>No recipes are available yet.</p>}
 <section className="cf-queue"><div className="cf-section-heading"><h3>Crafting queue</h3><span>{stationJobs.length} / {d.settings.queue_limit} at this table</span></div><p className="cf-muted">Materials are reserved when queued. Finished jobs wait safely until collected. Cancelling returns materials to Inventory deliveries.</p><label>Collect finished items into<select aria-label="Crafted item destination" value={destination} onChange={e=>setDestination(e.target.value)}><option value="carried">Carried inventory</option><option value="storage">The job’s property storage</option></select></label>
 {d.jobs.map(j=>{const ready=Date.parse(j.ready_at)<=now,waiting=Date.parse(j.starts_at)>now;return <article key={j.id} className="cf-job"><CommodityArtwork goodId={j.output_good_id} size={64}/><div><strong>{j.recipe_name} × {j.output_units}</strong><span>{j.code} · {ready?"Ready to collect":waiting?"Queued · starts in "+craftTime((Date.parse(j.starts_at)-now)/1000):craftTime((Date.parse(j.ready_at)-now)/1000)+" remaining"}</span></div><div className="cf-job-actions"><button className="cf-outline" disabled={h.busy||!bag.playable||!ready} onClick={()=>ask("collect",{job_id:j.id,destination},"Collect finished items","Move this job’s finished items into "+(destination==="storage"?"its property storage":"your carried inventory")+"?")}>Collect</button><button className="cf-cancel" aria-label={"Cancel "+j.recipe_name+" job"} disabled={h.busy||!bag.playable} onClick={()=>ask("cancel",{job_id:j.id},"Cancel crafting job","Cancel this job and return all reserved materials to Inventory deliveries?")}>×</button></div></article>;})}{!d.jobs.length&&<p className="cf-empty">Your next creation starts here.</p>}</section>
 </section><div className="cf-property-column">{store?<StockPanel title={station?.name==="Warehouse"?"Warehouse inventory":"Property inventory"} items={store.contents} d={bag} store={store}/>:<aside className="cf-panel cf-no-property"><GameIcon name="property" size={38}/><h2>Your workshop awaits</h2><p>Open an installed crafting table from a property you own or actively lease.</p><Link className="cf-outline" href="/districts">Find a property →</Link></aside>}
 <aside className="cf-panel cf-how"><p className="cf-eyebrow">A PLAYER-DRIVEN ECONOMY</p><h2>Make your next move.</h2><p>Find a blueprint. Learn its recipe. Buy refined materials from other players or produce your own.</p><Link href="/market">Visit the player market →</Link></aside></div></div>
 {confirmation&&<dialog ref={dialog} className="cf-dialog" aria-label={confirmation.title} onCancel={e=>{if(h.busy)e.preventDefault();else setConfirmation(null);}}><h2>{confirmation.title}</h2><p>{confirmation.body}</p>{h.notice&&<p className={"cf-notice "+(h.failed?"error":"")} role={h.failed?"alert":"status"}>{h.notice}</p>}<button className="cf-gold" disabled={h.working||(!h.retry&&confirmation.payload.season_id!==bag.season.id)} onClick={async()=>{if(h.retry?await h.retryAction():await h.act(confirmation.action,confirmation.payload))setConfirmation(null);}}>{h.retry?"Retry safely":h.working?"Working…":"Confirm "+(confirmation.action==="learn"?"learning":confirmation.action==="start"?"crafting":confirmation.action==="cancel"?"cancellation":"collection")}</button><button className="cf-outline" disabled={h.busy} onClick={()=>setConfirmation(null)}>Go back</button></dialog>}
 </div>;
}

