"use client";
import Link from "next/link";
import {useState,type FormEvent} from "react";
import {money} from "@/lib/game";
import {eligibleBuildings,type DistrictState,type Plot} from "@/lib/districts";
export type DistrictAction=(action:string,payload?:Record<string,unknown>)=>Promise<boolean>;
export function DistrictActionForm({label,children,onSubmit,busy}:{label:string;children:React.ReactNode;onSubmit:(values:Record<string,string>)=>Promise<unknown>;busy:boolean}){
 return <form className="district-action-form" onSubmit={e=>{e.preventDefault();void onSubmit(Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string,string>);}}><fieldset disabled={busy}>{children}<button className="district-gold" type="submit">{label}</button></fieldset></form>;
}
export function PlotDetails({p,state,act,busy,onClose,initialSection="plot"}:{p:Plot;state:DistrictState;initialSection?:string;act:DistrictAction;busy:boolean;onClose:()=>void}){
 const [section,setSection]=useState(initialSection),[confirm,setConfirm]=useState(false);
 const own=p.owner_type==="player"&&p.owner_id===state.player_id,b=state.buildings.find(b=>b.plot_id===p.id),biz=state.businesses.find(b=>b.plot_id===p.id),bt=state.building_types.find(t=>t.id===b?.building_type),auction=state.auctions.find(a=>a.plot_id===p.id),offers=state.offers.filter(o=>o.plot_id===p.id),allowed=eligibleBuildings(p,state),total=p.price+Math.ceil(p.price*p.tax/100),ended=auction&&Date.parse(auction.ends_at)<=Date.parse(state.server_time);
 const action:DistrictAction=(a,v)=>act(a,{plot_id:p.id,...v});
 const disabled=busy||state.season.status!=="open";
 return <div className="plot-details"><header><div><p className="eyebrow">{state.district.name.toUpperCase()} / LAND REGISTRY</p><h2>Plot {p.code}</h2></div><button onClick={onClose} aria-label="Close plot details">×</button></header>
 <nav className="detail-breadcrumb" aria-label="Property hierarchy"><button onClick={()=>setSection("plot")}>Plot</button>{b&&<><span>›</span><button onClick={()=>setSection("building")}>Building</button></>}{biz&&<><span>›</span><button onClick={()=>setSection("business")}>Business</button></>}</nav>
 <div className="detail-scroll">
 {section==="plot"&&<><div className="plot-title-line"><span className={"district-badge "+p.status}>{own?"Your property":p.status}</span><button disabled={busy} className="watch-button" onClick={()=>action("watch")}>{p.watched?"★ Watching":"☆ Watch plot"}</button></div>
 <dl className="district-facts">{[["Zoning",p.zoning],["Size",p.size.toLocaleString()+" m²"],["Owner",p.owner_name],["Base land value",money(p.base_price)],["Tax rate",p.tax+"%"],["Utility level",p.utility_level+" / 100"],["Infrastructure",p.infrastructure_level+" / 100"],["Build capacity",p.build_capacity+" units"],["Designation",p.strategic_type||"Standard plot"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
 <h3>Permitted development</h3><div className="permit-list">{allowed.map(t=><span key={t.id}>{t.name}</span>)}{!allowed.length&&<p>No building currently meets this plot’s zoning and infrastructure rules.</p>}</div>
 {p.owner_type==="player"&&<Link className="district-text-link" href={"/players/"+p.owner_id}>View owner ↗</Link>}
 {biz&&<button className="business-link" onClick={()=>setSection("business")}><span className="eyebrow">{biz.business_type}</span><strong>{biz.name}</strong><span>{biz.owner_name} · {biz.status} ↗</span></button>}
 {(p.status==="available"||p.asking_price!==null)&&!own&&!auction&&<div className="purchase-quote"><span className="eyebrow">ACQUIRE THIS PROPERTY</span><h3>{money(p.price)}</h3><p>District tax {money(total-p.price)} · Total <strong>{money(total)}</strong></p><small>Attached buildings and businesses transfer with the plot.</small>{confirm?<div className="confirm-purchase"><p>Confirm the purchase of {p.code} for {money(total)}?</p><button className="district-gold" disabled={disabled||state.cash<total} onClick={async()=>{if(await action("buy",{version:p.version,total}))setConfirm(false);}}>Confirm purchase</button><button onClick={()=>setConfirm(false)}>Go back</button></div>:<button className="district-gold" disabled={disabled||state.cash<total} onClick={()=>setConfirm(true)}>{state.cash<total?"Not enough cash":"Buy Plot"}</button>}</div>}
 {auction&&<section className="district-auction"><span className="eyebrow">LIVE PROPERTY AUCTION</span><h3>{money(auction.bid||auction.minimum_bid)}</h3><p>{auction.bidder_id===state.player_id?"You hold the leading bid. ":""}Ends {new Date(auction.ends_at).toLocaleString()}</p><p>{auction.tax_rate}% tax applies. Leading bids reserve cash; outbid players are refunded.</p>{ended?<button className="district-gold" disabled={disabled} onClick={()=>action("auction_finish")}>Settle auction</button>:!own&&<DistrictActionForm busy={disabled} label="Place Bid" onSubmit={v=>action("bid",{price:v.price})}><label>Your bid<input name="price" type="number" required min={Math.max(auction.minimum_bid,auction.bid+(auction.bidder_id?state.settings.district_bid_increment:0))}/></label></DistrictActionForm>}</section>}
 {!own&&p.offers_allowed&&p.owner_type==="player"&&!auction&&<DistrictActionForm busy={disabled} label="Make funded offer" onSubmit={v=>action("offer",{price:v.price})}><p>Your offer and district tax are held until accepted or refunded.</p><label>Offer price<input type="number" name="price" min="1" required/></label></DistrictActionForm>}
 {own&&!auction&&<><h3>Manage property</h3>{!b&&<DistrictActionForm busy={disabled} label="Start construction" onSubmit={v=>action("build",{building_type:v.building_type,cost:state.building_types.find(t=>t.id===v.building_type)?.cost})}><label>Build<select name="building_type" required><option value="">Choose a building</option>{allowed.map(t=><option key={t.id} value={t.id}>{t.name} · {money(t.cost)} · {Math.ceil(t.construction_seconds/60)} min</option>)}</select></label></DistrictActionForm>}
 <DistrictActionForm busy={disabled} label="List for sale" onSubmit={v=>action("sell",{price:v.price,offers_allowed:v.offers_allowed==="on"})}><label>Asking price<input type="number" name="price" defaultValue={p.asking_price??p.price} min="1" required/></label><label className="district-checkbox"><input type="checkbox" name="offers_allowed" defaultChecked={p.offers_allowed}/>Accept funded offers</label></DistrictActionForm>
 {p.asking_price!==null&&<button disabled={disabled} onClick={()=>action("unlist")}>Withdraw sale</button>}
 <details><summary>List for auction</summary><DistrictActionForm busy={disabled} label="Open auction" onSubmit={v=>action("auction",{price:v.price})}><p>Auction duration: {state.settings.district_auction_hours} hours. A leading bid commits the sale.</p><label>Minimum bid<input type="number" name="price" min="1" required/></label></DistrictActionForm></details>
 <Link className="district-text-link" href="/ledger">View Financials ↗</Link></>}
 {!!offers.length&&<section><h3>Property offers</h3>{offers.map(o=><div className="district-offer" key={o.id}><strong>{money(o.price)}</strong><p>Expires {new Date(o.ends_at).toLocaleString()}</p>{own&&<button disabled={disabled} onClick={()=>action("offer_accept",{offer_id:o.id})}>Accept offer</button>}<button disabled={disabled} onClick={()=>action("offer_cancel",{offer_id:o.id})}>{own?"Decline & refund":"Cancel & refund"}</button></div>)}</section>}
 <details><summary>Property sale history</summary>{state.sales.filter(s=>s.plot_id===p.id).map(s=><p key={s.id}>{money(s.price)} · {s.method} · {new Date(s.created_at).toLocaleDateString()}</p>)}{!state.sales.some(s=>s.plot_id===p.id)&&<p>No recorded sales this season.</p>}</details></>}
 {own&&b?.construction_status==="ready"&&(b.building_type==="warehouse"||b.building_type==="garage")&&<Link className="district-gold" href="/inventory">Open secure storage →</Link>}
 {section==="building"&&b&&<><span className="eyebrow">{b.construction_status}</span><h3>{bt?.name??(b.building_type==="telegram"?"Telegram Office":b.building_type)}</h3><dl className="district-facts"><div><dt>Level</dt><dd>{b.level}</dd></div><div><dt>Condition</dt><dd>{b.condition}%</dd></div><div><dt>Construction value</dt><dd>{money(b.cost)}</dd></div></dl>{b.construction_status==="building"?<><p>Ready {new Date(b.ready_at).toLocaleString()}</p>{own&&<button className="district-gold" disabled={disabled||Date.parse(b.ready_at)>Date.parse(state.server_time)} onClick={()=>action("complete")}>Complete construction</button>}</>:biz&&<button className="district-gold" onClick={()=>setSection("business")}>View Business →</button>}</>}
 {section==="business"&&biz&&<><span className="eyebrow">{biz.business_type} · {biz.status}</span><h3>{biz.name}</h3><p>{biz.description}</p><dl className="district-facts"><div><dt>Owner</dt><dd>{biz.owner_name}</dd></div><div><dt>Buys</dt><dd>{biz.buys.join(", ")||"No goods declared"}</dd></div><div><dt>Sells</dt><dd>{biz.sells.join(", ")||"Services"}</dd></div>{biz.telegram_fee!==null&&<div><dt>Telegram Office fee</dt><dd>{money(biz.telegram_fee)}</dd></div>}</dl>
 {biz.business_type==="Refinery"&&<Link className="district-gold" href={"/refineries?plot="+p.id}>Open refinery →</Link>}{biz.telegram_fee!==null&&<Link className="district-gold" href="/telegrams">Open city Telegram Office →</Link>}{own&&biz.telegram_fee===null&&<><DistrictActionForm busy={disabled} label="Save business" onSubmit={v=>action("business",v)}><label>Business name<input name="name" defaultValue={biz.name} minLength={2} maxLength={80} required/></label><label>Description<textarea name="description" defaultValue={biz.description} maxLength={1000}/></label><label>Status<select name="status" defaultValue={biz.status}><option value="open">Open</option><option value="closed">Closed</option></select></label>{biz.telegram_fee!==null&&<label>Telegram fee<input name="telegram_fee" type="number" min="0" defaultValue={biz.telegram_fee} required/></label>}</DistrictActionForm>{bt?.good_id&&<div className="production-quote"><h3>Production</h3><p>{bt.batch_size} {bt.good_id} per {Math.ceil(bt.cycle_seconds/60)} minutes{bt.input_good_id?" · Requires "+bt.input_quantity+" "+bt.input_good_id+" per batch":""}</p><button className="district-gold" disabled={disabled||biz.status!=="open"} onClick={()=>action("collect")}>Collect production</button><Link href="/inventory">View inventory ↗</Link></div>}</>}</>}
 </div></div>;
}
