"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {DistrictState} from "@/lib/districts";
import {money,type GameState} from "@/lib/game";
import {CommodityArtwork} from "./commodity-artwork";
import {DistrictActionForm} from "./district-details";
import {MarketPagination,MARKET_PAGE_SIZE} from "./market-pagination";
type Request={action:string;payload:Record<string,unknown>};
export function DistrictBuyOrders({districtId,game,onChange,filter="all",search=""}:{districtId:string;game:GameState;onChange:()=>Promise<void>;filter?:string;search?:string}){
 const [data,setData]=useState<DistrictState|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[retry,setRetry]=useState<Request|null>(null),[page,setPage]=useState(0),[exchange,setExchange]=useState(districtId),[quantities,setQuantities]=useState<Record<string,string>>({});const lock=useRef(false),version=useRef(0);
 const refresh=useCallback(async()=>{const id=++version.current;const {data,error}=await createClient().rpc("district_state",{p_slug:districtId||null});if(error||!data)throw new Error("Buy orders could not refresh. Try again.");if(id===version.current)setData(data as DistrictState);},[districtId]);
 useEffect(()=>{setData(null);void refresh().catch(e=>setNotice(e.message));const timer=setInterval(()=>{if(!document.hidden&&!lock.current)void refresh().catch(e=>setNotice(e.message));},30000);return()=>{clearInterval(timer);version.current++;};},[refresh]);
 useEffect(()=>{setPage(0);setExchange(districtId);},[districtId]);useEffect(()=>setPage(0),[filter,search]);
 async function act(action:string,payload:Record<string,unknown>){if(lock.current)return;lock.current=true;setBusy(true);setNotice("");const request={action,payload:{...payload,season_id:game.season.id,request_id:payload.request_id??crypto.randomUUID()}};try{const r=await createClient().rpc("district_market_order",{p_action:action,p_payload:request.payload});if(r.error){setRetry(request);throw new Error("The reply was interrupted. Retry the same request to confirm it safely.");}setRetry(null);if(r.data?.error)throw new Error(r.data.error);setNotice(r.data.message);try{await Promise.all([refresh(),onChange()]);}catch{setNotice(r.data.message+" Refresh orders to see updated totals.");}}catch(e){setNotice(e instanceof Error?e.message:"Please try again.");}finally{lock.current=false;setBusy(false);}}
 const disabled=busy||!!retry||game.season.status!=="open";
 const orders=(data?.buy_orders??[]).filter(o=>(filter==="all"||filter===o.good_id)&&(!search||((game.goods.find(g=>g.id===o.good_id)?.name??o.good_id)+" "+o.buyer_name).toLowerCase().includes(search.toLowerCase())));
 const current=Math.min(page,Math.max(0,Math.ceil(orders.length/MARKET_PAGE_SIZE)-1));
 return <section className="district-view district-order-book game-panel"><header className="panel-heading"><div><p className="eyebrow">PLAYER REQUESTS · CASH HELD IN RESERVE</p><h2>Buy orders</h2></div><button className="market-outline" disabled={busy} onClick={()=>void refresh().catch(e=>setNotice(e.message))}>Refresh orders</button></header>{notice&&<p className="district-notice" role="status">{notice}</p>}{retry&&<button className="market-outline" disabled={busy} onClick={()=>void act(retry.action,retry.payload)}>Retry same order request</button>}
 <div className="district-order-columns"><div>{orders.slice(current*10,current*10+10).map(o=>{const remaining=o.remaining_quantity??o.quantity,own=o.buyer_id===game.player.id,stock=game.inventory.find(i=>i.good_id===o.good_id)?.quantity??0,qty=Number(quantities[o.id]??"1"),total=qty*o.unit_price,fee=Math.ceil(total*game.settings.market_fee_percent/100);return <article className="local-market-order" key={o.id}><div className="district-order-commodity"><CommodityArtwork goodId={o.good_id} size={44}/><strong>{game.goods.find(g=>g.id===o.good_id)?.name??o.good_id}</strong></div><p>{o.buyer_name} offers {money(o.unit_price)} per item</p><p>{o.quantity-remaining} of {o.quantity} filled · {remaining} remaining · {money(o.escrow)} reserved</p>{own?<button className="district-gold" disabled={disabled} onClick={()=>void act("cancel",{order_id:o.id})}>Cancel & refund {money(o.escrow)}</button>:<form onSubmit={e=>{e.preventDefault();void act("fill",{order_id:o.id,quantity:qty});}}><label>Quantity to sell<input type="number" required min={1} max={Math.min(stock,remaining)} step={1} value={quantities[o.id]??"1"} onChange={e=>setQuantities({...quantities,[o.id]:e.target.value})} disabled={disabled}/></label><p>{stock} available · You receive {money(Math.max(0,total-fee))} after {game.settings.market_fee_percent}% seller fee.</p><button className="district-gold" disabled={disabled||!Number.isSafeInteger(qty)||qty<1||qty>stock||qty>remaining}>Sell to this order</button></form>}</article>;})}{!data?<p className="district-empty">Loading buy orders…</p>:!orders.length&&<p className="district-empty">No matching buy orders yet.</p>}<MarketPagination page={current} total={orders.length} onPage={setPage} label="Buy orders"/><p className="form-help">Sell any available quantity. Orders stay open until filled or cancelled. Each completed sale sends both players a Telegram alert.</p></div>
 <div><DistrictActionForm busy={disabled||!data} label="Fund buy order" onSubmit={v=>act("create",{...v,district_id:districtId||exchange||data?.districts[0]?.id})}><label>Exchange<select value={districtId||exchange||data?.districts[0]?.id||""} onChange={e=>setExchange(e.target.value)} disabled={!!districtId} required>{data?.districts.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Wanted goods<select name="good_id">{game.goods.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Units wanted<input name="quantity" type="number" required min="1" max={game.settings.max_listing_quantity} defaultValue="1"/></label><label>Your unit price<input name="unit_price" type="number" required min="1" max={game.settings.max_unit_price} defaultValue="100"/></label><p>The full quantity × unit price is reserved from your cash. Other players can sell in parts. Cancel anytime to refund only the unfilled remainder.</p></DistrictActionForm></div></div></section>;
}
