"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";
import type {DistrictState} from "@/lib/districts";
type Field={key:string;label:string;type?:string;options?:{value:string;label:string}[];optional?:boolean};
const options=(values:string[])=>values.map(value=>({value,label:value.replaceAll("_"," ")}));
function Editor({title,fields,values,submit,busy,label="Save changes"}:{title:string;fields:Field[];values:Record<string,unknown>;submit:(v:Record<string,unknown>)=>Promise<void>;busy:boolean;label?:string}){
 return <section className="district-panel owner-district-editor"><h2>{title}</h2><form key={JSON.stringify(values)} onSubmit={e=>{e.preventDefault();const v:Record<string,unknown>={...values};for(const f of fields){const raw=new FormData(e.currentTarget).get(f.key)?.toString()??"";v[f.key]=f.type==="number"?(raw===""?null:Number(raw)):f.type==="boolean"?raw==="true":f.type==="list"?raw.split(",").map(v=>v.trim()).filter(Boolean):raw;}v.reason=new FormData(e.currentTarget).get("reason");void submit(v);}}><fieldset disabled={busy}><div className="district-editor-fields">{fields.map(f=><label key={f.key}>{f.label}{f.options?<select name={f.key} defaultValue={String(values[f.key]??"")} required={!f.optional}>{f.optional&&<option value="">None</option>}{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==="textarea"?<textarea name={f.key} defaultValue={String(values[f.key]??"")} required={!f.optional}/>:f.type==="boolean"?<select name={f.key} defaultValue={String(values[f.key]??false)}><option value="true">Yes</option><option value="false">No</option></select>:<input name={f.key} type={f.type==="number"?"number":"text"} step={f.type==="number"?"any":undefined} defaultValue={Array.isArray(values[f.key])?(values[f.key] as string[]).join(", "):String(values[f.key]??"")} required={!f.optional}/>}</label>)}</div><label>Reason for this change<textarea name="reason" required minLength={3} maxLength={1000}/></label><button className="district-gold">{label}</button></fieldset></form></section>;
}
export function DistrictOwner({initialSlug}:{initialSlug?:string}){
 const [state,setState]=useState<DistrictState|null>(null),[slug,setSlug]=useState(initialSlug??""),[section,setSection]=useState("district"),[record,setRecord]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function refresh(s=slug){const {data,error}=await createClient().rpc("district_state",{p_slug:s||null});if(error)throw new Error("Could not load district management.");setState(data as DistrictState);}
 useEffect(()=>{void refresh().catch(e=>setMessage(e.message));},[slug]);
 async function save(action:string,payload:Record<string,unknown>){setBusy(true);setMessage("");try{const {data,error}=await createClient().rpc("district_manage",{p_action:action,p_payload:payload});if(error||data?.error)throw new Error(data?.error??"Could not save this change.");setMessage(data.message);await refresh();}catch(e){setMessage(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}}
 if(!state)return <section className="district-panel"><p>{message||"Opening the city planning office…"}</p></section>;
 if(!state.can_manage||!state.management)return <section className="district-panel"><h2>District management permission required</h2><Link href="/districts">Return to the city</Link></section>;
 const m=state.management,d=m.districts.find(d=>d.slug===slug),districtId=d?.id??m.districts[0]?.id;
 const templates=m.templates.filter(p=>p.district_id===districtId),t=templates.find(p=>p.id===record),bt=state.building_types.find(b=>b.id===record),z=state.zoning.find(z=>z.id===record),site=m.site_templates.find(s=>s.id===record),p=state.plots.find(p=>p.id===record);
 const districtOptions=m.districts.map(d=>({value:d.id,label:d.name})),plotOptions=state.plots.map(p=>({value:p.id,label:p.code+" · "+p.owner_name})),gangOptions=m.gangs.map(g=>({value:g.id,label:g.name})),buildingOptions=state.building_types.map(b=>({value:b.id,label:b.name})),warOptions=state.wars.map(w=>({value:w.id,label:w.name}));
 const titleOptions=section==="plot"?templates.map(t=>({value:t.id,label:t.code})):section==="building_type"?buildingOptions:section==="zoning"?state.zoning.map(z=>({value:z.id,label:z.name})):section==="site"?m.site_templates.filter(s=>s.district_id===districtId).map(s=>({value:s.id,label:s.name})):section==="building"?plotOptions:section==="war"?warOptions:[];
 const districtFields:Field[]=[{key:"slug",label:"URL name"},{key:"name",label:"District name"},{key:"tagline",label:"Tagline"},{key:"description",label:"Description",type:"textarea"},{key:"district_type",label:"District type"},{key:"image_url",label:"Banner image path or HTTPS URL"},{key:"industries",label:"Industries, separated by commas",type:"list"},{key:"strategic_importance",label:"Strategic importance",type:"textarea"},{key:"tax_rate",label:"District tax (%)",type:"number"},{key:"police_heat",label:"Police heat (0–100)",type:"number"},{key:"property_value_index",label:"Property index",type:"number"},{key:"property_trend",label:"Property trend (%)",type:"number"},{key:"status",label:"District status",options:options(["neutral","controlled","contested","lockdown"])},{key:"map_x",label:"City map position X",type:"number"},{key:"map_y",label:"City map position Y",type:"number"},{key:"map_width",label:"City map width",type:"number"},{key:"map_height",label:"City map height",type:"number"}];
 const bounds=(polygon:[number,number][]|undefined)=>{const xs=polygon?.map(p=>p[0])??[100,300],ys=polygon?.map(p=>p[1])??[100,300];return {map_x:Math.min(...xs),map_y:Math.min(...ys),map_width:Math.max(...xs)-Math.min(...xs),map_height:Math.max(...ys)-Math.min(...ys)};};
 const rect=(v:Record<string,unknown>)=>{const x=Number(v.map_x),y=Number(v.map_y),w=Number(v.map_width),h=Number(v.map_height);return [[x,y],[x+w,y],[x+w,y+h],[x,y+h]];};
 return <div className="district-owner"><header className="district-section-heading"><div><p className="eyebrow">OWNER / CITY PLANNING</p><h1>Districts & property</h1></div><Link href="/districts">View City Map ↗</Link></header><div className="district-management-bar"><label>District<select value={slug} onChange={e=>{setSlug(e.target.value);setRecord("");}}><option value="">Create a district</option>{m.districts.map(d=><option key={d.id} value={d.slug}>{d.name}{d.archived_at?" · Archived":""}</option>)}</select></label><label>Manage<select value={section} onChange={e=>{setSection(e.target.value);setRecord("");}}>{[["district","District information"],["plot","Plots & zoning"],["site","Resources & strategic sites"],["building","Assign / remove building"],["building_type","Building types & production"],["zoning","Zoning permissions"],["control","District controller"],["influence","Gang influence"],["war","District wars"],["war_party","War participants"],["operation","Operations & convoys"],["event","Publish district event"],["event_visibility","Hide / restore event"],["archive","Archive district"]].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>{!!titleOptions.length&&<label>Record<select value={record} onChange={e=>setRecord(e.target.value)}><option value="">Create new / choose</option>{titleOptions.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}</div>{message&&<p role="status" className="district-notice">{message}</p>}
 {section==="district"&&<Editor title={d?"Edit "+d.name:"Create district"} fields={districtFields} values={{slug:"",name:"",tagline:"",description:"",district_type:"urban",image_url:"/art/harbor.webp",industries:[],strategic_importance:"",tax_rate:3,police_heat:0,property_value_index:100,property_trend:0,status:"neutral",...d,...bounds(d?.city_polygon)}} busy={busy} submit={v=>save("district",{...v,city_polygon:d&&JSON.stringify(bounds(d.city_polygon))===JSON.stringify({map_x:v.map_x,map_y:v.map_y,map_width:v.map_width,map_height:v.map_height})?d.city_polygon:rect(v)})}/>}
 {section==="plot"&&<Editor title={t?"Edit "+t.code:"Create plot"} busy={busy} values={{district_id:districtId,code:"",size:1000,zoning:state.zoning[0]?.id,status:"available",base_price:5000,tax_rate:null,utility_level:50,infrastructure_level:50,build_capacity:1,strategic_type:"",...t,...bounds(t?.polygon)}} fields={[{key:"code",label:"Plot code"},{key:"size",label:"Size (m²)",type:"number"},{key:"zoning",label:"Zoning",options:state.zoning.map(z=>({value:z.id,label:z.name}))},{key:"status",label:"Status",options:options(["available","owned","reserved","locked"])},...["base_price","tax_rate","utility_level","infrastructure_level","build_capacity"].map(key=>({key,label:key.replaceAll("_"," "),type:"number",optional:key==="tax_rate"})),{key:"strategic_type",label:"Strategic designation",optional:true},...["map_x","map_y","map_width","map_height"].map(key=>({key,label:key.replaceAll("_"," "),type:"number"}))]} submit={v=>save("plot",{...v,polygon:t&&JSON.stringify(bounds(t.polygon))===JSON.stringify({map_x:v.map_x,map_y:v.map_y,map_width:v.map_width,map_height:v.map_height})?t.polygon:rect(v)})}/>}
 {section==="site"&&<Editor title="Resource / strategic site" busy={busy} values={{district_id:districtId,name:"",kind:"resource",resource_type:"",plot_template_id:"",...site,capacity:site?.data.capacity??0,unit:site?.data.unit??"",description:site?.data.description??"",survey_status:site?.data.survey_status??"Unsurveyed"}} fields={[{key:"name",label:"Name"},{key:"kind",label:"Site kind",options:options(["resource","strategic"])},{key:"resource_type",label:"Resource or site type"},{key:"plot_template_id",label:"Plot",optional:true,options:templates.map(p=>({value:p.id,label:p.code}))},{key:"capacity",label:"Capacity / reserve estimate",type:"number"},{key:"unit",label:"Measurement unit",optional:true},{key:"survey_status",label:"Survey status"},{key:"description",label:"Description",type:"textarea"}]} submit={v=>save("site",{...v,plot_template_id:v.plot_template_id||null,data:{capacity:v.capacity,unit:v.unit,description:v.description,survey_status:v.survey_status}})}/>}
 {section==="building"&&<Editor title="Assign or remove building" busy={busy} values={{plot_id:p?.id??"",building_type:"",name:""}} fields={[{key:"plot_id",label:"Owned plot",options:plotOptions},{key:"building_type",label:"Building (None removes current building)",options:buildingOptions,optional:true},{key:"name",label:"Business name",optional:true}]} submit={v=>save("building",v)}/>}
 {section==="building_type"&&<Editor title="Building type & production rules" busy={busy} values={{id:"",name:"",cost:0,construction_seconds:300,capacity_required:1,minimum_utility:0,minimum_infrastructure:0,business_type:"",good_id:"",batch_size:0,cycle_seconds:300,input_good_id:"",input_quantity:0,telegram_fee:null,active:true,...bt}} fields={[{key:"id",label:"Building type ID"},{key:"name",label:"Name"},{key:"business_type",label:"Business category"},...["cost","construction_seconds","capacity_required","minimum_utility","minimum_infrastructure","batch_size","cycle_seconds","input_quantity"].map(key=>({key,label:key.replaceAll("_"," "),type:"number"})),{key:"good_id",label:"Produces",options:state.goods.map(g=>({value:g.id,label:g.name})),optional:true},{key:"input_good_id",label:"Consumes",options:state.goods.map(g=>({value:g.id,label:g.name})),optional:true},{key:"telegram_fee",label:"Telegram fee (leave empty for other businesses)",type:"number",optional:true},{key:"active",label:"Available for construction",type:"boolean"}]} submit={v=>save("building_type",v)}/>}
 {section==="zoning"&&<Editor title="Allowed buildings per zone" busy={busy} values={{id:"",name:"",allowed_buildings:[],...z}} fields={[{key:"id",label:"Zone ID"},{key:"name",label:"Zone name"},{key:"allowed_buildings",label:"Allowed building IDs, separated by commas",type:"list"}]} submit={v=>save("zoning",v)}/>}
 {section==="control"&&<Editor title="District control" busy={busy} values={{district_id:districtId,controller_gang_id:state.territory.controller_gang_id??"",neutral_influence:state.territory.neutral_influence??100,fortification:state.territory.fortification??0,status:state.territory.status??"neutral"}} fields={[{key:"controller_gang_id",label:"Controlling gang",options:gangOptions,optional:true},{key:"neutral_influence",label:"Neutral influence",type:"number"},{key:"fortification",label:"Fortification (0–100)",type:"number"},{key:"status",label:"Status",options:options(["neutral","controlled","contested","lockdown"])}]} submit={v=>save("control",v)}/>}
 {section==="influence"&&<Editor title="Set gang influence" busy={busy} values={{district_id:districtId,influence:0}} fields={[{key:"gang_id",label:"Gang",options:gangOptions},{key:"influence",label:"Influence points",type:"number"}]} submit={v=>save("influence",v)}/>}
 {section==="war"&&<Editor title="District war" busy={busy} values={{district_id:districtId,...state.wars.find(w=>w.id===record),objectives:""}} fields={[{key:"name",label:"War name"},{key:"status",label:"Status",options:options(["preparing","active","finished"])},{key:"objectives",label:"Objectives, one per line",type:"textarea"}]} submit={v=>save("war",{...v,objectives:String(v.objectives).split("\n").filter(Boolean)})}/>}
 {section==="war_party"&&<Editor title="Add or update a participating gang" busy={busy} values={{supply:0}} fields={[{key:"war_id",label:"War",options:warOptions},{key:"gang_id",label:"Gang",options:gangOptions},{key:"side",label:"Role",options:options(["attacker","defender","independent"])},{key:"supply",label:"Supply level",type:"number"}]} submit={v=>save("war_party",v)}/>}
 {section==="operation"&&<Editor title="Record a war operation" busy={busy} values={{status:"active"}} fields={[{key:"war_id",label:"War",options:warOptions},{key:"gang_id",label:"Participating gang",options:gangOptions},{key:"kind",label:"Operation kind",options:options(["operation","convoy","defense","participation","territory_change"])},{key:"status",label:"Status"},{key:"description",label:"Description",type:"textarea"}]} submit={v=>save("operation",v)}/>}
 {section==="event"&&<Editor title="Publish district event" busy={busy} values={{district_id:districtId}} fields={[{key:"description",label:"Public announcement",type:"textarea"}]} submit={v=>save("event",v)}/>}
 {section==="event_visibility"&&<Editor title="Event visibility" busy={busy} values={{hidden:true}} fields={[{key:"event_id",label:"Event",options:state.events.map(e=>({value:String(e.id),label:e.description}))},{key:"hidden",label:"Hide from players",type:"boolean"}]} submit={v=>save("event_visibility",v)}/>}
 {section==="archive"&&<Editor title="Archive / restore district" busy={busy} values={{id:districtId,archive:true}} fields={[{key:"id",label:"District",options:districtOptions},{key:"archive",label:"Archive this district",type:"boolean"}]} submit={v=>save("archive_district",v)}/>}
 </div>;
}
