"use client";
import {useCallback,useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {DistrictState} from "@/lib/districts";
import type {GameState} from "@/lib/game";
import {money} from "@/lib/game";
import {DistrictActionForm} from "./district-details";
export function DistrictBuyOrders({districtId,game,onChange}:{districtId:string;game:GameState;onChange:()=>Promise<void>}){
 const [data,setData]=useState<DistrictState|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const refresh=useCallback(async()=>{const {data,error}=await createClient().rpc("district_state",{p_slug:districtId||null});if(!error&&data)setData(data as DistrictState);},[districtId]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>{if(document.visibilityState==="visible")void refresh();},30000);return()=>clearInterval(timer);},[refresh]);
 async function act(action:string,payload:Record<string,unknown>){setBusy(true);try{const {data,error}=await createClient().rpc("district_market_order",{p_action:action,p_payload:{...payload,season_id:game.season.id,district_id:districtId}});if(error||data?.error)throw new Error(data?.error??"Could not complete this order.");setNotice(data.message);await Promise.all([refresh(),onChange()]);}catch(e){setNotice(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}}
 return <section className="district-view district-order-book game-panel"><header className="panel-heading"><div><p className="eyebrow">PLAYER DEMAND · CASH HELD IN RESERVE</p><h2>Funded buy orders</h2></div></header>{notice&&<p className="district-notice" role="status">{notice}</p>}<div className="district-order-columns"><div>{data?.buy_orders.map(o=><article className="local-market-order" key={o.id}><strong>{o.quantity} {game.goods.find(g=>g.id===o.good_id)?.name??o.good_id}</strong><span>{o.buyer_name} wants to buy · {money(o.unit_price)} each · {money(o.quantity*o.unit_price)} reserved</span><button className="district-gold" disabled={busy||game.season.status!=="open"} onClick={()=>act(o.buyer_id===game.player.id?"cancel":"fill",{order_id:o.id})}>{o.buyer_id===game.player.id?"Cancel & refund":"Supply whole lot"}</button></article>)}{!data?.buy_orders.length&&<p className="district-empty">No funded requests in this exchange yet.</p>}<p className="form-help">Suppliers receive the lot value less the current {game.settings.market_fee_percent}% market fee. An order can only be filled once.</p></div><div>{districtId?<DistrictActionForm busy={busy||game.season.status!=="open"} label="Fund buy order" onSubmit={v=>act("create",v)}><label>Wanted goods<select name="good_id">{game.goods.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Units wanted<input name="quantity" type="number" required min="1" max={game.settings.max_listing_quantity} defaultValue="1"/></label><label>Your unit price<input name="unit_price" type="number" required min="1" max={game.settings.max_unit_price} defaultValue="100"/></label><p>The full order value is reserved from your cash. Cancel an unfilled order to receive a refund.</p></DistrictActionForm>:<p className="district-empty">Choose a district market above to post a funded buy order.</p>}</div></div></section>;
}
