"use client";
import {useCallback,useEffect,useRef,useState,type ReactNode} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
type District={id:string;slug:string;name:string};
type TravelState={season_id:string;enabled:boolean;jailed:boolean;server_time:string;current:District;heat:number;journey:(District&{method:string;arrives_at:string;departed_at:string})|null;districts:(District&{status:string})[];vehicles:{id:string;name:string;fuel:number}[];options:{walk_seconds:number;train_seconds:number;drive_seconds:number;train_fare:number;drive_fuel:number;fuel_price:number}};
function useTravel(){
 const [data,setData]=useState<TravelState|null>(null),[error,setError]=useState(""),[now,setNow]=useState(Date.now()),alive=useRef(true),reading=useRef(false),offset=useRef(0);
 const refresh=useCallback(async()=>{if(reading.current)return;reading.current=true;try{const r=await createClient().rpc("travel_state");if(r.error||!r.data||r.data.error)throw Error("Travel details could not load. Please refresh.");if(alive.current){offset.current=Date.parse(r.data.server_time)-Date.now();setData(r.data);setError("");}}catch(e){if(alive.current)setError((e as Error).message);}finally{reading.current=false;}},[]);
 useEffect(()=>{alive.current=true;void refresh();const poll=()=>{if(!document.hidden)void refresh();};const tick=setInterval(()=>setNow(Date.now()+offset.current),1000),timer=setInterval(poll,5000);window.addEventListener("focus",poll);window.addEventListener("blackwater:game",poll);return()=>{alive.current=false;clearInterval(tick);clearInterval(timer);window.removeEventListener("focus",poll);window.removeEventListener("blackwater:game",poll);};},[refresh]);
 return {data,error,now,refresh};
}
export function DashboardTravelHeat(){const {data,error}=useTravel();return <div><dt>District heat</dt><dd><span className="command-meter" role="meter" aria-label="Your district heat" aria-valuemin={0} aria-valuemax={100} aria-valuenow={data?.heat}><i style={{width:(data?.heat??0)+"%",background:"#b26050"}}/></span><small>{data?`${data.heat} / 100 · ${data.current.name}`:error?"Unavailable":"Loading…"}</small>{data?.journey&&<small>Travelling to {data.journey.name}</small>}</dd></div>;}
const time=(n:number)=>`${Math.floor(Math.max(0,n)/60)}m ${Math.max(0,n)%60}s`;
export function DistrictTravelGate({target,children}:{target:string;children:ReactNode}){
 const {data,error,now,refresh}=useTravel(),router=useRouter(),[vehicle,setVehicle]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[retry,setRetry]=useState<{action:string;payload:Record<string,unknown>}|null>(null),lock=useRef(false);
 const destination=data?.districts.find(d=>d.id===target||d.slug===target),car=data?.vehicles.find(v=>v.id===vehicle)??data?.vehicles[0];
 const run=async(request:{action:string;payload:Record<string,unknown>})=>{if(lock.current)return;lock.current=true;setBusy(true);let uncertain=true;try{const r=await createClient().rpc("travel_action",{p_action:request.action,p_payload:request.payload});if(r.error)throw Error("The reply was interrupted. Retry to confirm the same request.");uncertain=false;setRetry(null);if(r.data?.error)throw Error(r.data.error);setNotice(r.data.message);await refresh();window.dispatchEvent(new Event("blackwater:game"));router.refresh();}catch(e){setNotice((e as Error).message);if(uncertain)setRetry(request);}finally{lock.current=false;setBusy(false);}};
 const act=(action:string,extra:Record<string,unknown>)=>{if(!data||retry)return;void run({action,payload:{season_id:data.season_id,request_id:crypto.randomUUID(),...extra}});};
 if(data&&!error&&(!data.enabled||!data.journey&&(data.current.id===target||data.current.slug===target)))return <>{children}</>;
 return <section className="district-travel-panel" aria-label="District travel"><p className="eyebrow">BLACKWATER / TRANSIT</p><h1>{data?.journey?`On your way to ${data.journey.name}`:`Travel to ${destination?.name??"this district"}`}</h1>{error?<p role="alert">{error} <button onClick={()=>void refresh()}>Refresh</button></p>:!data?<p>Checking your location…</p>:<><p>Current district: <strong>{data.current.name}</strong></p>{notice&&<p role="status">{notice}</p>}{retry&&<button disabled={busy} onClick={()=>void run(retry)}>Retry safely</button>}{data.jailed?<p>You must be released from prison before travelling.</p>:data.journey?<><p role="timer">Arrival in {time(Math.ceil((Date.parse(data.journey.arrives_at)-now)/1000))}</p><p>Your trip continues if you leave this page.</p><button onClick={()=>router.push("/districts/"+data.journey!.slug)}>View destination</button></>:<><p>Choose how you want to get there. Costs are paid when you depart.</p><div className="district-travel-options">{[["walk","Walk",data.options.walk_seconds,"Free"],["train","Train",data.options.train_seconds,`$${data.options.train_fare}`],["drive","Drive",data.options.drive_seconds,`${data.options.drive_fuel} fuel`]].map(([method,label,seconds,cost])=><button key={method} disabled={busy||!!retry||!destination||destination.status==="lockdown"||(method==="drive"&&(!car||car.fuel<data.options.drive_fuel))} onClick={()=>act("start",{district_id:destination!.id,method,vehicle_id:method==="drive"?car?.id:undefined})}><strong>{label}</strong><span>{time(Number(seconds))}</span><small>{cost}</small></button>)}</div>{data.vehicles.length?<div className="district-travel-fuel"><label>Your car<select value={car?.id??""} disabled={busy||!!retry} onChange={e=>setVehicle(e.target.value)}>{data.vehicles.map(v=><option key={v.id} value={v.id}>{v.name} · {v.fuel}/100 fuel</option>)}</select></label><p>Fuel: ${data.options.fuel_price} per unit.</p><button disabled={busy||!!retry||!car||car.fuel===100} onClick={()=>act("refuel",{vehicle_id:car!.id,units:Math.min(10,100-car!.fuel)})}>Buy {Math.min(10,100-(car?.fuel??0))} fuel · ${Math.min(10,100-(car?.fuel??0))*data.options.fuel_price}</button></div>:<p>Store an owned car in your garage to unlock driving.</p>}</>}</>}</section>;
}
