"use client";
import {useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {PRISON_PATH} from "@/lib/prison";
import {footStep} from "@/lib/first-person-movement";
import {routePosition,type ScavengingState,type StreetPosition,type StreetSession} from "@/lib/scavenging";
import {eventNames} from "@/lib/street-operations";
import type {StreetScene,StreetInput} from "./street-scene";
import "./first-person-street.css";
type Props={state:ScavengingState;season:string;district:string;now:number;busy:boolean;blocked:boolean;cooldown:number;lockpicks:number;act:(action:string,payload?:Record<string,unknown>)=>Promise<boolean>;close:()=>void};
const still:StreetInput={dx:0,dy:0,sprint:false};
function position(session:StreetSession,now:number):StreetPosition{const start=Date.parse(session.departed_at),end=Date.parse(session.arrives_at);return routePosition(session.route_points??[[session.node%5,Math.floor(session.node/5)]],end>start?(now-start)/(end-start):1);}
export function FirstPersonStreet(props:Props){
 const acting=useRef(false);
 const router=useRouter(),latest=useRef(props);latest.current=props;
 const host=useRef<HTMLDivElement>(null),engine=useRef<StreetScene|null>(null),input=useRef<StreetInput>(still),point=useRef<StreetPosition>(position(props.state.session!,props.now)),transport=useRef<{stop:()=>Promise<boolean>}|null>(null),interact=useRef<()=>void>(()=>{});
 const [status,setStatus]=useState("Connecting to the street…"),[ready,setReady]=useState(false),[locked,setLocked]=useState(false),[overview,setOverview]=useState(false),[failed,setFailed]=useState(false),[actionBusy,setActionBusy]=useState(false),[p,setP]=useState(point.current),[notice,setNotice]=useState("");
 const ops=props.state.operations,pursuit=ops?.pursuit,pending=props.state.session?.pending,radius=(props.state.settings.scavenging_interaction_radius_percent??8)/100;
 const nearby=props.state.targets.map(t=>({target:t,distance:Math.abs(p[0]-t.node%5)+Math.abs(p[1]-Math.floor(t.node/5))})).sort((a,b)=>a.distance-b.distance)[0];
 const target=nearby&&nearby.distance<=radius?nearby.target:undefined;
 const event=ops?.event,nearEvent=event&&(Math.abs(p[0]-event.node%5)+Math.abs(p[1]-Math.floor(event.node/5)))<=radius;
 const restock=!!target?.ready_at&&Date.parse(target.ready_at)>props.now,wait=pending?Math.max(0,Math.ceil((Date.parse(pending.ready_at)-props.now)/1000)):0;
 const disabled=!ready||props.busy||props.blocked||actionBusy;
 const run=async(action:string,payload:Record<string,unknown>={})=>{if(disabled)return;acting.current=true;setActionBusy(true);setNotice("");try{if(await transport.current?.stop())await latest.current.act(action,payload);}finally{acting.current=false;setActionBusy(false);}};
 interact.current=()=>{if(pending){if(!wait)void run('scav_finish',{attempt_id:pending.id});}else if(!pursuit&&!props.cooldown&&!restock){if(target&&(target.kind==='bin'||props.lockpicks))void run('scav_search',{target_id:target.id});else if(nearEvent&&event.kind!=='sweep')void run('scav_event',{event_id:event.id});}};
 useEffect(()=>{
  if(!host.current)return;let alive=true,inFlight:Promise<boolean>|null=null,sequence=0,active=false,ack=0,ui=0,localState=latest.current.state,localTime=latest.current.now,correction:StreetPosition=[0,0];
  const controller=crypto.randomUUID(),client=createClient(),districtId=localState.session!.district_id;
  const snapshot=(data:{server_time:string;session:StreetSession;patrols:ScavengingState['patrols']})=>{if(!alive||!data.session)return;ack=performance.now();const time=Date.parse(data.server_time),actual=position(data.session,time);if(Math.hypot(actual[0]-point.current[0],actual[1]-point.current[1])>.2||!active){point.current=actual;correction=[0,0];}else correction=[actual[0]-point.current[0],actual[1]-point.current[1]];localState={...latest.current.state,session:data.session,patrols:data.patrols};if(localState.operations&&'pursuit' in data.session)localState={...localState,operations:{...localState.operations,pursuit:(data.session as StreetSession&{pursuit:typeof pursuit}).pursuit}};localTime=time;engine.current?.update(localState,time);};
  const send=async(action:'begin'|'step',direction=still):Promise<boolean>=>{
   const request={season_id:latest.current.season,district_id:districtId,controller,...(action==='step'?{sequence:++sequence,...direction}:{})};
   try{const {data,error}=await client.rpc('street_motion',{p_action:action,p_payload:request});if(!alive)return false;if(error||data?.error){input.current=still;active=false;setReady(false);setStatus(data?.error??'Connection interrupted. Return to the map and re-enter street view.');engine.current?.unlock();return false;}if(data?.caught){router.replace(PRISON_PATH);return false;}if(data?.pursuit)window.dispatchEvent(new Event('blackwater:game'));snapshot(data);return true;}
   catch{if(alive){input.current=still;active=false;setReady(false);setStatus('Connection interrupted. Return to the map and reconnect.');engine.current?.unlock();}return false;}
  };
  const step=async(direction:StreetInput)=>{if(inFlight)await inFlight;if(!active)return false;const call=send('step',direction);inFlight=call;try{return await call;}finally{if(inFlight===call)inFlight=null;}};
  transport.current={stop:async()=>{input.current=still;return step(still);}};
  let previousMotion=false;
  const timer=setInterval(()=>{const motion=Math.hypot(input.current.dx,input.current.dy)>.001;if(active&&!inFlight&&(motion||previousMotion)){previousMotion=motion;void step({...input.current});}},220);
  const start=async()=>{try{const {createStreetScene}=await import('./street-scene');if(!alive||!host.current)return;
   engine.current=createStreetScene(host.current,{district:latest.current.district,width:(localState.settings.scavenging_foot_road_half_percent??13)/100,state:localState,now:localTime,interact:()=>interact.current(),locked:setLocked,failed:()=>{setFailed(true);setStatus('Your graphics connection was interrupted. The aerial map is still available.');},frame:(direction,dt)=>{
    if(acting.current||!active||latest.current.busy||latest.current.blocked||document.hidden)direction=still;
    input.current=direction;const settings=latest.current.state.settings;let speed=settings.scavenging_foot_walk_seconds??10;if(direction.sprint)speed*=100/(settings.scavenging_foot_sprint_percent??150);const chase=latest.current.state.operations?.pursuit;if(chase?.vehicle_id)speed=chase.rules.scavenging_getaway_seconds_per_block??2;
    // Prediction stops when the last accepted input lease expires; it never produces rewards.
    if(Math.hypot(correction[0],correction[1])>.0001){const fraction=Math.min(1,dt*8);point.current=[point.current[0]+correction[0]*fraction,point.current[1]+correction[1]*fraction];correction=[correction[0]*(1-fraction),correction[1]*(1-fraction)];}
    if(ack&&performance.now()-ack<Math.max(350,settings.scavenging_input_lease_ms??500))point.current=footStep(point.current,direction.dx,direction.dy,dt,speed,(settings.scavenging_foot_road_half_percent??13)/100);
    if(performance.now()-ui>100){ui=performance.now();setP([...point.current]);}return point.current;
   }});if(await send('begin')){active=true;setReady(true);setStatus('Walk into Blackwater.');}
  }catch{if(alive){setFailed(true);setStatus('This device could not open the 3D street view. You can continue in the aerial map.');}}};void start();
  return()=>{alive=false;active=false;clearInterval(timer);input.current=still;const payload={season_id:latest.current.season,district_id:districtId,controller,sequence:++sequence,...still};void client.rpc('street_motion',{p_action:'step',p_payload:payload});engine.current?.dispose();engine.current=null;transport.current=null;window.dispatchEvent(new Event('blackwater:game'));};
 },[props.season,props.state.session?.district_id,router]);
 useEffect(()=>{engine.current?.update(props.state,props.now);},[props.state,props.now]);
 const touchOrigin=useRef({x:0,y:0}),lookOrigin=useRef({x:0,y:0});
 const exit=!!pursuit&&Math.abs(p[0])+Math.abs(p[1])<=radius&&props.now>=Date.parse(pursuit.started_at)+(pursuit.rules.scavenging_escape_min_seconds??6)*1000;
 return <section className="fp-street" aria-label="First-person Scavenging">
 <header className="fp-toolbar"><div><span className="eyebrow">BLACKWATER / STREET VIEW</span><strong>{props.district}</strong></div><div><button onClick={()=>{const value=!overview;setOverview(value);engine.current?.overview(value);void transport.current?.stop();}} disabled={!ready}>{overview?'Street view':'Aerial view'}</button><button onClick={props.close}>Exit street view</button></div></header>
 <div className="fp-world"><div className="fp-canvas" ref={host}/><div className="fp-vignette"/>
 <div className="fp-topline"><span>{props.state.streets[Math.max(0,Math.min(2,Math.round(p[1])))]??props.district}</span><span>{pursuit?'WANTED':pending?'SEARCHING':'ON FOOT'}</span></div>
 {!overview&&ready&&locked&&<span className="fp-crosshair" aria-hidden="true">+</span>}
 {(!locked&&!overview||failed)&&<div className="fp-pause"><span className="eyebrow">A CITY OF OPPORTUNITY</span><h2>{failed?'The streets are still open.':ready?'Step into Blackwater.':'Opening the streets…'}</h2><p>{status}</p>{ready&&!failed&&<button className="bin-gold" onClick={()=>engine.current?.lock()}>Walk the streets</button>}<p className="fp-control-help">W A S D · Move &nbsp; Mouse · Look<br/>Shift · Run &nbsp; E · Interact &nbsp; Esc · Release cursor<br/>On mobile: left pad to move, drag the right side to look.</p>{failed&&<button className="bin-gold" onClick={props.close}>Return to aerial map</button>}</div>}
 {ready&&locked&&!overview&&<div className="fp-touch"><div className="fp-look" aria-label="Drag to look" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);lookOrigin.current={x:e.clientX,y:e.clientY};}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId)){engine.current?.look(e.clientX-lookOrigin.current.x,e.clientY-lookOrigin.current.y);lookOrigin.current={x:e.clientX,y:e.clientY};}}}/><div className="fp-stick" aria-label="Movement pad" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);touchOrigin.current={x:e.clientX,y:e.clientY};}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))engine.current?.touch(Math.max(-1,Math.min(1,(e.clientX-touchOrigin.current.x)/34)),Math.max(-1,Math.min(1,(e.clientY-touchOrigin.current.y)/34)));}} onPointerUp={()=>engine.current?.touch(0,0)} onPointerCancel={()=>engine.current?.touch(0,0)}><span>MOVE</span></div></div>}
 <div className={'fp-objective'+(pursuit?' wanted':'')}><span className="eyebrow">{pursuit?'POLICE PURSUIT':pending?'KEEP WATCH':target?'WITHIN REACH':'EXPLORE THE DISTRICT'}</span><h3>{pursuit?'Break away from the patrols.':pending?wait?`Searching · ${wait}s`:'Search complete':target?target.vehicle?.name??(target.kind==='car'?'Parked car':'Street bin'):nearEvent?eventNames[event.kind]:'The next opportunity is around the corner.'}</h3><p>{pursuit?`${Math.max(0,Math.ceil((Date.parse(pursuit.deadline)-props.now)/1000))}s until the cordon closes. Find the district exit.`:pending?'Moving away abandons your search.':restock?'Already searched. Try another location.':props.cooldown?`Next search in ${props.cooldown}s.`:target?target.kind==='car'?`${props.lockpicks} lockpicks carried. A theft starts a pursuit.`:'Press E or search below. Watch for police.':'Walk to a bin, parked car or street event. Ordinary walking is safe.'}</p>
 <div className="fp-actions">{pursuit?<><button className="bin-gold" disabled={disabled||!exit} onClick={()=>void run('scav_escape')}>{pursuit.vehicle_id?'Escape with vehicle':'Leave the district'}</button><button disabled={disabled||!ops?.weapon||ops.weapon.ammo<(pursuit.rules.scavenging_combat_bullets??3)||props.now<Date.parse(pursuit.next_shot_at)} onClick={()=>void run('scav_fight')}>Return fire · {pursuit.rules.scavenging_combat_bullets} rounds</button><button disabled={disabled} onClick={()=>void run('scav_abandon')}>{pursuit.vehicle_id?'Abandon car':'Surrender'}</button></>:pending?<><button className="bin-gold" disabled={disabled||wait>0} onClick={()=>void run('scav_finish',{attempt_id:pending.id})}>{wait?'Searching…':pending.mode==='theft'?'Start getaway':'Collect find'}</button><button disabled={disabled} onClick={()=>void run('scav_cancel')}>Abandon search</button></>:target?<><button className="bin-gold" disabled={disabled||restock||props.cooldown>0||(target.kind==='car'&&!props.lockpicks)} onClick={()=>void run('scav_search',{target_id:target.id})}>{target.kind==='car'?'Lockpick car':'Search bin'}</button>{target.kind==='car'&&target.vehicle&&<button disabled={disabled||restock||props.cooldown>0||!props.lockpicks} onClick={()=>void run('scav_steal',{target_id:target.id})}>Steal vehicle</button>}</>:nearEvent&&event.kind!=='sweep'?<button className="bin-gold" disabled={disabled||props.cooldown>0} onClick={()=>void run('scav_event',{event_id:event.id})}>Investigate</button>:null}</div>{notice&&<p role="status">{notice}</p>}</div>
 <div className="fp-vitals"><span>HEALTH <b>{Math.ceil(ops?.vitals.health??0)}</b></span><meter aria-label="Street health" min={0} max={ops?.vitals.health_max??100} value={ops?.vitals.health??0}/><span>{ops?.weapon?`${ops.weapon.name} · ${ops.weapon.ammo} rounds`:'No weapon equipped'}</span></div>
 </div></section>;
}
