"use client";
import {useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {PRISON_PATH} from "@/lib/prison";
import {acknowledgedStreetPosition,applyStreetCorrection,beginStreetCorrection,meaningfulDirectionChange,motionActive,predictStreetPosition,predictionDeadline,predictionDeadlineForInput,streetSendInterval,streetSessionPosition} from "@/lib/street-prediction";
import type {StreetQuality} from "@/lib/street-quality";
import {patrolPosition,type ScavengingState,type StreetPosition,type StreetSession} from "@/lib/scavenging";
import {eventNames} from "@/lib/street-operations";
import type {StreetScene,StreetInput} from "./street-scene";
import {createStreetAudio,type StreetAudioEngine} from "@/lib/street-audio";
import {GameIcon} from "./game-icon";
import {StreetEquipment} from "./street-equipment";
import "./first-person-street.css";
type Props={state:ScavengingState;season:string;district:string;now:number;busy:boolean;blocked:boolean;cooldown:number;lockpicks:number;act:(action:string,payload?:Record<string,unknown>)=>Promise<boolean>;close:()=>void};
const still:StreetInput={dx:0,dy:0,sprint:false};
export function FirstPersonStreet(props:Props){
 const acting=useRef(false),audio=useRef<StreetAudioEngine|null>(null);
 const [sound,setSound]=useState(true),[volume,setVolume]=useState(.65);
 useEffect(()=>{let enabled=true,level=.65;try{enabled=localStorage.getItem('blackwater:street-sound')!=='off';const saved=localStorage.getItem('blackwater:street-volume');if(saved!==null&&Number.isFinite(Number(saved)))level=Math.max(0,Math.min(1,Number(saved)));}catch{}setSound(enabled);setVolume(level);const player=createStreetAudio();player.setEnabled(enabled);player.setVolume(level);audio.current=player;return()=>{player.dispose();audio.current=null;};},[]);
 const changeSound=()=>{const enabled=!sound;setSound(enabled);audio.current?.setEnabled(enabled);try{localStorage.setItem('blackwater:street-sound',enabled?'on':'off');}catch{}};
 const changeVolume=(level:number)=>{setVolume(level);audio.current?.setVolume(level);try{localStorage.setItem('blackwater:street-volume',String(level));}catch{}};
 const router=useRouter(),latest=useRef(props);latest.current=props;
 const host=useRef<HTMLDivElement>(null),engine=useRef<StreetScene|null>(null),input=useRef<StreetInput>(still),point=useRef<StreetPosition>(streetSessionPosition(props.state.session!,props.now)),transport=useRef<{stop:()=>Promise<boolean>}|null>(null),interact=useRef<()=>void>(()=>{});
 const [status,setStatus]=useState("Connecting to the street…"),[ready,setReady]=useState(false),[locked,setLocked]=useState(false),[overview,setOverview]=useState(false),[failed,setFailed]=useState(false),[actionBusy,setActionBusy]=useState(false),[p,setP]=useState(point.current),[notice,setNotice]=useState("");
 const [quality,setQuality]=useState<StreetQuality>('auto'),[fullscreen,setFullscreen]=useState(false),[canFullscreen,setCanFullscreen]=useState(false);
 useEffect(()=>{try{const saved=localStorage.getItem('blackwater:street-quality');if(saved==='high'||saved==='performance')setQuality(saved);}catch{}setCanFullscreen(!!document.fullscreenEnabled);const changed=()=>{setFullscreen(document.fullscreenElement===host.current?.closest('.fp-street'));window.dispatchEvent(new Event('resize'));};document.addEventListener('fullscreenchange',changed);return()=>document.removeEventListener('fullscreenchange',changed);},[]);
 const toggleFullscreen=async()=>{engine.current?.unlock();void transport.current?.stop();try{const root=host.current?.closest('.fp-street');if(document.fullscreenElement===root)await document.exitFullscreen();else await root?.requestFullscreen();}catch{setNotice('Full screen is unavailable in this browser. Street view remains ready.');}};
 const ops=props.state.operations,pursuit=ops?.pursuit,pending=props.state.session?.pending,radius=(props.state.settings.scavenging_interaction_radius_percent??8)/100;
 const nearby=props.state.targets.map(t=>({target:t,distance:Math.abs(p[0]-t.node%5)+Math.abs(p[1]-Math.floor(t.node/5))})).sort((a,b)=>a.distance-b.distance)[0];
 const target=nearby&&nearby.distance<=radius?nearby.target:undefined;
 const event=ops?.event,nearEvent=event&&(Math.abs(p[0]-event.node%5)+Math.abs(p[1]-Math.floor(event.node/5)))<=radius;
 const restock=!!target?.ready_at&&Date.parse(target.ready_at)>props.now,wait=pending?Math.max(0,Math.ceil((Date.parse(pending.ready_at)-props.now)/1000)):0;
 const disabled=!ready||props.busy||props.blocked||actionBusy;
 const run=async(action:string,payload:Record<string,unknown>={})=>{if(disabled)return;acting.current=true;setActionBusy(true);setNotice("");try{if(await transport.current?.stop()){const success=await latest.current.act(action,payload);if(success&&action==='scav_fight'){engine.current?.shot();void audio.current?.playConfirmedGunshot();}}}finally{acting.current=false;setActionBusy(false);}};
 interact.current=()=>{if(pending){if(!wait)void run('scav_finish',{attempt_id:pending.id});}else if(!pursuit&&!props.cooldown&&!restock){if(target&&(target.kind==='bin'||props.lockpicks))void run('scav_search',{target_id:target.id});else if(nearEvent&&event.kind!=='sweep')void run('scav_event',{event_id:event.id});}};
 useEffect(()=>{
  if(!host.current)return;let alive=true,inFlight:Promise<boolean>|null=null,sequence=0,active=false,graphicsFailed=false,ui=0,localState=latest.current.state,localTime=latest.current.now,correction:StreetPosition=[0,0],predictionUntil=0,lastFrame=performance.now(),lastDispatch=-Infinity,lastSent:StreetInput=still,dirty=false,wake:ReturnType<typeof setTimeout>|null=null;
  const stops:Array<(value:boolean)=>void>=[],requests=new Set<AbortController>(),heartbeatMs=220;
  const controller=crypto.randomUUID(),client=createClient(),districtId=localState.session!.district_id;
  const lease=()=>Math.max(350,latest.current.state.settings.scavenging_input_lease_ms??500),sendInterval=()=>streetSendInterval(latest.current.state.settings.scavenging_input_rate??360),finishStops=(value:boolean)=>{for(const resolve of stops.splice(0))resolve(value);};
  const snapshot=(data:{server_time:string;session:StreetSession;patrols:ScavengingState['patrols']},sentAt:number,receivedAt:number)=>{if(!alive||!data.session)return;const time=Date.parse(data.server_time),roundTrip=receivedAt-sentAt,actual=acknowledgedStreetPosition(data.session,time,roundTrip),next=!active?{point:actual,remaining:[0,0] as StreetPosition}:beginStreetCorrection(point.current,actual,(latest.current.state.settings.scavenging_foot_road_half_percent??13)/100);point.current=next.point;correction=next.remaining;predictionUntil=predictionDeadline(receivedAt,data.session,time,roundTrip);localState={...latest.current.state,session:data.session,patrols:data.patrols};if(localState.operations&&'pursuit' in data.session)localState={...localState,operations:{...localState.operations,pursuit:(data.session as StreetSession&{pursuit:typeof pursuit}).pursuit??null}};localTime=time+Math.max(0,roundTrip)/2;engine.current?.update(localState,localTime);};
  const send=async(action:'begin'|'step',direction=still):Promise<boolean>=>{
   const request={season_id:latest.current.season,district_id:districtId,controller,...(action==='step'?{sequence:++sequence,...direction}:{})};
   const sentAt=performance.now(),requestAbort=new AbortController(),timeout=setTimeout(()=>requestAbort.abort(),6000);requests.add(requestAbort);
   try{const {data,error}=await client.rpc('street_motion',{p_action:action,p_payload:request}).abortSignal(requestAbort.signal);const receivedAt=performance.now();if(!alive)return false;if(error||data?.error){input.current=still;active=false;predictionUntil=0;finishStops(false);setReady(false);setStatus(data?.error??'Connection interrupted. Return to the map and re-enter street view.');engine.current?.unlock();return false;}if(data?.caught){input.current=still;active=false;predictionUntil=0;finishStops(false);router.replace(PRISON_PATH);return false;}if(data?.pursuit)window.dispatchEvent(new Event('blackwater:game'));snapshot(data,sentAt,receivedAt);return true;}
   catch{if(alive){input.current=still;active=false;predictionUntil=0;finishStops(false);setReady(false);setStatus('Connection interrupted. Return to the map and reconnect.');engine.current?.unlock();}return false;}
   finally{clearTimeout(timeout);requests.delete(requestAbort);}
  };
  function queueMotion(){if(!alive||!active)return;dirty=true;if(inFlight||wake)return;const delay=Math.max(0,sendInterval()-(performance.now()-lastDispatch));wake=setTimeout(dispatchMotion,delay);}
  function dispatchMotion(){wake=null;if(!alive||!active||inFlight)return;dirty=false;const direction={...input.current},sent=performance.now();lastDispatch=sent;lastSent=direction;predictionUntil=Math.max(predictionUntil,sent+lease());const call=send('step',direction);inFlight=call;void call.then(ok=>{if(!ok)finishStops(false);else if(!motionActive(direction))finishStops(true);}).finally(()=>{if(inFlight===call)inFlight=null;if(alive&&active&&(dirty||meaningfulDirectionChange(lastSent,input.current)))queueMotion();});}
  transport.current={stop:()=>{input.current=still;predictionUntil=0;if(!active)return Promise.resolve(false);return new Promise(resolve=>{stops.push(resolve);queueMotion();});}};
  const timer=setInterval(()=>{if(active&&motionActive(input.current))queueMotion();},heartbeatMs);
  const halt=()=>{if(!active)return;const changed=motionActive(input.current);input.current=still;predictionUntil=0;if(changed||motionActive(lastSent))queueMotion();},visibility=()=>{if(document.hidden)halt();};
  window.addEventListener('blur',halt);window.addEventListener('offline',halt);document.addEventListener('visibilitychange',visibility);
  const start=async()=>{try{const {createStreetScene}=await import('./street-scene');if(!alive||!host.current)return;
   engine.current=createStreetScene(host.current,{sound:frame=>audio.current?.update(frame),district:latest.current.district,width:(localState.settings.scavenging_foot_road_half_percent??13)/100,state:localState,now:localTime,interact:()=>interact.current(),locked:value=>{setLocked(value);if(!value)audio.current?.pause();},failed:()=>{graphicsFailed=true;halt();setReady(false);engine.current?.unlock();setFailed(true);setStatus('Your graphics connection was interrupted. The aerial map is still available.');},frame:(direction,dt)=>{
    if(acting.current||!active||graphicsFailed||latest.current.busy||latest.current.blocked||document.hidden)direction=still;
    const stamp=performance.now(),prior=input.current;if(meaningfulDirectionChange(prior,direction)){input.current=direction;predictionUntil=predictionDeadlineForInput(predictionUntil,stamp,lease(),prior,direction);queueMotion();}else input.current=direction;
    const settings=latest.current.state.settings,width=(settings.scavenging_foot_road_half_percent??13)/100;let speed=settings.scavenging_foot_walk_seconds??10;if(direction.sprint)speed*=100/(settings.scavenging_foot_sprint_percent??150);const chase=latest.current.state.operations?.pursuit;if(chase?.vehicle_id)speed=chase.rules.scavenging_getaway_seconds_per_block??2;
    // Prediction is collision checked and ends at the last sent/accepted lease horizon.
    point.current=predictStreetPosition(point.current,direction,lastFrame,stamp,predictionUntil,speed,width);lastFrame=stamp;
    if(Math.hypot(...correction)>.0001){const next=applyStreetCorrection(point.current,correction,dt,width);point.current=next.point;correction=next.remaining;}
    if(stamp-ui>100){ui=stamp;setP([...point.current]);}return point.current;
   }});if(await send('begin')){active=true;setReady(true);setStatus('Walk into Blackwater.');}
  }catch{if(alive){setFailed(true);setStatus('This device could not open the 3D street view. You can continue in the aerial map.');}}};void start();
  return()=>{alive=false;active=false;clearInterval(timer);if(wake)clearTimeout(wake);for(const request of requests)request.abort();requests.clear();window.removeEventListener('blur',halt);window.removeEventListener('offline',halt);document.removeEventListener('visibilitychange',visibility);finishStops(false);input.current=still;const payload={season_id:latest.current.season,district_id:districtId,controller,sequence:++sequence,...still};void client.rpc('street_motion',{p_action:'step',p_payload:payload});engine.current?.dispose();engine.current=null;transport.current=null;window.dispatchEvent(new Event('blackwater:game'));};
 },[props.season,props.state.session?.district_id,router]);
 useEffect(()=>{engine.current?.update(props.state,props.now);},[props.state,props.now]);
 useEffect(()=>{const world=host.current?.parentElement,root=world?.parentElement;if(!world||!root)return;const toolbar=root.querySelector('.fp-toolbar');const resize=()=>{const full=document.fullscreenElement===root,header=full?0:document.querySelector('.estate-header')?.getBoundingClientRect().height??76,bar=toolbar?.getBoundingClientRect().height??68;world.style.height=Math.max(260,window.innerHeight-header-bar-(full?0:20))+'px';};resize();const observer=new ResizeObserver(resize);if(toolbar)observer.observe(toolbar);const frame=requestAnimationFrame(()=>{const header=document.querySelector('.estate-header')?.getBoundingClientRect().height??76;window.scrollTo({top:window.scrollY+root.getBoundingClientRect().top-header-8,behavior:'instant'});});window.addEventListener('resize',resize);return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('resize',resize);};},[]);
 const touchOrigin=useRef({x:0,y:0}),lookOrigin=useRef({x:0,y:0});
 const exit=!!pursuit&&Math.abs(p[0])+Math.abs(p[1])<=radius&&props.now>=Date.parse(pursuit.started_at)+(pursuit.rules.scavenging_escape_min_seconds??6)*1000;
 return <section className="fp-street" aria-label="First-person Scavenging">
 <header className="fp-toolbar"><div><span className="eyebrow">BLACKWATER / STREET VIEW</span><strong>{props.district}</strong></div><div className="fp-tools"><div className="fp-audio"><button aria-label={sound?"Mute street sound":"Enable street sound"} aria-pressed={sound} onClick={changeSound}><GameIcon name={sound?"volume":"volume-off"} size={18}/></button><label>Volume<input aria-label="Street sound volume" type="range" min="0" max="100" value={Math.round(volume*100)} onChange={e=>changeVolume(Number(e.target.value)/100)}/></label></div><label className="fp-quality">Graphics<select aria-label="Street graphics quality" disabled={!ready} value={quality} onChange={e=>{const mode=e.target.value as StreetQuality;setQuality(mode);engine.current?.quality(mode);}}><option value="auto">Auto</option><option value="high">High</option><option value="performance">Performance</option></select></label>{canFullscreen&&<button className="fp-fullscreen" aria-label={fullscreen?"Exit full screen":"Full screen"} onClick={()=>void toggleFullscreen()}><span className="fp-mobile-label" aria-hidden="true">⛶</span><span className="fp-desktop-label">{fullscreen?'Exit full screen':'Full screen'}</span></button>}<button aria-label={overview?"Street view":"Aerial view"} onClick={()=>{const value=!overview;setOverview(value);engine.current?.overview(value);void transport.current?.stop();}} disabled={!ready}><span className="fp-desktop-label">{overview?'Street view':'Aerial view'}</span><span className="fp-mobile-label" aria-hidden="true">{overview?'Street':'Map'}</span></button><button aria-label="Exit street view" onClick={props.close}><span className="fp-desktop-label">Exit street view</span><span className="fp-mobile-label" aria-hidden="true">Exit</span></button></div></header>
 <div className="fp-world"><div className="fp-canvas" ref={host}/><div className="fp-vignette"/>
 <div className="fp-topline"><span>{props.state.streets[Math.max(0,Math.min(2,Math.round(p[1])))]??props.district}</span><span>{pursuit?'WANTED':pending?'SEARCHING':'ON FOOT'}</span></div>
 {!overview&&ready&&<figure className="fp-minimap"><svg viewBox="0 0 148 70" role="img" aria-label="Your district position"><rect x="0" y="0" width="148" height="70" fill="#142429"/>{[0,1,2].map(y=><path key={'h'+y} d={`M10 ${10+y*25}H138`} stroke="#7e867c" strokeWidth="4"/>)}{[0,1,2,3,4].map(x=><path key={'v'+x} d={`M${10+x*32} 10V60`} stroke="#7e867c" strokeWidth="4"/>)}{props.state.targets.map(t=><circle key={t.id} cx={10+t.node%5*32} cy={10+Math.floor(t.node/5)*25} r="1.8" fill={t.ready_at&&Date.parse(t.ready_at)>props.now?'#617277':'#c4a068'}/>)}{(pursuit?.patrols??props.state.patrols??[]).map(patrol=>{const [x,y]=patrolPosition(patrol,props.now);return <circle key={patrol.id} cx={10+x*32} cy={10+y*25} r="2.2" fill="#bd6956"/>;})}<circle cx={10+p[0]*32} cy={10+p[1]*25} r="3.2" fill="#e5d5a9" stroke="#253b35" strokeWidth="1.2"/></svg><figcaption>N ↑ · DISTRICT MAP</figcaption></figure>}
 {!overview&&ready&&locked&&<span className="fp-crosshair" aria-hidden="true">+</span>}
 {(!locked&&!overview||failed)&&<div className="fp-pause"><span className="eyebrow">A CITY OF OPPORTUNITY</span><h2>{failed?'The streets are still open.':ready?'Step into Blackwater.':'Opening the streets…'}</h2><p>{status}</p>{ready&&!failed&&<button className="bin-gold" onClick={()=>{audio.current?.update({moving:false,sprinting:false,pursuit:!!pursuit,locked:true,deltaSeconds:0});void audio.current?.start();engine.current?.lock();}}>Walk the streets</button>}<p className="fp-control-help">W A S D · Move &nbsp; Mouse · Look<br/>Shift · Run &nbsp; E · Interact &nbsp; Esc · Release cursor<br/>On mobile: left pad to move, drag the right side to look.</p>{failed&&<button className="bin-gold" onClick={props.close}>Return to aerial map</button>}</div>}
 {ready&&locked&&!overview&&<div className="fp-touch"><div className="fp-look" aria-label="Drag to look" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);lookOrigin.current={x:e.clientX,y:e.clientY};}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId)){engine.current?.look(e.clientX-lookOrigin.current.x,e.clientY-lookOrigin.current.y);lookOrigin.current={x:e.clientX,y:e.clientY};}}}/><div className="fp-stick" aria-label="Movement pad" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);touchOrigin.current={x:e.clientX,y:e.clientY};}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))engine.current?.touch(Math.max(-1,Math.min(1,(e.clientX-touchOrigin.current.x)/34)),Math.max(-1,Math.min(1,(e.clientY-touchOrigin.current.y)/34)));}} onPointerUp={()=>engine.current?.touch(0,0)} onPointerCancel={()=>engine.current?.touch(0,0)} onLostPointerCapture={()=>engine.current?.touch(0,0)}><span>MOVE</span></div></div>}
 <div className={'fp-objective'+(pursuit?' wanted':!target&&!pending&&!nearEvent?' exploring':'')}><span className="eyebrow">{pursuit?'POLICE PURSUIT':pending?'KEEP WATCH':target?'WITHIN REACH':'EXPLORE THE DISTRICT'}</span><h3>{pursuit?'Break away from the patrols.':pending?wait?`Searching · ${wait}s`:'Search complete':target?target.vehicle?.name??(target.kind==='car'?'Parked car':'Street bin'):nearEvent?eventNames[event.kind]:'The next opportunity is around the corner.'}</h3><p>{pursuit?`${Math.max(0,Math.ceil((Date.parse(pursuit.deadline)-props.now)/1000))}s until the cordon closes. Find the district exit.`:pending?'Moving away abandons your search.':restock?'Already searched. Try another location.':props.cooldown?`Next search in ${props.cooldown}s.`:target?target.kind==='car'?`${props.lockpicks} lockpicks carried. A theft starts a pursuit.`:'Press E or search below. Watch for police.':'Walk to a bin, parked car or street event. Ordinary walking is safe.'}</p>
 <div className="fp-actions">{pursuit?<><button className="bin-gold" disabled={disabled||!exit} onClick={()=>void run('scav_escape')}>{pursuit.vehicle_id?'Escape with vehicle':'Leave the district'}</button><button disabled={disabled||!ops?.weapon||ops.weapon.ammo<(pursuit.rules.scavenging_combat_bullets??3)||props.now<Date.parse(pursuit.next_shot_at)} onClick={()=>void run('scav_fight')}>Return fire · {pursuit.rules.scavenging_combat_bullets} rounds</button><button disabled={disabled} onClick={()=>void run('scav_abandon')}>{pursuit.vehicle_id?'Abandon car':'Surrender'}</button></>:pending?<><button className="bin-gold" disabled={disabled||wait>0} onClick={()=>void run('scav_finish',{attempt_id:pending.id})}>{wait?'Searching…':pending.mode==='theft'?'Start getaway':'Collect find'}</button><button disabled={disabled} onClick={()=>void run('scav_cancel')}>Abandon search</button></>:target?<><button className="bin-gold" disabled={disabled||restock||props.cooldown>0||(target.kind==='car'&&!props.lockpicks)} onClick={()=>void run('scav_search',{target_id:target.id})}>{target.kind==='car'?'Lockpick car':'Search bin'}</button>{target.kind==='car'&&target.vehicle&&<button disabled={disabled||restock||props.cooldown>0||!props.lockpicks} onClick={()=>void run('scav_steal',{target_id:target.id})}>Steal vehicle</button>}</>:nearEvent&&event.kind!=='sweep'?<button className="bin-gold" disabled={disabled||props.cooldown>0} onClick={()=>void run('scav_event',{event_id:event.id})}>Investigate</button>:null}</div>{notice&&<p role="status">{notice}</p>}</div>
 {!overview&&ready&&locked&&<span className="fp-control-hint">WASD · MOVE &nbsp; SHIFT · RUN &nbsp; E · INTERACT</span>}
 {!overview&&ready&&<StreetEquipment pause={()=>{engine.current?.unlock();void transport.current?.stop();}} revision={JSON.stringify([pending?.id,ops?.weapon?.ammo,ops?.weapon?.condition])}/>}
 <div className="fp-vitals"><span>HEALTH <b>{Math.ceil(ops?.vitals.health??0)}</b></span><meter aria-label="Street health" min={0} max={ops?.vitals.health_max??100} value={ops?.vitals.health??0}/><span>{ops?.weapon?`${ops.weapon.name} · ${ops.weapon.ammo} rounds`:'No weapon equipped'}</span></div>
 </div></section>;
}
