"use client";
import {useEffect,useRef,useState,type ReactNode} from "react";
import Link from "next/link";
import {GameIcon} from "@/components/game-icon";
import {PlayerAvatar} from "@/components/player-avatar";
import {useGangs} from "@/components/use-gangs";
import {money} from "@/lib/game";
import type {GangWorkspaceState,GangMember,GangApplication} from "@/lib/gangs";
type Action={kind:string;member?:GangMember;application?:GangApplication};
const number=(n:number)=>Number(n).toLocaleString("en-US");
const date=(s:string)=>new Date(s).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"});
function Panel({title,icon="people",children,extra,className=""}:{title:string;icon?:string;children:ReactNode;extra?:ReactNode;className?:string}){return <section className={"gh-panel "+className}><header><GameIcon name={icon}/><h2>{title}</h2>{extra}</header>{children}</section>;}
function Empty({title,children}:{title:string;children:ReactNode}){return <div className="gh-empty"><GameIcon name="people" size={38}/><h3>{title}</h3><p>{children}</p></div>;}
function Command({action,h,close}:{action:Action;h:ReturnType<typeof useGangs>;close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[original]=useState(h.data),[name,setName]=useState(""),[amount,setAmount]=useState(""),[rank,setRank]=useState(action.member?.rank_id??"associate"),[description,setDescription]=useState(original.selected?.description??""),[recruitment,setRecruitment]=useState(original.selected?.recruiting?"open":"closed");
 useEffect(()=>{dialog.current?.showModal();},[]);
 const kind=action.kind,d=h.data,g=original.selected,bank=kind==="deposit"||kind==="withdraw",n=Number(amount),maximum=Math.min(d.settings.gang_bank_max_transfer,kind==="deposit"?d.player.cash:d.selected?.bank?.balance??0);
 const titles:Record<string,string>={create:"Establish a gang",request_join:"Request to join",cancel_request:"Cancel join request",accept:"Welcome a new member",decline:"Decline join request",rank:"Change member rank",remove:"Remove gang member",leave:"Leave this gang",settings:"Gang settings",deposit:"Deposit gang funds",withdraw:"Withdraw gang funds"};
 const buttons:Record<string,string>={create:"Establish gang",request_join:"Send join request",cancel_request:"Cancel request",accept:"Accept request",decline:"Decline request",rank:"Save rank",remove:"Remove member",leave:"Confirm leave",settings:"Save gang settings",deposit:"Confirm deposit",withdraw:"Confirm withdrawal"};
 const valid=d.playable&&d.season.id===original.season.id&&(!bank||Number.isSafeInteger(n)&&n>0&&n<=maximum)&&(!bank||kind!=="deposit"||d.settings.gang_bank_deposits_enabled===1);
 async function submit(){
  const payload:Record<string,unknown>={season_id:original.season.id,gang_id:g?.id,request_id:crypto.randomUUID()};
  if(bank)payload.amount=n;if(kind==="create")payload.name=name;
  if(kind==="rank"||kind==="remove"){payload.player_id=action.member?.id;payload.version=action.member?.version;payload.rank_id=rank;}
  if(kind==="accept"||kind==="decline")payload.application_id=action.application?.id;
  if(kind==="cancel_request")payload.application_id=g?.application?.id;
  if(kind==="settings")Object.assign(payload,{description,recruitment,version:g?.version});
  if(await h.act({action:kind,payload}))close();
 }
 return <dialog className="command-modal gh-dialog" ref={dialog} onCancel={e=>{if(h.busy)e.preventDefault();else close();}} aria-labelledby="gang-dialog-title">
 <button className="gh-close" aria-label="Close gang action" disabled={h.busy} onClick={close}>×</button><p className="gh-eyebrow">BLACKWATER / {bank?"GANG BANK":"THE FAMILY"}</p><h2 id="gang-dialog-title">{titles[kind]}</h2>
 <form onSubmit={e=>{e.preventDefault();if(valid&&!h.busy)void submit();}}>
 {kind==="create"&&<><p>A name for your crew. A place in the city.</p><label>Gang name<input autoFocus required minLength={3} maxLength={60} value={name} onChange={e=>setName(e.target.value)} disabled={h.busy}/></label><div className="gh-receipt"><span>Founding cost</span><strong>{money(d.settings.district_gang_creation_cost)}</strong></div><p className="gh-help">You become the gang leader. New members must request your approval.</p></>}
 {bank&&<><p>{kind==="deposit"?"Contribute money from your wallet to the family's shared reserve.":"Move gang funds into your wallet. Every member can see this withdrawal."}</p><label>Amount ($)<input autoFocus type="number" inputMode="numeric" required min={1} step={1} max={maximum} value={amount} onChange={e=>setAmount(e.target.value)} disabled={h.busy}/></label><div className="gh-receipt"><span>{money(maximum)} available</span><button type="button" disabled={h.busy||maximum<1} onClick={()=>setAmount(String(maximum))}>Use maximum</button></div><p className="gh-help">No transfer fee. Deposits become gang funds; only the gang leader can withdraw. Funds belong to this season.</p></>}
 {kind==="settings"&&<><label>Gang description<textarea maxLength={300} rows={4} value={description} onChange={e=>setDescription(e.target.value)} disabled={h.busy}/></label><label>Recruitment<select aria-label="Recruitment" value={recruitment} onChange={e=>setRecruitment(e.target.value)} disabled={h.busy}><option value="open">Accept join requests</option><option value="closed">Recruitment closed</option></select></label></>}
 {kind==="rank"&&<><p>Set the role of <strong>{action.member?.name}</strong> within the gang.</p><label>Member rank<select aria-label="Member rank" value={rank} onChange={e=>setRank(e.target.value)} disabled={h.busy}>{d.ranks.filter(r=>r.assignable).map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label><p className="gh-help">Underbosses can review requests and manage lower ranks. Bank withdrawals remain with the gang leader.</p></>}
 {kind==="request_join"&&<p>Ask to join <strong>{g?.name}</strong>. A free automatic Telegram will notify the gang leader. Membership begins only after approval.</p>}
 {kind==="cancel_request"&&<p>Withdraw your pending request to join {g?.name}.</p>}
 {(kind==="accept"||kind==="decline")&&<p>{kind==="accept"?"Welcome":"Decline"} <strong>{action.application?.name}</strong>{kind==="accept"?" as an Associate. They will gain access to the gang panel and future gang Telegrams.":"'s application to join this gang."}</p>}
 {kind==="remove"&&<p>Remove <strong>{action.member?.name}</strong> from {g?.name}. Their access to the gang bank, panel and gang Telegrams ends immediately. Their past contributions stay in the records.</p>}
 {kind==="leave"&&<p>Leave {g?.name}. Your deposits remain in the gang bank, and you will lose access to the member panel and gang Telegrams.</p>}
 {h.notice&&<p className={"gh-notice "+(h.failed?"error":"")} role={h.failed?"alert":"status"}>{h.notice}</p>}
 {h.retry?<button className="gh-gold" type="button" disabled={h.working} onClick={async()=>{if(await h.retryAction())close();}}>Retry safely <GameIcon name="refresh"/></button>:<button className="gh-gold" disabled={!valid||h.busy}>{h.working?"Confirming…":buttons[kind]} <GameIcon name="arrow"/></button>}
 </form></dialog>;
}
export function GangWorkspace({initial,initialTab}:{initial:GangWorkspaceState;initialTab?:string}){
 const h=useGangs(initial),d=h.data,g=d.selected,[tab,setTab]=useState(initialTab??"overview"),[search,setSearch]=useState(""),[memberSearch,setMemberSearch]=useState(""),[action,setAction]=useState<Action|null>(null);
 const tabs=g?.is_member?["overview","members",...(g.can_review?["requests"]:[]),"bank","activity"]:["overview"];
 const active=tabs.includes(tab)?tab:"overview";
 const open=(kind:string,extra:Omit<Action,"kind">={})=>{if(!h.busy)setAction({kind,...extra});};
 const summary=d.directory.find(x=>x.id===g?.id);
 return <div className="gh-page" data-feature="gang-headquarters">
 <div className="gh-topline"><Link href="/dashboard">← Dashboard</Link><span>/ GANGS</span><span>{d.season.name}</span></div>
 <div className="gh-layout"><aside className="gh-registry gh-panel">
 <header><GameIcon name="people"/><h2>The families</h2><span>{d.total}</span></header><p className="gh-registry-intro">Names carry weight.<br/>Loyalty builds an empire.</p>
 {d.my_gang_id&&<Link className="gh-outline gh-my-gang" href={"/gangs?gang="+d.my_gang_id}>My headquarters <GameIcon name="arrow" size={16}/></Link>}
 <label className="gh-search"><GameIcon name="search" size={18}/><input aria-label="Search gangs" placeholder="Find a gang…" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 <div className="gh-gang-list">{d.directory.filter(x=>x.name.toLowerCase().includes(search.toLowerCase())).map(x=><Link className={x.id===g?.id?"selected":""} href={"/gangs?gang="+x.id} key={x.id} aria-current={x.id===g?.id?"page":undefined}><span className="gh-crest">{x.name.slice(0,1)}</span><span><strong>{x.name}</strong><small>#{x.rank} · {x.members} members</small><em>{x.joined?"YOUR GANG":x.recruiting?"REQUESTS OPEN":"RECRUITMENT CLOSED"}</em></span><GameIcon name="arrow" size={15}/></Link>)}</div>
 {!d.directory.length&&<p className="gh-help">No gangs have been established this season.</p>}
 {d.directory.length>0&&!d.directory.some(x=>x.name.toLowerCase().includes(search.toLowerCase()))&&<p className="gh-help">No gangs match this name.</p>}
 {d.total>100&&<p className="gh-help">Showing the top 100 gangs by power.</p>}
 {!d.my_gang_id&&<button className="gh-gold" disabled={h.busy||!d.playable||d.player.cash<d.settings.district_gang_creation_cost} onClick={()=>open("create")}>Establish a gang <GameIcon name="plus" size={17}/></button>}
 {!d.my_gang_id&&<p className="gh-help">Founding cost: {money(d.settings.district_gang_creation_cost)}</p>}
 <div className="gh-registry-foot"><GameIcon name="shield" size={26}/><span>POWER IS EARNED.<br/>LOYALTY IS CHOSEN.</span></div></aside>
 <div className="gh-content">
 <section className="gh-hero"><img src="/art/harbor.webp" alt="" fetchPriority="high"/><div className="gh-hero-copy"><p className="gh-eyebrow">BLACKWATER / {g?.is_member?"GANG HEADQUARTERS":"THE CITY'S FAMILIES"}</p><h1>{g?.name??"An empire needs a family."}</h1><span className="gh-rule"/><p className="gh-motto">{g?.description||"A name is earned. A family is built."}</p><p className="gh-hero-caption">{g?.is_member?g.my_rank+" · "+d.player.name:g?"Stand together. Build influence. Make your mark on Blackwater.":"Find your people, pool your resources, and build your place in the city."}</p>
 <div className="gh-hero-actions">{g?.is_owner&&<button className="gh-outline" disabled={h.busy||!d.playable} onClick={()=>open("settings")}><GameIcon name="gear" size={17}/> Gang settings</button>}{g?.is_member&&<Link className="gh-outline" href="/telegrams"><GameIcon name="mail" size={17}/> Gang Telegrams</Link>}
 {g&&!g.is_member&&!d.my_gang_id&&(g.application?.status==="pending"?<><span className="gh-pending">Join request pending</span><button className="gh-outline" disabled={h.busy||!d.playable} onClick={()=>open("cancel_request")}>Cancel request</button></>:<button className="gh-gold" disabled={h.busy||!d.playable||!g.recruiting} onClick={()=>open("request_join")}>{g.recruiting?"Request to join":"Recruitment closed"} <GameIcon name="arrow" size={17}/></button>)}
 {g&&!g.is_member&&d.my_gang_id&&<Link className="gh-outline" href={"/gangs?gang="+d.my_gang_id}>Return to your gang <GameIcon name="arrow" size={17}/></Link>}
 </div></div><div className="gh-hero-seal"><GameIcon name="people" size={48}/><span>TRUST. CAPITAL. CONTROL.</span></div></section>
 {!d.playable&&<p className="gh-notice">The season is closed. Gang actions resume when a season opens.</p>}
 {h.notice&&!action&&<div className={"gh-notice "+(h.failed?"error":"")} role={h.failed?"alert":"status"}>{h.notice}</div>}
 {g?<><div className="gh-stats"><div><GameIcon name="people"/><span>Members<strong>{g.member_count} <small>/ {d.settings.gang_member_limit}</small></strong></span></div><div><GameIcon name="respect"/><span>Gang power<strong>{number(g.respect)}</strong></span></div><div><GameIcon name="trophy"/><span>City standing<strong>{summary?"#"+summary.rank:"—"}</strong></span></div><div><GameIcon name="shield"/><span>Recruitment<strong>{g.recruiting?"By request":"Closed"}</strong></span></div></div>
 <nav className="gh-tabs" aria-label="Gang sections">{tabs.map(t=><button key={t} aria-pressed={active===t} onClick={()=>setTab(t)}>{t==="bank"?"Gang bank":t}{t==="requests"&&g.requests.length>0&&<b>{g.requests.length}</b>}</button>)}<button className="gh-refresh" aria-label="Refresh gang" disabled={h.working||h.reading} onClick={()=>h.refresh()}><GameIcon name="refresh" size={17}/></button></nav>
 {active==="overview"&&<div className="gh-overview">
 <Panel title="The family" extra={<span>{g.is_member?"MEMBER ACCESS":"GANG PROFILE"}</span>}><div className="gh-leader"><PlayerAvatar src={g.leader.avatar_url} name={g.leader.name} size={88}/><div><span className="gh-eyebrow">DON / GANG LEADER</span><Link href={"/players/"+g.leader.id}>{g.leader.name}</Link><p>{g.is_member?"Your rank: "+g.my_rank:"Applications are reviewed by the gang leadership."}</p></div></div><p className="gh-about">{g.description||"This family has yet to write its story."}</p>{g.is_member?<div className="gh-action-row"><button className="gh-outline" onClick={()=>setTab("members")}>View members <GameIcon name="arrow" size={17}/></button>{g.can_review&&<button className="gh-outline" onClick={()=>setTab("requests")}>Join requests · {g.requests.length}</button>}</div>:<p className="gh-help">The gang bank, member panel and activity log are private to members.</p>}</Panel>
 {g.bank?<Panel title="Gang bank" icon="bank" className="gh-bank-summary"><p className="gh-eyebrow">THE FAMILY'S RESERVE</p><strong className="gh-balance">{money(g.bank.balance)}</strong><p>Shared capital. A record of every contribution.</p><button className="gh-gold" disabled={h.busy||!d.playable||d.settings.gang_bank_deposits_enabled!==1||d.player.cash<1} onClick={()=>open("deposit")}>Deposit money <GameIcon name="arrow" size={18}/></button><button className="gh-text-button" onClick={()=>setTab("bank")}>View bank statement →</button></Panel>:<Panel title="District influence" icon="map">{g.territories.length?g.territories.map(t=><Link key={t.slug} className="gh-territory" href={"/districts/"+t.slug}>{t.name}<span>{t.status}</span><GameIcon name="arrow" size={16}/></Link>):<Empty title="Influence starts on the street.">This gang does not currently control a district.</Empty>}</Panel>}
 {g.is_member&&<Panel title="Recent activity" icon="ledger" extra={<button onClick={()=>setTab("activity")}>View all →</button>} className="gh-wide"><Activity events={g.events.slice(0,4)}/></Panel>}
 </div>}
 {active==="members"&&<Panel title="Gang members" extra={<span>{g.members.length} ON THE ROSTER</span>}><div className="gh-member-toolbar"><label className="gh-search"><GameIcon name="search" size={18}/><input aria-label="Search gang members" value={memberSearch} onChange={e=>setMemberSearch(e.target.value)} placeholder="Find a member…"/></label><p>{g.can_manage?"Manage ranks below your position in the family.":"Your gang's people and their standing."}</p></div><div className="gh-members">{g.members.filter(m=>m.name.toLowerCase().includes(memberSearch.toLowerCase())).map(m=><article key={m.id}><PlayerAvatar src={m.avatar_url} name={m.name} size={54}/><div className="gh-member-name"><Link href={"/players/"+m.id}>{m.name}</Link><small><i className={m.online?"online":""}/>{m.online?"Online":"Offline"} · {m.rank_label}</small></div><div className="gh-member-stat"><strong>{number(m.respect)}</strong><small>POWER</small></div><div className="gh-member-actions">{m.can_edit&&<><button className="gh-outline" disabled={h.busy||!d.playable} onClick={()=>open("rank",{member:m})}>Change rank</button><button className="gh-text-button" disabled={h.busy||!d.playable} onClick={()=>open("remove",{member:m})}>Remove</button></>}{m.is_owner&&<span className="gh-rank-badge">GANG LEADER</span>}</div></article>)}</div>
 <details className="gh-rank-guide"><summary>Gang ranks & permissions</summary><p>The Don leads the gang, controls recruitment settings and can withdraw funds. Underbosses can review join requests and manage members below them. Every member can deposit.</p><div>{d.ranks.map(r=><span key={r.id}>{r.label}</span>)}</div></details>{!g.is_owner&&<button className="gh-text-button" disabled={h.busy||!d.playable} onClick={()=>open("leave")}>Leave gang</button>}</Panel>}
 {active==="requests"&&<Panel title="Join requests" icon="mail" extra={<span>{g.requests.length} PENDING</span>}><p className="gh-section-intro">New applications notify the gang leader by Telegram. Approved players join as Associates.</p>{g.requests.length?<div className="gh-applications">{g.requests.map(a=><article key={a.id}><PlayerAvatar src={a.avatar_url} name={a.name} size={58}/><div><Link href={"/players/"+a.player_id}>{a.name}</Link><p>{number(a.respect)} power · Requested {date(a.created_at)}</p></div><div><button className="gh-gold" disabled={h.busy||!d.playable} onClick={()=>open("accept",{application:a})}>Accept</button><button className="gh-outline" disabled={h.busy||!d.playable} onClick={()=>open("decline",{application:a})}>Decline</button></div></article>)}</div>:<Empty title="No one waiting at the door.">New join requests will appear here.</Empty>}</Panel>}
 {active==="bank"&&g.bank&&<div className="gh-bank-layout"><Panel title="Shared bank account" icon="bank" className="gh-bank-summary"><p className="gh-eyebrow">GANG BALANCE</p><strong className="gh-balance">{money(g.bank.balance)}</strong><dl className="gh-facts"><div><dt>Your wallet</dt><dd>{money(d.player.cash)}</dd></div><div><dt>Your deposits</dt><dd>{money(g.bank.my_deposits)}</dd></div><div><dt>Transfer fee</dt><dd>No fee</dd></div><div><dt>Withdrawal authority</dt><dd>Gang leader</dd></div></dl><button className="gh-gold" disabled={h.busy||!d.playable||d.settings.gang_bank_deposits_enabled!==1||d.player.cash<1} onClick={()=>open("deposit")}>Deposit money <GameIcon name="arrow" size={17}/></button>{g.bank.can_withdraw&&<button className="gh-outline" disabled={h.busy||!d.playable||g.bank.balance<1} onClick={()=>open("withdraw")}>Withdraw funds</button>}<p className="gh-help">Deposits belong to the gang. Leaving does not return them. The statement remains in the season's records.</p></Panel><Panel title="Bank statement" icon="ledger" className="gh-statement" extra={<span>THIS SEASON</span>}>{g.bank.history.length?<><div className="gh-table-scroll"><table><thead><tr><th>Member / Date</th><th>Transaction</th><th>Balance</th></tr></thead><tbody>{g.bank.history.map(e=><tr key={e.id}><td><Link href={"/players/"+e.actor_id}>{e.name}</Link><small>{date(e.created_at)} · {new Date(e.created_at).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"UTC"})} UTC</small></td><td className={e.delta>0?"gh-in":"gh-out"}>{e.delta>0?"+":"−"}{money(Math.abs(e.delta))}<small>{e.delta>0?"Deposit":"Withdrawal"}</small></td><td>{money(e.balance_after)}</td></tr>)}</tbody></table></div><div className="gh-pagination"><button disabled={h.reading||g.bank.offset===0} onClick={()=>h.refresh(Math.max(0,g.bank!.offset-10))}>← Previous</button><span>Page {Math.floor(g.bank.offset/10)+1} of {Math.max(1,Math.ceil(g.bank.total/10))}</span><button disabled={h.reading||g.bank.offset+10>=g.bank.total} onClick={()=>h.refresh(g.bank!.offset+10)}>Next →</button></div></>:<Empty title="The reserve starts with you.">The first deposit opens your gang's account.</Empty>}</Panel></div>}
 {active==="activity"&&<Panel title="Gang activity" icon="ledger" extra={<span>LATEST 50 RECORDS</span>}><Activity events={g.events}/></Panel>}
 </>:<Panel title="Find your family"><Empty title="Enter a gang headquarters.">Choose a family from the register to view its profile and request to join, or establish a gang of your own.</Empty><Link className="gh-meet-link" href="/players">Meet the players <GameIcon name="arrow" size={17}/></Link></Panel>}
 <div className="gh-footer"><span>BLACKWATER MAFIA</span><span>ONE FAMILY. A STRONGER TOMORROW.</span></div>
 </div></div>{action&&<Command key={action.kind} action={action} h={h} close={()=>setAction(null)}/>}</div>;
}
function Activity({events}:{events:NonNullable<GangWorkspaceState["selected"]>["events"]}){return events.length?<div className="gh-activity">{events.map(e=><article key={e.id}><GameIcon name={e.kind==="deposit"||e.kind==="withdraw"?"bank":e.kind==="rank"?"shield":"people"}/><div><p>{e.description}</p><small>{date(e.created_at)} · {new Date(e.created_at).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"UTC"})} UTC</small></div><Link href={"/players/"+e.actor_id} aria-label="View acting player"><GameIcon name="arrow" size={16}/></Link></article>)}</div>:<Empty title="Your family's story starts here.">Membership, rank changes and bank transactions will appear as they happen.</Empty>;}
