"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {GameIcon} from "@/components/game-icon";
import {CommodityArtwork} from "@/components/commodity-artwork";
import {useInventory} from "@/components/use-inventory";
import {categoryNames,countGood,storeReady,equipmentSlots,kg,carryRoom,type Gear,type InventoryGood,type InventoryState} from "@/lib/inventory";
import {money} from "@/lib/game";
type Move={action:"store"|"retrieve";good:InventoryGood;season:string;building?:string;gear?:Gear};
function Transfer({move,h,close}:{move:Move;h:ReturnType<typeof useInventory>;close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[building,setBuilding]=useState(move.building??h.data.stores.find(s=>storeReady(s)&&(move.action==="store"?s.enabled&&!s.listed:countGood(s.contents,move.good.id)>0))?.id??""),[quantity,setQuantity]=useState(String(move.gear?.quantity??1));
 const d=h.data,storing=move.action==="store",eligible=d.stores.filter(s=>storeReady(s)&&(storing?s.enabled&&!s.listed:(move.gear?s.id===move.gear.building_id:s.contents.some(x=>x.good_id===move.good.id&&x.quantity>0))));
 const selected=eligible.find(s=>s.id===building),available=move.gear?.quantity??(storing?countGood(d.carried,move.good.id):countGood(selected?.contents??[],move.good.id));
 const max=Math.max(0,Math.min(available,d.max_transfer,storing?Infinity:move.gear?(d.capacity.used_slots<d.capacity.slots&&d.capacity.used_grams+move.good.weight_grams*move.gear.quantity<=d.capacity.weight_grams?move.gear.quantity:0):carryRoom(d,move.good),storing?Math.max(0,(selected?.capacity??0)-(selected?.used??0)):Infinity)),n=Number(quantity);
 const valid=!!selected&&Number.isSafeInteger(n)&&n>0&&n<=max&&d.playable&&move.season===d.season.id;
 useEffect(()=>{dialog.current?.showModal();},[]);
 return <dialog ref={dialog} className="inv-dialog" aria-labelledby="inventory-move-title" onCancel={e=>{if(h.busy)e.preventDefault();else close();}}><button className="inv-close" aria-label="Close item transfer" disabled={h.busy} onClick={close}>×</button><p className="inv-eyebrow">BLACKWATER / SECURE STORAGE</p><h2 id="inventory-move-title">{storing?"Secure your goods":"Retrieve your goods"}</h2>
 <div className="inv-move-item"><CommodityArtwork goodId={move.good.id} size={88}/><div><strong>{move.good.name}</strong><span>{available.toLocaleString()} available</span></div></div>
 <form onSubmit={async e=>{e.preventDefault();if(valid&&await h.act(move.gear?(storing?"gear_store":"gear_retrieve"):move.action,{item_key:move.gear?"gear:"+move.gear.id:undefined,season_id:move.season,building_id:selected.id,good_id:move.good.id,quantity:n}))close();}}>
 <label>{storing?"Store in":"Retrieve from"}<select aria-label="Storage building" value={selected?.id??""} disabled={h.busy} onChange={e=>setBuilding(e.target.value)}>{eligible.length?eligible.map(s=><option key={s.id} value={s.id}>{s.code} {s.name} · {s.district}</option>):<option value="">No eligible storage</option>}</select></label>
 {selected&&<p className="inv-help">{selected.used.toLocaleString()} / {selected.capacity.toLocaleString()} units in this property.</p>}
 <label>Quantity<input autoFocus type="number" inputMode="numeric" min={1} max={max} step={1} value={quantity} disabled={h.busy||!!move.gear} required onChange={e=>setQuantity(e.target.value)}/></label><div className="inv-amount-tools"><span>{max.toLocaleString()} can be moved</span><button type="button" disabled={h.busy||max<1} onClick={()=>setQuantity(String(max))}>Use maximum</button></div>
 <p className="inv-help">{storing?"Stored goods stay in this property. Retrieve them before trading or using them.":"Retrieved goods return to your carried inventory, ready to trade or use."}</p>
 {h.notice&&<p className={"inv-notice "+(h.failed?"error":"")} role={h.failed?"alert":"status"}>{h.notice}</p>}
 {h.retry?<button type="button" className="inv-gold" disabled={h.working} onClick={async()=>{if(await h.retryAction())close();}}>Retry safely <GameIcon name="refresh" size={17}/></button>:<button className="inv-gold" disabled={h.busy||!valid}>{h.working?"Moving…":storing?"Confirm storage":"Confirm retrieval"}<GameIcon name="arrow" size={17}/></button>}
 </form></dialog>;
}

type BagItem={key:string;good:InventoryGood;quantity:number;gear?:Gear};
type EquipChoice={item:BagItem;slot:string;season:string};
const dragType="application/x-blackwater-item";
function ConfirmEquipment({choice,h,close}:{choice:EquipChoice;h:ReturnType<typeof useInventory>;close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{dialog.current?.showModal();},[]);
 return <dialog ref={dialog} className="inv-dialog" aria-labelledby="inv-equip-title" onCancel={e=>{if(h.busy)e.preventDefault();else close();}}><button className="inv-close" aria-label="Close equipment confirmation" disabled={h.busy} onClick={close}>×</button><p className="inv-eyebrow">YOUR BLACKWATER LOADOUT</p><h2 id="inv-equip-title">Equip {choice.item.good.name}</h2><p>Move this item to {equipmentSlots.find(([id])=>id===choice.slot)?.[1]}. Any item already there returns to your inventory with its condition preserved.</p>{h.notice&&<p role={h.failed?"alert":"status"} className="inv-notice">{h.notice}</p>}<button className="inv-gold" disabled={h.working||choice.season!==h.data.season.id} onClick={async()=>{if(h.retry?await h.retryAction():await h.act("equip",{season_id:choice.season,item_key:choice.item.key,equipment_slot:choice.slot}))close();}}>{h.retry?"Retry safely":"Confirm equipment"}</button></dialog>;
}
function DeliveryCollection({id,h,close}:{id:string;h:ReturnType<typeof useInventory>;close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[quantity,setQuantity]=useState("1"),season=useRef(h.data.season.id);
 useEffect(()=>{dialog.current?.showModal();},[]);
 const row=h.data.deliveries.find(x=>x.id===id),g=h.data.goods.find(g=>g.id===row?.good_id),max=row&&g?Math.min(row.quantity,carryRoom(h.data,g)):0,n=Number(quantity);
 return <dialog ref={dialog} className="inv-dialog" aria-labelledby="delivery-title" onCancel={e=>{if(h.busy)e.preventDefault();else close();}}><button className="inv-close" aria-label="Close delivery collection" disabled={h.busy} onClick={close}>×</button><p className="inv-eyebrow">GOODS OWED TO YOU</p><h2 id="delivery-title">Collect delivery</h2><p>{g?.name} · {row?.quantity.toLocaleString()} waiting. Make room in your carried inventory to collect these goods.</p><label>Quantity<input type="number" min={1} max={max} step={1} value={quantity} onChange={e=>setQuantity(e.target.value)} disabled={h.busy}/></label><p className="inv-help">{max.toLocaleString()} can fit now.</p>{h.notice&&<p role={h.failed?"alert":"status"} className="inv-notice">{h.notice}</p>}<button className="inv-gold" disabled={h.working||(!h.retry&&(!Number.isSafeInteger(n)||n<1||n>max||season.current!==h.data.season.id))} onClick={async()=>{if(h.retry?await h.retryAction():await h.act("claim_delivery",{season_id:season.current,delivery_id:id,quantity:n}))close();}}>{h.retry?"Retry safely":"Collect goods"}</button></dialog>;
}
export function InventoryWorkspace({initial}:{initial:InventoryState}){
 const h=useInventory(initial),d=h.data;
 const [search,setSearch]=useState(""),[category,setCategory]=useState("all"),[scope,setScope]=useState("carried"),[sort,setSort]=useState("manual"),[view,setView]=useState("grid"),[selected,setSelected]=useState(""),[moving,setMoving]=useState(""),[dragging,setDragging]=useState(""),[move,setMove]=useState<Move|null>(null),[equip,setEquip]=useState<EquipChoice|null>(null),[delivery,setDelivery]=useState<string|null>(null);
 const detail=useRef<HTMLElement>(null);
 const secured=d.stores.flatMap(s=>s.contents),carriedTotal=d.carried.reduce((a,x)=>a+x.quantity,0)+d.gear.filter(g=>g.location==="carried").reduce((a,x)=>a+x.quantity,0),securedTotal=secured.reduce((a,x)=>a+x.quantity,0)+d.gear.filter(g=>g.location==="storage").reduce((a,x)=>a+x.quantity,0),committedTotal=d.committed.reduce((a,x)=>a+x.quantity,0);
 const rows=scope==="carried"?d.carried:scope==="stored"?secured:scope==="committed"?d.committed:scope.startsWith("building:")?d.stores.find(s=>s.id===scope.slice(9))?.contents??[]:[...d.carried,...secured,...d.committed];
 const gearItem=(g:Gear):BagItem=>({key:"gear:"+g.id,good:d.goods.find(x=>x.id===g.good_id)!,quantity:g.quantity,gear:g});
 const entries:BagItem[]=[...d.goods.filter(g=>countGood(rows,g.id)>0).map(g=>({key:"good:"+g.id,good:g,quantity:countGood(rows,g.id)})),...d.gear.filter(g=>scope==="all"||scope==="carried"&&g.location==="carried"||scope==="stored"&&g.location==="storage"||scope.startsWith("building:")&&g.building_id===scope.slice(9)).map(gearItem)].filter(x=>x.good);
 const filtered=entries.filter(x=>(category==="all"||x.good.category===category)&&x.good.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==="quantity"?b.quantity-a.quantity:sort==="name"?a.good.name.localeCompare(b.good.name):0);
 const chosen=filtered.find(x=>x.key===selected)??(selected.startsWith("gear:")&&d.gear.some(g=>"gear:"+g.id===selected&&g.location==="equipped")?gearItem(d.gear.find(g=>"gear:"+g.id===selected)!):filtered[0]);
 const good=chosen?.good,inHand=good?countGood(d.carried,good.id):0,inStore=good?countGood(secured,good.id):0,inUse=good?countGood(d.committed,good.id):0;
 const fixedSlots=scope==="carried"&&view==="grid"&&sort==="manual";
 const canStore=d.stores.some(s=>storeReady(s)&&s.enabled&&!s.listed&&s.used<s.capacity);
 const setLocation=(v:string)=>{setScope(v);setSelected("");setMoving("");};
 const choose=(x:BagItem)=>{setSelected(x.key);if(window.innerWidth<850&&!moving)detail.current?.scrollIntoView({behavior:"smooth",block:"start"});};
 const open=(action:"store"|"retrieve",building?:string)=>{if(good&&chosen&&!h.busy){h.clear();setMove({action,good,season:d.season.id,building:chosen.gear?.building_id??building,gear:chosen.gear});}};
 const known=(key:string)=>d.layout.some(x=>x.item_key===key)||d.gear.some(g=>"gear:"+g.id===key&&g.location==="equipped");
 const moveTo=async(key:string,position:number)=>{if(h.busy||!d.playable||!known(key))return;const g=d.gear.find(g=>"gear:"+g.id===key);if(await h.act(g?.location==="equipped"?"unequip":"move",{season_id:d.season.id,item_key:key,position,version:d.version})){setMoving("");setDragging("");}};
 const equipTo=async(key:string,slot:string)=>{if(h.busy||!d.playable||!known(key))return;if(await h.act("equip",{season_id:d.season.id,item_key:key,equipment_slot:slot})){setMoving("");setDragging("");}};
 const dragStart=(e:React.DragEvent,key:string)=>{e.dataTransfer.setData(dragType,key);e.dataTransfer.effectAllowed="move";setDragging(key);};
 const dropSlot=(e:React.DragEvent,n:number)=>{e.preventDefault();const key=e.dataTransfer.getData(dragType);setDragging("");void moveTo(key,n);};
 const card=(x:BagItem,n?:number)=><button className={"inv-item "+(chosen?.key===x.key?"selected":"")+(moving===x.key?" moving":"")} aria-label={x.good.name+", "+x.quantity.toLocaleString()+" units"+(x.gear?", individual equipment":"")} aria-pressed={chosen?.key===x.key} draggable={scope==="carried"&&!h.busy&&d.playable} onDragStart={e=>dragStart(e,x.key)} onDragEnd={()=>setDragging("")} onClick={()=>moving&&n?void moveTo(moving,n):choose(x)}><div className="inv-item-art">{n&&<span className="inv-slot-number">{String(n).padStart(2,"0")}</span>}<CommodityArtwork goodId={x.good.id} size={145}/><strong>×{x.quantity.toLocaleString()}</strong></div><div className="inv-item-copy"><h3>{x.good.name}</h3><span>{categoryNames[x.good.category]??x.good.category}</span><small>{kg(x.quantity*x.good.weight_grams)}{x.gear?.condition!==null&&x.gear?.condition!==undefined?" · Condition "+x.gear.condition:""}</small></div></button>;
 const over=d.capacity.used_grams>d.capacity.weight_grams||d.capacity.used_slots>d.capacity.slots;
 return <div className="inv-page inv-loadout-page" data-feature="inventory-loadout">
 <div className="inv-topline"><Link href="/dashboard">← Dashboard</Link><span>/ YOUR INVENTORY</span>{d.management&&<Link href="/owner?section=inventory">Owner inventory controls ↗</Link>}</div>
 <div className="inv-layout"><aside className="inv-sidebar inv-panel"><h2>Inventory</h2><p className="inv-eyebrow">EVERY ASSET. YOUR NEXT MOVE.</p><nav aria-label="Inventory categories"><button aria-pressed={category==="all"} onClick={()=>setCategory("all")}><GameIcon name="overview" size={18}/><span>All items</span><b>{entries.length}</b></button>{Object.entries(categoryNames).filter(([id])=>entries.some(x=>x.good.category===id)).map(([id,label])=><button key={id} aria-pressed={category===id} onClick={()=>setCategory(id)}><GameIcon name={id==="tools"?"pickaxe":id==="blueprints"?"blueprint":"inventory"} size={18}/><span>{label}</span><b>{entries.filter(x=>x.good.category===id).length}</b></button>)}</nav>
 <h3>Where it is</h3><nav aria-label="Inventory locations">{[["carried","Carried",carriedTotal],["stored","Secure storage",securedTotal],["all","All holdings",carriedTotal+securedTotal+committedTotal+d.gear.filter(g=>g.location==="equipped").reduce((a,x)=>a+x.quantity,0)],["committed","In use / listed",committedTotal]].map(([v,label,n])=><button key={v} aria-pressed={scope===v} onClick={()=>setLocation(String(v))}><GameIcon name={v==="stored"?"lock":"inventory"} size={18}/><span>{label}</span><b>{Number(n).toLocaleString()}</b></button>)}</nav><div className="inv-sidebar-art"><img src="/art/harbor.webp" alt="" width={240} height={190}/><p>Goods move.<br/>Power grows.</p><span>THAT’S BLACKWATER.</span></div></aside>
 <section className="inv-workbench"><header className="inv-heading"><div><p className="inv-eyebrow">ASSETS. TOOLS. OPPORTUNITIES.</p><h1>Inventory</h1></div><button className="inv-refresh" disabled={h.reading||h.working} onClick={()=>h.refresh()} aria-label="Refresh inventory"><GameIcon name="refresh" size={19}/></button></header>
 <div className={"inv-carry-capacity "+(over?"over-limit":"")}><div><span><GameIcon name="inventory" size={18}/>Carried slots</span><strong>{d.capacity.used_slots} <small>/ {d.capacity.slots}</small></strong><meter aria-label="Carried slots" min={0} max={Math.max(d.capacity.slots,d.capacity.used_slots)} value={d.capacity.used_slots}/></div><div><span><GameIcon name="weight" size={18}/>Carried weight</span><strong>{kg(d.capacity.used_grams)} <small>/ {kg(d.capacity.weight_grams)}</small></strong><meter aria-label="Carried weight" min={0} max={Math.max(d.capacity.weight_grams,d.capacity.used_grams)} value={d.capacity.used_grams}/></div></div>
 {over&&<p className="inv-notice error" role="status">Your existing items are preserved, but you are over capacity. Store or trade items before receiving more.</p>}
 <div className="inv-toolbar"><label className="inv-search"><GameIcon name="search" size={17}/><input aria-label="Search inventory" placeholder="Search your items…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Sort inventory" value={sort} onChange={e=>setSort(e.target.value)}><option value="manual">Your slot order</option><option value="name">Name</option><option value="quantity">Quantity</option></select><div className="inv-view-toggle"><button aria-label="Grid view" aria-pressed={view==="grid"} onClick={()=>setView("grid")}><GameIcon name="overview" size={18}/></button><button aria-label="List view" aria-pressed={view==="list"} onClick={()=>setView("list")}><GameIcon name="ledger" size={18}/></button></div></div>
 <div className="inv-scope-line"><span>{scope==="carried"?"Carried inventory":scope==="stored"?"Secured in your properties":scope==="committed"?"Committed to the economy":scope==="all"?"All your holdings":"Property contents"}</span><b>{filtered.length} stacks</b></div>
 {h.notice&&!move&&!equip&&!delivery&&<div className={"inv-notice "+(h.failed?"error":"")} role={h.failed?"alert":"status"}>{h.notice}{h.retry&&<button className="inv-outline" disabled={h.working} onClick={()=>h.retryAction()}>Retry safely</button>}</div>}
 {moving?<div className="inv-moving-note" role="status">Choose a carried slot or compatible equipment space.<button onClick={()=>setMoving("")}>Cancel move</button></div>:scope==="carried"&&<p className="inv-move-help">Drag to rearrange or equip. On touch screens, select an item and press Move.</p>}
 {fixedSlots?<div className={"inv-items inv-slot-grid "+(dragging||moving?"accepting-move":"")} aria-label="Carried inventory slots">{Array.from({length:d.capacity.slots},(_,i)=>{const n=i+1,key=d.layout.find(p=>p.position===n)?.item_key,x=filtered.find(x=>x.key===key);return <div className="inv-slot" key={n} data-slot={n} onDragOver={e=>{if(dragging)e.preventDefault();}} onDrop={e=>dropSlot(e,n)}>{x?card(x,n):<button className={"inv-empty-slot "+(key?"filtered":"")} aria-label={"Inventory slot "+n+(key?", filtered item":", empty")} disabled={!moving&&!dragging} onClick={()=>moving&&void moveTo(moving,n)}><span>{String(n).padStart(2,"0")}</span><GameIcon name={key?"inventory":"plus"} size={27}/><small>{key?"Filtered item":"Empty slot"}</small></button>}</div>;})}</div>:filtered.length?<div className={"inv-items "+(view==="list"?"as-list":"")}>{filtered.map(x=><div key={x.key}>{card(x)}</div>)}</div>:<div className="inv-empty"><GameIcon name="inventory" size={42}/><h2>No matching items.</h2><p>Try another location or search, or find something new in Blackwater.</p><Link href="/bin-diving" className="inv-outline">Explore bin diving →</Link></div>}
 {fixedSlots&&filtered.some(x=>!d.layout.some(p=>p.item_key===x.key))&&<section className="inv-overflow"><h2>Over-capacity items</h2><p>These existing items need space. Move them into your property.</p><div className="inv-items">{filtered.filter(x=>!d.layout.some(p=>p.item_key===x.key)).map(x=><div key={x.key}>{card(x)}</div>)}</div></section>}
 <section className="inv-storage-section"><header><div><p className="inv-eyebrow">PUT YOUR FORTUNE UNDER LOCK</p><h2>Your garages & warehouses</h2></div><Link href="/districts">Find property ↗</Link></header><p className="inv-help">Stored goods do not use carried slots or weight. Retrieve them before trading or using them.</p>
 {d.stores.length?<div className="inv-stores">{d.stores.map(s=><button key={s.id} className={"inv-store "+(scope==="building:"+s.id?"selected":"")} onClick={()=>setLocation("building:"+s.id)}><GameIcon name={s.building_type==="garage"?"home":"businesses"} size={32}/><div><strong>{s.code} · {s.name}</strong><span>{s.district}</span><meter aria-label={s.code+" storage capacity"} min={0} max={Math.max(s.capacity,s.used)} value={s.used}/><small>{s.used.toLocaleString()} / {s.capacity.toLocaleString()} units · {s.construction_status!=="ready"?"Under construction":s.locked?"District locked":!s.enabled?"Deposits paused":s.listed?"Listed for sale":"Secure storage"}</small></div></button>)}</div>:<div className="inv-no-storage"><GameIcon name="lock" size={28}/><div><strong>You don’t own a storage building yet.</strong><p>Buy a plot and build a garage or warehouse in the districts. Completed buildings appear here automatically.</p><Link href="/districts">Open the city map →</Link></div></div>}
 {d.stores.filter(s=>s.construction_status!=="ready").map(s=><Link className="inv-build-link" key={s.id} href={"/districts/"+s.district_slug+"?tab=Plots&plot="+s.plot_id}>Manage construction at {s.code} →</Link>)}</section>
 {!!d.deliveries.length&&<section className="inv-storage-section inv-deliveries"><header><h2>Awaiting collection</h2><span>{d.deliveries.length} deliveries</span></header><p className="inv-help">Auction goods and automatic payments stay here when your bag is full. They cannot be used or traded until collected.</p>{d.deliveries.map(x=><div className="inv-delivery" key={x.id}><CommodityArtwork goodId={x.good_id} size={54}/><div><strong>{d.goods.find(g=>g.id===x.good_id)?.name}</strong><span>{x.quantity.toLocaleString()} units · {x.reason}</span></div><button className="inv-outline" disabled={h.busy||!d.playable} onClick={()=>{h.clear();setDelivery(x.id);}}>Collect</button></div>)}</section>}
 </section>
 <aside ref={detail} className="inv-detail"><section className="inv-panel inv-equipment"><header><h2>Equipment</h2><span>YOUR LOADOUT</span></header><div className="inv-loadout-grid inv-equipped" aria-label="Equipment slots">{equipmentSlots.map(([id,label,icon])=>{const g=d.gear.find(g=>g.location==="equipped"&&g.equipment_slot===id),item=g&&gearItem(g);return <button key={id} className={"inv-gear-slot "+(g?"occupied":"")} aria-label={label+(item?": "+item.good.name:", empty")} disabled={h.busy} draggable={!!g&&!h.busy&&d.playable} onDragStart={e=>g&&dragStart(e,"gear:"+g.id)} onDragEnd={()=>setDragging("")} onDragOver={e=>{if(dragging)e.preventDefault();}} onDrop={e=>{e.preventDefault();const key=e.dataTransfer.getData(dragType);setDragging("");void equipTo(key,id);}} onClick={()=>{if(moving)void equipTo(moving,id);else if(item)choose(item);else if(chosen?.good.equipment_slots.includes(id)&&chosen.gear?.location!=="storage"&&(chosen.gear||inHand>0)){h.clear();setEquip({item:chosen,slot:id,season:d.season.id});}}}><span>{label}</span>{item?<><CommodityArtwork goodId={item.good.id} size={91}/><strong>{item.good.name}</strong><small>{item.good.id==="pickaxe"?"Equipped pickaxe · ":""}{g?.condition!==null?"Condition "+g?.condition:kg(item.good.weight_grams*item.quantity)}</small></>:<><GameIcon name={icon} size={48}/><small>Empty</small></>}</button>;})}</div><p className="inv-help">Equipment counts toward your carried weight. Items must fit the selected space.</p><Link href="/districts/mines-and-quarries">Visit Mines & Quarries →</Link></section>
 <section className="inv-panel inv-selected"><header><h2>Item details</h2><span>{good?categoryNames[good.category]:"YOUR HOLDINGS"}</span></header>{good&&chosen?<><div className="inv-detail-art"><CommodityArtwork goodId={good.id} size={260}/></div><h2>{good.name}</h2><p>{good.description||"Part of your Blackwater inventory."}</p><dl>{chosen.gear?<><div><dt>Location</dt><dd>{chosen.gear.location}</dd></div>{chosen.gear.condition!==null&&<div><dt>Condition</dt><dd>{chosen.gear.condition}</dd></div>}<div><dt>Quantity</dt><dd>{chosen.quantity}</dd></div></>:<><div><dt>Carried</dt><dd>{inHand.toLocaleString()}</dd></div><div><dt>In secure storage</dt><dd>{inStore.toLocaleString()}</dd></div><div><dt>In use / listed</dt><dd>{inUse.toLocaleString()}</dd></div></>}<div><dt>Unit weight</dt><dd>{kg(good.weight_grams)}</dd></div><div><dt>Selected stack</dt><dd>{kg(good.weight_grams*chosen.quantity)}</dd></div></dl>
 {!!good.equipment_slots.length&&(chosen.gear?.location==="carried"||!chosen.gear&&inHand>0)&&<div className="inv-equip-actions">{good.equipment_slots.filter(s=>equipmentSlots.some(([id])=>id===s)).map(slot=><button key={slot} className="inv-gold" disabled={h.busy||!d.playable||slot==="utility"&&d.tool.working} onClick={()=>{h.clear();setEquip({item:chosen,slot,season:d.season.id});}}>{good.id==="pickaxe"?"Equip pickaxe":"Equip "+equipmentSlots.find(([id])=>id===slot)?.[1]} <GameIcon name="arrow" size={17}/></button>)}</div>}
 {chosen.gear?.location==="equipped"&&<button className="inv-gold" disabled={h.busy||!d.playable||chosen.gear.equipment_slot==="utility"&&d.tool.working} onClick={()=>h.act("unequip",{season_id:d.season.id,item_key:chosen.key})}>Unequip <GameIcon name="arrow" size={17}/></button>}
 <div className="inv-detail-actions"><button className="inv-outline" disabled={h.busy||!d.playable||chosen.gear?.location==="storage"||!chosen.gear&&inHand<1} onClick={()=>{setMoving(chosen.key);setScope("carried");setCategory("all");setSearch("");setSort("manual");setView("grid");document.querySelector(".inv-workbench")?.scrollIntoView({behavior:"smooth",block:"start"});}}>Move <GameIcon name="move" size={17}/></button><button className="inv-gold" disabled={h.busy||!d.playable||!canStore||chosen.gear?.location==="storage"||!chosen.gear&&inHand<1} onClick={()=>open("store")}>Store <GameIcon name="lock" size={17}/></button></div>
 {(chosen.gear?.location==="storage"||!chosen.gear&&inStore>0)&&<button className="inv-outline inv-full" disabled={h.busy||!d.playable} onClick={()=>open("retrieve",scope.startsWith("building:")?scope.slice(9):undefined)}>Retrieve <GameIcon name="arrow" size={17}/></button>}
 {!chosen.gear&&inHand>0&&<Link className="inv-outline" href={"/market?view=inventory&good="+encodeURIComponent(good.id)}>Trade on the market <GameIcon name="trade" size={17}/></Link>}
 {chosen.gear&&<p className="inv-help">This is individual equipment. Its condition stays with it when you equip, carry or store it.</p>}
 {!chosen.gear&&d.stores.filter(s=>countGood(s.contents,good.id)>0).map(s=><div className="inv-stock-location" key={s.id}><GameIcon name="lock" size={15}/><span>{s.code} {s.name}</span><b>{countGood(s.contents,good.id).toLocaleString()}</b></div>)}
 </>:<div className="inv-empty"><p>Select an item to inspect it, move it or use equipment.</p></div>}</section></aside></div>
 <section className="inv-bottom-grid"><div className="inv-panel inv-recent"><header><h2>Inventory activity</h2><span>THIS SEASON</span></header>{d.history.length?<ul>{d.history.map(e=><li key={e.id}><GameIcon name={e.location==="storage"?"lock":"inventory"} size={18}/><div><strong>{d.goods.find(g=>g.id===e.good_id)?.name??e.good_id}</strong><span>{e.reason}</span></div><b className={e.delta>0?"positive":"negative"}>{e.delta>0?"+":""}{e.delta.toLocaleString()}</b><time dateTime={e.created_at}>{new Date(e.created_at).toLocaleString("en-GB",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"UTC"})} UTC</time></li>)}</ul>:<p className="inv-help">New finds and item movements will appear here.</p>}<div className="inv-pagination"><button disabled={h.reading||d.offset===0} onClick={()=>h.refresh(Math.max(0,d.offset-20))}>← Previous</button><span>Page {Math.floor(d.offset/20)+1} of {Math.max(1,Math.ceil(d.history_total/20))}</span><button disabled={h.reading||d.offset+20>=d.history_total} onClick={()=>h.refresh(d.offset+20)}>Next →</button></div></div><div className="inv-panel inv-wallet"><GameIcon name="bank" size={32}/><p className="inv-eyebrow">CASH & CAPITAL</p><h2>{money(d.cash)}</h2><p>Cash stays in your wallet. Use the National Bank to put money aside.</p><Link className="inv-outline" href="/bank">Open National Bank →</Link><blockquote>“Preparation buys freedom.”</blockquote></div></section>
 {move&&<Transfer move={move} h={h} close={()=>setMove(null)}/>}
 {equip&&<ConfirmEquipment choice={equip} h={h} close={()=>setEquip(null)}/>}
 {delivery&&<DeliveryCollection id={delivery} h={h} close={()=>setDelivery(null)}/>}
 </div>;
}
