"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {GameIcon} from "@/components/game-icon";
import {CommodityArtwork} from "@/components/commodity-artwork";
import {useInventory} from "@/components/use-inventory";
import {categoryNames,countGood,storeReady,type InventoryGood,type InventoryState} from "@/lib/inventory";
import {money} from "@/lib/game";
type Move={action:"store"|"retrieve";good:InventoryGood;season:string;building?:string};
function Transfer({move,h,close}:{move:Move;h:ReturnType<typeof useInventory>;close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[building,setBuilding]=useState(move.building??h.data.stores.find(s=>storeReady(s)&&(move.action==="store"?s.enabled&&!s.listed:countGood(s.contents,move.good.id)>0))?.id??""),[quantity,setQuantity]=useState("1");
 const d=h.data,storing=move.action==="store",eligible=d.stores.filter(s=>storeReady(s)&&(storing?s.enabled&&!s.listed:s.contents.some(x=>x.good_id===move.good.id&&x.quantity>0)));
 const selected=eligible.find(s=>s.id===building),available=storing?countGood(d.carried,move.good.id):countGood(selected?.contents??[],move.good.id);
 const max=Math.max(0,Math.min(available,d.max_transfer,storing?Math.max(0,(selected?.capacity??0)-(selected?.used??0)):Infinity)),n=Number(quantity);
 const valid=!!selected&&Number.isSafeInteger(n)&&n>0&&n<=max&&d.playable&&move.season===d.season.id;
 useEffect(()=>{dialog.current?.showModal();},[]);
 return <dialog ref={dialog} className="inv-dialog" aria-labelledby="inventory-move-title" onCancel={e=>{if(h.busy)e.preventDefault();else close();}}><button className="inv-close" aria-label="Close item transfer" disabled={h.busy} onClick={close}>×</button><p className="inv-eyebrow">BLACKWATER / SECURE STORAGE</p><h2 id="inventory-move-title">{storing?"Secure your goods":"Retrieve your goods"}</h2>
 <div className="inv-move-item"><CommodityArtwork goodId={move.good.id} size={88}/><div><strong>{move.good.name}</strong><span>{available.toLocaleString()} available</span></div></div>
 <form onSubmit={async e=>{e.preventDefault();if(valid&&await h.act(move.action,{season_id:move.season,building_id:selected.id,good_id:move.good.id,quantity:n}))close();}}>
 <label>{storing?"Store in":"Retrieve from"}<select aria-label="Storage building" value={selected?.id??""} disabled={h.busy} onChange={e=>setBuilding(e.target.value)}>{eligible.length?eligible.map(s=><option key={s.id} value={s.id}>{s.code} {s.name} · {s.district}</option>):<option value="">No eligible storage</option>}</select></label>
 {selected&&<p className="inv-help">{selected.used.toLocaleString()} / {selected.capacity.toLocaleString()} units in this property.</p>}
 <label>Quantity<input autoFocus type="number" inputMode="numeric" min={1} max={max} step={1} value={quantity} disabled={h.busy} required onChange={e=>setQuantity(e.target.value)}/></label><div className="inv-amount-tools"><span>{max.toLocaleString()} can be moved</span><button type="button" disabled={h.busy||max<1} onClick={()=>setQuantity(String(max))}>Use maximum</button></div>
 <p className="inv-help">{storing?"Stored goods stay in this property. Retrieve them before trading or using them.":"Retrieved goods return to your carried inventory, ready to trade or use."}</p>
 {h.notice&&<p className={"inv-notice "+(h.failed?"error":"")} role={h.failed?"alert":"status"}>{h.notice}</p>}
 {h.retry?<button type="button" className="inv-gold" disabled={h.working} onClick={async()=>{if(await h.retryAction())close();}}>Retry safely <GameIcon name="refresh" size={17}/></button>:<button className="inv-gold" disabled={h.busy||!valid}>{h.working?"Moving…":storing?"Confirm storage":"Confirm retrieval"}<GameIcon name="arrow" size={17}/></button>}
 </form></dialog>;
}
export function InventoryWorkspace({initial}:{initial:InventoryState}){
 const h=useInventory(initial),d=h.data;
 const [search,setSearch]=useState(""),[category,setCategory]=useState("all"),[scope,setScope]=useState("all"),[sort,setSort]=useState("name"),[view,setView]=useState("grid"),[selected,setSelected]=useState(""),[move,setMove]=useState<Move|null>(null),[equip,setEquip]=useState<string|null>(null);
 const detail=useRef<HTMLElement>(null),equipment=useRef<HTMLDialogElement>(null);
 const secured=d.stores.flatMap(s=>s.contents),carriedTotal=d.carried.reduce((a,x)=>a+x.quantity,0),securedTotal=secured.reduce((a,x)=>a+x.quantity,0),committedTotal=d.committed.reduce((a,x)=>a+x.quantity,0);
 const rows=scope==="carried"?d.carried:scope==="stored"?secured:scope==="committed"?d.committed:scope.startsWith("building:")?d.stores.find(s=>s.id===scope.slice(9))?.contents??[]:[...d.carried,...secured,...d.committed];
 const quantity=(g:InventoryGood)=>countGood(rows,g.id),owned=d.goods.filter(g=>quantity(g)>0);
 const latest=(id:string)=>d.history.find(x=>x.good_id===id)?.id??0;
 const filtered=owned.filter(g=>(category==="all"||g.category===category)&&g.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==="quantity"?quantity(b)-quantity(a):sort==="recent"?latest(b.id)-latest(a.id):a.name.localeCompare(b.name));
 const good=filtered.find(g=>g.id===selected)??filtered[0],inHand=good?countGood(d.carried,good.id):0,inStore=good?countGood(secured,good.id):0,inUse=good?countGood(d.committed,good.id):0;
 const setLocation=(value:string)=>{setScope(value);setSelected("");};
 const open=(action:"store"|"retrieve",building?:string)=>{if(good&&!h.busy){h.clear();setMove({action,good,season:d.season.id,building});}};
 const canStore=d.stores.some(s=>storeReady(s)&&s.enabled&&!s.listed&&s.used<s.capacity);
 const openEquip=()=>{h.clear();setEquip(d.season.id);};
 useEffect(()=>{if(equip)equipment.current?.showModal();},[equip]);
 return <div className="inv-page" data-feature="inventory-storage">
 <div className="inv-topline"><Link href="/dashboard">← Dashboard</Link><span>/ YOUR INVENTORY</span>{d.management&&<Link href="/owner?section=inventory">Owner inventory controls ↗</Link>}</div>
 <div className="inv-layout"><aside className="inv-sidebar inv-panel"><h2>Inventory</h2><p className="inv-eyebrow">EVERY ASSET. YOUR NEXT MOVE.</p><nav aria-label="Inventory categories"><button aria-pressed={category==="all"} onClick={()=>setCategory("all")}><GameIcon name="overview" size={18}/><span>All items</span><b>{owned.length}</b></button>{Object.entries(categoryNames).filter(([id])=>owned.some(g=>g.category===id)).map(([id,label])=><button key={id} aria-pressed={category===id} onClick={()=>setCategory(id)}><GameIcon name={id==="tools"?"pickaxe":id==="blueprints"?"blueprint":"inventory"} size={18}/><span>{label}</span><b>{owned.filter(g=>g.category===id).length}</b></button>)}</nav>
 <h3>Where it is</h3><nav aria-label="Inventory locations">{[["all","All holdings",carriedTotal+securedTotal+committedTotal],["carried","Carried",carriedTotal],["stored","Secure storage",securedTotal],["committed","In use / listed",committedTotal]].map(([value,label,count])=><button key={value} aria-pressed={scope===value} onClick={()=>setLocation(String(value))}><GameIcon name={value==="stored"?"lock":"inventory"} size={18}/><span>{label}</span><b>{Number(count).toLocaleString()}</b></button>)}</nav>
 <div className="inv-sidebar-art"><img src="/art/harbor.webp" alt="" width={240} height={190}/><p>Goods move.<br/>Power grows.</p><span>THAT’S BLACKWATER.</span></div>
 </aside>
 <section className="inv-workbench"><header className="inv-heading"><div><p className="inv-eyebrow">ASSETS. TOOLS. OPPORTUNITIES.</p><h1>Inventory</h1></div><button className="inv-refresh" disabled={h.reading||h.working} onClick={()=>h.refresh()} aria-label="Refresh inventory"><GameIcon name="refresh" size={19}/></button></header>
 <div className="inv-toolbar"><label className="inv-search"><GameIcon name="search" size={17}/><input aria-label="Search inventory" placeholder="Search your items…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Sort inventory" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name</option><option value="quantity">Quantity</option><option value="recent">Recent activity</option></select><div className="inv-view-toggle"><button aria-label="Grid view" aria-pressed={view==="grid"} onClick={()=>setView("grid")}><GameIcon name="overview" size={18}/></button><button aria-label="List view" aria-pressed={view==="list"} onClick={()=>setView("list")}><GameIcon name="ledger" size={18}/></button></div></div>
 <div className="inv-scope-line"><span>{scope==="all"?"Your complete holdings":scope==="carried"?"Carried inventory":scope==="stored"?"Secured in your properties":scope==="committed"?"Committed to the economy":"Property contents"}</span><b>{filtered.length} item types</b></div>
 {h.notice&&!move&&!equip&&<p className={"inv-notice "+(h.failed?"error":"")} role={h.failed?"alert":"status"}>{h.notice}</p>}
 {filtered.length?<div className={"inv-items "+(view==="list"?"as-list":"")}>{filtered.map(g=><button className={"inv-item "+(good?.id===g.id?"selected":"")} key={g.id} aria-label={g.name+", "+quantity(g).toLocaleString()+" units"} aria-pressed={good?.id===g.id} onClick={()=>{setSelected(g.id);if(window.innerWidth<850)detail.current?.scrollIntoView({behavior:"smooth",block:"start"});}}><div className="inv-item-art"><CommodityArtwork goodId={g.id} size={172}/><strong>×{quantity(g).toLocaleString()}</strong></div><div className="inv-item-copy"><h3>{g.name}</h3><span>{categoryNames[g.category]??g.category}</span><small>{countGood(secured,g.id)>0?<><GameIcon name="lock" size={12}/>{countGood(secured,g.id).toLocaleString()} secured</>:countGood(d.carried,g.id)>0?"Carried":"In use / listed"}</small></div></button>)}</div>:<div className="inv-empty"><GameIcon name="inventory" size={42}/><h2>{carriedTotal+securedTotal+committedTotal?"No matching items.":"Your inventory starts here."}</h2><p>{carriedTotal+securedTotal+committedTotal?"Try another category, location or search.":"New finds, purchases and collected production arrive here."}</p><Link className="inv-outline" href="/bin-diving">Explore bin diving <GameIcon name="arrow" size={17}/></Link></div>}
 <section className="inv-storage-section"><header><div><p className="inv-eyebrow">PUT YOUR FORTUNE UNDER LOCK</p><h2>Your garages & warehouses</h2></div><Link href="/districts">Find property ↗</Link></header><p className="inv-help">Move goods into your own completed property for secure storage. Retrieve them before trading or using them.</p>
 {d.stores.length?<div className="inv-stores">{d.stores.map(s=><button key={s.id} className={"inv-store "+(scope==="building:"+s.id?"selected":"")} onClick={()=>setLocation("building:"+s.id)}><GameIcon name={s.building_type==="garage"?"home":"businesses"} size={32}/><div><strong>{s.code} · {s.name}</strong><span>{s.district}</span><meter aria-label={s.code+" storage capacity"} min={0} max={Math.max(s.capacity,s.used)} value={s.used}/><small>{s.used.toLocaleString()} / {s.capacity.toLocaleString()} units · {s.construction_status!=="ready"?"Under construction":s.locked?"District locked":!s.enabled?"Deposits paused":s.listed?"Listed for sale":"Secure storage"}</small></div></button>)}</div>:<div className="inv-no-storage"><GameIcon name="lock" size={28}/><div><strong>You don’t own a storage building yet.</strong><p>Buy a plot and build a garage or warehouse in the districts. Completed buildings appear here automatically.</p><Link href="/districts">Open the city map →</Link></div></div>}
 {d.stores.filter(s=>s.construction_status!=="ready").map(s=><Link className="inv-build-link" key={s.id} href={"/districts/"+s.district_slug+"?tab=Plots&plot="+s.plot_id}>Manage construction at {s.code} →</Link>)}
 </section>
 </section>
 <aside ref={detail} className="inv-detail"><section className="inv-panel inv-equipment"><header><h2>Equipment</h2><span>MINING</span></header><div className="inv-equipped"><CommodityArtwork goodId="pickaxe" size={88}/><div><strong>{d.tool.condition>0?"Equipped pickaxe":"No pickaxe equipped"}</strong><small>{d.tool.condition>0?d.tool.condition.toLocaleString()+" condition remaining":"Equip a carried pickaxe to mine."}</small>{d.tool.condition>0&&<meter aria-label="Equipped pickaxe condition" min={0} max={Math.max(d.tool.maximum,d.tool.condition)} value={d.tool.condition}/>}</div></div><button className="inv-outline" disabled={h.busy||!d.playable||countGood(d.carried,"pickaxe")<1||d.tool.working||d.tool.condition>=d.tool.maximum} onClick={openEquip}>{d.tool.condition>0?"Replace worn pickaxe":"Equip pickaxe"} <GameIcon name="pickaxe" size={17}/></button><Link href="/districts/mines-and-quarries">Visit Mines & Quarries →</Link></section>
 <section className="inv-panel inv-selected"><header><h2>Item details</h2><span>{good?categoryNames[good.category]:"YOUR HOLDINGS"}</span></header>{good?<><div className="inv-detail-art"><CommodityArtwork goodId={good.id} size={260}/></div><h2>{good.name}</h2><p>{good.description||"Part of your Blackwater inventory."}</p><dl><div><dt>Carried</dt><dd>{inHand.toLocaleString()}</dd></div><div><dt>In secure storage</dt><dd>{inStore.toLocaleString()}</dd></div><div><dt>In use / listed</dt><dd>{inUse.toLocaleString()}</dd></div><div><dt>Storage space</dt><dd>1 unit per item</dd></div></dl>
 <div className="inv-detail-actions"><button className="inv-gold" disabled={h.busy||!d.playable||inHand<1||!canStore} onClick={()=>open("store")}>Store <GameIcon name="lock" size={17}/></button><button className="inv-outline" disabled={h.busy||!d.playable||inStore<1} onClick={()=>open("retrieve",scope.startsWith("building:")?scope.slice(9):undefined)}>Retrieve <GameIcon name="arrow" size={17}/></button></div>{inHand>0&&<Link className="inv-outline" href={"/market?view=inventory&good="+encodeURIComponent(good.id)}>Trade on the market <GameIcon name="trade" size={17}/></Link>}
 {d.stores.filter(s=>countGood(s.contents,good.id)>0).map(s=><div className="inv-stock-location" key={s.id}><GameIcon name="lock" size={15}/><span>{s.code} {s.name}</span><b>{countGood(s.contents,good.id).toLocaleString()}</b></div>)}
 {d.committed.filter(x=>x.good_id===good.id).map(x=><Link className="inv-commit-link" key={x.destination} href={x.destination==="market"?"/market?view=mine":"/refineries"}>{x.quantity.toLocaleString()} {x.destination==="market"?"reserved on the market":"loaded as refinery fuel"} ↗</Link>)}
 </>:<div className="inv-empty"><p>Select an item to inspect its locations and actions.</p></div>}</section></aside></div>
 <section className="inv-bottom-grid"><div className="inv-panel inv-recent"><header><h2>Inventory activity</h2><span>THIS SEASON</span></header>{d.history.length?<ul>{d.history.map(e=><li key={e.id}><GameIcon name={e.location==="storage"?"lock":"inventory"} size={18}/><div><strong>{d.goods.find(g=>g.id===e.good_id)?.name??e.good_id}</strong><span>{e.reason}</span></div><b className={e.delta>0?"positive":"negative"}>{e.delta>0?"+":""}{e.delta.toLocaleString()}</b><time dateTime={e.created_at}>{new Date(e.created_at).toLocaleString("en-GB",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"UTC"})} UTC</time></li>)}</ul>:<p className="inv-help">New finds and item movements will appear here.</p>}<div className="inv-pagination"><button disabled={h.reading||d.offset===0} onClick={()=>h.refresh(Math.max(0,d.offset-20))}>← Previous</button><span>Page {Math.floor(d.offset/20)+1} of {Math.max(1,Math.ceil(d.history_total/20))}</span><button disabled={h.reading||d.offset+20>=d.history_total} onClick={()=>h.refresh(d.offset+20)}>Next →</button></div></div>
 <div className="inv-panel inv-wallet"><GameIcon name="bank" size={32}/><p className="inv-eyebrow">CASH & CAPITAL</p><h2>{money(d.cash)}</h2><p>Cash stays in your wallet. Use the National Bank to put money aside.</p><Link className="inv-outline" href="/bank">Open National Bank <GameIcon name="arrow" size={17}/></Link><blockquote>“Preparation buys freedom.”</blockquote></div></section>
 {move&&<Transfer move={move} h={h} close={()=>setMove(null)}/>}
 {equip&&<dialog className="inv-dialog" ref={equipment} aria-labelledby="inv-equip-title" onCancel={e=>{if(h.busy)e.preventDefault();else setEquip(null);}}><button className="inv-close" aria-label="Close equipment confirmation" disabled={h.busy} onClick={()=>setEquip(null)}>×</button><p className="inv-eyebrow">YOUR MINING EQUIPMENT</p><h2 id="inv-equip-title">Equip a pickaxe</h2><p>This consumes one carried pickaxe. Replacing a worn pickaxe discards its remaining condition.</p>{h.notice&&<p className={"inv-notice "+(h.failed?"error":"")} role={h.failed?"alert":"status"}>{h.notice}</p>}<button className="inv-gold" disabled={h.working||(!h.retry&&equip!==d.season.id)} onClick={async()=>{if(h.retry?await h.retryAction():await h.act("equip",{season_id:equip},"bin_diving_action"))setEquip(null);}}>{h.retry?"Retry safely":"Confirm equipment"} <GameIcon name="pickaxe" size={18}/></button></dialog>}
 </div>;
}
