"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {MarketPagination} from "./market-pagination";
type History={good_id:string;total:number;units:number;average:number|null;low:number|null;high:number|null;recent:{source_id:string;source_kind:string;quantity:number;total:number;unit_price:number;created_at:string}[];daily:{day:string;units:number;average:number}[]};
const price=(n:number|null)=>n===null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(n);
export function MarketPriceHistory({good,goods,onSelect}:{good:string;goods:{id:string;name:string}[];onSelect:(id:string)=>void}){
 const [page,setPage]=useState(0),[data,setData]=useState<History|null>(null),[error,setError]=useState(""),[version,setVersion]=useState(0);
 useEffect(()=>{let active=true;setData(null);setError("");void(async()=>{try{const r=await createClient().rpc("market_price_history",{p_good:good,p_offset:page*10});if(r.error||!r.data)throw new Error("Price history could not load. Try again.");if(active)setData(r.data);}catch(e){if(active)setError(e instanceof Error?e.message:"Price history could not load.");}})();return()=>{active=false;};},[good,page,version]);
 const max=Math.max(1,...(data?.daily.map(d=>d.average)??[]));
 return <section className="command-panel price-history" aria-label="Market price history"><div className="command-panel-head"><h2>Market price history</h2><button className="command-more" onClick={()=>setVersion(v=>v+1)}>Refresh history</button></div><p className="market-help">Completed trades across Blackwater · current season · last 30 days. Unit prices include the seller fee. Averages are weighted by units sold.</p><label className="history-select">History item<select value={good} onChange={e=>{setPage(0);onSelect(e.target.value);}}>{goods.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>
 {error?<p role="alert">{error} <button className="market-outline" onClick={()=>setVersion(v=>v+1)}>Try again</button></p>:!data?<p role="status">Loading completed trades…</p>:<><dl className="history-stats">{[["Average / unit",price(data.average)],["Lowest / unit",price(data.low)],["Highest / unit",price(data.high)],["Units traded",data.units.toLocaleString("en-US")]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{data.total===0?<div className="market-empty"><h3>No completed trades recorded.</h3><p>Sales will appear here once players trade this item.</p></div>:<><h3>Daily average unit price</h3><div className="history-trend" aria-label="Daily average prices in UTC">{data.daily.map(d=><div key={d.day} className="history-day" title={d.day+": "+price(d.average)+" per unit · "+d.units+" units"}><span className="history-bar" style={{height:Math.max(3,d.average/max*100)+"%"}}/><span className="sr-only">{d.day}: {price(d.average)} per unit, {d.units} units</span></div>)}</div><p className="market-help">{data.daily[0]?.day} — {data.daily.at(-1)?.day} · UTC · days with sales</p><h3>Recent completed trades</h3><div className="history-table-wrap"><table className="history-table"><thead><tr><th>Date (UTC)</th><th>Sale</th><th>Units</th><th>Per unit</th><th>Total</th></tr></thead><tbody>{data.recent.map(t=><tr key={t.source_kind+":"+t.source_id}><td><time dateTime={t.created_at}>{new Date(t.created_at).toLocaleString("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"UTC"})}</time></td><td>{t.source_kind==="auction"?"Auction":t.source_kind==="order"?"Buy order":"Fixed price"}</td><td>{t.quantity}</td><td>{price(t.unit_price)}</td><td>{price(t.total)}</td></tr>)}</tbody></table></div><MarketPagination page={page} total={data.total} onPage={setPage} label="Price history"/></>}<p className="market-help">History includes recorded district sales and settled auctions. Older city-only sales without a completion date are excluded.</p></>}
 </section>;
}
