"use client";
import Link from "next/link";
import {useEffect,useState,type ReactNode} from "react";
import {GameIcon} from "./game-icon";
import {CommodityArtwork} from "./commodity-artwork";
import {money,duration,remaining} from "@/lib/game";
import {mineNextBid,mineStatus,type Mine,type MiningState} from "@/lib/mining";
import {useMining,type MiningAction} from "./use-mining";
import {MineAuctionForm} from "./mine-controls";
import "./mining-overhaul.css";

function Panel({title,children,className=""}:{title:string;children:ReactNode;className?:string}){
 return <section className={"command-panel "+className}><header className="command-panel-head"><h2>{title}</h2></header>{children}</section>;
}
function Equipment({data}:{data:MiningState}){
 const condition=data.tool.durability;
 return <Panel title="Your field equipment" className="mine-equipment">
  <div className="mine-equipment-item"><span className="mine-tool-icon"><GameIcon name="pickaxe" size={34}/></span><div><h3>Mining pickaxe</h3><span className={"mine-status "+(condition?"status-open":"")}>{condition?condition+" condition remaining":"Not equipped"}</span></div></div>
  {condition>0?<><div className="mine-meter"><span style={{width:Math.min(100,condition/data.settings.mining_pickaxe_durability*100)+"%"}}/></div><p>Use your pickaxe at public sites. Each shift wears down its condition.</p></>:<p>You’ll need to find a pickaxe before working a public site. Search the bins across Blackwater to find equipment.</p>}
  <Link className="command-action" href="/bin-diving">Find equipment · Bin Diving →</Link><Link className="command-action" href="/refineries">Refine your ore →</Link><span className="mine-equipment-note"><GameIcon name="lock" size={13}/>Pickaxes are found, never bought.</span>
 </Panel>;
}
function MineBid({site,data,now,busy,act}:{site:Mine;data:MiningState;now:number;busy:boolean;act:MiningAction}){
 const next=mineNextBid(site,data.settings.district_bid_increment),[price,setPrice]=useState(String(next)),a=site.auction!;
 useEffect(()=>setPrice(p=>String(Math.max(Number(p)||0,next))),[next]);
 const total=Number(price)+Math.ceil(Number(price)*a.tax_rate/100),credit=a.bidder_id===data.world.player_id?a.escrow:0;
 return <form className="mine-form mine-bid" onSubmit={e=>{e.preventDefault();void act("bid",{mine_id:site.id,price:Number(price)});}}>
  <span className="eyebrow">EXTRACTION RIGHTS AUCTION</span><h3>{money(a.bid||a.minimum_bid)}</h3><p>{a.bidder_name?"Leading: "+a.bidder_name:"Opening bid"} · {remaining(a.ends_at,now)>0?duration(remaining(a.ends_at,now))+" remaining":"Awaiting settlement"}</p>
  <p>Seasonal title · {site.remaining.toLocaleString("en-US")} resource units · {site.access_mode} access</p>
  {remaining(a.ends_at,now)<=0?<button type="button" className="market-gold" disabled={busy||!data.playable} onClick={()=>void act("settle",{mine_id:site.id})}>Settle auction</button>:site.owner_id===data.world.player_id&&site.owner_type==="player"?<p>Your property is on auction.</p>:<>
   <label>Your bid for the mine ($)<input required type="number" min={next} step="1" value={price} onChange={e=>setPrice(e.target.value)}/></label>
   <dl className="mine-facts"><div><dt>Buyer tax · {a.tax_rate}%</dt><dd>{money(total-Number(price))}</dd></div><div><dt>Additional cash reserved</dt><dd>{money(Math.max(0,total-credit))}</dd></div></dl>
   <p>Outbid funds return automatically. The winner receives the mine and its remaining reserves.</p><button className="market-gold" disabled={busy||!data.playable||total-credit>data.world.cash}>Confirm mine bid</button>
  </>}
 </form>;
}
function MineDetails({site,data,now,busy,act,onClose}:{site:Mine;data:MiningState;now:number;busy:boolean;act:MiningAction;onClose:()=>void}){
 const own=site.owner_type==="player"&&site.owner_id===data.world.player_id,accessible=site.access_mode==="public"||own;
 const shift=data.shift?.mine_id===site.id?data.shift:null;
 return <div className="mine-detail-content">
  <div className="mine-detail-art"><img src={site.image_url} alt={site.name} width={640} height={853}/><button aria-label="Close mine details" className="mine-close" onClick={onClose}>×</button><span className={"mine-status status-"+(site.auction?"auction":site.status)}>{mineStatus(site)}</span></div>
  <header className="mine-detail-heading"><span className="eyebrow">{site.code} / EXTRACTION REGISTRY</span><h2>{site.name}</h2></header>
  <div className="mine-resource-preview"><CommodityArtwork goodId={site.good_id} size={86}/><div><span className="eyebrow">RESOURCE DEPOSIT</span><h3>{site.good_name}</h3><strong>{site.remaining.toLocaleString("en-US")} <small>units remaining</small></strong></div></div>
  <div className="mine-meter" aria-label="Remaining deposit"><span style={{width:Math.min(100,site.remaining/Math.max(1,site.initial_reserve)*100)+"%"}}/></div>
  <dl className="mine-facts"><div><dt>Registered owner</dt><dd>{own?"You":site.owner_name}</dd></div><div><dt>Access</dt><dd>{site.access_mode==="public"?"Public · pickaxe required":"Property owner only"}</dd></div></dl>
  {site.auction?<MineBid key={site.auction.id} site={site} data={data} now={now} busy={busy} act={act}/>:<>
   {accessible&&site.status==="open"&&site.remaining>0&&<div className="mine-public-action"><h3>Work the seam</h3><div className="mine-shift-terms"><span><strong>{site.hand_yield}</strong>units / shift</span><span><strong>{duration(site.hand_seconds)}</strong>shift time</span><span><strong>{site.tool_wear}</strong>tool wear</span><span className="mine-xp-reward"><strong>+{site.hand_yield*data.settings.mining_skill_xp_per_ore}</strong>Mining XP</span></div>
    {shift?<button className="market-gold" disabled={busy||!data.playable||remaining(shift.ready_at,now)>0} onClick={()=>void act("claim",{mine_id:site.id,run_id:shift.id})}>{remaining(shift.ready_at,now)>0?"Shift running · "+duration(remaining(shift.ready_at,now)):"Collect this shift"}</button>:data.tool.durability<site.tool_wear?<div className="mine-tool-required"><GameIcon name="pickaxe" size={23}/><div><strong>Pickaxe required</strong><p>{data.tool.durability?"Your pickaxe is too worn for this seam. ":""}Find a spare by bin diving. Pickaxes cannot be purchased.</p></div></div>:<button className="market-gold" disabled={busy||!data.playable||!!data.shift} onClick={()=>void act("start",{mine_id:site.id})}>{data.shift?"Finish your current shift first":"Start mining shift"}</button>}
   </div>}
   {own&&<div className="mine-operation"><h3>Your extraction operation</h3><p>{site.operation_yield} units every {duration(site.operation_seconds)} · +{site.operation_yield*data.settings.mining_skill_xp_per_ore} Mining XP per cycle · up to {data.settings.mining_offline_cycles} cycles offline.</p><button className="market-gold" disabled={busy||!data.playable||site.status!=="open"||site.ready_output<1} onClick={()=>void act("collect",{mine_id:site.id})}>Collect {site.ready_output.toLocaleString("en-US")} resources</button><details><summary>Sell extraction rights</summary><MineAuctionForm site={site} data={data} busy={busy} act={act}/></details></div>}
   {!own&&site.access_mode==="private"&&<p className="mine-help">Private extraction rights. Watch for an auction to acquire this site.</p>}
   {site.status!=="open"&&<p className="mine-help">{site.status==="reserved"?"This claim is reserved for a future release.":"This site is closed. The city Owner controls when it opens."}</p>}
  </>}
  <details className="mine-site-file"><summary>Site information <GameIcon name="arrow" size={12}/></summary><p>{site.description}</p><dl className="mine-facts"><div><dt>Survey</dt><dd>{site.survey_status}</dd></div><div><dt>Transport</dt><dd>{site.transport}</dd></div><div><dt>Property tax</dt><dd>{site.tax_rate}%</dd></div></dl></details>
  <div className="mine-detail-links"><Link className="market-outline" href={"/market?good="+site.good_id+"&district="+site.district_id}>Trade {site.good_name.toLowerCase()} <GameIcon name="arrow" size={14}/></Link>{data.can_manage&&<Link className="market-outline" href={"/owner?section=mines&mine="+site.id}>Owner site controls <GameIcon name="gear" size={14}/></Link>}</div>
 </div>;
}

function Shift({data,now,busy,act}:{data:MiningState;now:number;busy:boolean;act:MiningAction}){
 const s=data.shift;if(!s)return null;
 const left=remaining(s.ready_at,now),total=Math.max(1,Date.parse(s.ready_at)-Date.parse(s.started_at));
 const progress=Math.max(0,Math.min(100,100*(now-Date.parse(s.started_at))/total));
 return <section className="mine-shift command-panel" aria-label="Your mining shift"><CommodityArtwork goodId={s.good_id} size={64}/><div className="mine-shift-copy"><span className="eyebrow">{s.code} / {left>0?"SHIFT IN PROGRESS":"READY TO COLLECT"}</span><h2>{s.mine_name}</h2><p>{s.quantity} {s.good_name.toLowerCase()} · +{s.quantity*data.settings.mining_skill_xp_per_ore} Mining XP</p><div className="mine-meter" role="progressbar" aria-label="Mining shift progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress)}><span style={{width:progress+"%"}}/></div></div><strong className="mine-shift-clock">{left>0?duration(left):"Ready"}</strong><button className="market-gold" disabled={busy||!data.playable||left>0} onClick={()=>void act("claim",{mine_id:s.mine_id,run_id:s.id})}>Collect mined resources</button><button className="market-outline" disabled={busy||!data.playable} onClick={()=>void act("cancel",{mine_id:s.mine_id,run_id:s.id})}>Cancel shift</button></section>;
}
export function MiningDistrict({initial}:{initial:MiningState}){
 const mining=useMining(initial),{data,now,busy,notice,failed,retry,act}=mining;
 const [selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState("all"),[goodFilter,setGoodFilter]=useState("all"),[search,setSearch]=useState(""),[view,setView]=useState("sites"),[sort,setSort]=useState("code");
 useEffect(()=>{const read=()=>setSelected(new URLSearchParams(location.search).get("mine"));read();window.addEventListener("popstate",read);return()=>window.removeEventListener("popstate",read);},[]);
 const select=(id:string|null)=>{setSelected(id);const u=new URL(location.href);u.hash="";if(id)u.searchParams.set("mine",id);else u.searchParams.delete("mine");history.pushState(null,"",u);window.scrollTo({top:0,behavior:"instant"});};
 if(!data)return null;
 const d=data.world.district,sites=data.sites,site=sites.find(m=>m.id===selected);
 const owns=(m:Mine)=>m.owner_type==="player"&&m.owner_id===data.world.player_id;
 const publicSites=sites.filter(m=>m.status==="open"&&m.access_mode==="public"&&!m.auction&&m.remaining>0);
 const ores=Array.from(new Map(sites.map(m=>[m.good_id,{id:m.good_id,name:m.good_name}])).values());
 const shown=sites.filter(m=>(filter==="all"||filter==="public"&&publicSites.includes(m)||filter==="auction"&&!!m.auction||filter==="mine"&&owns(m)||filter==="reserved"&&m.status==="reserved")&&(goodFilter==="all"||m.good_id===goodFilter)&&[m.name,m.code,m.good_name,m.owner_name].join(" ").toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==="reserves"?b.remaining-a.remaining:sort==="output"?b.output_today-a.output_today:a.code.localeCompare(b.code));
 const reset=()=>{setGoodFilter("all");setFilter("all");setSearch("");};
 const close=()=>select(null);
 const totals=[["mountain","SITES",sites.length],["pickaxe","PUBLIC SITES",publicSites.length],["auction","AUCTIONS",sites.filter(m=>m.auction).length],["lock","YOUR MINES",sites.filter(owns).length],["pickaxe","MINING XP",data.mining_skill_xp]] as const;
 const status=<>{notice&&<div className={"mine-notice "+(failed?"error":"")} role={failed?"alert":"status"}>{notice}{retry&&<button className="market-outline" disabled={mining.working} onClick={()=>void mining.retryAction()}>Retry same request</button>}</div>}{!data.playable&&<p className="mine-notice">Mining is paused while this season is closed.</p>}</>;
 const shift=<Shift data={data} now={now} busy={busy} act={act}/>;
 const activity=(plot?:string)=>{const events=data.world.events.filter(e=>!plot||e.plot_id===plot);return <Panel title={plot?"Site activity":"District activity"} className="mine-event-panel">{events.length?<ol className="mine-history">{events.map(e=><li key={e.id}><GameIcon name={e.category==="property"?"auction":"pickaxe"} size={20}/><div><strong>{e.description}</strong><time dateTime={e.created_at}>{new Date(e.created_at).toLocaleString()}</time>{e.actor_id&&<Link href={"/players/"+e.actor_id}>{e.actor_name}</Link>}</div>{!plot&&sites.some(m=>m.plot_id===e.plot_id)&&<button className="command-more" onClick={()=>{setView("sites");select(sites.find(m=>m.plot_id===e.plot_id)!.id);}}>View site →</button>}</li>)}</ol>:<p className="command-empty">No recent activity recorded here.</p>}</Panel>;};
 if(site)return <div className="mining-district mining-refined mine-site-view mining-overhaul">
  <header className="mine-site-title"><button className="mine-back market-outline" onClick={close}>← Back to Mines & Quarries</button><div><span className="eyebrow">{site.code} / {d.name}</span><h1>{site.name}</h1><p>{owns(site)?"Your extraction operation":site.owner_name}</p></div><div className="mine-title-actions"><span className={"mine-status status-"+(site.auction?"auction":site.status)}>{mineStatus(site)}</span><button className="market-outline" onClick={mining.refresh} disabled={mining.working}><GameIcon name="refresh" size={16}/>Refresh</button></div></header>
  {status}{shift}
  <nav className="mine-section-links" aria-label="Mine sections"><a href="#mine-operations">Operations</a><a href="#mine-deposit">Deposit report</a><a href="#mine-equipment">Equipment</a><a href="#mine-activity">Site activity</a></nav>
  <div className="mine-site-workspace"><div className="mine-site-main">
   <section className="mine-site-scene command-panel" aria-label="Mine overview"><img src={site.image_url} alt={site.name} width={640} height={853} fetchPriority="high"/><span className="mine-scene-code">{site.code}<small>REGISTERED CLAIM</small></span><div className="mine-site-scene-caption"><span className="eyebrow">BENEATH BLACKWATER</span><h2>{site.good_name}<em>Built from the ground up.</em></h2><p>{site.description}</p><a className="market-gold" href="#mine-operations">{site.auction?"View live auction":"Open extraction controls"}<GameIcon name="arrow" size={18}/></a></div><div className="mine-scene-footer"><span><GameIcon name="rail" size={18}/>{site.transport}</span><span>{site.active_shifts} active shifts</span></div></section>
   <div id="mine-deposit" className="mine-site-metrics"><Panel title="Deposit remaining"><div className="mine-deposit-total"><CommodityArtwork goodId={site.good_id} size={64}/><strong>{site.remaining.toLocaleString("en-US")}<small>resource units</small></strong></div><div className="mine-meter"><span style={{width:Math.max(0,Math.min(100,site.remaining/Math.max(1,site.initial_reserve)*100))+"%"}}/></div><p>{site.survey_status}</p></Panel><Panel title="Site output today"><strong>{site.output_today.toLocaleString("en-US")}<small>units extracted</small></strong><p>Across all extraction at this site.</p></Panel><Panel title="Shift reward"><strong>+{site.hand_yield*data.settings.mining_skill_xp_per_ore}<small>Mining XP / completed shift</small></strong><p>{site.hand_yield} units · {duration(site.hand_seconds)} per shift</p></Panel></div>
   <div id="mine-activity">{activity(site.plot_id)}</div>
  </div><aside className="mine-operation-sidebar"><section id="mine-operations" className="command-panel mine-desktop-details"><div className="mine-operation-label"><GameIcon name={site.auction?"auction":"pickaxe"} size={19}/>{site.auction?"EXTRACTION RIGHTS":"OPERATIONS DESK"}</div><MineDetails site={site} data={data} now={now} busy={busy} act={act} onClose={close}/></section><div id="mine-equipment"><Equipment data={data}/></div></aside></div>
 </div>;
 return <div className="mining-district mining-refined mining-overhaul">
  <header className="mine-masthead"><div><Link className="mine-back" href="/districts"><GameIcon name="arrow" size={14}/>Back to City Map</Link><p className="eyebrow">BLACKWATER / THE NORTHERN CLAIMS</p><h1>{d.name}</h1><p className="mine-tagline">{d.tagline}</p></div><div className="mine-masthead-note"><GameIcon name="mountain" size={42}/><p>Raw materials.<br/><em>Real influence.</em></p><small>Work the seams. Supply the city.</small></div></header>
  <div className="mine-top-stats">{totals.map(([icon,label,value])=><div key={label}><GameIcon name={icon} size={22}/><strong>{value.toLocaleString("en-US")}</strong><span>{label}</span></div>)}</div>
  <nav className="mine-nav" aria-label="Mining sections">{[["sites","Sites & claims"],["activity","District activity"]].map(([id,label])=><button key={id} aria-current={view===id?"page":undefined} onClick={()=>setView(id)}>{label}</button>)}<button className="mine-refresh" onClick={mining.refresh} disabled={mining.working}><GameIcon name="refresh" size={16}/>Refresh</button>{data.can_manage&&<Link href="/owner?section=mines">Owner controls</Link>}</nav>
  {status}{shift}
  {view==="sites"?<div className="mine-registry-layout"><div className="mine-registry-main">
   <section className="mine-resource-strip" aria-label="Mine resources"><header><span className="eyebrow">THE RESOURCE SEAMS</span><h2>Fuel Blackwater's industry.</h2><p>Choose a resource to explore its claims.</p></header><div>{ores.map(g=><button key={g.id} aria-label={"Show "+g.name+" sites"} aria-pressed={goodFilter===g.id} onClick={()=>setGoodFilter(goodFilter===g.id?"all":g.id)}><CommodityArtwork goodId={g.id} size={64}/><span><strong>{g.name}</strong><small>{sites.filter(m=>m.good_id===g.id).length} registered sites</small></span></button>)}</div></section>
   <section className="mine-site-section"><header className="mine-section-head"><div><span className="eyebrow">EXTRACTION REGISTRY</span><h2>Find your next claim.<small>{shown.length} / {sites.length} sites</small></h2></div>{(goodFilter!=="all"||filter!=="all"||search)&&<button className="market-outline" onClick={reset}>Clear filters</button>}</header>
   <div className="mine-registry-filters"><label className="mine-search"><GameIcon name="search" size={18}/><input aria-label="Search mine sites" placeholder="Search a site, resource or owner…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter mine sites" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All sites</option><option value="public">Public mining</option><option value="auction">Live auctions</option><option value="mine">Your mines</option><option value="reserved">Reserved claims</option></select><select aria-label="Sort mine sites" value={sort} onChange={e=>setSort(e.target.value)}><option value="code">Site number</option><option value="reserves">Largest reserves</option><option value="output">Highest output today</option></select></div>
   <div className="mine-cards">{shown.map(m=><button key={m.id} className="mine-card command-panel" onClick={()=>select(m.id)} aria-label={"Open "+m.code+" "+m.name}><div className="mine-card-art"><img src={m.image_url} alt="" width={640} height={853} loading="lazy"/><span className="eyebrow">{m.code}</span><span className={"mine-status status-"+(m.auction?"auction":m.status)}>{mineStatus(m)}</span><CommodityArtwork goodId={m.good_id} size={64}/></div><div className="mine-card-body"><span className="mine-card-resource">{m.good_name}</span><h3>{m.name}</h3><small>{owns(m)?"Your operation":m.owner_name}</small><div className="mine-card-facts"><span>Deposit<strong>{m.remaining.toLocaleString("en-US")} <small>units</small></strong></span><span>{m.auction?"Current bid":"Manual shift"}<strong>{m.auction?money(m.auction.bid||m.auction.minimum_bid):m.hand_yield+" units"}<small>{m.auction?(remaining(m.auction.ends_at,now)>0?duration(remaining(m.auction.ends_at,now))+" left":"Awaiting settlement"):duration(m.hand_seconds)+" · +"+m.hand_yield*data.settings.mining_skill_xp_per_ore+" XP"}</small></strong></span></div><span className="mine-card-link">{m.auction?"View auction":m.status==="reserved"?"Inspect reserved claim":"Enter mining site"}<GameIcon name="arrow" size={18}/></span></div></button>)}</div>
   {!shown.length&&<div className="mine-empty-results"><GameIcon name="search" size={32}/><h3>No matching claims.</h3><p>Try another resource, owner or site status.</p><button className="market-outline" onClick={reset}>Clear filters</button></div>}</section>
  </div><aside className="mine-registry-sidebar"><Equipment data={data}/><Panel title="Mining progression" className="mine-skill-panel"><GameIcon name="pickaxe" size={25}/><strong>{data.mining_skill_xp.toLocaleString("en-US")} <small>XP</small></strong><p>Every collected ore builds your Mining skill.</p><Link className="command-action" href="/skills">View your skills <GameIcon name="arrow" size={16}/></Link></Panel><Panel title="District report" className="mine-district-report"><dl className="mine-facts"><div><dt>Output today</dt><dd>{sites.reduce((n,m)=>n+m.output_today,0).toLocaleString("en-US")} units</dd></div><div><dt>Active shifts</dt><dd>{sites.reduce((n,m)=>n+m.active_shifts,0)}</dd></div><div><dt>Public claims</dt><dd>{publicSites.length}</dd></div><div><dt>Your operations</dt><dd>{sites.filter(owns).length}</dd></div></dl><p>{d.description}</p></Panel></aside></div>:activity()}
 </div>;
}
