"use client";
import Link from "next/link";
import {useEffect,useRef,useState,type ReactNode} from "react";
import {GameIcon} from "./game-icon";
import {CommodityArtwork} from "./commodity-artwork";
import {PanMap} from "./district-map";
import {money,duration,remaining} from "@/lib/game";
import {mineNextBid,mineStatus,type Mine,type MiningState} from "@/lib/mining";
import {useMining,type MiningAction} from "./use-mining";
import {MineAuctionForm} from "./mine-controls";

function Panel({title,children,className=""}:{title:string;children:ReactNode;className?:string}){
 return <section className={"command-panel "+className}><header className="command-panel-head"><h2>{title}</h2></header>{children}</section>;
}
function Equipment({data}:{data:MiningState}){
 const condition=data.tool.durability;
 return <Panel title="Your field equipment" className="mine-equipment">
  <div className="mine-equipment-item"><span className="mine-tool-icon"><GameIcon name="pickaxe" size={34}/></span><div><h3>Mining pickaxe</h3><span className={"mine-status "+(condition?"status-open":"")}>{condition?condition+" condition remaining":"Not equipped"}</span></div></div>
  {condition>0?<><div className="mine-meter"><span style={{width:Math.min(100,condition/data.settings.mining_pickaxe_durability*100)+"%"}}/></div><p>Use your pickaxe at public sites. Each shift wears down its condition.</p></>:<p>You’ll need to find a pickaxe before working a public site. Search the bins across Blackwater to find equipment.</p>}
  <Link className="command-action" href="/bin-diving">Find equipment · Bin Diving →</Link><Link className="command-action" href="/refineries">Refine your ore →</Link><span className="mine-equipment-note"><GameIcon name="lock" size={13}/>Pickaxes are found, never bought.</span>
 </Panel>;
}
function MineBid({site,data,now,busy,act}:{site:Mine;data:MiningState;now:number;busy:boolean;act:MiningAction}){
 const next=mineNextBid(site,data.settings.district_bid_increment),[price,setPrice]=useState(String(next)),a=site.auction!;
 useEffect(()=>setPrice(p=>String(Math.max(Number(p)||0,next))),[next]);
 const total=Number(price)+Math.ceil(Number(price)*a.tax_rate/100),credit=a.bidder_id===data.world.player_id?a.escrow:0;
 return <form className="mine-form mine-bid" onSubmit={e=>{e.preventDefault();void act("bid",{mine_id:site.id,price:Number(price)});}}>
  <span className="eyebrow">EXTRACTION RIGHTS AUCTION</span><h3>{money(a.bid||a.minimum_bid)}</h3><p>{a.bidder_name?"Leading: "+a.bidder_name:"Opening bid"} · {remaining(a.ends_at,now)>0?duration(remaining(a.ends_at,now))+" remaining":"Awaiting settlement"}</p>
  <p>Seasonal title · {site.remaining.toLocaleString("en-US")} resource units · {site.access_mode} access</p>
  {remaining(a.ends_at,now)<=0?<button type="button" className="market-gold" disabled={busy||!data.playable} onClick={()=>void act("settle",{mine_id:site.id})}>Settle auction</button>:site.owner_id===data.world.player_id&&site.owner_type==="player"?<p>Your property is on auction.</p>:<>
   <label>Your bid for the mine ($)<input required type="number" min={next} step="1" value={price} onChange={e=>setPrice(e.target.value)}/></label>
   <dl className="mine-facts"><div><dt>Buyer tax · {a.tax_rate}%</dt><dd>{money(total-Number(price))}</dd></div><div><dt>Additional cash reserved</dt><dd>{money(Math.max(0,total-credit))}</dd></div></dl>
   <p>Outbid funds return automatically. The winner receives the mine and its remaining reserves.</p><button className="market-gold" disabled={busy||!data.playable||total-credit>data.world.cash}>Confirm mine bid</button>
  </>}
 </form>;
}
function MineDetails({site,data,now,busy,act,onClose}:{site:Mine;data:MiningState;now:number;busy:boolean;act:MiningAction;onClose:()=>void}){
 const own=site.owner_type==="player"&&site.owner_id===data.world.player_id,accessible=site.access_mode==="public"||own;
 const shift=data.shift?.mine_id===site.id?data.shift:null;
 return <div className="mine-detail-content">
  <div className="mine-detail-art"><img src={site.image_url} alt={site.name} width={640} height={853}/><button aria-label="Close mine details" className="mine-close" onClick={onClose}>×</button><span className={"mine-status status-"+(site.auction?"auction":site.status)}>{mineStatus(site)}</span></div>
  <header className="mine-detail-heading"><span className="eyebrow">{site.code} / EXTRACTION REGISTRY</span><h2>{site.name}</h2></header>
  <div className="mine-resource-preview"><CommodityArtwork goodId={site.good_id} size={86}/><div><span className="eyebrow">RESOURCE DEPOSIT</span><h3>{site.good_name}</h3><strong>{site.remaining.toLocaleString("en-US")} <small>units remaining</small></strong></div></div>
  <div className="mine-meter" aria-label="Remaining deposit"><span style={{width:Math.min(100,site.remaining/Math.max(1,site.initial_reserve)*100)+"%"}}/></div>
  <dl className="mine-facts"><div><dt>Registered owner</dt><dd>{own?"You":site.owner_name}</dd></div><div><dt>Access</dt><dd>{site.access_mode==="public"?"Public · pickaxe required":"Property owner only"}</dd></div></dl>
  {site.auction?<MineBid key={site.auction.id} site={site} data={data} now={now} busy={busy} act={act}/>:<>
   {accessible&&site.status==="open"&&site.remaining>0&&<div className="mine-public-action"><h3>Work the seam</h3><div className="mine-shift-terms"><span><strong>{site.hand_yield}</strong>units / shift</span><span><strong>{duration(site.hand_seconds)}</strong>shift time</span><span><strong>{site.tool_wear}</strong>tool wear</span></div>
    {shift?<button className="market-gold" disabled={busy||!data.playable||remaining(shift.ready_at,now)>0} onClick={()=>void act("claim",{mine_id:site.id,run_id:shift.id})}>{remaining(shift.ready_at,now)>0?"Shift running · "+duration(remaining(shift.ready_at,now)):"Collect this shift"}</button>:data.tool.durability<site.tool_wear?<div className="mine-tool-required"><GameIcon name="pickaxe" size={23}/><div><strong>Pickaxe required</strong><p>{data.tool.durability?"Your pickaxe is too worn for this seam. ":""}Find a spare by bin diving. Pickaxes cannot be purchased.</p></div></div>:<button className="market-gold" disabled={busy||!data.playable||!!data.shift} onClick={()=>void act("start",{mine_id:site.id})}>{data.shift?"Finish your current shift first":"Start mining shift"}</button>}
   </div>}
   {own&&<div className="mine-operation"><h3>Your extraction operation</h3><p>{site.operation_yield} units every {duration(site.operation_seconds)} · up to {data.settings.mining_offline_cycles} cycles offline.</p><button className="market-gold" disabled={busy||!data.playable||site.status!=="open"||site.ready_output<1} onClick={()=>void act("collect",{mine_id:site.id})}>Collect {site.ready_output.toLocaleString("en-US")} resources</button><details><summary>Sell extraction rights</summary><MineAuctionForm site={site} data={data} busy={busy} act={act}/></details></div>}
   {!own&&site.access_mode==="private"&&<p className="mine-help">Private extraction rights. Watch for an auction to acquire this site.</p>}
   {site.status!=="open"&&<p className="mine-help">{site.status==="reserved"?"This claim is reserved for a future release.":"This site is closed. The city Owner controls when it opens."}</p>}
  </>}
  <details className="mine-site-file"><summary>Site information <GameIcon name="arrow" size={12}/></summary><p>{site.description}</p><dl className="mine-facts"><div><dt>Survey</dt><dd>{site.survey_status}</dd></div><div><dt>Transport</dt><dd>{site.transport}</dd></div><div><dt>Property tax</dt><dd>{site.tax_rate}%</dd></div></dl></details>
  <div className="mine-detail-links"><Link className="market-outline" href={"/market?good="+site.good_id+"&district="+site.district_id}>Trade {site.good_name.toLowerCase()} <GameIcon name="arrow" size={14}/></Link>{data.can_manage&&<Link className="market-outline" href={"/owner?section=mines&mine="+site.id}>Owner site controls <GameIcon name="gear" size={14}/></Link>}</div>
 </div>;
}
export function MiningDistrict({initial}:{initial:MiningState}){
 const mining=useMining(initial),{data,now,busy,notice,failed,retry,act}=mining;
 const [selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState("all"),[goodFilter,setGoodFilter]=useState("all"),[search,setSearch]=useState(""),[view,setView]=useState("sites");
 const sheet=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const read=()=>setSelected(new URLSearchParams(location.search).get("mine"));read();window.addEventListener("popstate",read);return()=>window.removeEventListener("popstate",read);},[]);
 const select=(id:string|null)=>{setSelected(id);const u=new URL(location.href);if(id)u.searchParams.set("mine",id);else u.searchParams.delete("mine");history.pushState(null,"",u);};
 const site=data?.sites.find(m=>m.id===selected);
 useEffect(()=>{if(!site)return;const mq=matchMedia("(max-width:900px)"),dialog=sheet.current;const sync=()=>{if(mq.matches&&!dialog?.open)dialog?.showModal();else if(!mq.matches&&dialog?.open)dialog?.close();};sync();mq.addEventListener("change",sync);return()=>mq.removeEventListener("change",sync);},[site?.id]);
 if(!data)return null;
 const d=data.world.district,sites=data.sites,own=sites.filter(m=>m.owner_type==="player"&&m.owner_id===data.world.player_id);
 const shown=sites.filter(m=>(filter==="all"||filter==="public"&&m.status==="open"&&m.access_mode==="public"&&!m.auction||filter==="auction"&&!!m.auction||filter==="mine"&&own.includes(m)||filter==="reserved"&&m.status==="reserved")&&(goodFilter==="all"||m.good_id===goodFilter)&&[m.name,m.code,m.good_name,m.owner_name].join(" ").toLowerCase().includes(search.toLowerCase()));
 const totals=[["mountain","SITES",sites.length],["pickaxe","PUBLIC SITES",sites.filter(m=>m.status==="open"&&m.access_mode==="public"&&!m.auction).length],["auction","AUCTIONS",sites.filter(m=>m.auction).length],["lock","RESERVED",sites.filter(m=>m.status==="reserved").length]] as const;
 const close=()=>{sheet.current?.close();select(null);};
 const noticeContent=notice&&<div className={"mine-notice "+(failed?"error":"")} role={failed?"alert":"status"}>{notice}{retry&&<button className="market-outline" disabled={mining.working} onClick={()=>void mining.retryAction()}>Retry same request</button>}</div>;
 return <div className="mining-district mining-refined">
  <header className="mine-masthead command-panel"><div><Link className="mine-back" href="/districts"><GameIcon name="arrow" size={14}/>Back to City Map</Link><p className="eyebrow">BLACKWATER / THE NORTHERN CLAIMS</p><h1>{d.name}</h1><p className="mine-tagline">{d.tagline}</p></div><div className="mine-top-stats">{totals.map(([icon,label,value])=><div key={label}><GameIcon name={icon} size={23}/><strong>{value}</strong><span>{label}</span></div>)}</div></header>
  <nav className="mine-nav" aria-label="Mining sections">{[["sites","Sites & claims"],["work","Your haul"],["activity","District activity"]].map(([id,label])=><button key={id} aria-current={view===id?"page":undefined} onClick={()=>setView(id)}>{label}</button>)}<Link href={"/market?district="+d.id}>Local market</Link><Link href={"/districts/"+d.slug+"?registry=1&tab=Territory"}>Territory</Link><button className="mine-refresh" onClick={mining.refresh} disabled={mining.working}><GameIcon name="refresh" size={14}/>Refresh</button>{data.can_manage&&<Link href="/owner?section=mines">Owner controls</Link>}</nav>
  {noticeContent}{!data.playable&&<p className="mine-notice">Mining is paused while this season is closed.</p>}
  {data.shift&&<section className="mine-shift command-panel" aria-label="Your mining shift"><CommodityArtwork goodId={data.shift.good_id} size={54}/><div><span className="eyebrow">{data.shift.code} / YOUR SHIFT</span><h2>{data.shift.mine_name}</h2><p>{data.shift.quantity} {data.shift.good_name.toLowerCase()} · {remaining(data.shift.ready_at,now)>0?duration(remaining(data.shift.ready_at,now))+" remaining":"Ready to collect"}</p></div><button className="market-gold" disabled={busy||!data.playable||remaining(data.shift.ready_at,now)>0} onClick={()=>void act("claim",{mine_id:data.shift!.mine_id,run_id:data.shift!.id})}>Collect mined resources</button><button className="market-outline" disabled={busy||!data.playable} onClick={()=>void act("cancel",{mine_id:data.shift!.mine_id,run_id:data.shift!.id})}>Cancel shift</button></section>}
  {view==="sites"?<>
   <div className="mine-layout"><div className="mine-map-column">
    <div className="mine-map-tools"><div><span className="eyebrow">LIVE EXTRACTION REGISTRY</span><strong>Choose your ground.</strong></div><label className="mine-search"><GameIcon name="search" size={15}/><input aria-label="Search mine sites" placeholder="Search sites or resources…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter mine sites" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All sites</option><option value="public">Public mining</option><option value="auction">Live auctions</option><option value="mine">Your mines</option><option value="reserved">Reserved claims</option></select></div>
    <div className="mine-map"><PanMap contain label="Mines and Quarries site map" background="/art/mining/map.webp" height={600} instruction="Drag to explore · Select a mine or quarry">
     {sites.map(m=>{const tone=m.auction?"auction":own.includes(m)?"owned":m.status==="open"&&m.access_mode==="public"?"public":"closed";return <g key={m.id} className={"mine-marker "+tone+(selected===m.id?" selected":"")+(shown.includes(m)?"":" dimmed")} role="button" tabIndex={0} aria-label={"View "+m.code+" "+m.name} aria-pressed={selected===m.id} onClick={()=>select(m.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();select(m.id);}}} transform={"translate("+m.map_x+" "+m.map_y+")"}><title>{m.name+" · "+mineStatus(m)}</title><rect x="-91" y="-27" width="182" height="55" rx="2"/><foreignObject x="-86" y="-21" width="42" height="42"><CommodityArtwork goodId={m.good_id} size={42}/></foreignObject><text x="-36" y="-5" className="mine-marker-code">{m.code}</text><text x="-36" y="12">{m.name.length>21?m.name.slice(0,20)+"…":m.name}</text><circle className="mine-marker-dot" cx="82" cy="-19" r="4"/></g>;})}
     <g className="mine-terminal" transform="translate(195 532)"><rect x="-137" y="-23" width="250" height="48"/><text x="-118" y="-2">RAIL LOADING TERMINAL</text><text x="-118" y="14">CITY FREIGHT INFRASTRUCTURE</text></g>
    </PanMap></div><div className="mine-map-legend"><span><i className="mine-dot public"/>Public</span><span><i className="mine-dot auction"/>Auction</span><span><i className="mine-dot owned"/>Your mine</span><span><i className="mine-dot"/>Closed / reserved</span><span className="mine-transport"><GameIcon name="rail" size={16}/>{sites[0]?.transport||"Unregistered"}</span></div>
   </div><aside className="mine-sidebar">
    {site?<section className="command-panel mine-desktop-details" key={site.id}><MineDetails site={site} data={data} now={now} busy={busy} act={act} onClose={close}/></section>:<Panel title="The district" className="mine-overview"><p className="mine-overview-intro">{d.description}</p><dl className="mine-facts">{[["Controller",data.world.territory.controller_name||"Neutral"],["Your operations",String(own.length)],["Output today",sites.reduce((n,m)=>n+m.output_today,0).toLocaleString("en-US")+" units"],["Police heat",d.police_heat+" / 100"],["Property tax",d.tax_rate+"%"]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="mine-overview-quote"><span>RAW MATERIALS.</span><em>Real influence.</em><p>Every empire starts with what lies beneath.</p></div></Panel>}
    <Equipment data={data}/>
   </aside></div>
   <section className="mine-resource-strip" aria-label="District resources"><header><span className="eyebrow">BENEATH BLACKWATER</span><h2>The raw materials.</h2><p>Select a resource to find its sites.</p></header><div>{data.inventory.map(g=><button key={g.good_id} aria-label={"Show "+g.name+" sites"} aria-pressed={goodFilter===g.good_id} onClick={()=>setGoodFilter(goodFilter===g.good_id?"all":g.good_id)}><CommodityArtwork goodId={g.good_id} size={76}/><span><strong>{g.name}</strong><small>{sites.filter(m=>m.good_id===g.good_id).length} sites · {g.quantity.toLocaleString("en-US")} in your haul</small></span></button>)}</div></section>
   <section className="mine-site-section"><header className="mine-section-head"><div><span className="eyebrow">CITY MINING AUTHORITY</span><h2>Sites & claims <small>{shown.length}</small></h2></div>{(goodFilter!=="all"||filter!=="all"||search)&&<button className="market-outline" onClick={()=>{setGoodFilter("all");setFilter("all");setSearch("");}}>Clear filters</button>}</header><div className="mine-cards">{shown.map(m=><button key={m.id} className={"mine-card command-panel"+(selected===m.id?" selected":"")} onClick={()=>select(m.id)} aria-label={"Open "+m.code+" "+m.name}><div className="mine-card-art"><img src={m.image_url} alt="" width={640} height={853} loading="lazy"/><span className="eyebrow">{m.code}</span><span className={"mine-status status-"+(m.auction?"auction":m.status)}>{mineStatus(m)}</span><CommodityArtwork goodId={m.good_id} size={64}/></div><div className="mine-card-body"><h3>{m.name}</h3><p>{m.good_name} <span>·</span> {m.remaining.toLocaleString("en-US")} units</p><small>{own.includes(m)?"Your operation":m.owner_name}</small><span className="mine-card-link">{m.auction?"View auction":"Explore site"}<GameIcon name="arrow" size={15}/></span></div></button>)}</div>{!shown.length&&<p className="command-empty">No sites match these filters.</p>}</section>
  </>:view==="work"?<>
   <header className="mine-haul-heading"><div><span className="eyebrow">YOUR MATERIAL RESERVES</span><h2>Your haul.</h2><p>Raw materials gathered from the hills, ready for the player economy.</p></div><Link className="market-outline" href="/market?view=inventory">Open market inventory <GameIcon name="arrow" size={15}/></Link></header>
   <div className="mine-inventory">{data.inventory.map(g=><Link key={g.good_id} href={"/market?good="+g.good_id+"&view=inventory"}><CommodityArtwork goodId={g.good_id} size={220}/><div><h3>{g.name}</h3><strong>{g.quantity.toLocaleString("en-US")} <span>units</span></strong><span className="mine-card-link">Trade resource <GameIcon name="arrow" size={15}/></span></div></Link>)}</div>
   <div className="mine-work-grid"><Panel title="Recent extraction">{data.history.length?<ol className="mine-history">{data.history.map(e=><li key={e.id}><CommodityArtwork goodId={e.good_id} size={46}/><div><strong>{e.quantity} {e.good_name}</strong><span>{e.mine_name} · {e.source==="operation"?"Your operation":"Mining shift"}</span><time dateTime={e.created_at}>{new Date(e.created_at).toLocaleString()}</time></div></li>)}</ol>:<div className="mine-empty-haul"><GameIcon name="pickaxe" size={29}/><h3>Your first seam awaits.</h3><p>Completed mining shifts will appear here. Find and equip a pickaxe through bin diving.</p></div>}</Panel><Equipment data={data}/></div>
  </>:<Panel title="District activity"><ol className="mine-history">{data.world.events.map(e=><li key={e.id}><GameIcon name={e.category==="property"?"auction":"pickaxe"} size={19}/><div><strong>{e.description}</strong><time dateTime={e.created_at}>{new Date(e.created_at).toLocaleString()}</time>{e.actor_id&&<Link href={"/players/"+e.actor_id}>{e.actor_name}</Link>}</div>{sites.some(m=>m.plot_id===e.plot_id)&&<button className="command-more" onClick={()=>{setView("sites");select(sites.find(m=>m.plot_id===e.plot_id)!.id);}}>View site →</button>}</li>)}</ol></Panel>}
  {site&&<dialog ref={sheet} className="mine-sheet" aria-label={site.code+" mine details"} onCancel={e=>{if(mining.working)e.preventDefault();else close();}}>{noticeContent}<MineDetails site={site} data={data} now={now} busy={busy} act={act} onClose={close}/></dialog>}
 </div>;
}
