"use client";
import Link from "next/link";
import {Artwork} from "@/components/artwork";
import {GameIcon} from "@/components/game-icon";
import {money,readyUnits,duration,type GameState} from "@/lib/game";
import {seasonPlayable} from "@/lib/seasons";
export const propertyArt=(id:string)=>id==="whiskey"?"distillery":id==="silk"?"textile":"foundry";
export const propertyDistrict=(id:string)=>id==="whiskey"?"The Docks":id==="silk"?"Old Town":"Industrial Quarter";
export function PropertyEstate({state,now,propertyId,busy,onAction,onSelect,onSell,notice}:{state:GameState;now:number;propertyId:string;busy:boolean;onAction:(action:string,payload:Record<string,string|number>)=>Promise<boolean>;onSelect:(id:string)=>void;onSell:(id:string)=>void;notice:React.ReactNode}){
 const good=state.goods.find(g=>g.id===propertyId)||state.goods[0],owned=state.businesses.find(b=>b.good_id===good.id),playing=seasonPlayable(state.season,now);
 const clock=playing?now:Date.parse(state.season.locked_at||state.season.ends_at||state.server_time);
 const ready=owned?readyUnits(owned,good,clock,state.settings.offline_batches):0,capacity=good.batch_size*state.settings.offline_batches;
 const elapsed=owned?Math.max(0,(clock-Date.parse(owned.collected_at))/1000):0;
 const until=Math.max(0,Math.ceil(good.cycle_seconds-(elapsed%good.cycle_seconds)));
 const stock=state.inventory.find(i=>i.good_id===good.id)?.quantity||0,totalStock=state.inventory.reduce((s,i)=>s+i.quantity,0);
 const escrow=state.my_listings.filter(l=>l.good_id===good.id).reduce((s,l)=>s+l.quantity,0);
 const offers=state.market.filter(l=>l.good_id===good.id),low=offers.length?Math.min(...offers.map(l=>l.unit_price)):null;
 const hourly=good.batch_size*3600/good.cycle_seconds;
 const progress=Math.min(100,ready/capacity*100);
 const stats=[["inventory","READY TO COLLECT",ready.toLocaleString("en-US"),"units"],["production","PRODUCTION RATE",hourly.toLocaleString("en-US",{maximumFractionDigits:1}),"units / hour"],["businesses","WAREHOUSE STOCK",stock.toLocaleString("en-US"),"units"],["market","LISTED FOR SALE",escrow.toLocaleString("en-US"),"units"],["clock","PRODUCTION CYCLE",duration(good.cycle_seconds),"per batch"],["cash","PROPERTY VALUE",money(good.business_cost),""]];
 return <div className="property-estate">
  <section className="estate-hero property-hero"><Artwork name={propertyArt(good.id)} priority/><div className="estate-hero-shade"/><div className="estate-hero-copy"><p className="eyebrow"><Link href="/properties">PROPERTIES</Link><span>›</span>{good.name.toUpperCase()}</p><h1>{good.business_name}</h1><p className="estate-location">{propertyDistrict(good.id).toUpperCase()} / {owned?"YOUR PROPERTY":"ACQUISITION OPPORTUNITY"}</p><i className="estate-gold-rule"/><p className="estate-motto">{good.id==="whiskey"?"Quiet operations. A city with a thirst.":good.id==="silk"?"Fine resources. A finer reputation.":"Hard resources. A stronger tomorrow."}</p><p className="estate-description">Supply the goods that keep Blackwater moving. {owned?"Managed by you.":"Ready for your next move."} Produce {good.name.toLowerCase()}, set your price, and build your fortune through trade.</p></div><div className="estate-hero-quote">THE CITY BELONGS<br/>TO THOSE WHO<br/><strong>BUILD IT.</strong></div></section>
  <div className="estate-body property-body">{notice}<div className="property-layout"><div className="property-main">
   <div className="property-stats stats-grid">{stats.map(([icon,label,value,unit])=><article key={label}><GameIcon name={icon} size={29}/><div><span>{label}</span><strong>{value} <small>{unit}</small></strong></div></article>)}</div>
   <div className="production-grid"><section className="estate-panel production-panel"><div className="estate-panel-title"><GameIcon name="production" size={25}/><h2>Production</h2><span className={"estate-status"+(!owned||!playing?" inactive":"")}>{owned?(playing?"ACTIVE":"PAUSED"):"NOT OWNED"}</span></div><div className="production-reading"><div><span>CURRENT PRODUCTION</span><strong>{owned?hourly.toLocaleString("en-US",{maximumFractionDigits:1}):"—"} <em>units / hour</em></strong></div><div><span>PER BATCH</span><strong>{good.batch_size} <small>units</small></strong></div><div><span>NEXT BATCH</span><strong>{!owned?"—":!playing?"Paused":ready>=capacity?"At limit":duration(until)}</strong></div></div><div className="estate-progress" role="progressbar" aria-label="Completed production ready for collection" aria-valuenow={Math.round(progress)} aria-valuemin={0} aria-valuemax={100}><span style={{width:progress+"%"}}/></div><div className="production-capacity"><span>COLLECTION LIMIT · {state.settings.offline_batches} BATCHES</span><strong>{ready.toLocaleString("en-US")} / {capacity.toLocaleString("en-US")} units</strong></div><div className="production-schedule"><p className="eyebrow">THE PRODUCTION CYCLE</p><div><GameIcon name="clock" size={25}/><p><small>Collection interval</small>{duration(good.cycle_seconds)} per batch</p><GameIcon name="inventory" size={25}/><p><small>Waiting for collection</small>{Math.floor(ready/good.batch_size)} completed batches</p></div></div></section>
   <section className="estate-panel resource-panel"><div className="estate-panel-title"><GameIcon name="inventory" size={25}/><h2>Resources & storage</h2></div><div className="resource-rows">{state.goods.map(g=>{const quantity=state.inventory.find(i=>i.good_id===g.id)?.quantity||0,share=totalStock?quantity/totalStock*100:0;return <div className="resource-row" key={g.id}><span className="resource-emblem"><GameIcon name={g.id==="steel"?"production":g.id==="silk"?"inventory":"businesses"} size={24}/></span><span>{g.name}</span><strong>{quantity.toLocaleString("en-US")} <small>units</small></strong><div className="estate-progress" aria-label={Math.round(share)+"% of available stock"}><span style={{width:share+"%"}}/></div><small>{Math.round(share)}%</small></div>;})}</div><div className="resource-total"><span>Available warehouse stock</span><strong>{totalStock.toLocaleString("en-US")} <small>units</small></strong></div><p className="estate-fineprint">Listed goods are held separately until a player buys them or you withdraw the offer.</p></section></div>
   <div className="property-lower"><section className="estate-panel portfolio-panel"><div className="estate-panel-title"><GameIcon name="businesses"/><h2>Your properties</h2></div>{state.goods.map(g=><button className={"property-switch"+(g.id===good.id?" selected":"")} key={g.id} onClick={()=>onSelect(g.id)}><GameIcon name="businesses" size={22}/><span><strong>{g.business_name}</strong><small>{state.businesses.some(b=>b.good_id===g.id)?"Owned · "+g.name:money(g.business_cost)+" · Available"}</small></span><span>›</span></button>)}<p className="estate-fineprint">{state.businesses.length} of {state.goods.length} properties acquired.</p></section>
   <section className="estate-panel supply-panel"><div className="estate-panel-title"><GameIcon name="gear"/><h2>Supply & trade</h2></div><dl><div><dt>Available to sell</dt><dd>{stock} units</dd></div><div><dt>In your offers</dt><dd>{escrow} units</dd></div><div><dt>Seller fee</dt><dd>{state.settings.market_fee_percent}%</dd></div></dl><p>Every deal is made with another player. Supply the city. Name your price.</p><button className="estate-outline-button" onClick={()=>onSell(good.id)}>Manage inventory <GameIcon name="arrow" size={15}/></button></section>
   <section className="estate-panel market-insights"><div className="estate-panel-title"><GameIcon name="market"/><h2>Market insights</h2></div><p>{good.name} · lowest asking price</p><strong className="insight-price">{low===null?"No offers":money(low)}</strong><div className="insight-facts"><span>Open player offers</span><strong>{offers.length}</strong></div><div className="insight-facts"><span>Units on the market</span><strong>{offers.reduce((n,o)=>n+o.quantity,0)}</strong></div><p className="estate-fineprint">Live asking prices. A sale happens when another player accepts an offer.</p><button className="button full" onClick={()=>onSell(good.id)}>Sell goods <GameIcon name="arrow" size={16}/></button></section>
   <section className="estate-panel property-activity"><div className="estate-panel-title"><GameIcon name="ledger"/><h2>Recent activity</h2><Link href="/ledger">View all →</Link></div>{state.events.slice(0,5).map(e=><div className="estate-event" key={e.id}><span className="presence-dot"/><time>{new Date(e.created_at).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"UTC"})}</time><p>{e.description}</p></div>)}{!state.events.length&&<p>Your next operation or trade will appear here.</p>}</section></div>
  </div><aside className="property-controls"><section className="estate-panel property-deed"><div><p className="eyebrow">{owned?"YOUR PROPERTY":"PROPERTY DOSSIER"}</p><span className={"estate-status"+(!owned?" inactive":"")}>{owned?"OWNED":"AVAILABLE"}</span></div><div className="deed-art"><Artwork name={propertyArt(good.id)}/><span className="deed-seal">BW</span></div><p><GameIcon name="pin" size={16}/>{propertyDistrict(good.id)}</p><p><GameIcon name="businesses" size={16}/>{good.business_name}</p><p><GameIcon name="people" size={16}/>{owned?"Owned by "+state.player.handle:"Available for acquisition"}</p><Link href="/districts">VIEW DISTRICT <GameIcon name="arrow" size={15}/></Link></section><section className="estate-panel property-command"><div className="estate-panel-title"><GameIcon name="shield"/><h2>Property controls</h2></div>{owned?<button className="button full" disabled={busy||!ready} onClick={()=>void onAction("collect",{good_id:good.id})}><GameIcon name="production" size={18}/>{ready?"Collect "+ready+" units":"Production in progress"}</button>:<button className="button full" disabled={busy||state.player.cash<good.business_cost} onClick={()=>void onAction("business",{good_id:good.id})}>Buy business · {money(good.business_cost)}</button>}<button className="estate-outline-button" onClick={()=>onSell(good.id)}><GameIcon name="inventory"/>Manage inventory <GameIcon name="arrow" size={15}/></button><Link className="estate-outline-button" href={"/market?good="+good.id}><GameIcon name="market"/>Visit market <GameIcon name="arrow" size={15}/></Link><Link className="estate-outline-button" href="/districts"><GameIcon name="map"/>City operations <GameIcon name="arrow" size={15}/></Link><Link className="estate-outline-button" href="/ledger"><GameIcon name="ledger"/>Financial history <GameIcon name="arrow" size={15}/></Link></section></aside></div></div>
 </div>;
}
