"use client";
import {useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";
import type {DistrictState} from "@/lib/districts";
export function PropertyRegistryOwner({state,refresh}:{state:DistrictState;refresh:()=>Promise<void>}){
 const [streetId,setStreetId]=useState(""),[plotId,setPlotId]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const streets=state.streets??[],street=streets.find(s=>s.id===streetId),templates=state.management?.templates.filter(t=>t.district_id===state.district.id)??[],plot=templates.find(p=>p.id===plotId),terms=state.lease_terms?.find(t=>t.template_id===plotId);
 async function save(action:string,payload:Record<string,unknown>){if(busy)return;setBusy(true);setNotice("");try{const {data,error}=await createClient().rpc("property_manage",{p_action:action,p_payload:payload});if(error||data?.error)throw new Error(data?.error??"Could not save the registry.");setNotice(data.message);await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not save.");}finally{setBusy(false);}}
 if(!state.can_manage_properties)return <p>Owner property permission is required.</p>;
 return <><p className="district-notice">City leases only. Changes apply to new rentals and renewals. Existing lease end dates stay the same.</p>{notice&&<p role="status" className="district-notice">{notice}</p>}<div className="dp-owner-grid">
 <section className="district-panel"><h2>District streets</h2><label>Street record<select value={streetId} onChange={e=>setStreetId(e.target.value)}><option value="">Create a street</option>{streets.map(s=><option key={s.id} value={s.id}>{s.name}{s.archived_at?" · Archived":""}</option>)}</select></label>
 <form key={JSON.stringify(street)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save("street",{id:streetId||null,district_id:state.district.id,name:f.get("name"),description:f.get("description"),sort_order:Number(f.get("order")),archived:f.get("archived")==="on",reason:f.get("reason")});}}><fieldset disabled={busy}>
 <label>Street name<input name="name" required minLength={2} maxLength={80} defaultValue={street?.name??""}/></label><label>Street description<textarea name="description" maxLength={600} defaultValue={street?.description??""}/></label><label>Display order<input name="order" type="number" step={1} required defaultValue={street?.sort_order??streets.length+1}/></label>
 {street&&<label>Archive this street<input type="checkbox" name="archived" defaultChecked={!!street.archived_at}/></label>}<label>Street audit reason<textarea name="reason" minLength={5} maxLength={500} required/></label><button className="district-gold">Save street</button></fieldset></form></section>
 <section className="district-panel"><h2>Property listings & city leases</h2><label>Property record<select value={plotId} onChange={e=>setPlotId(e.target.value)}><option value="">Choose a property</option>{templates.map(p=><option value={p.id} key={p.id}>{p.code}</option>)}</select></label>
 {plot?<form key={JSON.stringify([plot,terms])} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save("property",{template_id:plotId,street_id:f.get("street_id"),image_url:f.get("image_url"),lease_enabled:f.get("enabled")==="true",rent:Number(f.get("rent")),term_hours:Number(f.get("hours")),reason:f.get("reason")});}}><fieldset disabled={busy}>
 <label>Property street<select name="street_id" defaultValue={plot.street_id??""}><option value="">No assigned street</option>{streets.map(s=><option key={s.id} value={s.id}>{s.name}{s.archived_at?" · Archived":""}</option>)}</select></label><label>Property image<input name="image_url" defaultValue={plot.image_url??""} placeholder="/art/harbor.webp"/></label>
 <label>Accept city leases<select name="enabled" defaultValue={String(terms?.enabled??false)}><option value="false">No</option><option value="true">Yes — city storage buildings only</option></select></label>
 <label>Rent per period ($)<input type="number" name="rent" min={1} max={1000000000} step={1} required defaultValue={terms?.rent??""}/></label><label>Rental period (hours)<input type="number" name="hours" min={1} max={8760} step={1} required defaultValue={terms?.term_hours??""}/></label><label>Property audit reason<textarea name="reason" minLength={5} maxLength={500} required/></label><button className="district-gold">Save property listing</button></fieldset></form>:<p>Choose a property to edit its street, artwork and rental terms. A lease requires a completed city-owned garage or warehouse.</p>}
 <p>Storage capacities are managed in <Link href="/owner?section=inventory">Owner inventory settings</Link>. Crafting-station installation cost and space are editable in <Link href="/owner?section=economy">Owner economy settings</Link>.</p></section></div></>;
}
