"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {GameIcon} from "@/components/game-icon";
import {CommodityArtwork} from "@/components/commodity-artwork";
import {PlayerAvatar} from "@/components/player-avatar";
import {Range3DLane} from "./range-3d-lane";
import {useRange} from "@/components/use-range";
import {useRangeAudio} from "@/components/use-range-audio";
import {formatRangeAccuracy,rangeTarget,rangeImpact,type RangeImpact,type RangeDifficulty,type RangeConfig,type RangeSession,type RangeState} from "@/lib/range";
const timer=(ms:number)=>{const n=Math.max(0,Math.ceil(ms/1000));return `${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;};
function RangeLane({session,config,clock,canFire,automatic,onFire}:{session:RangeSession|null;config:RangeConfig;clock:()=>number;canFire:boolean;automatic:boolean;onFire:(x:number,y:number,elapsed:number)=>void}){
 const [damage,setDamage]=useState<{sessionId:string|null;holes:RangeImpact[]}>({sessionId:null,holes:[]});
 const [now,setNow]=useState(clock),[aim,setAim]=useState({x:50,y:50}),[holding,setHolding]=useState(false),surface=useRef<HTMLDivElement>(null);
 useEffect(()=>{let id:number,last=0;const frame=(t:number)=>{if(t-last>30){setNow(clock());last=t;}id=requestAnimationFrame(frame);};id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id);},[clock]);
 const elapsed=session?Math.max(0,Math.floor(now-Date.parse(session.started_at))):0,round=Math.min(config.rounds-1,Math.floor(elapsed/(config.round_seconds*1000))),active=session?.status==="active"&&now<Date.parse(session.ends_at);
 useEffect(()=>{if(!automatic||!holding||!active||!canFire)return;const id=setTimeout(()=>onFire(aim.x,aim.y,elapsed),0);return()=>clearTimeout(id);},[automatic,holding,active,canFire,aim.x,aim.y,elapsed,onFire]);
 useEffect(()=>{if(!automatic||!active)setHolding(false);},[automatic,active]);
 const point=(e:React.PointerEvent)=>{const b=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(100,(e.clientX-b.left)/b.width*100)),y:Math.max(0,Math.min(100,(e.clientY-b.top)/b.height*100))};};
  const shot=session?.last_shot;
 useEffect(()=>{
  setDamage(previous=>{
   const holes=previous.sessionId===session?.id?previous.holes.filter(h=>h.round===round):[];
   const impact=shot&&shot.round===round&&session?rangeImpact(session.seed,shot,config):null;
   if(impact&&!holes.some(h=>h.id===impact.id))holes.push(impact);
   return {sessionId:session?.id??null,holes};
  });
 },[session?.id,shot?.id,round,config]);
 const holes=damage.sessionId===session?.id?damage.holes.filter(h=>h.round===round):[];
 const fresh=shot&&now-Date.parse(shot.created_at)<650;
 return <div className={"range-lane "+(active?"in-session":"at-rest")+(fresh?shot.hit?" hit-flash":" miss-flash":"")} ref={surface} role="button" tabIndex={0} aria-label="Shooting lane" aria-describedby="range-instructions" aria-disabled={!canFire} onPointerMove={e=>setAim(point(e))} onPointerDown={e=>{if(e.button!==0||!e.isPrimary)return;surface.current?.focus({preventScroll:true});const p=point(e);setAim(p);if(automatic){e.currentTarget.setPointerCapture(e.pointerId);setHolding(true);}if(canFire&&active)onFire(p.x,p.y,elapsed);}} onPointerUp={e=>{setHolding(false);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>setHolding(false)} onLostPointerCapture={()=>setHolding(false)} onBlur={()=>setHolding(false)} onKeyDown={e=>{if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(e.key)){e.preventDefault();setAim(p=>({x:Math.max(0,Math.min(100,p.x+(e.key==="ArrowRight"?2:e.key==="ArrowLeft"?-2:0))),y:Math.max(0,Math.min(100,p.y+(e.key==="ArrowDown"?2:e.key==="ArrowUp"?-2:0)))}));}if(e.key===" "&&!e.repeat){e.preventDefault();if(automatic)setHolding(true);if(canFire&&active)onFire(aim.x,aim.y,elapsed);}if(e.key==="Enter"&&!e.repeat){e.preventDefault();if(canFire&&active)onFire(aim.x,aim.y,elapsed);}}} onKeyUp={e=>{if(e.key===" "){e.preventDefault();setHolding(false);}}}>
 <img className="range-backdrop" src="/art/shooting-range.png" alt="Blackwater's lamplit warehouse shooting range" width={1672} height={941} fetchPriority="high"/>
 <div className="range-lane-shade"/>
 <svg className="range-targets" viewBox="0 0 1000 600" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="range-paper" x2="1" y2="1"><stop stopColor="#d5bb8b"/><stop offset=".5" stopColor="#b9a07a"/><stop offset="1" stopColor="#857157"/></linearGradient><filter id="range-shadow"><feDropShadow dx="0" dy="6" stdDeviation="5" floodOpacity=".65"/></filter></defs>
 {Array.from({length:config.targets_per_round},(_,lane)=>{const p=rangeTarget(session?.seed??100,round,lane,active?elapsed:0,config),done=!!session?.hit_targets.includes(`${round}:${lane}`),rx=p.rx*10,ry=p.ry*6;return <g key={lane} className={"range-target "+(done?"scored":"")} data-lane={lane} transform={`translate(${p.x*10} ${p.y*6})`}><path d={`M 0 ${-ry*1.65} V ${-p.y*6}`} stroke="#141914" strokeWidth="4"/><rect x="-11" y={-ry*1.65-12} width="22" height="15" fill="#8f774e" stroke="#282922"/><g filter="url(#range-shadow)"><rect x={-rx*1.35} y={-ry*1.65} width={rx*2.7} height={ry*3.1} rx="2" fill="url(#range-paper)" stroke="#4e4834" strokeWidth="2"/><path d={`M ${-rx} ${ry} L ${-rx} ${-ry*.3} Q ${-rx} ${-ry*.85} ${-rx*.35} ${-ry*.85} A ${rx*.37} ${rx*.37} 0 1 1 ${rx*.35} ${-ry*.85} Q ${rx} ${-ry*.85} ${rx} ${-ry*.3} L ${rx} ${ry} Z`} fill="#252923"/>{[1,.7,config.bullseye_percent/100].map((k,i)=><ellipse key={i} rx={rx*k} ry={ry*k} fill="none" stroke={k===config.bullseye_percent/100?"#a26441":"#a18e66"} strokeWidth={k===config.bullseye_percent/100?"1.8":"1"}/>)}<circle r="3" fill="#b27850"/><defs><clipPath id={"range-paper-clip-"+lane}><rect x={-rx*1.35} y={-ry*1.65} width={rx*2.7} height={ry*3.1} rx="2"/></clipPath></defs><g clipPath={"url(#range-paper-clip-"+lane+")"}>{holes.filter(h=>h.lane===lane).map(h=><g key={h.id} className="range-bullet-hole" data-impact-version="2" data-shot-id={h.id} transform={'translate('+h.x+' '+h.y+') scale(1.35)'}><circle r="7" fill="#0a0b09" opacity=".38"/><path d="M-5 -2L-7 -4L-3 -4L-2 -7L1 -4L5 -5L4 -1L7 2L3 3L2 7L-1 4L-5 5L-4 1Z" fill="#c8b38c" stroke="#5e4c32" strokeWidth=".8"/><path d="M-3 -2L0 -4L3 -2L4 1L1 4L-3 2Z" fill="#090c0b"/><path d="M-5 -4L-8 -7M4 -3L8 -6M4 3L7 7M-3 4L-6 8" stroke="#5b4932" strokeWidth=".7" opacity=".85"/></g>)}</g><text y={ry*1.3} textAnchor="middle" fill="#3f392e" fontSize="8" letterSpacing="2">BLACKWATER · {lane+1}</text></g></g>;})}
 {active&&<g className="range-reticle" transform={`translate(${aim.x*10} ${aim.y*6})`}><circle r="20" fill="none" stroke="currentColor" opacity=".65"/><path d="M0 -30v14M0 16v14M-30 0h14M16 0h14" stroke="currentColor" strokeWidth="1.5"/><circle r="2" fill="currentColor"/></g>}
 {fresh&&shot&&<g transform={`translate(${shot.x*10} ${shot.y*6})`} className="range-shot-mark"><circle r="8" fill="none" stroke={shot.hit?"#e9bc7c":"#bc7c66"}/><path d="M-4 -4L4 4M4 -4L-4 4" stroke="#edddbe"/></g>}
 </svg><span className="range-lane-number">LANE 01 <i/> BLACKWATER TRAINING HALL</span>
 {active&&<><div className="range-round-track" aria-hidden="true"><i style={{width:`${100*(1-elapsed%(config.round_seconds*1000)/(config.round_seconds*1000))}%`}}/></div><span className="range-next-round">Next targets in {timer(config.round_seconds*1000-elapsed%(config.round_seconds*1000))}</span>{shot&&<div className={"range-shot-result "+(shot.hit?"on-target":"off-target")}><small>LAST SHOT</small><strong>{shot.hit?shot.points>0?"Target hit":"Repeat hit":"Miss"}</strong><span>{formatRangeAccuracy(shot.accuracy_percent)}% precision · +{shot.points} points</span></div>}</>}
 </div>;
}
export function RangeWorkspace({initial}:{initial:RangeState}){
 const [view,setView]=useState<"3d"|"2d">("2d"),[renderError,setRenderError]=useState(false);
 useEffect(()=>{try{if(localStorage.getItem("blackwater:range-view-v2")==="3d")setView("3d");}catch{}},[]);
 function chooseView(next:"3d"|"2d"){setView(next);setRenderError(false);try{localStorage.setItem("blackwater:range-view-v2",next);}catch{}}
 const board=useRef<HTMLElement>(null),sound=useRangeAudio(),heard=useRef<string|null>(null),h=useRange(initial),d=h.data,[mode]=useState<RangeDifficulty>("advanced"),[slot,setSlot]=useState(initial.weapons[0]?.slot??"secondary"),[now,setNow]=useState(Date.parse(initial.server_time));
 useEffect(()=>{const id=setInterval(()=>setNow(h.clock()),100);return()=>clearInterval(id);},[h.clock]);
 const session=d.session,active=session?.status==="active",inTime=!!active&&now<Date.parse(session!.ends_at),c=active?session!.config:(d.difficulties?.find(m=>m.id===mode)?.config??d.config);
 const cooldown=Math.max(0,Date.parse(d.cooldown_until??"")-now)||0,requiredRounds=c.required_rounds??c.rounds,rewardXp=c.completion_xp??0,remainingRounds=Math.max(0,requiredRounds-(session?.participated_rounds??0));
 // Collapsing the entry cards must not leave mobile targets behind the fixed HUD.
 useEffect(()=>{
  if(!active||h.receipt?.action!=="start")return;
  const id=requestAnimationFrame(()=>{
   if(!board.current)return;
   const header=document.querySelector(".estate-header")?.getBoundingClientRect().height??0;
   window.scrollTo({top:window.scrollY+board.current.getBoundingClientRect().top-header-12,behavior:"instant"});
   board.current.querySelector<HTMLElement>(".range-lane")?.focus({preventScroll:true});
  });
  return()=>cancelAnimationFrame(id);
 },[active,h.receipt?.id,h.receipt?.action]);
 const raw=d.weapons.find(w=>active?w.id===session!.weapon_id:w.slot===slot)??(!active?d.weapons[0]:undefined);
 const weapon=raw&&active?{...raw,condition:Math.min(session!.weapon_rule.condition_max,raw.raw_condition??session!.weapon_rule.condition_max),condition_max:session!.weapon_rule.condition_max,wear_per_shot:session!.weapon_rule.wear_per_shot,ammo_good_id:session!.weapon_rule.ammo_good_id}:raw;
 const supplied=!!weapon&&!!d.ammo&&d.ammo.good_id===weapon.ammo_good_id&&d.ammo.quantity>0,ready=!!weapon?.enabled&&(weapon.condition??0)>0&&supplied&&d.season.status==="open"&&!!d.config.enabled;
 const magazine=weapon?.magazine;
 const automatic=weapon?.good_id==="m4-carbine";
 useEffect(()=>{if(!h.receipt||heard.current===h.receipt.id)return;heard.current=h.receipt.id;if(h.receipt.action==="fire")sound.shot(weapon?.good_id);else if(h.receipt.action==="reload"&&h.receipt.reload_ready_at&&h.receipt.reload_started_at){const duration=Date.parse(h.receipt.reload_ready_at)-Date.parse(h.receipt.reload_started_at),elapsed=Math.max(0,Date.parse(h.receipt.server_time)-Date.parse(h.receipt.reload_started_at));if(elapsed<duration)sound.reload(duration,elapsed,weapon?.good_id);}},[h.receipt,sound,weapon?.good_id]);
 useEffect(()=>{if(!magazine?.ready_at)return;const id=setTimeout(()=>h.refresh(),Math.max(0,Date.parse(magazine.ready_at)-h.clock()+80));return()=>clearTimeout(id);},[magazine?.ready_at,h.clock]);
 const reloading=!!magazine?.reloading,loaded=magazine?.loaded??0,capacity=magazine?.capacity??0,canReload=inTime&&ready&&!h.busy&&!reloading&&loaded<Math.min(capacity,d.ammo?.quantity??0);
 const reload=()=>{if(!canReload)return;sound.unlock(weapon?.good_id);void h.act("reload",{season_id:d.season.id,session_id:session!.id});};
 const settled=!session?.last_shot_at||now-Date.parse(session.last_shot_at)>=c.fire_interval_ms,canFire=inTime&&ready&&loaded>0&&!reloading&&settled&&!h.busy;
 const reason=!d.config.enabled?"The range is closed.":d.season.status!=="open"?"Practice resumes when the season opens.":!weapon?"Equip a primary or secondary weapon to enter.":!weapon.enabled?"This weapon is not approved for this range.":!weapon.condition?"Your weapon is broken. Equip another weapon.":!supplied?"Equip compatible bullets before firing.":"Your loadout is ready.";
 const finish=()=>h.act("finish",{season_id:d.season.id,session_id:session!.id});
 const fire=(x:number,y:number,elapsed:number)=>{if(canFire){sound.unlock(weapon?.good_id);void h.act("fire",{season_id:d.season.id,session_id:session!.id,x,y,elapsed_ms:elapsed});}};
 return <div className="range-page" onKeyDown={e=>{if(e.key.toLowerCase()==="r"&&!e.repeat&&!/^(INPUT|TEXTAREA|SELECT)$/.test((e.target as HTMLElement).tagName)){e.preventDefault();reload();}}}><header className="range-heading"><div><Link href="/dashboard">← Dashboard</Link><p className="range-kicker">BLACKWATER / TRAINING HALL</p><h1>Shooting Range</h1><p>Steady hands. Every shot counts.</p></div><span className={"range-open "+(d.config.enabled?"":"closed")}><i/>{d.config.enabled?"Range open":"Range closed"}</span></header>
 <div className="range-workspace"><section className="range-main"><section className={"range-entry"+(active?" training":"")} aria-label="Range difficulty"><header><div><p className="range-kicker">ADVANCED TRAINING</p><h2>{active?`${session!.difficulty==="advanced"?"Advanced":"Beginner"} practice`:"Step up to the firing line"}</h2></div><span><GameIcon name="clock" size={18}/>{Math.round((c.cooldown_seconds??600)/60)} min recovery</span></header><div className="range-difficulties range-advanced-only" role="radiogroup" aria-label="Choose range difficulty">{(d.difficulties??[]).filter(m=>m.id==="advanced").map(m=><button key={m.id} type="button" role="radio" aria-checked={(active?session!.difficulty:mode)===m.id} disabled={!!active||h.busy}><GameIcon name="target" size={30}/><span><strong>{m.name}</strong><small>{m.id==="advanced"?"Distant targets · Rapid movement":"Closer targets · Steady movement"}</small></span><b>Up to {m.config.completion_xp} XP</b></button>)}</div><p>{active&&session!.difficulty==="legacy"?"This session keeps its original rules. Completion XP starts with your next practice.":active?`${session!.participated_rounds??0} / ${requiredRounds} rounds practised. ${remainingRounds?"Fire in "+remainingRounds+" more rounds, then finish":"Stay until the timer ends"} to claim your score-based XP.`:`Higher scores earn more XP, up to ${rewardXp}. Finish the session and fire in ${requiredRounds} of ${c.rounds} rounds. Recovery applies after practice, including early exits.`}</p>{active&&<div className="range-xp-preview"><span>XP at current score <strong>{session!.score_xp??0} XP</strong></span><span>Last shot <strong>{formatRangeAccuracy(session!.last_shot?.accuracy_percent)}{session!.last_shot?"%":""}</strong></span><small>Earned on completion · Up to {rewardXp} XP</small></div>}{!active&&session&&<div className="range-session-result"><span>{session.difficulty==="advanced"?"Advanced":session.difficulty==="beginner"?"Beginner":"Previous"} session {session.status==="stopped"?"ended early":"recorded"}</span><strong>+{session.xp_awarded??0} XP</strong></div>}</section><section className="range-board" ref={board}><div className="range-scoreboard"><div><span>Round</span><strong>{active?Math.min(c.rounds,Math.floor(Math.max(0,now-Date.parse(session!.started_at))/(c.round_seconds*1000))+1):"—"} <small>/ {c.rounds}</small></strong></div><div className="range-time"><span>Time remaining</span><strong>{timer(active?Math.min(c.rounds*c.round_seconds*1000,Date.parse(session!.ends_at)-now):c.rounds*c.round_seconds*1000)}</strong></div><div><span>Score</span><strong>{session?.score.toLocaleString()??"0"}</strong></div><div><span>Accuracy</span><strong>{formatRangeAccuracy(session?.accuracy_percent??0)}<small>%</small></strong></div><div><span>Streak</span><strong>×{session?.streak??0}</strong></div></div>
 <div className="range-view-controls" role="group" aria-label="Range view"><button className="range-outline" aria-pressed={view==="3d"} onClick={()=>chooseView("3d")}>3D indoor range</button><button className="range-outline" aria-pressed={view==="2d"} onClick={()=>chooseView("2d")}>Classic targets</button><span>{view==="3d"?"Your weapon. Your firing booth. Every shot recorded.":"Original target range · precision training"}</span></div>{renderError&&<p className="range-render-error" role="status">3D rendering is unavailable on this device. Classic targets are ready with the same scoring.</p>}
 <div className="range-scene">{view==="3d"?<Range3DLane session={active?session:null} config={c} clock={h.clock} canFire={canFire} automatic={automatic} weapon={weapon?.good_id??null} magazine={magazine} onFire={fire} onUnavailable={()=>{setView("2d");setRenderError(true);}}/>:<RangeLane session={active?session:null} config={c} clock={h.clock} canFire={canFire} automatic={automatic} onFire={fire}/> }{!inTime&&<div className="range-intro"><GameIcon name="target" size={42}/><p className="range-kicker">{active?"TIME’S UP":session?"BACK TO THE FIRING LINE":"DISCIPLINE BUILDS POWER"}</p><h2>{active?"Session complete.":cooldown>0?"Let the smoke settle.":session?"Make your next shot count.":"Take your place."}</h2><p>{active?`${session!.score.toLocaleString()} points · ${formatRangeAccuracy(session!.accuracy_percent??0)}% accuracy`: `${c.rounds} rounds. ${c.targets_per_round} moving targets per round.`}</p>{active?<button className="range-gold" disabled={h.busy} onClick={()=>void finish()}>Record session <GameIcon name="arrow"/></button>:ready?<button className="range-gold" disabled={h.busy||cooldown>0} onClick={()=>{sound.unlock(weapon?.good_id);void h.act("start",{season_id:d.season.id,equipment_slot:weapon!.slot,difficulty:mode});}}>Start session <GameIcon name="arrow"/></button>:<Link className="range-gold" href="/inventory">Prepare your loadout <GameIcon name="arrow"/></Link>}<small>{active?"Your ammunition and weapon condition have been saved.":reason}</small>{!active&&cooldown>0&&<div className="range-cooldown" role="timer" aria-label="Range cooldown"><GameIcon name="clock" size={20}/>Next session in <strong>{timer(cooldown)}</strong></div>}</div>}{inTime&&reloading&&<div className="range-reload-progress" role="status"><strong>Reloading...</strong><progress aria-label="Reload progress" max={magazine!.reload_ms} value={Math.max(0,Math.min(magazine!.reload_ms,now-Date.parse(magazine!.started_at!)))}/><span>{Math.max(0,(Date.parse(magazine!.ready_at!)-now)/1000).toFixed(1)}s · Hold your fire</span></div>}</div>
 <footer className={"range-firebar"+(automatic?" range-automatic-fire":"")}><div><GameIcon name="ammo" size={23}/><strong>{d.ammo?.quantity.toLocaleString()??0}</strong><span>bullets equipped</span></div><div className="range-magazine-counter"><b>{loaded} / {capacity}</b><span>magazine · {magazine?.reserve??0} reserve</span></div><button className="range-outline range-reload-button" aria-label={reloading?"Reloading weapon":"Reload weapon"} aria-keyshortcuts="R" disabled={!canReload} onClick={reload}><GameIcon name="refresh" size={17}/>{reloading?"Reloading...":"Reload"}<kbd>R</kbd></button><p id="range-instructions">{automatic?"Hold to fire automatically.":"Click or tap to shoot."} <span>{automatic?"Move to aim · Hold click, touch or Space · R reloads":"Arrow keys aim · Space fires · R reloads"}</span></p><span className="range-action-state">{h.working?"Confirming shot…":h.retry?"Confirm last shot":!inTime?"Stand by":!ready?"Check loadout":reloading?"Reloading...":loaded===0?"Magazine empty - reload":settled?"Ready to fire":"Steady…"}</span></footer>
 </section>
 <div className={"range-feedback "+(h.failed?"error":"")} role={h.failed?"alert":"status"}>{h.notice||"One shot. One bullet. Weapon wear applies even when you miss."}{h.retry&&<button className="range-outline" disabled={h.working} onClick={()=>{sound.unlock(weapon?.good_id);void h.retryAction();}}>Retry safely</button>}<button className="range-refresh" aria-label="Refresh shooting range" disabled={h.working} onClick={h.refresh}><GameIcon name="refresh" size={18}/></button></div>
  <div className="range-audio-controls"><button className="range-outline" aria-label={sound.enabled?"Mute range sound":"Enable range sound"} aria-pressed={sound.enabled} onClick={sound.toggle}><GameIcon name={sound.enabled?"volume":"volume-off"} size={19}/>{sound.enabled?"Sound on":"Sound off"}</button><label>Volume<input aria-label="Range sound volume" type="range" min={0} max={100} step={5} value={sound.volume} onChange={e=>sound.setVolume(Number(e.target.value))}/><span>{sound.volume}%</span></label><span>{sound.error||"Gunfire · Reloads · Range ambience"}</span></div>
 <section className="range-rules"><div><GameIcon name="target"/><h3>Find the centre</h3><p>{c.hit_points}–{c.bullseye_points} points per hit. The closer to the centre, the higher your score. Accuracy measures precision: 100% at the centre, falling to 0% at the edge or on a miss. Each target scores once per round.</p></div><div><GameIcon name="pistol"/><h3>Care for your equipment</h3><p>Every shot uses one equipped bullet and reduces weapon condition. Reload when the magazine is empty. Worn weapons retain their condition in your inventory.</p></div><div><GameIcon name="trade"/><h3>Supply your next session</h3><p>Craft or trade for compatible ammunition. Equip your supplies before returning to the firing line.</p><Link href={`/market?view=inventory&good=${weapon?.ammo_good_id??"homemade-bullets"}`}>Visit player market →</Link></div></section>
 </section><aside className="range-sidebar"><section className="range-panel range-loadout"><header><h2>Your loadout</h2><Link href="/inventory">Inventory ↗</Link></header>{weapon?<><div className="range-weapon-art"><CommodityArtwork goodId={weapon.good_id} size={256}/></div><h3>{weapon.name}</h3><label>Equipped weapon<select aria-label="Range weapon" value={weapon.slot} disabled={!!active||h.busy} onChange={e=>setSlot(e.target.value)}>{d.weapons.map(w=><option key={w.id} value={w.slot}>{w.slot==="primary"?"Primary":"Secondary"} · {w.name}</option>)}</select></label><div className="range-condition"><span>Weapon condition</span><strong>{weapon.condition??0} / {weapon.condition_max??"—"}</strong><meter aria-label="Weapon condition" min={0} max={weapon.condition_max??100} value={weapon.condition??0}/></div><dl><div><dt>Wear per shot</dt><dd>{weapon.wear_per_shot??"—"}</dd></div><div><dt>Ammunition</dt><dd>{d.ammo?.good_id===weapon.ammo_good_id?d.ammo.name:weapon.ammo_name??"None equipped"}</dd></div><div><dt>Rounds equipped</dt><dd>{supplied?d.ammo!.quantity.toLocaleString():0}</dd></div></dl></>:<div className="range-empty"><GameIcon name="pistol" size={42}/><h3>No weapon equipped</h3><p>Open Inventory and equip a weapon with its compatible bullets.</p></div>}<p className={"range-loadout-status "+(ready?"ready":"")}>{reason}</p>{active&&<button className="range-outline" disabled={h.busy} onClick={()=>void finish()}>End session</button>}</section>
 <section className="range-panel"><header><h2>Your range record</h2><GameIcon name="target"/></header><div className="range-best"><strong>{d.stats.best_score.toLocaleString()}</strong><span>Best session score</span></div><dl><div><dt>Completion XP this season</dt><dd>{(d.stats.xp_earned??0).toLocaleString()} XP</dd></div><div><dt>Best accuracy</dt><dd>{formatRangeAccuracy(d.stats.best_accuracy)}%</dd></div><div><dt>Sessions recorded</dt><dd>{d.stats.sessions}</dd></div><div><dt>Shots fired</dt><dd>{d.stats.shots.toLocaleString()}</dd></div><div><dt>Targets hit</dt><dd>{d.stats.hits.toLocaleString()}</dd></div></dl></section>
 <section className="range-panel range-advanced-record"><header><h2>Advanced record</h2><GameIcon name="target"/></header><div className="range-best range-advanced-average"><strong>{formatRangeAccuracy(d.advanced_stats?.average_accuracy)}{d.advanced_stats?.average_accuracy!=null?"%":""}</strong><span>Average accuracy · {d.season.name}</span></div><p className="range-empty-copy">Bullseye precision across every recorded Advanced shot, including misses and early exits.</p><dl><div><dt>Attempts with shots</dt><dd>{d.advanced_stats?.sessions??0}</dd></div><div><dt>Shots recorded</dt><dd>{d.advanced_stats?.shots??0}</dd></div><div><dt>Best session accuracy</dt><dd>{formatRangeAccuracy(d.advanced_stats?.best_accuracy)}{d.advanced_stats?.best_accuracy!=null?"%":""}</dd></div><div><dt>Advanced XP earned</dt><dd>{d.advanced_stats?.xp_earned??0} XP</dd></div></dl></section>
 <section className="range-panel"><header><h2>Season marksmen</h2><GameIcon name="trophy"/></header>{d.leaders.length?<ol className="range-leaders">{d.leaders.map((p,i)=><li key={p.player_id}><span>{i+1}</span><PlayerAvatar src={p.avatar_url} name={p.username} size={28}/><Link href={"/players/"+p.player_id}>{p.username}</Link><strong>{p.score.toLocaleString()}</strong></li>)}</ol>:<p className="range-empty-copy">The firing line is waiting. Record the first score this season.</p>}<small>{d.season.name}</small></section>
 <section className="range-panel"><header><h2>Recent attempts</h2><GameIcon name="clock"/></header>{d.recent.length?<ol className="range-recent">{d.recent.map(r=><li key={r.id}><time dateTime={r.started_at}>{new Date(r.started_at).toLocaleDateString("en-GB",{day:"numeric",month:"short",timeZone:"UTC"})}</time><strong>{r.score.toLocaleString()}</strong><span>{formatRangeAccuracy(r.accuracy_percent)}{r.accuracy_percent!=null?"%":""}</span><small>{r.difficulty==="advanced"?"Advanced":r.difficulty==="beginner"?"Beginner":"Practice"} · +{r.xp_awarded??0} XP</small></li>)}</ol>:<p className="range-empty-copy">Your completed sessions will be recorded here.</p>}</section>
 {d.can_manage&&<Link className="range-owner-link" href="/owner?section=shooting-range"><GameIcon name="gear" size={18}/>Range Owner controls <GameIcon name="arrow" size={16}/></Link>}
 </aside></div></div>;
}
