"use client";
import {useEffect,useRef,useState} from "react";
import type {RangeConfig,RangeSession,RangeMagazine} from "@/lib/range";
import type {RangeScene} from "./range-scene";
type Props={session:RangeSession|null;config:RangeConfig;clock:()=>number;canFire:boolean;automatic:boolean;weapon:string|null;magazine:RangeMagazine|undefined;onFire:(x:number,y:number,elapsed:number)=>void;onUnavailable:()=>void};
export function Range3DLane(props:Props){
 const host=useRef<HTMLDivElement>(null),surface=useRef<HTMLDivElement>(null),engine=useRef<RangeScene|null>(null),latest=useRef(props),aim=useRef({x:.5,y:.5}),holding=useRef(false),lastAttempt=useRef(-Infinity),loopFire=useRef<()=>void>(()=>{}),reticle=useRef<HTMLSpanElement>(null);latest.current=props;
 const [ready,setReady]=useState(false),[loading,setLoading]=useState(true);
 function fire(){const p=latest.current,s=p.session;if(!engine.current||!p.canFire||!s||s.status!=="active"||document.hidden)return;const now=p.clock(),elapsed=Math.floor(now-Date.parse(s.started_at));if(now>=Date.parse(s.ends_at)||elapsed<0||performance.now()-lastAttempt.current<Math.max(100,p.config.fire_interval_ms))return;const point=engine.current.aim(aim.current.x,aim.current.y);if(point){lastAttempt.current=performance.now();p.onFire(point.x,point.y,elapsed);}}
 loopFire.current=fire;
 useEffect(()=>{
  let live=true,id=0,visible=true,lastFrame=0;const reduced=matchMedia("(prefers-reduced-motion: reduce)");const stop=()=>{holding.current=false;};const lost=()=>{if(live){stop();latest.current.onUnavailable();}};
  const observer=new IntersectionObserver(entries=>{visible=entries[0]?.isIntersecting??true;if(!visible)stop();});if(surface.current)observer.observe(surface.current);
  void import("./range-scene").then(({createRangeScene})=>{if(!live||!host.current)return;try{engine.current=createRangeScene(host.current,lost);setReady(true);setLoading(false);const frame=(t:number)=>{if(!live)return;id=requestAnimationFrame(frame);if(!visible||document.hidden||t-lastFrame<1000/45)return;lastFrame=t;const p=latest.current;try{engine.current?.render({session:p.session,config:p.config,weapon:p.weapon,magazine:p.magazine,now:p.clock(),aim:aim.current,reducedMotion:reduced.matches});}catch{lost();return;}if(holding.current&&p.automatic)loopFire.current();};id=requestAnimationFrame(frame);}catch{lost();}}).catch(lost);
  const visibility=()=>{if(document.hidden)stop();};window.addEventListener("blur",stop);document.addEventListener("visibilitychange",visibility);
  return()=>{live=false;cancelAnimationFrame(id);observer.disconnect();window.removeEventListener("blur",stop);document.removeEventListener("visibilitychange",visibility);engine.current?.dispose();engine.current=null;};
 },[]);
 useEffect(()=>{holding.current=false;lastAttempt.current=-Infinity;},[props.session?.id,props.session?.status,props.weapon]);
 function move(x:number,y:number){aim.current={x:Math.max(0,Math.min(1,x)),y:Math.max(0,Math.min(1,y))};if(reticle.current){reticle.current.style.left=aim.current.x*100+"%";reticle.current.style.top=aim.current.y*100+"%";}}
 const point=(e:React.PointerEvent)=>{const b=e.currentTarget.getBoundingClientRect();move((e.clientX-b.left)/b.width,(e.clientY-b.top)/b.height);};
 return <div ref={surface} className="range-lane range-3d-lane" role="button" tabIndex={0} aria-label="Shooting lane" aria-describedby="range-instructions" aria-disabled={!ready||!props.canFire} onPointerMove={e=>{if(e.isPrimary)point(e);}} onPointerDown={e=>{if(e.button!==0||!e.isPrimary)return;e.preventDefault();e.currentTarget.focus({preventScroll:true});point(e);e.currentTarget.setPointerCapture(e.pointerId);holding.current=props.automatic;fire();}} onPointerUp={e=>{holding.current=false;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{holding.current=false;}} onLostPointerCapture={()=>{holding.current=false;}} onBlur={()=>{holding.current=false;}} onKeyDown={e=>{const directions:Record<string,[number,number]>={ArrowLeft:[-.015,0],ArrowRight:[.015,0],ArrowUp:[0,-.015],ArrowDown:[0,.015]};const direction=directions[e.key];if(direction){e.preventDefault();move(aim.current.x+direction[0],aim.current.y+direction[1]);}if((e.key===" "||e.key==="Enter")&&!e.repeat){e.preventDefault();holding.current=e.key===" "&&props.automatic;fire();}if(e.key==="Escape")holding.current=false;}} onKeyUp={e=>{if(e.key===" "){e.preventDefault();holding.current=false;}}}>
 <div className="range-3d-canvas" ref={host}/><span className="range-lane-number">LANE 02 <i/> INDOOR TRAINING RANGE</span><span className="range-3d-reticle" aria-hidden="true" ref={reticle}/><span className="range-3d-weapon-label">{props.weapon==="m4-carbine"?"M4 CARBINE · AUTOMATIC":props.weapon?"PISTOL · SEMI-AUTO":"EQUIP YOUR WEAPON"}</span>{loading&&<span className="range-3d-loading" role="status">Preparing the 3D range…</span>}
 </div>;
}
