"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {RangeState} from "@/lib/range";
const labels:Record<string,string>={range_beginner_target_percent:"Beginner target size (%)",range_advanced_target_percent:"Advanced target size (%)",range_beginner_speed_percent:"Beginner speed (%)",range_advanced_speed_percent:"Advanced speed (%)",range_beginner_completion_xp:"Beginner completion XP",range_advanced_completion_xp:"Advanced completion XP",range_completion_round_percent:"Rounds with a shot required for XP (%)",range_cooldown_seconds:"Shared session cooldown (seconds)",range_enabled:"Range open (1) / closed (0)",range_rounds:"Rounds per session",range_round_seconds:"Seconds per round",range_targets_per_round:"Targets per round",range_move_amplitude:"Horizontal target movement",range_move_vertical:"Vertical target movement",range_move_speed:"Target speed (%)",range_radius_x:"Target width radius (%)",range_radius_y:"Target height radius (%)",range_hit_points:"Outer hit points",range_bullseye_points:"Bullseye points",range_bullseye_percent:"Bullseye radius (%)",range_fire_interval_ms:"Minimum time between shots (ms)",range_lag_tolerance_ms:"Network timing tolerance (ms)",range_actions_per_minute:"Range requests per minute"};
export function RangeOwner(){
 const [d,setData]=useState<RangeState|null>(null),[good,setGood]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{void createClient().rpc("range_state").then(r=>{if(r.error)setNotice("Range controls could not load.");else setData(r.data);});},[]);
 const save=async(action:string,payload:Record<string,unknown>)=>{setBusy(true);try{const r=await createClient().rpc("range_manage",{p_action:action,p_payload:payload});if(r.error||r.data?.error)throw new Error(r.data?.error||r.error?.message||"Save failed.");setNotice(r.data.message);setData(r.data.state);}catch(e){setNotice(e instanceof Error?e.message:"Save failed.");}finally{setBusy(false);}};
 if(!d?.management)return <section className="range-owner"><h2>Shooting range</h2><p>{notice||"Loading range controls…"}</p></section>;
 const m=d.management,weapons=m.goods.filter(g=>g.equipment_slots.some(s=>["primary","secondary"].includes(s))),selected=weapons.find(g=>g.id===good)??weapons[0],rule=m.weapons.find(w=>w.good_id===selected?.id),ammo=m.goods.filter(g=>g.equipment_slots.includes("ammo"));
 return <section className="range-owner"><h2>Shooting range</h2><p>Control Beginner and Advanced targets, completion XP, shared cooldown, scoring, ammunition compatibility and weapon wear. Active sessions keep their starting rules. Closing the range or disabling a weapon stops further shots immediately.</p>{notice&&<p role="status">{notice}</p>}
 <form key={selected?.id+":"+(rule?.version??0)} onSubmit={e=>{e.preventDefault();const v=new FormData(e.currentTarget);void save("weapon",{good_id:selected?.id,version:rule?.version??0,ammo_good_id:v.get("ammo"),condition_max:Number(v.get("maximum")),wear_per_shot:Number(v.get("wear")),magazine_capacity:Number(v.get("magazine")),reload_ms:Math.round(Number(v.get("reload"))*1000),enabled:v.get("enabled")==="on",reason:v.get("reason")});}}><h3>Weapon condition & ammunition</h3><label>Weapon<select aria-label="Edit range weapon" value={selected?.id??""} disabled={busy} onChange={e=>setGood(e.target.value)}>{weapons.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Ammunition<select name="ammo" defaultValue={rule?.ammo_good_id??ammo[0]?.id} disabled={busy} required>{ammo.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><div className="range-owner-grid"><label>Maximum condition<input name="maximum" type="number" min={1} max={10000} defaultValue={rule?.condition_max??100} required disabled={busy}/></label><label>Condition lost per shot<input name="wear" type="number" min={1} max={10000} defaultValue={rule?.wear_per_shot??1} required disabled={busy}/></label></div><div className="range-owner-grid"><label>Magazine capacity<input name="magazine" type="number" min={1} max={1000} defaultValue={rule?.magazine_capacity??10} required disabled={busy}/></label><label>Reload time (seconds)<input name="reload" type="number" min={.5} max={15} step={.1} defaultValue={(rule?.reload_ms??1800)/1000} required disabled={busy}/></label></div><label><span><input name="enabled" type="checkbox" style={{width:20,minHeight:20}} defaultChecked={rule?.enabled??true} disabled={busy}/> Weapon enabled</span></label><label>Weapon audit reason<input name="reason" minLength={5} maxLength={500} required disabled={busy}/></label><button className="range-gold" disabled={busy||!selected||!ammo.length}>Save weapon rules</button></form>
 <form key={JSON.stringify(m.settings)} onSubmit={e=>{e.preventDefault();const v=new FormData(e.currentTarget);void save("settings",{settings:Object.fromEntries(m.settings.map(s=>[s.key,Number(v.get(s.key))])),reason:v.get("reason")});}}><h3>Sessions & moving targets</h3><div className="range-owner-grid">{m.settings.map(s=><label key={s.key}>{labels[s.key]??s.key}<input name={s.key} type="number" min={s.minimum} max={s.maximum} step={1} defaultValue={s.value} required disabled={busy}/><small>{s.minimum}–{s.maximum}</small></label>)}</div><label>Settings audit reason<input name="reason" minLength={5} maxLength={500} required disabled={busy}/></label><button className="range-gold" disabled={busy}>Save range settings</button></form></section>;
}
