"use client";
import {useEffect,useRef,useState,type ReactNode} from "react";
import Link from "next/link";
import {GameIcon} from "@/components/game-icon";
import {CommodityArtwork} from "@/components/commodity-artwork";
import {useRefinery} from "@/components/use-refinery";
import {refiningQuote,type Refinery,type RefineryState,type Recipe} from "@/lib/refineries";
import {money} from "@/lib/game";
type Action=(action:string,payload:Record<string,unknown>)=>Promise<boolean>;
type Order={kind:"buy"|"refine";title:string;payload:Record<string,unknown>;lines:[string,string][]};
function Panel({title,children,className=""}:{title:string;children:ReactNode;className?:string}){return <section className={"ref-panel "+className}><header><h2>{title}</h2></header>{children}</section>;}
const location=(r:Refinery)=>"/districts/"+r.district_slug+"?tab=Plots&plot="+r.plot_id;
function OwnerControls({r,data,busy,act}:{r:Refinery;data:RefineryState;busy:boolean;act:Action}){
 const [mode,setMode]=useState(r.fee_mode),[cash,setCash]=useState(r.cash_fee),[share,setShare]=useState(r.output_percent),[status,setStatus]=useState(r.status),[fuel,setFuel]=useState(data.recipes[0]?.fuel_good_id??""),[qty,setQty]=useState(1);
 const fuels=[...new Set([...data.recipes.map(x=>x.fuel_good_id),...Object.keys(r.fuel)])],name=(id:string)=>data.goods.find(g=>g.id===id)?.name??id;
 const base={refinery_id:r.id,version:r.version,plot_version:r.plot_version};
 return <div className="ref-management"><Panel title="Your terms"><form onSubmit={e=>{e.preventDefault();void act("settings",{...base,fee_mode:mode,cash_fee:cash,output_percent:share,status});}}>
 <label>Charge customers<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="cash">Money per batch</option><option value="output">A share of refined output</option></select></label>
 <div className="ref-form-grid"><label>Cash fee per batch<input type="number" required min={0} max={data.settings.refinery_max_cash_fee} step={1} value={cash} onChange={e=>setCash(Number(e.target.value))}/></label><label>Refined output share (%)<input type="number" required min={0} max={data.settings.refinery_max_output_percent} step="0.01" value={share} onChange={e=>setShare(Number(e.target.value))}/></label></div>
 <label>Refinery status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Open to customers</option><option value="closed">Closed</option></select></label>
 <p className="ref-help">Only the selected fee applies. Output fees round up to whole items. Your own refining pays no service fee, but still consumes ore and fuel.</p>
 <button className="ref-gold" disabled={busy}>Save refining terms →</button></form></Panel>
 <Panel title="The fuel bunker"><p>You supply the fuel for every customer. Buy coal from other players, then load it here.</p>
 <div className="ref-form-grid"><label>Fuel<select value={fuel} onChange={e=>setFuel(e.target.value)}>{fuels.map(g=><option key={g} value={g}>{name(g)}</option>)}</select></label><label>Fuel quantity<input type="number" min={1} max={data.settings.refinery_fuel_capacity} value={qty} step={1} onChange={e=>setQty(Number(e.target.value))}/></label></div>
 <dl className="ref-facts"><div><dt>In your inventory</dt><dd>{(data.inventory[fuel]??0).toLocaleString()} {name(fuel)}</dd></div><div><dt>In this bunker</dt><dd>{(r.fuel[fuel]??0).toLocaleString()} {name(fuel)}</dd></div><div><dt>Total bunker capacity</dt><dd>{data.settings.refinery_fuel_capacity.toLocaleString()}</dd></div></dl>
 <div className="ref-buttons"><button className="ref-gold" disabled={busy||!Number.isInteger(qty)||qty<1||qty>(data.inventory[fuel]??0)} onClick={()=>void act("stock",{...base,good_id:fuel,quantity:qty})}>Load fuel</button><button className="ref-outline" disabled={busy||!Number.isInteger(qty)||qty<1||qty>(r.fuel[fuel]??0)} onClick={()=>void act("withdraw",{...base,good_id:fuel,quantity:qty})}>Withdraw fuel</button></div>
 <Link className="ref-market-link" href={"/market?good="+fuel}>Buy {name(fuel).toLowerCase()} on the player market →</Link><p className="ref-help">Bunker stock belongs to the property and transfers with a sale. Withdraw it before listing if you want to keep it.</p></Panel>
 <Panel title="Revenue this season"><div className="ref-income"><span>CASH FEES EARNED<strong>{money(r.my_cash_revenue)}</strong></span><span>REFINED GOODS KEPT<strong>{Object.values(r.my_output_revenue).reduce((a,b)=>a+b,0).toLocaleString()}</strong></span></div>{Object.entries(r.my_output_revenue).filter(([,n])=>n>0).map(([g,n])=><p key={g}>{n.toLocaleString()} {name(g)}</p>)}<p className="ref-help">Gross receipts earned by you at this refinery. Fuel costs reduce profit. Cash goes straight to your wallet; your output share goes straight to inventory.</p><div className="ref-buttons"><Link href="/ledger">Cash ledger ↗</Link><Link href="/market?view=inventory">Sell your output ↗</Link><Link href={location(r)}>Sell or auction property ↗</Link></div></Panel></div>;
}
function Service({r,data,busy,order}:{r:Refinery;data:RefineryState;busy:boolean;order:(o:Order)=>void}){
 const enabled=data.recipes.filter(x=>x.enabled),[id,setId]=useState(enabled[0]?.id??""),[batches,setBatches]=useState(1);
 const recipe=enabled.find(x=>x.id===id),own=r.owner_type==="player"&&r.owner_id===data.player_id,name=(id:string)=>data.goods.find(g=>g.id===id)?.name??id;
 const q=recipe?refiningQuote(r,recipe,batches,own):null;
 const available=r.owner_type==="player"&&r.status==="open"&&!r.locked;
 const enough=!!q&&!!recipe&&Number.isInteger(batches)&&batches>0&&batches<=data.settings.refinery_max_batches&&q.take>0&&q.input<=(data.inventory[recipe.input_good_id]??0)&&q.fuel<=(r.fuel[recipe.fuel_good_id]??0)&&q.cash<=data.cash;
 return <Panel title="Refine your ore"><p className="ref-intro">Raw materials in. A more valuable haul out.</p>
 <form onSubmit={e=>{e.preventDefault();if(!recipe||!q)return;order({kind:"refine",title:"Confirm this refining order",payload:{refinery_id:r.id,version:r.version,plot_version:r.plot_version,recipe_id:recipe.id,recipe_version:recipe.version,batches},lines:[["Refinery",r.name],["You supply",q.input+" "+name(recipe.input_good_id)],["You receive",q.take+" "+name(recipe.output_good_id)],["Owner keeps",q.share+" "+name(recipe.output_good_id)],["Cash fee",money(q.cash)],["Owner’s fuel burned",q.fuel+" "+name(recipe.fuel_good_id)]]});}}>
 <div className="ref-form-grid"><label>Refining recipe<select value={recipe?.id??""} onChange={e=>setId(e.target.value)}>{!recipe&&<option value="">No enabled recipes</option>}{enabled.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Batches<input type="number" min={1} max={data.settings.refinery_max_batches} step={1} required value={batches} onChange={e=>setBatches(Number(e.target.value))}/></label></div>
 {recipe&&q&&<><div className="ref-process"><div><CommodityArtwork goodId={recipe.input_good_id} size={76}/><strong>{q.input.toLocaleString()}</strong><span>{name(recipe.input_good_id)}</span><small>{data.inventory[recipe.input_good_id]??0} in your inventory</small></div><span className="ref-process-arrow"><GameIcon name="flame" size={23}/><span>→</span><small>{q.fuel} {name(recipe.fuel_good_id)}</small></span><div><CommodityArtwork goodId={recipe.output_good_id} size={76}/><strong>{q.take.toLocaleString()}</strong><span>{name(recipe.output_good_id)}</span><small>Your take after the fee</small></div></div>
 <dl className="ref-facts"><div><dt>Your cash fee</dt><dd>{money(q.cash)}</dd></div><div><dt>Owner’s output share</dt><dd>{q.share} {name(recipe.output_good_id)}</dd></div><div><dt>Owner’s fuel stock</dt><dd>{r.fuel[recipe.fuel_good_id]??0} {name(recipe.fuel_good_id)}</dd></div></dl></>}
 <p className="ref-help">{!available?"This refinery needs a player owner, an open business and an accessible district before it can serve customers.":!enough?"Check your ore, cash and the refinery’s fuel stock. The owner must supply enough fuel for the whole order.":own?"You own this refinery. Only your ore and bunker fuel will be used.":"The whole order settles together. Review the quote before any ore, fuel or money moves."}</p>
 <button className="ref-gold" disabled={busy||!available||!enough}>Review refining order <span>→</span></button></form>
 <div className="ref-buttons"><Link href="/districts/mines-and-quarries">Mine more ore ↗</Link><Link href={"/market?good="+(recipe?.input_good_id??"iron-ore")}>Buy ore on the market ↗</Link></div></Panel>;
}
function Confirm({order,close,h}:{order:Order;close:()=>void;h:ReturnType<typeof useRefinery>}){
 const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{dialog.current?.showModal();},[]);
 return <dialog className="command-modal ref-modal" ref={dialog} onCancel={e=>{if(h.working)e.preventDefault();else close();}} aria-labelledby="ref-order-title"><button className="ref-close" disabled={h.working} onClick={close} aria-label="Close order">×</button><p className="eyebrow">BLACKWATER / CONFIRM THE DEAL</p><h2 id="ref-order-title">{order.title}</h2><dl className="ref-facts">{order.lines.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{h.notice&&<p role={h.failed?"alert":"status"}>{h.notice}</p>}{order.kind==="buy"&&<p className="ref-help">The plot, refinery business and any fuel in the bunker transfer together. You will need to supply fuel before serving customers.</p>}{h.retry?<button className="ref-gold" disabled={h.working} onClick={async()=>{if(await h.retryAction())close();}}>Retry safely</button>:<button className="ref-gold" disabled={h.busy} onClick={async()=>{if(await h.act(order.kind,order.payload))close();}}>{h.working?"Confirming…":order.kind==="buy"?"Confirm purchase":"Confirm refining"}</button>}</dialog>;
}
export function RefineryWorkspace({initial,initialPlot}:{initial:RefineryState;initialPlot?:string}){
 const h=useRefinery(initial),data=h.data!,[selected,setSelected]=useState(initial.refineries.find(x=>x.plot_id===initialPlot)?.id??initial.refineries[0]?.id??""),[tab,setTab]=useState("service"),[order,setOrder]=useState<Order|null>(null);
 const r=data.refineries.find(x=>x.id===selected),own=r?.owner_type==="player"&&r.owner_id===data.player_id;
 const playable=data.playable&&(!data.season.ends_at||Date.parse(data.season.ends_at)>h.now),busy=h.busy||!playable;
 const name=(id:string)=>data.goods.find(g=>g.id===id)?.name??id;
 return <div className="ref-page" data-feature="refinery-v1"><nav className="ref-breadcrumb"><Link href="/dashboard">← Dashboard</Link><span>/</span><Link href="/districts">City map</Link><span>/ REFINERIES</span>{data.can_manage&&<Link href="/owner?section=refineries">Owner controls ↗</Link>}</nav>
 <header className="ref-hero"><div><p className="eyebrow">BLACKWATER / PLAYER-OWNED INDUSTRY</p><h1>Ore becomes opportunity.</h1><p>Supply the fire. Set your terms.<br/>Build a business on the work of the city.</p></div><span className="ref-seal"><GameIcon name="production" size={29}/>THE REFINERY EXCHANGE</span></header>
 <div className="ref-summary"><span><GameIcon name="property"/><b>{data.refineries.length}</b> registered refineries</span><span><GameIcon name="people"/><b>{data.refineries.filter(x=>x.owner_type==="player").length}</b> player owned</span><span><GameIcon name="coins"/><b>{money(data.cash)}</b> your cash</span><span>{data.season.name}</span></div>
 {h.notice&&!order&&<div className={"ref-notice "+(h.failed?"error":"")} role={h.failed?"alert":"status"}>{h.notice}{h.retry&&<button disabled={h.working} onClick={()=>void h.retryAction()}>Retry safely</button>}</div>}
 {!playable&&<p className="ref-notice">The season is closed for gameplay.</p>}
 <div className="ref-layout"><aside><Panel title="The refinery register"><button className="ref-refresh" onClick={h.refresh}>Refresh refineries ↻</button>{data.refineries.map(x=><button className={"ref-registry "+(x.id===selected?"active":"")} key={x.id} onClick={()=>{setSelected(x.id);setTab("service");}}><GameIcon name="production" size={25}/><span><strong>{x.name}</strong><small>{x.district_name} · {x.code}</small><em>{x.for_sale?"FOR SALE":x.owner_id===data.player_id?"YOUR REFINERY":x.locked?"LOCKDOWN":x.status.toUpperCase()}</em></span></button>)}{!data.refineries.length&&<p>No refineries are registered in the open districts.</p>}</Panel><div className="ref-principle"><span className="eyebrow">A PLAYER-DRIVEN ECONOMY</span><h3>From the seam<br/>to the furnace.</h3><p>Miners supply ore and coal. Refinery owners supply the service. Players set the price.</p><Link href="/market">Open the player market →</Link></div></aside>
 <div className="ref-main">{r?<><section className="ref-panel ref-heading"><div><span className="eyebrow">{r.district_name.toUpperCase()} / PLOT {r.code}</span><h2>{r.name}</h2><p>Owner: {r.owner_type==="player"?<Link href={"/players/"+r.owner_id}>{own?"You":r.owner_name}</Link>:r.owner_name}</p></div><Link className="ref-outline" href={location(r)}>View property →</Link></section>
 {r.for_sale&&!own&&!r.auction&&<div className="ref-sale"><div><span className="eyebrow">ACQUIRE THE BUSINESS</span><strong>{money(r.price+Math.ceil(r.price*r.tax_rate/100))}</strong><small>Includes {money(Math.ceil(r.price*r.tax_rate/100))} district tax</small></div><button className="ref-gold" disabled={busy||r.locked||data.cash<r.price+Math.ceil(r.price*r.tax_rate/100)} onClick={()=>setOrder({kind:"buy",title:"Buy "+r.name+"?",payload:{refinery_id:r.id,plot_version:r.plot_version,total:r.price+Math.ceil(r.price*r.tax_rate/100)},lines:[["Property",r.code+" · "+r.district_name],["Price",money(r.price)],["District tax",money(Math.ceil(r.price*r.tax_rate/100))],["Total",money(r.price+Math.ceil(r.price*r.tax_rate/100))],["Fuel included",Object.entries(r.fuel).map(([g,n])=>n+" "+name(g)).join(", ")||"Empty bunker"]]})}>Buy refinery →</button></div>}
 {r.auction&&<p className="ref-notice">This property is at auction. <Link href={location(r)}>View the auction →</Link></p>}
 <nav className="ref-tabs" aria-label="Refinery sections">{[["service","Refining service"],...(own?[["manage","Manage refinery"]]:[]),["history","Your receipts"]].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 <div className="ref-terms"><span><GameIcon name="coins" size={18}/>{own?"Your own refining is fee-free":r.fee_mode==="cash"?money(r.cash_fee)+" per batch":r.output_percent+"% of refined output"}</span><span><GameIcon name="flame" size={18}/> Fuel supplied by the owner</span></div>
 {tab==="service"?<Service key={r.id} r={r} data={data} busy={busy} order={setOrder}/>:tab==="manage"&&own?<OwnerControls key={r.id+":"+r.version} r={r} data={data} busy={busy} act={h.act}/>:<Panel title="Your refining receipts"><div className="ref-history">{data.history.filter(x=>x.refinery_id===r.id).map(x=><article key={x.id}><CommodityArtwork goodId={x.output_good_id} size={48}/><div><strong>{x.input_quantity} {name(x.input_good_id)} → {x.output_quantity} {name(x.output_good_id)}</strong><p>{x.customer_id===data.player_id?"You received "+x.customer_quantity+" "+name(x.output_good_id):"Your fee: "+money(x.cash_fee)+" / "+x.owner_quantity+" "+name(x.output_good_id)}</p><small>{x.fuel_quantity} {name(x.fuel_good_id)} burned · {new Date(x.created_at).toLocaleString()}</small></div></article>)}{!data.history.some(x=>x.refinery_id===r.id)&&<p>No orders involving you at this refinery yet.</p>}</div></Panel>}</>:<Panel title="Refinery unavailable"><p>Choose a refinery from the register.</p></Panel>}</div></div>
 {order&&<Confirm order={order} close={()=>setOrder(null)} h={h}/>}</div>;
}
