"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {robberyRuleFields,type RobberyRules,type RobberyState} from "@/lib/robbery";
import "./robbery.css";
export function RobberyOwner(){
 const [data,setData]=useState<RobberyState|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{const r=await createClient().rpc("robbery_state");if(r.error||!r.data)throw new Error("Robbery controls could not load.");setData(r.data);};
 useEffect(()=>{void load().catch(e=>setNotice(e.message));},[]);
 const save=async(action:string,payload:Record<string,unknown>)=>{if(busy||!data)return;setBusy(true);setNotice("");try{const r=await createClient().rpc("robbery_action",{p_action:action,p_payload:{...payload,season_id:data.season_id}});if(r.error)throw new Error("Reply interrupted. Refresh the controls before saving again.");if(r.data?.error)throw new Error(r.data.error);setNotice(r.data.message);await load();}catch(e){setNotice(e instanceof Error?e.message:"Could not save.");}finally{setBusy(false);}};
 return <section className="robbery-owner"><h2>Player robberies</h2><p>Only carried cash can be stolen. All attempts use server-side rolls, shared victim protection and immutable records. Gear bonuses apply once per equipped slot; ammunition quantity never multiplies a bonus.</p>{notice&&<p role="status">{notice}</p>}<button className="bin-outline" disabled={busy} onClick={()=>void load().catch(e=>setNotice(e.message))}>Refresh robbery controls</button>
 {!data?<p>Loading rules…</p>:!data.management?<p>Owner robbery permission required.</p>:<><form key={data.rules.version} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const rules=Object.fromEntries(robberyRuleFields.map(([key])=>[key,Number(f.get(key))])) as Partial<RobberyRules>;rules.enabled=f.get("enabled")==="on";void save("configure",{version:data.rules.version,rules,reason:f.get("reason")});}}><h3>Chance, ammunition & protection</h3><label className="robbery-toggle"><input name="enabled" type="checkbox" defaultChecked={data.rules.enabled}/>Enable player robberies</label><div className="robbery-owner-fields">{robberyRuleFields.map(([key,label,min,max])=><label key={key}>{label}<input name={key} type="number" min={min} max={max} step={1} defaultValue={data.rules[key]} required disabled={busy}/></label>)}</div><p>Bullet use is randomly rolled inclusively between the limits on every valid attempt, successful or not. Attackers must have the maximum available. Zero bullets represents a gun-only threat. Cash limits stay within 1–80%.</p><p>Success starts at the base chance. Relative Sharpshooting level, advanced bullseye accuracy, power and condition-adjusted equipment modify it, then the minimum and maximum chances apply.</p><label>Audit reason<input name="reason" minLength={5} maxLength={500} required disabled={busy}/></label><button className="bin-gold" disabled={busy}>Save robbery rules</button></form>
 <h3>Equipped item influence</h3><p>Attack bonuses oppose the victim’s defense bonuses. Worn items contribute proportionally less; pristine items use full strength. Compatible gun, ammunition and wear rules remain in Shooting range controls.</p>{data.management.gear.map(g=><form key={g.id+":"+g.version} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save("gear",{good_id:g.id,version:g.version,attack:Number(f.get("attack")),defense:Number(f.get("defense")),condition_max:Number(f.get("condition_max")),reason:f.get("reason")});}}><h3>{g.name}</h3><div className="robbery-owner-fields"><label>Attack bonus<input name="attack" type="number" min={0} max={1000} step={1} defaultValue={g.attack} required/></label><label>Defense bonus<input name="defense" type="number" min={0} max={1000} step={1} defaultValue={g.defense} required/></label><label>Full condition<input name="condition_max" type="number" min={1} max={10000} step={1} defaultValue={g.condition_max} required/></label></div><label>Audit reason<input name="reason" minLength={5} maxLength={500} required/></label><button className="bin-gold" disabled={busy}>Save {g.name} influence</button></form>)}</>}
 </section>;
}
