"use client";
import {useEffect,useState} from "react";
import type {ScavengingState} from "@/lib/scavenging";
import {GameIcon} from "./game-icon";
type Props={state?:ScavengingState;district?:{id:string;name:string};now:number;busy:boolean;blocked:boolean;cooldown:number;lockpicks:number;act:(action:string,payload?:Record<string,unknown>)=>Promise<boolean>};
export function ScavengingChoices({state,district,now,busy,blocked,cooldown,lockpicks,act}:Props){
 const [queued,setQueued]=useState<string|null>(null);
 const session=state?.session,entered=!!session&&session.district_id===district?.id,pending=entered?session.pending:null,pursuit=entered?state?.operations?.pursuit:null;
 const travelling=entered&&Date.parse(session.arrives_at)>now,remaining=pending?Math.max(0,Math.ceil((Date.parse(pending.ready_at)-now)/1000)):0;
 useEffect(()=>{setQueued(null);},[district?.id]);
 useEffect(()=>{if(!queued||busy||blocked||travelling||pending)return;const target=state?.targets.find(t=>t.id===queued);setQueued(null);if(target&&session?.node===target.node)void act('scav_search',{target_id:target.id});},[queued,busy,blocked,travelling,pending,state,session,act]);
 const search=async(id:string)=>{const target=state?.targets.find(t=>t.id===id);if(!target)return;if(await act('scav_move',{node:target.node}))setQueued(id);};
 return <section className="simple-scav" aria-label="District scavenging"><header><p className="eyebrow">CHOOSE YOUR NEXT SEARCH</p><h2>{district?.name??'Choose a district'}</h2><p>Choose a location. Travel and searching take a little time. Finished searches send finds straight to Inventory.</p></header>
 {!entered?<button className="bin-gold" disabled={busy||blocked||!district} onClick={()=>void act('scav_enter',{district_id:district?.id})}>Enter {district?.name??'district'}</button>:pursuit?<div className="simple-scav-status" role="status"><h3>Police pursuit</h3><p>Police spotted you. Reach the district exit to escape, or surrender.</p><button className="bin-gold" disabled={busy||blocked||travelling} onClick={()=>void act(session.node===0?'scav_escape':'scav_move',session.node===0?{}:{node:0})}>{travelling?'Heading to the exit…':session.node===0?'Escape district':'Run to the exit'}</button><button className="bin-outline" disabled={busy} onClick={()=>void act('scav_abandon')}>Surrender</button></div>:<>
 {(pending||travelling||queued)&&<div className="simple-scav-status" role="status"><h3>{pending?'Searching…':'Travelling to your search…'}</h3><p>{pending?remaining?remaining+' seconds remaining. Keep watch for police.':'Adding your find to Inventory…':'You will start searching when you arrive.'}</p>{pending&&<><progress aria-label="Search progress" max={100} value={Math.max(0,Math.min(100,(now-Date.parse(pending.started_at))/Math.max(1,Date.parse(pending.ready_at)-Date.parse(pending.started_at))*100))}/><button className="bin-outline" disabled={busy} onClick={()=>{setQueued(null);void act('scav_cancel');}}>Cancel search</button>{!remaining&&<button className="bin-outline" disabled={busy} onClick={()=>void act('scav_finish',{attempt_id:pending.id})}>{pending.mode==='theft'?'Start getaway':'Retry collection'}</button>}</>}</div>}
 {cooldown>0&&!pending&&<p role="status">Next search in {cooldown}s.</p>}
 <div className="simple-scav-grid">{state?.targets.map((target,index)=>{const restock=target.ready_at&&Date.parse(target.ready_at)>now,car=target.kind==='car';return <article key={target.id}><GameIcon name={car?'lock':'bin'} size={30}/><h3>{car?'Parked car':'Street bin'} {index+1}</h3><p>{state.streets[Math.floor(target.node/5)]??district?.name}</p><small>{car?'Requires 1 lockpick · Earn Lockpicking XP':'No tool needed · Chance of loot or cash'}</small><button className="bin-gold" disabled={busy||blocked||!!pending||!!queued||travelling||cooldown>0||!!restock||(car&&!lockpicks)} onClick={()=>void search(target.id)}>{restock?'Already searched':car&&!lockpicks?'Lockpick required':car?'Lockpick car':'Search bin'}</button></article>;})}</div></>}
 </section>;
}
