"use client";
import {useEffect,useState,useRef} from "react";
import {FirstPersonStreet} from "./first-person-street";
import {ScavengingPolice} from "./scavenging-police";
import {ScavengingStreetLife} from "./scavenging-street-life";
import {GameIcon} from "./game-icon";
import {streetPoint,walkingPosition,nearestStreetPosition,mapPoint,sessionDestination,STREET_ROWS,type StreetPosition,type ScavengingState} from "@/lib/scavenging";
import {eventNames} from "@/lib/street-operations";
import {money} from "@/lib/game";
import {binCountdown} from "@/lib/bin-diving";
import "./scavenging.css";
import "./scavenging-map-art.css";

type Props={season:string;state?:ScavengingState;district:{id:string;name:string;image_url:string}|undefined;now:number;busy:boolean;blocked:boolean;cooldown:number;lockpicks:number;act:(action:string,payload?:Record<string,unknown>)=>Promise<boolean>};
export function ScavengingMap({season,state,district,now,busy,blocked,cooldown,lockpicks,act}:Props){
 const [firstPerson,setFirstPerson]=useState(false);
 const [selected,setSelected]=useState<string|null>(null),[queued,setQueued]=useState<StreetPosition|null>(null),[frame,setFrame]=useState(now),[zoom,setZoom]=useState(1),[streetLife,setStreetLife]=useState(true);
 const session=state?.session,ops=state?.operations;
 const [garage,setGarage]=useState("");
 const workspace=useRef<HTMLDivElement>(null),mapViewport=useRef<HTMLDivElement>(null);
 const [fit,setFit]=useState({width:640,height:440,header:76});
 useEffect(()=>{const start=performance.now();let id:number;const tick=()=>{setFrame(now+performance.now()-start);id=requestAnimationFrame(tick);};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[now]);
 useEffect(()=>{setSelected(null);setQueued(null);setZoom(1);},[district?.id]);
 const entered=!!session&&session.district_id===district?.id;
 useEffect(()=>{
  if(firstPerson||!entered||!workspace.current||!mapViewport.current)return;
  const root=workspace.current,viewport=mapViewport.current,header=document.querySelector('.estate-header'),toolbar=root.querySelector('.scav-map-toolbar'),desk=root.querySelector('.scav-action-desk');
  const resize=()=>{const headerHeight=header?.getBoundingClientRect().height??76;const available=Math.max(120,window.innerHeight-headerHeight-(toolbar?.getBoundingClientRect().height??70)-(desk?.getBoundingClientRect().height??180)-24);const width=Math.min(viewport.clientWidth,available*1000/680);setFit(old=>old.width===width&&old.height===available&&old.header===headerHeight?old:{width,height:available,header:headerHeight});};
  const observer=new ResizeObserver(resize);for(const element of [viewport,header,toolbar,desk])if(element)observer.observe(element);
  resize();const frame=requestAnimationFrame(()=>window.scrollTo({top:window.scrollY+root.getBoundingClientRect().top-(header?.getBoundingClientRect().height??76)-8,behavior:'instant'}));window.addEventListener('resize',resize);
  return()=>{observer.disconnect();cancelAnimationFrame(frame);window.removeEventListener('resize',resize);};
 },[entered,district?.id,firstPerson]);
 const moving=entered&&Date.parse(session.arrives_at)>frame;
 const pending=entered?session.pending:null,pursuit=entered?ops?.pursuit:null,event=entered?ops?.event:null;
 const atEvent=!!event&&entered&&!moving&&sessionDestination(session)[0]===event.node%5&&sessionDestination(session)[1]===Math.floor(event.node/5);
 const exitReady=!!pursuit&&entered&&!moving&&sessionDestination(session)[0]===0&&sessionDestination(session)[1]===0&&frame>=Date.parse(pursuit.started_at)+pursuit.rules.scavenging_escape_min_seconds*1000;
 const target=entered?state?.targets.find(t=>t.id===selected):undefined;
 const atTarget=!!target&&entered&&sessionDestination(session)[0]===target.node%5&&sessionDestination(session)[1]===Math.floor(target.node/5)&&!moving;
 const searched=target?.ready_at?Date.parse(target.ready_at)>frame:false;
 const remaining=pending?Math.max(0,Math.ceil((Date.parse(pending.ready_at)-frame)/1000)):0;
 const point=entered?walkingPosition(session,frame):streetPoint(0);
 const travel=(position:StreetPosition)=>{if(!entered||blocked||pending)return;setSelected(null);setQueued(position);};
 const choose=(id:string)=>{const site=state?.targets.find(t=>t.id===id);if(site)travel([site.node%5,Math.floor(site.node/5)]);setSelected(id);};
 useEffect(()=>{if(queued===null||!entered||busy||blocked||pending)return;const timer=setTimeout(()=>{setQueued(null);void act("scav_move",{x:queued[0],y:queued[1]});},120);return()=>clearTimeout(timer);},[queued,entered,busy,blocked,pending,act]);
 const streets=[0,1,2].map((n)=>state?.streets[n]??[`${district?.name??"District"} Road`,"Lantern Street","Foundry Lane"][n]);
 if(firstPerson&&entered&&state)return <FirstPersonStreet state={state} season={season} district={district?.name??"Blackwater"} now={now} busy={busy} blocked={blocked} cooldown={cooldown} lockpicks={lockpicks} act={act} close={()=>setFirstPerson(false)}/>;
 return <div ref={workspace} className={"scav-workspace"+(pursuit?" pursued":"")} style={{scrollMarginTop:fit.header+8}}>
 <div className="scav-map-toolbar"><span><i className="scav-dot-key"/>{district?.name}<span className="scav-key">{pursuit?"POLICE PURSUIT":(state?.patrols?.length??0)+" patrols · "+lockpicks+" lockpicks"}</span></span><div>{entered&&<button className="bin-gold scav-street-enter" onClick={()=>setFirstPerson(true)}>First-person streets</button>}<button aria-label="Street activity" title="Toggle background street activity" aria-pressed={streetLife} onClick={()=>setStreetLife(v=>!v)}>◌</button><button aria-label="Zoom out" disabled={zoom===1} onClick={()=>setZoom(z=>Math.max(1,z-.25))}>−</button><button aria-label="Zoom in" disabled={zoom===2} onClick={()=>setZoom(z=>Math.min(2,z+.25))}>+</button></div></div>
 {!entered?<div className="scav-entry" style={{backgroundImage:`linear-gradient(90deg,#071316e8,#07131666),url(/art/scavenging/blackwater-streets.webp)`}}><p className="eyebrow">BLACKWATER / STREET OPERATIONS</p><h2>The city rewards<br/>a curious mind.</h2><p>Search the backstreets, investigate fleeting opportunities and steal parked cars. Read police patrols before making your move.</p><button className="bin-gold" disabled={busy||blocked||!district} onClick={()=>void act("scav_enter",{district_id:district?.id})}>Enter {district?.name??"district"} <GameIcon name="arrow"/></button></div>:<>
 <div ref={mapViewport} className="scav-map-scroll scav-map-fitted" style={{height:Math.min(fit.height,fit.width*680/1000*zoom)}} tabIndex={0} aria-label="Street map; scroll to pan when zoomed">
 <svg className="scav-map" viewBox="0 0 1000 680" style={{width:fit.width*zoom}} role="group" aria-label={district?.name+" scavenging street map"} onClick={event=>{const box=event.currentTarget.getBoundingClientRect();const x=(event.clientX-box.left)/box.width*1000,y=(event.clientY-box.top)/box.height*680;travel(nearestStreetPosition(x,y));}}>
 <defs><linearGradient id="scav-map-shade" x2="0" y2="1"><stop stopColor="#051114" stopOpacity=".25"/><stop offset=".45" stopColor="#051114" stopOpacity="0"/><stop offset="1" stopColor="#051114" stopOpacity=".15"/></linearGradient></defs>
 <image className="scav-map-art" href="/art/scavenging/blackwater-streets.webp" x="0" y="0" width="1000" height="680" preserveAspectRatio="none" pointerEvents="none"/><rect width="1000" height="680" fill="url(#scav-map-shade)" pointerEvents="none"/>



 {streetLife&&<ScavengingStreetLife/>}
 {STREET_ROWS.map((y,i)=><g key={y} className="scav-street-label" pointerEvents="none"><rect x="285" y={y-54} width="230" height="32" rx="3"/><text x="400" y={y-32} textAnchor="middle" fontSize="18" letterSpacing="1.5">{streets[i]}</text></g>)}
 <g className="scav-map-title" pointerEvents="none"><rect x="24" y="14" width="370" height="52" rx="3"/><text x="42" y="47" fontFamily="Georgia" fontSize="22">{district?.name.toUpperCase()}</text></g><text className="scav-compass" x="962" y="652" textAnchor="end" fontSize="17" pointerEvents="none">N ↑</text>
 {Array.from({length:15},(_,node)=>{const p=streetPoint(node);return <g key={node} role="button" tabIndex={0} aria-label={`Walk to ${streets[Math.floor(node/5)]}, block ${node%5+1}`} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();travel([node%5,Math.floor(node/5)]);}}}><circle cx={p.x} cy={p.y} r="35" fill="transparent"/></g>;})}
 {moving&&<polyline className="scav-walking-route" points={(session.route_points??session.path.map(n=>[n%5,Math.floor(n/5)] as StreetPosition)).map(n=>{const p=mapPoint(n);return `${p.x},${p.y}`;}).join(" ")} fill="none" stroke="#d8b777" strokeWidth="3" strokeDasharray="5 8" pointerEvents="none"/>}
 {!!state?.patrols?.length&&<ScavengingPolice patrols={state.patrols} now={frame}/>}
 {event&&<g className={"street-event-marker "+event.kind} role="button" tabIndex={0} aria-label={eventNames[event.kind]} onClick={e=>{e.stopPropagation();travel([event.node%5,Math.floor(event.node/5)]);setSelected("event");}} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();travel([event.node%5,Math.floor(event.node/5)]);setSelected("event");}}}><circle cx={streetPoint(event.node).x-27} cy={streetPoint(event.node).y-20} r="24"/><text x={streetPoint(event.node).x-27} y={streetPoint(event.node).y-13} textAnchor="middle">{event.kind==="sweep"?"!":"◇"}</text></g>}
 {pursuit&&<g className="street-escape-marker" role="button" tabIndex={0} aria-label="Reach the district exit" onClick={e=>{e.stopPropagation();travel([0,0]);}} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();travel([0,0]);}}}><circle cx="73" cy="114" r="34"/><text x="73" y="120" textAnchor="middle">↗</text><text x="73" y="70" textAnchor="middle">ESCAPE</text></g>}
 {state?.targets.map((site,index)=>{const road=streetPoint(site.node),p={x:road.x+24,y:road.y+20},empty=site.ready_at&&Date.parse(site.ready_at)>frame;return <g className={"scav-target "+(selected===site.id?"selected ":"")+(empty?"searched":"")} key={site.id} role="button" tabIndex={0} aria-label={`${site.kind==="bin"?"Bin":"Car"} ${index+1} on ${streets[Math.floor(site.node/5)]}${empty?", searched":""}`} onClick={e=>{e.stopPropagation();choose(site.id);}} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();choose(site.id);}}}><rect x={p.x-24} y={p.y-24} width="48" height="48" rx="7"/>{site.kind==="bin"?<path d={`M${p.x-10} ${p.y-8}h20l-2 23h-16z M${p.x-13} ${p.y-11}h26 M${p.x-5} ${p.y-16}h10`}/>:<path d={`M${p.x-16} ${p.y-6}l5-9h22l5 9v19h-32z M${p.x-16} ${p.y-2}h32 M${p.x-9} ${p.y+7}h3 M${p.x+6} ${p.y+7}h3`}/>}<text x={p.x+31} y={p.y+5} fontSize="13">{index+1}</text></g>;})}
 {(moving||queued)&&<g className="scav-destination" pointerEvents="none" aria-label="Walking destination"><circle cx={mapPoint(queued??sessionDestination(session)).x} cy={mapPoint(queued??sessionDestination(session)).y} r="17" fill="#d6af6922" stroke="#e3bd7c" strokeWidth="2"/><circle cx={mapPoint(queued??sessionDestination(session)).x} cy={mapPoint(queued??sessionDestination(session)).y} r="4" fill="#e3bd7c"/></g>}
 <g pointerEvents="none" aria-label="Your position"><circle cx={point.x} cy={point.y} r="19" fill="#81b49a" opacity=".18"/><circle cx={point.x} cy={point.y} r="8" fill="#9ed1ad" stroke="#edf6d8" strokeWidth="2"/>{pursuit?.vehicle_id&&<path d={`M${point.x-13} ${point.y-7}h26v15h-26z`} fill="#c4a265" stroke="#f4deb0"/>}<text x={point.x} y={point.y+34} textAnchor="middle" fill="#eddfb7" fontSize="13">{pursuit?.vehicle_id?"GETAWAY":"YOU"}</text></g>
 </svg></div>
 <div className="scav-action-desk"><div><p className="eyebrow">{pursuit?"WANTED / GETAWAY":pending?"ACTION IN PROGRESS":moving?"ON FOOT":"STREET INTELLIGENCE"}</p><h3>{pursuit?"Lose the law.":pending?pending.mode==="theft"?"Bypassing the ignition":pending.mode==="event"?"Investigating the opportunity":pending.kind==="car"?"Working the lock":"Searching the bin":selected==="event"&&event?eventNames[event.kind]:target?target.vehicle?.name??(target.kind==="car"?"Parked car":"Street bin"):"Choose your next stop"}</h3><p>{pursuit?`${pursuit.vehicle_name} · ${Math.max(0,Math.ceil((Date.parse(pursuit.deadline)-frame)/1000))}s until the cordon closes. Reach the green escape marker. Health ${Math.ceil(ops?.vitals.health??0)}.`:pending?remaining?`Ready in ${binCountdown(remaining)}`:"Your search is ready to collect.":moving?"Follow the route. Click another street to change direction.":target?.kind==="car"?`One lockpick per attempt · ${state?.settings.scavenging_car_success_percent}% opening chance · +${state?.settings.scavenging_lock_xp} XP when opened. Uses the loot chances below.`:target?"Search for cash, tools or blueprints. One find per search.":"Click anywhere along a street to walk, or choose a bin or parked car."}</p></div>
 <div className="scav-desk-actions">{pursuit?<><div className="street-pursuit-buttons"><button className="bin-gold" disabled={busy||blocked||!exitReady} onClick={()=>void act("scav_escape")}>{pursuit.vehicle_id?'Escape with car':'Leave district'}</button><button className="street-fight" disabled={busy||blocked||!ops?.weapon||ops.weapon.ammo<pursuit.rules.scavenging_combat_bullets||frame<Date.parse(pursuit.next_shot_at)} onClick={()=>void act("scav_fight")}>Fight back · {pursuit.rules.scavenging_combat_bullets} bullets</button></div><small>Police return fire. Gun condition and health are at risk.</small><button className="street-abandon" disabled={busy} onClick={()=>void act("scav_abandon")}>{pursuit.vehicle_id?'Abandon car':'Surrender'}</button></>:<>
 {!!state?.patrols?.length&&<p className="scav-police-warning">Police notice active searches. Watch patrols and keep an escape route.</p>}
 {pending?<><div className="street-operation-progress" role="progressbar" aria-label="Operation progress" aria-valuenow={Math.min(100,Math.round((frame-Date.parse(pending.started_at))/Math.max(1,Date.parse(pending.ready_at)-Date.parse(pending.started_at))*100))} aria-valuemin={0} aria-valuemax={100}><span style={{width:Math.min(100,(frame-Date.parse(pending.started_at))/Math.max(1,Date.parse(pending.ready_at)-Date.parse(pending.started_at))*100)+"%"}}/></div><button className="bin-gold" disabled={busy||blocked||remaining>0} onClick={()=>void act("scav_finish",{attempt_id:pending.id})}>{remaining?`Searching · ${binCountdown(remaining)}`:pending.mode==="theft"?"Start getaway":"Collect search"}</button><button className="street-abandon" disabled={busy} onClick={()=>void act("scav_cancel")}>Abandon search</button></>:selected==="event"&&event?<button className="bin-gold" disabled={busy||blocked||!atEvent||cooldown>0||event.kind==="sweep"} onClick={()=>void act("scav_event",{event_id:event.id})}>{event.kind==="sweep"?"Avoid the sweep":moving?"Walking to opportunity":"Investigate opportunity"}</button>:<>
 <button className="bin-gold" disabled={busy||blocked||!atTarget||searched||cooldown>0||(target?.kind==="car"&&!lockpicks)} onClick={()=>void act("scav_search",{target_id:target?.id})}>{moving?`Walking · ${Math.max(1,Math.ceil((Date.parse(session.arrives_at)-frame)/1000))}s`:cooldown?"Next search in "+binCountdown(cooldown):searched?"Already searched":!target?"Select a location":target.kind==="car"?lockpicks?"Lockpick car":"Lockpick required":"Search the bins"}</button>
 {target?.kind==="car"&&target.vehicle&&<div className="street-theft-choice"><button className="bin-outline" disabled={busy||blocked||!atTarget||searched||cooldown>0||!lockpicks} onClick={()=>void act("scav_steal",{target_id:target.id,garage_id:garage||undefined})}>Steal vehicle · {state?.settings.scavenging_theft_success_percent}%</button>{!!ops?.garages.length?<label>Garage<select aria-label="Getaway garage" value={garage} onChange={e=>setGarage(e.target.value)}><option value="">First available garage</option>{ops.garages.map(g=><option key={g.id} value={g.id}>{g.code} · {g.district_name}</option>)}</select></label>:<small>No garage: sold for {money(target.vehicle.sale_value)} after escape.</small>}</div>}
 </>}
 <small>{lockpicks} lockpicks carried</small></>}</div></div>
 <div className="scav-location-list" aria-label="Nearby search locations">{state?.targets.map((site,i)=><button key={site.id} aria-pressed={selected===site.id} onClick={e=>{e.stopPropagation();choose(site.id);}}>{site.kind==="bin"?"Bin":"Car"} {i+1}<span>{streets[Math.floor(site.node/5)]}</span></button>)}</div>
 </>}
 </div>;
}
