"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";
import {GameIcon} from "./game-icon";
import {skillTheme,skillProgress,type SkillsState,type SkillId} from "@/lib/skills";
const count=(n:number)=>n.toLocaleString("en-US");
export function SkillsWorkspace({initial,initialSkill}:{initial:SkillsState;initialSkill?:string}){
 const [data,setData]=useState(initial),[selected,setSelected]=useState<SkillId>(initial.skills.find(s=>s.id===initialSkill)?.id??"crafting"),[milestone,setMilestone]=useState(20),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const alive=useRef(true),reading=useRef(false);
 const refresh=useCallback(async()=>{if(reading.current)return;reading.current=true;setBusy(true);try{const r=await createClient().rpc("skills_state");if(r.error||!r.data)throw new Error("Skills could not refresh. Your last saved progress is shown.");if(alive.current){setData(r.data);setNotice("");}}catch(e){if(alive.current)setNotice(e instanceof Error?e.message:"Skills could not refresh.");}finally{reading.current=false;if(alive.current)setBusy(false);}},[]);
 useEffect(()=>{alive.current=true;const visible=()=>{if(!document.hidden)void refresh();};const timer=setInterval(visible,30000);window.addEventListener("focus",visible);window.addEventListener("blackwater:game",visible);document.addEventListener("visibilitychange",visible);return()=>{alive.current=false;clearInterval(timer);window.removeEventListener("focus",visible);window.removeEventListener("blackwater:game",visible);document.removeEventListener("visibilitychange",visible);};},[refresh]);
 const skill=data.skills.find(s=>s.id===selected)??data.skills[0],theme=skillTheme[skill.id],target=skill.thresholds.find(t=>t.level===milestone)!;
 const choose=(id:SkillId)=>{setSelected(id);window.history.replaceState(null,"","/skills?skill="+id);};
 return <div className="skills-workspace"><header className="skills-hero"><div><Link className="skills-back" href="/dashboard">← Back to dashboard</Link><p className="skills-kicker">BLACKWATER / PERSONAL PROGRESSION</p><h1>Skills</h1><p className="skills-lead">An empire is built on what you know.</p><p>Work the bench. Find your aim. Open the doors others cannot.</p></div><div className="skills-season"><GameIcon name="respect" size={38}/><span>{data.season.name}</span><strong>20 <small>LEVEL CAP</small></strong><span>Progress starts fresh each season</span></div></header>
 <div className="skills-toolbar"><p>Four disciplines. Earned through action.</p><div>{data.can_manage&&<Link href="/owner?section=skills">Owner controls <GameIcon name="gear" size={17}/></Link>}<button disabled={busy} onClick={()=>void refresh()} aria-label="Refresh skills"><GameIcon name="refresh" size={18}/>{busy?"Refreshing…":"Refresh"}</button></div></div>
 {notice&&<p className="skills-notice" role="alert">{notice}</p>}
 <div className="skills-cards" role="tablist" aria-label="Skills">{data.skills.map(s=>{const t=skillTheme[s.id];return <button type="button" key={s.id} role="tab" id={"skill-tab-"+s.id} aria-selected={s.id===skill.id} aria-controls="skill-detail" className={"skill-card "+s.id+(s.id===skill.id?" selected":"")} onClick={()=>choose(s.id)}><div className="skill-card-art"><img src={t.image} alt="" width={600} height={300}/><span>{t.caption}</span><i><GameIcon name={t.icon} size={32}/></i></div><div className="skill-card-body"><div className="skill-card-title"><strong>{s.name}</strong><span>LEVEL <b>{s.level}</b><small> / 20</small></span></div><p>{s.description}</p><div className="skill-progress-label"><span>{count(s.xp)} XP earned</span><strong>{s.level===20?"MAX LEVEL":`${count(s.next_level_xp!-s.xp)} XP to level ${s.level+1}`}</strong></div><div className="skill-meter" role="progressbar" aria-label={s.name+" level progress"} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(skillProgress(s))}><i style={{width:skillProgress(s)+"%"}}/></div><footer><span>Level 20 · {count(s.xp_to_20)} XP</span><span>{s.id===skill.id?"Viewing progression":"View progression"} →</span></footer></div></button>;})}</div>
 <div className="skills-bottom"><section className="skills-panel skills-detail" role="tabpanel" id="skill-detail" aria-labelledby={"skill-tab-"+skill.id}><header><div><p className="skills-kicker">YOUR NEXT ADVANTAGE</p><h2>{skill.name} progression</h2></div><GameIcon name={theme.icon} size={32}/></header><div className="skill-detail-summary"><div className="skill-level-seal"><span>LEVEL</span><strong>{skill.level}</strong><span>OF 20</span></div><div><h3>{skill.level===20?"Discipline mastered":"Every session moves you forward"}</h3><p>{skill.level===20?"You have reached the highest level. Your earned XP remains recorded.":`${count(skill.next_level_xp!-skill.xp)} XP until level ${skill.level+1}. Each level takes more practice than the last.`}</p><Link className="skills-gold-button" href={theme.href}>{theme.action}<GameIcon name="arrow" size={19}/></Link></div></div>
 <div className="skill-milestone-heading"><h3>The road to level 20</h3><span>Select a level to inspect its XP target</span></div><div className="skill-milestones">{skill.thresholds.map(t=><button type="button" key={t.level} className={(t.level<=skill.level?"reached ":"")+(milestone===t.level?"inspecting":"")} aria-label={`Level ${t.level}: ${count(t.xp)} total XP`} aria-pressed={milestone===t.level} onClick={()=>setMilestone(t.level)}><small>LEVEL</small><strong>{t.level}</strong><span>{count(t.xp)} XP</span></button>)}</div><div className="skill-target-summary" aria-live="polite"><GameIcon name={skill.xp>=target.xp?"shield":"target"}/><span>Level {milestone}<strong>{count(target.xp)} total XP</strong></span><b>{skill.xp>=target.xp?"Reached":`${count(target.xp-skill.xp)} XP remaining`}</b></div></section>
 <aside className="skills-panel skills-history"><header><h2>Recent skill XP</h2><GameIcon name="ledger"/></header>{data.recent.length?<ol>{data.recent.map(r=><li key={r.id}><GameIcon name={skillTheme[r.skill_id].icon}/><div><strong>{data.skills.find(s=>s.id===r.skill_id)?.name}</strong><p>{r.description}</p><time dateTime={r.created_at}>{new Date(r.created_at).toLocaleString("en-GB",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"UTC"})} UTC</time></div><b>+{count(r.delta)} XP</b></li>)}</ol>:<div className="skills-empty"><GameIcon name="blueprint" size={40}/><h3>Your story starts here</h3><p>Complete crafting jobs, mine ore, earn range rewards or open a prison lock. Your skill XP will appear here.</p></div>}<p className="skills-history-note">Your latest 20 skill rewards this season. Completed activity is recorded once; cancelled work and failed attempts earn no skill XP.</p></aside></div></div>;
}
