"use client";
import {useEffect,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {GameIcon} from "./game-icon";
import {skillTheme,skillThreshold,type Skill,type SkillsState} from "@/lib/skills";
function SkillForm({skill,rate,busy,save}:{skill:Skill;rate:number;busy:boolean;save:(payload:Record<string,unknown>)=>void}){
 const [total,setTotal]=useState(String(skill.xp_to_20));const valid=Number.isSafeInteger(Number(total))&&Number(total)>=19&&Number(total)<=1000000000;
 return <form className="skills-owner-card" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({skill_id:skill.id,version:skill.version,xp_to_20:Number(total),reason:String(f.get("reason")),...(skill.id==="crafting"?{crafting_xp_per_minute:Number(f.get("rate")),expected_crafting_rate:rate}:{})});}}><header><GameIcon name={skillTheme[skill.id].icon} size={28}/><h3>{skill.name}</h3><span>MAX LEVEL 20</span></header><label>Total XP to reach level 20<input aria-label={skill.name+" XP to level 20"} type="number" min={19} max={1000000000} step={1} required value={total} onChange={e=>setTotal(e.target.value)} disabled={busy}/></label>{skill.id==="crafting"&&<label>Crafting XP per minute of work<input name="rate" aria-label="Crafting XP per minute" type="number" min={1} max={10000} step={1} required defaultValue={rate} disabled={busy}/></label>}<div className="skill-curve-preview" aria-label={skill.name+" curve preview"}>{[1,5,10,15,20].map(l=><span key={l}>Level {l}<strong>{valid?skillThreshold(l,Number(total)).toLocaleString("en-US"):"—"} XP</strong></span>)}</div><label>Audit reason<input name="reason" aria-label={skill.name+" audit reason"} minLength={5} maxLength={500} required placeholder="Explain this progression change" disabled={busy}/></label><button className="skills-gold-button" disabled={busy||!valid} type="submit">Save {skill.name}<GameIcon name="arrow" size={18}/></button></form>;
}
export function SkillsOwner(){
 const [data,setData]=useState<SkillsState|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[retry,setRetry]=useState<Record<string,unknown>|null>(null);const lock=useRef(false),alive=useRef(true);
 const read=async()=>{if(lock.current)return;try{const r=await createClient().rpc("skills_state");if(r.error||!r.data)throw new Error("Skill controls could not load.");if(alive.current){setData(r.data);setNotice("");}}catch(e){if(alive.current)setNotice(e instanceof Error?e.message:"Could not load skills.");}};
 useEffect(()=>{alive.current=true;void read();return()=>{alive.current=false;};},[]);
 const save=async(payload:Record<string,unknown>)=>{if(lock.current)return;lock.current=true;setBusy(true);setNotice("");try{const r=await createClient().rpc("skills_manage",{p_payload:payload});if(r.error){setRetry(payload);throw new Error("The save reply was interrupted. Retry safely to check the same update.");}setRetry(null);if(r.data?.error)throw new Error(r.data.error);setData(r.data.state);setNotice(r.data.message);}catch(e){setNotice(e instanceof Error?e.message:"Skills could not save.");}finally{lock.current=false;setBusy(false);}};
 if(!data)return <section className="skills-owner"><h2>Skills & progression</h2><p role="status">{notice||"Loading skill controls…"}</p><button onClick={()=>void read()}>Retry loading</button></section>;
 if(!data.can_manage)return <p>Owner skill-management permission required.</p>;
 return <section className="skills-owner"><header><p className="skills-kicker">OWNER / PROGRESSION</p><h2>Skills & progression</h2><p>Set the total XP needed for each skill to reach level 20. The intermediate levels adjust automatically. Earned XP is retained, so current levels may rise or fall after a change.</p><p>Crafting rewards are fixed when a job starts. Mining awards XP per ore delivered, Sharpshooting uses earned range XP, and Lockpicking uses the power reward from successful prison breaks. Scavenging rewards completed bin searches and successfully opened cars. Change Scavenging skill XP per search in Economy & production. Skills reset each season.</p></header><div className="skills-owner-actions"><button disabled={busy||!!retry} onClick={()=>void read()}>Refresh controls</button>{retry&&<button disabled={busy} onClick={()=>void save(retry)}>Retry skill save safely</button>}</div>{notice&&<p role="status" className="skills-notice">{notice}</p>}<div className="skills-owner-grid">{data.skills.map(skill=><SkillForm key={skill.id+":"+skill.version} skill={skill} rate={data.crafting_xp_per_minute} busy={busy||!!retry} save={p=>void save({...p,request_id:crypto.randomUUID()})}/>)}</div></section>;
}
