"use client";
import Link from "next/link";
import {GameIcon} from "./game-icon";
import {money} from "@/lib/game";
import {eventNames,type StreetOperations} from "@/lib/street-operations";
export function StreetOperationsPanel({ops,busy,act,buildingId}:{ops?:StreetOperations;busy:boolean;act:(a:string,p?:Record<string,unknown>)=>Promise<boolean>;buildingId?:string}){
 if(!ops)return null;const vehicles=ops.vehicles.filter(v=>!buildingId||v.building_id===buildingId);
 return <aside className="street-intelligence">
 {!buildingId&&<><section className={"street-card "+(ops.island?"danger":"")}><p className="eyebrow">{ops.island?"BLACKWATER ISLAND / RESTRICTED":"DISTRICT INTELLIGENCE"}</p><h3>{ops.island?"Fortune behind the wire.":"Read the streets."}</h3><p>{ops.island?"Prison patrols are faster and cover more ground. Cash finds are worth more here. Getting caught carries a longer sentence.":"Searching can attract police. A stolen car starts a pursuit. Use the escape action to reach the district exit."}</p><dl><div><dt>Cash reward</dt><dd>×{ops.cash_multiplier}</dd></div><div><dt>Health</dt><dd>{Math.ceil(ops.vitals.health)} / {ops.vitals.health_max}</dd></div><div><dt>Armour</dt><dd>{Math.ceil(ops.vitals.armour)}</dd></div></dl><div className="street-health"><span style={{width:Math.min(100,ops.vitals.health/ops.vitals.health_max*100)+"%"}}/></div>{ops.vitals.health<ops.vitals.health_max&&<Link href="/inventory">Treat injuries in Inventory →</Link>}</section>
 {ops.event&&<section className={"street-card "+(ops.event.kind==="sweep"?"danger":"opportunity")}><p className="eyebrow">LIVE STREET EVENT</p><h3>{eventNames[ops.event.kind]}</h3><p>{ops.event.kind==="sweep"?"Extra patrol presence. Stay out of their detection zones while committing a crime.":"A temporary opportunity in this district. Investigate before it disappears; cash finds receive an extra bonus."}</p><small>Expires {new Date(ops.event.expires_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</small></section>}</>}
 <section className="street-card"><p className="eyebrow">YOUR MOTOR POOL</p><h3>Vehicles secured</h3>{vehicles.length?vehicles.map(v=><article className="street-vehicle" key={v.id}><GameIcon name="truck" size={30}/><div><strong>{v.name}</strong><small>{v.code} · {v.garage_active?"In your garage":"Garage access expired; vehicle recoverable by sale"}</small><span>{money(v.sale_value)} sale value</span></div><button className="bin-outline" disabled={busy} onClick={()=>{if(window.confirm("Sell "+v.name+" for "+money(v.sale_value)+"?"))void act("scav_sell_vehicle",{vehicle_id:v.id});}}>Sell vehicle</button></article>):<p>No stolen vehicles stored here yet.</p>}{!buildingId&&<><p>{ops.garages.length?"A usable garage lets you keep a stolen car. If its bays fill or access expires during a chase, the car is sold on escape.":"No garage available. A successful getaway sells the stolen car immediately."}</p><Link href="/districts">Find a garage →</Link></>}</section>
 {!buildingId&&<section className="street-card"><p className="eyebrow">YOUR STREET RECORD</p>{ops.history.length?ops.history.slice(0,6).map((h,i)=><article className="street-record" key={h.created_at+i}><span>{h.details.message}</span><time>{new Date(h.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></article>):<p>Your next operation starts the story.</p>}</section>}
 </aside>;
}
