import * as THREE from "three";
import {PointerLockControls} from "three/addons/controls/PointerLockControls.js";
import {createStreetHands} from "./street-hands";
import type {StreetAudioFrame} from "@/lib/street-audio";
import {createStreetEnvironment} from "./street-environment";
import {streetPixelRatio,adaptStreetResolution,type StreetQuality} from "@/lib/street-quality";
import {STREET_METRES} from "@/lib/first-person-movement";
import {patrolPosition,type ScavengingState,type StreetPosition} from "@/lib/scavenging";
export type StreetInput={dx:number;dy:number;sprint:boolean};
export type StreetScene={shot:()=>void;quality:(mode:StreetQuality)=>void;dispose:()=>void;lock:()=>void;unlock:()=>void;touch:(x:number,y:number)=>void;look:(x:number,y:number)=>void;overview:(value:boolean)=>void;update:(state:ScavengingState,now:number)=>void};
type Options={sound?:(frame:StreetAudioFrame)=>void;district:string;width:number;state:ScavengingState;now:number;frame:(input:StreetInput,dt:number)=>StreetPosition;interact:()=>void;locked:(value:boolean)=>void;failed:()=>void};
// The scene is presentation only: movement inputs, proximity and all rewards are checked by the server.
export function createStreetScene(host:HTMLDivElement,options:Options):StreetScene{
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:"high-performance"});
 renderer.outputColorSpace=THREE.SRGBColorSpace;
 const coarse=matchMedia('(pointer:coarse)').matches;let quality:StreetQuality='auto',adaptive=1;try{const saved=localStorage.getItem('blackwater:street-quality');if(saved==='high'||saved==='performance')quality=saved;}catch{}
 renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
 renderer.domElement.setAttribute('aria-label','First-person Blackwater streets');renderer.domElement.setAttribute('role','img');host.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#27343c');scene.fog=new THREE.FogExp2('#27343c',.006);
 const camera=new THREE.PerspectiveCamera(72,1,.08,320);camera.rotation.order='YXZ';camera.rotation.y=-Math.PI/2;
 scene.add(camera);const hands=createStreetHands(camera);
 const overhead=new THREE.PerspectiveCamera(48,1,1,1000);overhead.position.set(84,158,145);overhead.lookAt(84,0,42);
 const controls=new PointerLockControls(camera,renderer.domElement);controls.pointerSpeed=.6;controls.minPolarAngle=.25;controls.maxPolarAngle=Math.PI-.25;
 let disposed=false,overview=false,locked=false,touchMode=false,touchX=0,touchY=0,state=options.state,time=options.now,received=performance.now(),last=performance.now(),elapsed=0;
 const keys=new Set<string>(),materials:THREE.Material[]=[],geometries:THREE.BufferGeometry[]=[],textures:THREE.Texture[]=[],patrolMeshes=new Map<string,THREE.Group>(),targets=new THREE.Group();scene.add(targets);
 const mat=(color:string,roughness=.8,metalness=0,emissive?:string)=>{const m=new THREE.MeshStandardMaterial({color,roughness,metalness,emissive:emissive??'#000000',emissiveIntensity:emissive?1.5:0});materials.push(m);return m;};
 const iron=mat('#242c30',.48,.65),stone=mat('#595954'),wood=mat('#403b31'),glass=mat('#172d35',.2,.7),gold=mat('#b89860',.5,.5),rubber=mat('#141719'),cream=mat('#b7b0a1'),lamp=mat('#ecd4a1',.5,0,'#e1a45c');
 const unitBox=new THREE.BoxGeometry(1,1,1);geometries.push(unitBox);
 function box(parent:THREE.Object3D,x:number,y:number,z:number,w:number,h:number,d:number,m:THREE.Material){const o=new THREE.Mesh(unitBox,m);o.position.set(x,y,z);o.scale.set(w,h,d);parent.add(o);return o;}
 const cylinderCache=new Map<string,THREE.CylinderGeometry>();
 function cylinder(parent:THREE.Object3D,x:number,y:number,z:number,r:number,h:number,m:THREE.Material,segments=10){const key=`${r}:${h}:${segments}`;let geo=cylinderCache.get(key);if(!geo){geo=new THREE.CylinderGeometry(r,r,h,segments);cylinderCache.set(key,geo);geometries.push(geo);}const o=new THREE.Mesh(geo,m);o.position.set(x,y,z);parent.add(o);return o;}
 function label(text:string,x:number,y:number,z:number,width=6){const c=document.createElement('canvas');c.width=768;c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle='#111c20';ctx.fillRect(0,0,768,128);ctx.strokeStyle='#ac8959';ctx.lineWidth=5;ctx.strokeRect(5,5,758,118);ctx.fillStyle='#dfd0b4';ctx.font='36px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text.toUpperCase(),384,64,730);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;textures.push(texture);const material=new THREE.SpriteMaterial({map:texture});materials.push(material);const o=new THREE.Sprite(material);o.position.set(x,y,z);o.scale.set(width,width/6,1);o.userData.ownedLabel=true;scene.add(o);return o;}
 const M=STREET_METRES;
 const environment=createStreetEnvironment({scene,width:options.width,streets:options.state.streets,district:options.district,materials,textures,geometries,box,cylinder,mat,anisotropy:Math.min(4,renderer.capabilities.getMaxAnisotropy())});
 // Instance repeated architecture, railings, lamps and puddles by geometry and material.
 const batches=new Map<THREE.Material,Map<THREE.BufferGeometry,THREE.Matrix4[]>>();
 for(const child of [...scene.children])if(child instanceof THREE.Mesh&&!Array.isArray(child.material)){child.updateMatrix();const geos=batches.get(child.material)??new Map<THREE.BufferGeometry,THREE.Matrix4[]>();const matrices=geos.get(child.geometry)??[];matrices.push(child.matrix.clone());geos.set(child.geometry,matrices);batches.set(child.material,geos);scene.remove(child);}
 for(const [material,geos] of batches)for(const [geometry,matrices] of geos){const mesh=new THREE.InstancedMesh(geometry,material,matrices.length);matrices.forEach((matrix,i)=>mesh.setMatrixAt(i,matrix));mesh.computeBoundingSphere();scene.add(mesh);}
 // Reuse bevelled period-car shapes and instance their repeated trim; no per-frame mesh allocation.
 const shellShape=new THREE.Shape();shellShape.moveTo(-1.95,.48);shellShape.lineTo(-1.95,.7);shellShape.quadraticCurveTo(-1.9,.95,-1.55,.95);shellShape.lineTo(-1,.98);shellShape.lineTo(-.65,1.62);shellShape.quadraticCurveTo(-.5,1.79,.1,1.79);shellShape.lineTo(.63,1.69);shellShape.lineTo(1.03,1.03);shellShape.lineTo(1.7,.87);shellShape.quadraticCurveTo(1.97,.83,1.95,.48);shellShape.closePath();
 const shellGeo=new THREE.ExtrudeGeometry(shellShape,{depth:1.5,bevelEnabled:true,bevelThickness:.09,bevelSize:.08,bevelSegments:2,steps:1,curveSegments:5});shellGeo.translate(0,0,-.75);shellGeo.rotateY(Math.PI/2);geometries.push(shellGeo);
 const carPaint=['#344b4c','#4b3030','#58533f'].map(color=>mat(color,.3,.5)),policePaint=mat('#19272d',.35,.5),chrome=mat('#a2a8a2',.23,.8),beaconMat=mat('#b33824',.25,0,'#eb4b32');beaconMat.emissiveIntensity=1.6;
 const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=64;const ctx=shadowCanvas.getContext('2d')!,gradient=ctx.createRadialGradient(32,32,8,32,32,32);gradient.addColorStop(0,'rgba(0,0,0,.6)');gradient.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,64,64);const shadowTexture=new THREE.CanvasTexture(shadowCanvas);textures.push(shadowTexture);const shadowMat=new THREE.MeshBasicMaterial({map:shadowTexture,transparent:true,depthWrite:false});materials.push(shadowMat);const shadowGeo=new THREE.PlaneGeometry(1,1);geometries.push(shadowGeo);
 function shadow(group:THREE.Object3D,w:number,h:number){const p=new THREE.Mesh(shadowGeo,shadowMat);p.rotation.x=-Math.PI/2;p.position.y=.02;p.scale.set(w,h,1);group.add(p);}
 function batchParts(group:THREE.Group){const batches=new Map<THREE.Material,Map<THREE.BufferGeometry,THREE.Matrix4[]>>();for(const child of [...group.children])if(child instanceof THREE.Mesh&&!child.name&&!Array.isArray(child.material)&&child.geometry!==shadowGeo){child.updateMatrix();const geos=batches.get(child.material)??new Map<THREE.BufferGeometry,THREE.Matrix4[]>();const matrices=geos.get(child.geometry)??[];matrices.push(child.matrix.clone());geos.set(child.geometry,matrices);batches.set(child.material,geos);group.remove(child);}for(const [material,geos] of batches)for(const [geo,matrices] of geos){const m=new THREE.InstancedMesh(geo,material,matrices.length);matrices.forEach((matrix,i)=>m.setMatrixAt(i,matrix));m.computeBoundingSphere();group.add(m);}}
 function vehicle(police=false){
  const g=new THREE.Group(),paint=police?policePaint:carPaint[targets.children.length%3];g.add(new THREE.Mesh(shellGeo,paint));shadow(g,2.8,5);
  box(g,0,1.42,.89,1.28,.46,.045,glass).rotation.x=-.38;box(g,0,1.44,-.7,1.18,.42,.045,glass).rotation.x=.34;
  for(const x of [-.81,.81]){box(g,x,1.4,0,.035,.44,1.1,glass);box(g,x,1.4,.04,.07,.53,.06,chrome);box(g,x,1.08,-.1,.09,.045,1.85,chrome);box(g,x*1.06,.4,0,.23,.12,1.55,iron);box(g,x*1.04,1.02,-.37,.025,.045,.22,chrome);}
  for(const x of [-.85,.85])for(const z of [-1.24,1.18]){const tyre=cylinder(g,x,.43,z,.39,.22,rubber,16);tyre.rotation.z=Math.PI/2;const hub=cylinder(g,x*1.035,.43,z,.24,.24,chrome,12);hub.rotation.z=Math.PI/2;}
  box(g,0,.43,1.97,1.9,.13,.13,chrome);box(g,0,.42,-1.93,1.8,.12,.12,chrome);box(g,0,.76,1.92,.62,.43,.09,iron);for(let i=0;i<6;i++)box(g,-.25+i*.1,.76,1.98,.035,.38,.035,chrome);
  for(const x of [-.59,.59]){const light=cylinder(g,x,.86,1.79,.17,.12,lamp,12);light.rotation.x=Math.PI/2;box(g,x,.69,-1.88,.16,.12,.06,beaconMat);}
  if(police){box(g,0,1.91,0,.56,.12,.27,chrome);const beacon=cylinder(g,0,2.05,0,.12,.2,beaconMat,12);beacon.name='beacon';}
  batchParts(g);return g;
 }
 function retireGroup(group:THREE.Group){group.traverse(o=>{if(o instanceof THREE.InstancedMesh)o.dispose();if(o instanceof THREE.Sprite&&o.userData.ownedLabel){const m=o.material,t=m.map;if(t){t.dispose();const i=textures.indexOf(t);if(i>=0)textures.splice(i,1);}m.dispose();const i=materials.indexOf(m);if(i>=0)materials.splice(i,1);}});}
 let targetKey='';function populate(){const key=state.targets.map(t=>t.id).join('|');if(key===targetKey)return;targetKey=key;retireGroup(targets);targets.clear();for(const t of state.targets){const g=t.kind==='car'?vehicle():new THREE.Group();if(t.kind==='bin'){cylinder(g,0,.58,0,.42,1.1,iron,12);cylinder(g,0,1.16,0,.47,.09,iron,12);box(g,0,1.25,0,.19,.09,.09,gold);for(let i=0;i<8;i++){const a=i*Math.PI/4;box(g,Math.cos(a)*.4,.57,Math.sin(a)*.4,.04,.95,.04,stone);}}g.position.set((t.node%5+.035)*M,0,(Math.floor(t.node/5)+.035)*M);if(t.node%5===4)g.position.x-=.07*M;if(t.node>=10)g.position.z-=.07*M;if(t.kind==='bin'){shadow(g,1.9,1.9);batchParts(g);}g.userData.target=t.id;const hint=label(t.vehicle?.name??(t.kind==='car'?'Parked car':'Street bin'),0,2.1,0,1.6);hint.name='target-hint';g.add(hint);targets.add(g);}}
 populate();
 const eventGroup=new THREE.Group();scene.add(eventGroup);box(eventGroup,0,.45,0,.9,.8,.65,wood);const eventLabel=label('Street opportunity',0,2.4,0,4);eventGroup.add(eventLabel);
 const normalFog=scene.fog;lamp.emissiveIntensity=.75;
 const playerMarker=cylinder(scene,0,1,0,.9,1,mat('#b8cca5',.5,0,'#638976'));playerMarker.visible=false;
 const exit=label('District exit',0,3.8,0,5);
 const onLock=()=>{locked=true;touchMode=false;options.locked(true);},onUnlock=()=>{locked=false;keys.clear();options.locked(touchMode);};controls.addEventListener('lock',onLock);controls.addEventListener('unlock',onUnlock);
 const keydown=(e:KeyboardEvent)=>{if(e.code==='Escape'){keys.clear();touchX=touchY=0;touchMode=false;controls.unlock();options.locked(false);return;}if(!locked)return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','ShiftRight'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.code==='KeyE'&&!e.repeat)options.interact();};const keyup=(e:KeyboardEvent)=>keys.delete(e.code),blur=()=>{keys.clear();touchX=touchY=0;touchMode=false;locked=false;controls.unlock();options.locked(false);},visibility=()=>{if(document.hidden)blur();};
 window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);
 const resize=()=>{const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setPixelRatio(streetPixelRatio(w,h,window.devicePixelRatio,quality,coarse,adaptive));renderer.setSize(w,h,false);renderer.domElement.dataset.quality=quality;renderer.domElement.dataset.pixelRatio=renderer.getPixelRatio().toFixed(2);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();overhead.aspect=camera.aspect;const altitude=Math.max(145,225/camera.aspect);overhead.position.set(84,altitude,42+altitude*.2);overhead.lookAt(84,0,42);overhead.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(host);resize();
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const lost=(e:Event)=>{e.preventDefault();options.failed();};renderer.domElement.addEventListener('webglcontextlost',lost);
 let sampleAt=performance.now(),frameTotal=0,frameCount=0,statsAt=0,bob=0,previousPoint:StreetPosition|null=null;
 function tick(){if(disposed)return;const stamp=performance.now(),rawDt=(stamp-last)/1000,dt=Math.min(.08,rawDt);last=stamp;elapsed+=dt;const now=time+stamp-received;
  if(!document.hidden&&rawDt<2){frameTotal+=rawDt*1000;frameCount++;}if(stamp-sampleAt>3000){if(quality==='auto'){const next=adaptStreetResolution(adaptive,frameTotal/Math.max(1,frameCount),frameCount);if(next!==adaptive){adaptive=next;resize();}}sampleAt=stamp;frameTotal=frameCount=0;}
  let side=0,forward=0;if(!document.hidden&&!overview&&(locked||touchMode)){side=touchX+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);forward=-touchY+(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0);}
  const yaw=camera.rotation.y,input={dx:Math.cos(yaw)*side-Math.sin(yaw)*forward,dy:-Math.sin(yaw)*side-Math.cos(yaw)*forward,sprint:keys.has('ShiftLeft')||keys.has('ShiftRight')};const mag=Math.max(1,Math.hypot(input.dx,input.dy));input.dx/=mag;input.dy/=mag;
  const p=options.frame(input,dt),driving=!!state.operations?.pursuit?.vehicle_id,moving=previousPoint?Math.hypot(p[0]-previousPoint[0],p[1]-previousPoint[1])>.00005:false;previousPoint=[p[0],p[1]];bob+=((!reduced&&moving?1:0)-bob)*(1-Math.exp(-dt*10));camera.position.set(p[0]*M,(driving?1.25:1.72)+Math.sin(elapsed*9)*.018*bob,p[1]*M);const fov=72+(!reduced&&input.sprint&&bob>.1?3:0);if(Math.abs(camera.fov-fov)>.02){camera.fov+=(fov-camera.fov)*(1-Math.exp(-dt*6));camera.updateProjectionMatrix();}playerMarker.position.set(p[0]*M,1,p[1]*M);playerMarker.visible=overview;exit.visible=!!state.operations?.pursuit;
  const patrols=state.operations?.pursuit?.patrols??state.patrols??[];for(const [id,g] of patrolMeshes)if(!patrols.some(p=>p.id===id)){scene.remove(g);retireGroup(g);patrolMeshes.delete(id);}for(const patrol of patrols){let g=patrolMeshes.get(patrol.id);if(!g){g=vehicle(true);patrolMeshes.set(patrol.id,g);scene.add(g);}const a=patrolPosition(patrol,now),b=patrolPosition(patrol,now+150);g.position.set(a[0]*M,0,a[1]*M);if(Math.hypot(b[0]-a[0],b[1]-a[1])>.001){const heading=Math.atan2(b[0]-a[0],b[1]-a[1]);g.rotation.y+=Math.atan2(Math.sin(heading-g.rotation.y),Math.cos(heading-g.rotation.y))*(1-Math.exp(-dt*10));}g.getObjectByName('beacon')!.visible=Math.sin(elapsed*10)>-.2;}
  for(const g of targets.children){const hint=g.getObjectByName('target-hint');if(hint)hint.visible=overview||Math.hypot(g.position.x-p[0]*M,g.position.z-p[1]*M)<24;}
  const event=state.operations?.event;eventGroup.visible=!!event;if(event)eventGroup.position.set(event.node%5*M-.7,0,Math.floor(event.node/5)*M-.7);
  environment.update(camera,elapsed,dt,overview,quality==='performance'||adaptive<.75);
  const playing=!overview&&!document.hidden&&(locked||touchMode);hands.update({moving:moving?1:0,sprinting:input.sprint,time:elapsed,dt,weaponName:state.operations?.weapon?.name??null,visible:playing&&!driving,reducedMotion:reduced});
  const policeDistance=patrols.length?Math.min(...patrols.map(patrol=>{const a=patrolPosition(patrol,now);return Math.hypot(a[0]-p[0],a[1]-p[1]);})):null;options.sound?.({moving:moving&&!driving,sprinting:input.sprint,pursuit:!!state.operations?.pursuit,policeDistance,locked:playing,deltaSeconds:dt});
  renderer.domElement.dataset.hands=playing&&!driving?(state.operations?.weapon?'weapon':'unarmed'):'hidden';
  scene.fog=overview?null:normalFog;
  if(!document.hidden){renderer.render(scene,overview?overhead:camera);if(stamp-statsAt>1000){statsAt=stamp;renderer.domElement.dataset.environmentReady=String(environment.ready());renderer.domElement.dataset.drawCalls=String(renderer.info.render.calls);renderer.domElement.dataset.triangles=String(renderer.info.render.triangles);}}
 }
 renderer.setAnimationLoop(tick);
 return {shot:()=>hands.shot(),quality:(mode)=>{quality=mode;adaptive=1;try{localStorage.setItem('blackwater:street-quality',mode);}catch{}resize();},lock:()=>{keys.clear();touchX=touchY=0;if(matchMedia('(pointer: coarse)').matches){touchMode=true;options.locked(true);}else{void Promise.resolve(controls.lock()).catch(()=>options.locked(false));}},unlock:()=>{keys.clear();touchX=touchY=0;touchMode=false;locked=false;controls.unlock();options.locked(false);},touch:(x,y)=>{touchX=x;touchY=y;touchMode=true;},look:(x,y)=>{touchMode=true;camera.rotation.y-=x*.004;camera.rotation.x=Math.max(-1.25,Math.min(1.25,camera.rotation.x-y*.004));},overview:(v)=>{overview=v;if(v){keys.clear();touchX=touchY=0;touchMode=false;locked=false;controls.unlock();options.locked(false);}},update:(s,n)=>{state=s;time=n;received=performance.now();populate();},dispose:()=>{disposed=true;hands.dispose();environment.dispose();renderer.setAnimationLoop(null);controls.unlock();controls.dispose();observer.disconnect();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);renderer.domElement.removeEventListener('webglcontextlost',lost);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());scene.traverse(o=>{if(o instanceof THREE.InstancedMesh)o.dispose();});renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();}};
}
