"use client";
import {useEffect,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Preferences={purchases:boolean;sales:boolean};
export function TelegramPreferences(){
 const [value,setValue]=useState<Preferences|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[failed,setFailed]=useState(false),[version,setVersion]=useState(0);const lock=useRef(false);
 useEffect(()=>{let active=true;setNotice("");setFailed(false);void(async()=>{try{const r=await createClient().rpc("telegram_preferences");if(r.error||!r.data)throw new Error("Alert preferences could not load.");if(active)setValue(r.data);}catch(e){if(active){setFailed(true);setNotice(e instanceof Error?e.message:"Could not load preferences.");}}})();return()=>{active=false;};},[version]);
 async function save(){if(!value||lock.current)return;lock.current=true;setBusy(true);setNotice("");setFailed(false);try{const r=await createClient().rpc("telegram_preferences",{p_preferences:value});if(r.error||!r.data)throw new Error("Could not confirm your preferences. Save again to retry.");setValue(r.data);setNotice("Alert preferences saved.");}catch(e){setFailed(true);setNotice(e instanceof Error?e.message:"Could not save preferences.");}finally{lock.current=false;setBusy(false);}}
 return <details className="tg-preferences"><summary>Alert preferences</summary><p>Choose your free automatic market receipts. Changes apply to future trades; existing messages stay in your inbox.</p>{value?<form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}><label><input type="checkbox" checked={value.purchases} onChange={e=>setValue({...value,purchases:e.target.checked})}/>Items bought</label><label><input type="checkbox" checked={value.sales} onChange={e=>setValue({...value,sales:e.target.checked})}/>Items sold</label><button className="tg-gold" type="submit">{busy?"Saving…":"Save alert preferences"}</button></fieldset></form>:!failed?<p role="status">Loading preferences…</p>:<button onClick={()=>setVersion(v=>v+1)}>Try again</button>}{notice&&<p role={failed?"alert":"status"}>{notice}</p>}<p>Player and group Telegrams are unaffected.</p></details>;
}
