"use client";
import {useState,type FormEvent} from "react";
import Link from "next/link";
import {GameIcon} from "@/components/game-icon";
import {money} from "@/lib/game";
import {telegramFee,type TelegramOffice as Office} from "@/lib/telegrams";
export type OfficeSend=(action:string,payload:Record<string,string>)=>Promise<boolean>;
export function TelegramOffice({office:o,onManage}:{office:Office;onManage:()=>void}){
 return <aside className="tg-office"><section className="tg-panel"><p className="tg-panel-title"><GameIcon name="property"/>{o.can_operate?"YOUR PROPERTY":"CITY TELEGRAM OFFICE"}</p>
 <div className="tg-office-art"><img src="/art/telegram-office.jpg" alt="Blackwater Telegram Office, glowing above the waterfront at night"/><div><span className="eyebrow">UNIQUE STRATEGIC PROPERTY</span><h2>{o.name}</h2><p>{o.can_operate?"♛ Owned by you":o.owner_name}</p></div></div>
 <div className="tg-office-body"><p>The lifeline of Blackwater. Messages move business, and business builds empires.</p><dl className="tg-facts">
 <div><dt>Delivery</dt><dd>Instant</dd></div><div><dt>Fee per telegram</dt><dd className="tg-gold-text">{telegramFee(o.fee)}</dd></div><div><dt>Status</dt><dd><span className={"tg-dot "+(!o.available?"closed":"")}/>{o.available?"Open":"Unavailable"}</dd></div>
 <div><dt>Operating district</dt><dd>{o.district_name}</dd></div><div><dt>Strategic plot</dt><dd>{o.plot_code}</dd></div>
 {o.stats&&<><div><dt>Traffic today</dt><dd>{o.stats.today_count.toLocaleString()} telegrams</dd></div><div><dt>Revenue today</dt><dd>{money(o.stats.today_revenue)}</dd></div></>}</dl>
 <div className="tg-office-actions">{(o.can_operate||o.can_manage)&&<button onClick={onManage}><GameIcon name="gear"/>Manage Office</button>}<Link href={"/districts/"+o.district_slug+"?plot="+o.plot_id}><GameIcon name="pin"/>{o.asking_price?"View property · "+money(o.asking_price):"View property"}</Link></div>
 </div></section>
 {o.stats&&<section className="tg-panel tg-revenue"><p className="tg-panel-title"><GameIcon name="ledger"/>OFFICE REVENUE <button onClick={onManage}>View details →</button></p><strong>{money(o.stats.week_revenue)}</strong><span>Past 7 days · {o.stats.week_count.toLocaleString()} telegrams</span><div className="tg-bars" aria-label="Hourly telegram traffic, UTC">{o.hours.map(h=><i key={h.hour} style={{height:Math.max(3,100*h.count/Math.max(1,...o.hours.map(v=>v.count)))+"%"}} title={h.hour+":00 UTC · "+h.count+" telegrams"}/>)}</div></section>}
 <section className="tg-panel tg-privacy"><GameIcon name="shield"/><p>Private by design. Office owners see traffic and revenue totals. Your subjects and conversations stay private.</p></section>
 </aside>;
}
export function TelegramOfficeControls({office:o,send,admin=false}:{office:Office;send:OfficeSend;admin?:boolean}){
 const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>,action:string){e.preventDefault();setBusy(true);try{await send(action,Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>);}finally{setBusy(false);}}
 const reason=<label>Reason for this change<input name="reason" minLength={3} maxLength={1000} required placeholder="Recorded in audit history"/></label>;
 return <div className="tg-controls">
 <form onSubmit={e=>void submit(e,admin?"config":"office")} key={JSON.stringify([o.name,o.fee,o.status,o.config])}><h3>Office terms</h3><label>Office name<input name="name" defaultValue={o.name} minLength={2} maxLength={80} required/></label><label>Public description<textarea name="description" defaultValue={o.description} maxLength={1000}/></label><div className="tg-form-pair"><label>Fee per telegram<input name="fee" type="number" min={admin?0:o.minimum_fee} max={admin?undefined:o.maximum_fee} defaultValue={o.fee} required/></label><label>Business status<select name="status" defaultValue={o.status}><option value="open">Open</option><option value="closed">Closed</option></select></label></div>
 {admin&&o.config&&<><div className="tg-form-pair"><label>Minimum fee<input name="minimum_fee" type="number" min={0} defaultValue={o.config.minimum_fee} required/></label><label>Maximum fee<input name="maximum_fee" type="number" min={0} defaultValue={o.config.maximum_fee} required/></label></div><div className="tg-form-pair"><label>Default fee after reset<input name="default_fee" type="number" min={0} defaultValue={o.config.default_fee} required/></label><label>Sale price after reset<input name="reset_sale_price" type="number" min={1} defaultValue={o.config.reset_sale_price} required/></label></div><label>Telegram service<select name="available" defaultValue={String(o.config.available)}><option value="true">Available city-wide</option><option value="false">Unavailable city-wide</option></select></label></>}
 <p className="tg-muted">Fee changes apply to future sends. Delivery is always instant.</p>{reason}<button className="tg-gold" disabled={busy}>Save office terms</button></form>
 <section className="tg-statistics"><h3>Traffic & revenue</h3><p className="tg-muted">UTC · aggregate office totals only</p><dl className="tg-facts">{o.stats&&[["Telegrams today",o.stats.today_count],["Telegrams last 7 days",o.stats.week_count],["Telegrams this season",o.stats.season_count],["Revenue today",money(o.stats.today_revenue)],["Revenue last 7 days",money(o.stats.week_revenue)],["Revenue this season",money(o.stats.season_revenue)],["Average telegrams per day",o.stats.average_per_day]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><h4>Busiest hours</h4>{[...o.hours].filter(h=>h.count>0).sort((a,b)=>b.count-a.count).slice(0,5).map(h=><p key={h.hour}>{String(h.hour).padStart(2,"0")}:00 UTC <strong>{h.count} telegrams</strong></p>)}{!o.hours.some(h=>h.count>0)&&<p>No traffic yet.</p>}<h4>Archived seasons</h4>{o.archives.length?o.archives.map(a=><p key={a.id}>{a.name}: {a.traffic} telegrams · {money(a.revenue)}</p>):<p>No archived traffic yet.</p>}</section>
 <form onSubmit={e=>void submit(e,"transfer")}><h3>Transfer the property</h3><p>The plot, building and office transfer together, including control of future fees. Withdraw sale listings and settle auctions and offers first.</p><label>New owner username<input name="recipient" required maxLength={48} placeholder={admin?"Player username, or state":"Player username"}/></label>{reason}<button disabled={busy}>Transfer ownership</button></form>
 {admin&&<><form onSubmit={e=>void submit(e,"relocate")}><h3>Strategic location</h3><p>Choose an empty plot owned by the office owner or an unclaimed plot. The former plot keeps its existing owner.</p><label>Destination plot<select name="plot_id" required defaultValue=""><option value="" disabled>Choose a plot</option>{o.locations.filter(l=>l.id!==o.plot_id).map(l=><option key={l.id} value={l.id}>{l.label} · {l.owner_name}</option>)}</select></label>{reason}<button disabled={busy}>Relocate unique office</button></form><form onSubmit={e=>void submit(e,"sale")}><h3>City property sale</h3><p>Set or withdraw the asking price while the office is state owned. Player owners use the District property controls to sell or auction.</p><label>Asking price<input name="price" type="number" min={1} defaultValue={o.asking_price??""} placeholder="Leave empty to withdraw"/></label>{reason}<button disabled={busy}>Update property listing</button></form></>}
 <section><h3>Ownership history</h3>{o.history.length?o.history.map(h=><p key={h.id}>{h.new_owner_name}<small>{new Date(h.created_at).toLocaleDateString("en-GB",{timeZone:"UTC"})} · {h.reason}</small></p>):<p>Held by the city since the season opened.</p>}<Link href={"/districts/"+o.district_slug+"?plot="+o.plot_id}>Property sales & auctions →</Link></section>
 </div>;
}

