"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useInventory} from "./use-inventory";
import {CommodityArtwork} from "./commodity-artwork";
import {GameIcon} from "./game-icon";
import {createClient} from "@/lib/supabase/client";
import {money} from "@/lib/game";
import {type InventoryState,type Store} from "@/lib/inventory";
import type {DistrictState} from "@/lib/districts";
import {MarketPagination} from "./market-pagination";
const accepting=(s:Store)=>s.construction_status==="ready"&&!s.locked&&s.enabled&&!s.listed&&(!s.lease||s.lease.active);
const status=(s:Store)=>s.construction_status!=="ready"?"Under construction":s.locked?"District locked":s.lease&&!s.lease.active?"Collection locker":!s.enabled?"Deposits paused":s.listed?"Listed for sale":"Accepting deposits";
export function WarehouseOverview({initial}:{initial:InventoryState}){
 const h=useInventory(initial),d=h.data;const [orders,setOrders]=useState<DistrictState["buy_orders"]|null>(null),[error,setError]=useState(""),[version,setVersion]=useState(0),[page,setPage]=useState(0);
 useEffect(()=>{let active=true;setError("");setOrders(null);void(async()=>{try{const r=await createClient().rpc("district_state",{p_slug:null});if(r.error||!r.data)throw new Error("Buy orders could not refresh.");if(active)setOrders(r.data.buy_orders);}catch(e){if(active)setError(e instanceof Error?e.message:"Buy orders unavailable.");}})();return()=>{active=false;};},[version,d.season.id]);
 const stored=d.stores.reduce((n,s)=>n+s.used,0),room=d.stores.filter(accepting).reduce((n,s)=>n+Math.max(0,s.capacity-s.used),0);
 const stock=new Map<string,{carried:number;stored:number}>();for(const x of d.carried){stock.set(x.good_id,{carried:x.quantity,stored:0});}for(const s of d.stores)for(const x of s.contents){const row=stock.get(x.good_id)??{carried:0,stored:0};row.stored+=x.quantity;stock.set(x.good_id,row);}
 const matches=(orders??[]).filter(o=>o.buyer_id!==d.player_id&&(o.remaining_quantity??o.quantity)>0&&stock.has(o.good_id)&&(stock.get(o.good_id)!.carried+stock.get(o.good_id)!.stored)>0).sort((a,b)=>b.unit_price-a.unit_price);
 const current=Math.min(page,Math.max(0,Math.ceil(matches.length/10)-1));
 const name=(id:string)=>d.goods.find(g=>g.id===id)?.name??id;
 return <div className="warehouse-page"><header className="command-panel warehouse-header"><div><p className="eyebrow">BLACKWATER / YOUR SUPPLY</p><h1>Warehouse overview</h1><p>Every storage property. Every unit accounted for.</p></div><div className="warehouse-actions"><Link className="market-outline" href="/inventory">Open inventory</Link><button className="market-outline" disabled={h.reading} onClick={()=>{h.refresh();setVersion(v=>v+1);}}>Refresh warehouses <GameIcon name="refresh" size={16}/></button></div></header>
 {h.notice&&<p className="game-notice" role={h.failed?"alert":"status"}>{h.notice}</p>}<dl className="warehouse-totals">{[["Storage properties",d.stores.length],["Units stored",stored],["Space accepting deposits",room],["Units committed to trades",d.committed.reduce((n,x)=>n+x.quantity,0)]].map(([label,value])=><div className="command-panel" key={label}><dt>{label}</dt><dd>{value.toLocaleString("en-US")}</dd></div>)}</dl>
 <section className="warehouse-grid" aria-label="Your storage properties">{d.stores.map(s=>{const contents=new Map<string,number>();for(const x of [...s.contents,...d.gear.filter(g=>g.location==="storage"&&g.building_id===s.id)])contents.set(x.good_id,(contents.get(x.good_id)??0)+x.quantity);return <article className="command-panel warehouse-card" key={s.id}><div className="command-panel-head"><h2>{s.code} · {s.name}</h2><GameIcon name="inventory" size={22}/></div><div className="warehouse-card-body"><p className="eyebrow">{s.district}</p><strong className="warehouse-status">{status(s)}</strong><p>{s.used.toLocaleString()} / {s.capacity.toLocaleString()} units stored</p><meter aria-label={s.code+" storage capacity"} min={0} max={Math.max(1,s.capacity,s.used)} value={s.used}/><p>{accepting(s)?Math.max(0,s.capacity-s.used).toLocaleString()+" units available for deposits":"New deposits unavailable"}</p>{!!s.station_space&&<p className="market-help">Crafting station: {s.station_space} units reserved separately.</p>}{s.lease&&<p className="market-help">{s.lease.active?"Lease ends":"Lease ended"} {new Date(s.lease.ends_at).toLocaleDateString("en-GB",{timeZone:"UTC"})} (UTC)</p>}
 <details><summary>View contents ({contents.size} item types)</summary>{contents.size?<ul className="warehouse-contents">{[...contents].map(([id,quantity])=><li key={id}><CommodityArtwork goodId={id} size={42}/><span>{name(id)}</span><strong>{quantity.toLocaleString()}</strong></li>)}</ul>:<p className="market-help">No items stored here.</p>}</details><div className="warehouse-actions"><Link className="market-outline" href={"/inventory?building="+encodeURIComponent(s.id)}>Manage contents</Link><Link className="command-more" href={"/districts/"+s.district_slug+"?plot="+s.plot_id}>View property →</Link></div></div></article>;})}{!d.stores.length&&<div className="command-panel warehouse-card-body"><h2>Your first warehouse awaits.</h2><p>Lease a city garage or warehouse, or build storage on your own plot.</p><Link className="market-outline" href="/districts">Explore storage properties →</Link></div>}</section>
 <section className="command-panel warehouse-matches"><div className="command-panel-head"><h2>Buy orders for your goods</h2><Link className="command-more" href="/market?view=orders">Open buy orders →</Link></div><p className="market-help">Open requests matching your carried or stored stackable goods, highest unit price first. Retrieve stored goods before selling; availability is checked when you sell.</p>{error?<p role="alert">{error} <button className="market-outline" onClick={()=>setVersion(v=>v+1)}>Try again</button></p>:orders===null?<p role="status">Checking open buy orders…</p>:matches.length?<><div className="warehouse-order-list">{matches.slice(current*10,current*10+10).map(o=><article key={o.id}><CommodityArtwork goodId={o.good_id} size={52}/><div><strong>{name(o.good_id)}</strong><p>{o.buyer_name} wants {o.remaining_quantity??o.quantity} · {money(o.unit_price)} per unit</p><small>{stock.get(o.good_id)!.carried} carried · {stock.get(o.good_id)!.stored} stored</small></div><Link className="market-outline" href={"/market?view=orders&good="+encodeURIComponent(o.good_id)+"&district="+encodeURIComponent(o.district_id)}>View orders</Link></article>)}</div><MarketPagination page={current} total={matches.length} onPage={setPage} label="Matching buy orders"/></>:<p className="market-help">No open buy orders match your goods right now.</p>}</section></div>;
}
