import type {Season} from "./seasons";
export type RangeConfig={enabled:number;rounds:number;round_seconds:number;targets_per_round:number;move_vertical:number;bullseye_percent:number;move_amplitude:number;move_speed:number;radius_x:number;radius_y:number;hit_points:number;bullseye_points:number;fire_interval_ms:number;lag_tolerance_ms:number;actions_per_minute:number};
export type RangeRule={good_id:string;ammo_good_id:string;condition_max:number;wear_per_shot:number;enabled:boolean;version:number};
export type RangeWeapon={id:string;good_id:string;name:string;slot:string;raw_condition:number|null;condition:number|null;condition_max:number|null;wear_per_shot:number|null;enabled:boolean;ammo_good_id:string|null;ammo_name:string|null};
export type RangeShot={id:string;hit:boolean;points:number;round:number;lane:number|null;x:number;y:number;created_at:string};
export type RangeSession={id:string;weapon_id:string;weapon_good_id:string;equipment_slot:string;seed:number;config:RangeConfig;weapon_rule:RangeRule;started_at:string;ends_at:string;status:"active"|"finished"|"stopped";shots:number;hits:number;score:number;streak:number;best_streak:number;last_shot_at:string|null;hit_targets:string[];last_shot:RangeShot|null};
export type RangeState={season:Season;server_time:string;config:RangeConfig;can_manage:boolean;weapons:RangeWeapon[];ammo:{id:string;good_id:string;name:string;quantity:number}|null;session:RangeSession|null;stats:{sessions:number;best_score:number;shots:number;hits:number;best_accuracy:number};recent:{id:string;score:number;hits:number;shots:number;status:string;started_at:string}[];leaders:{player_id:string;username:string;avatar_url:string|null;score:number}[];management:null|{weapons:RangeRule[];goods:{id:string;name:string;equipment_slots:string[]}[];settings:{key:string;value:number;minimum:number;maximum:number}[]}};
export const rangeTarget=(seed:number,round:number,lane:number,elapsed:number,c:RangeConfig)=>{const phase=((seed+round*53+lane*137)%628)/100,t=(elapsed%(c.round_seconds*1000))/1000*c.move_speed/100;return {x:50+(lane-(c.targets_per_round-1)/2)*(c.targets_per_round===2?40:30)+c.move_amplitude*Math.sin(t+phase),y:45+c.move_vertical*Math.sin(t*.7+phase),rx:c.radius_x,ry:c.radius_y};};
export const accuracy=(hits:number,shots:number)=>shots?Math.round(hits/shots*100):0;
