export type Telegram={id:string;thread_id:string;sender_id:string;recipient_id:string|null;sender_name:string;sender_avatar?:string;body:string;created_at:string};
export type TelegramThread={kind?:'direct'|'group'|'gang';other_avatar?:string|null;member_count?:number;owner_id?:string;can_manage?:boolean;can_send?:boolean;closed?:boolean;id:string;subject:string;other_id:string;other_name:string;last_at:string;excerpt:string;unread:number;archived:boolean;starred:boolean};
export type TelegramDraft={id:string;recipient:string;subject:string;body:string;updated_at:string};
export type TelegramOffice={name:string;description:string;fee:number;status:string;available:boolean;owner_type:string;owner_id:string;owner_name:string;plot_id:string;plot_code:string;district_name:string;district_slug:string;building_id:string;business_id:string;asking_price:number|null;minimum_fee:number;maximum_fee:number;can_operate:boolean;can_manage:boolean;config:{minimum_fee:number;maximum_fee:number;default_fee:number;available:boolean;reset_sale_price:number}|null;stats:{today_count:number;week_count:number;season_count:number;today_revenue:number;week_revenue:number;season_revenue:number;average_per_day:number}|null;hours:{hour:number;count:number}[];archives:{id:string;name:string;traffic:number;revenue:number}[];history:{id:number;created_at:string;new_owner_name:string;reason:string}[];locations:{id:string;label:string;owner_name:string}[]};
export type TelegramMember={id:string;name:string;avatar_url?:string;status:string;owner:boolean};
export type TelegramState={player_avatar?:string;members?:TelegramMember[];invitations?:{thread_id:string;name:string;invited_by:string}[];gang?:{id:string;name:string}|null;player_id:string;cash:number;season:{id:string;name:string;status:string};office:TelegramOffice;server_time:string;limits:{subject:number;body:number;group_name?:number;group_members?:number};unread:number;thread:TelegramThread|null;threads:TelegramThread[];messages:Telegram[];drafts:TelegramDraft[];blocks:{id:string;name:string}[];reports:{id:string;message_id:string;status:string;response:string|null;created_at:string}[]};
export const telegramFee=(fee:number)=>fee===0?"Free":"$"+fee.toLocaleString("en-US");
export function telegramTime(value:string){return new Date(value).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"UTC"});}
export function telegramDay(value:string){return new Date(value).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"});}

